### ISSUE TITLE
Make the Maven Plugin ThreadSafe

### ISSUE THREAD

**Issue by Serverfrog** [dependency-check/DependencyCheck#1020]
The Maven Plugin is either marked with @threadSafe nor does it run stable when Multithreading is enabled (-T X>1 )

Informations:

- Plugin Version 2.1.0
- Maven Version: 3.3.9
- Java Version: OpenJDK: 1.8..0_151

Stacktrace:

`java.lang.NullPointerException
	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.search(CpeMemoryIndex.java:252)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:310)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:228)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:535)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:115)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:98)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

Full Log can't be provided. Company Polices

**Comment by jeremylong** [comment]
This issue was resolved with the 3.x branch. I would highly recommend upgrading to 3.0.2.
