### ISSUE TITLE
Maven Plugin: Unable to run dependancy check analysis IO Exception: Connection refused

### ISSUE THREAD

**Issue by the-nw1-group** [dependency-check/DependencyCheck#1033]
Running the following on our project fails:

`mvn org.owasp:dependency-check-maven:3.0.2:check`

with:
```
09:34:03.115 [INFO] Error stacktraces are turned on.
09:34:03.210 [INFO] Scanning for projects...
09:34:03.434 [INFO] ------------------------------------------------------------------------
09:34:03.434 [INFO] Reactor Build Order:
09:34:03.434 [INFO]
09:34:03.434 [INFO] XYZ base POM for Aspects and Aspects related projects
09:34:03.435 [INFO] XYZ Logging
09:34:03.435 [INFO] XYZ Check Weaving Maven Plugin
09:34:03.435 [INFO] XYZ Aspects
09:34:03.519 [INFO]
09:34:03.519 [INFO] ------------------------------------------------------------------------
09:34:03.519 [INFO] Building XYZ base POM for Aspects and Aspects related projects 0.0.0
09:34:03.519 [INFO] ------------------------------------------------------------------------
09:34:04.171 [INFO]
09:34:04.171 [INFO] --- dependency-check-maven:3.0.2:check (default-cli) @ sharedpoms-aspects ---
09:34:06.799 [INFO] Checking for updates
09:34:06.804 [INFO] starting getUpdatesNeeded() ...
09:34:07.328 [ERROR] IO Exception: Connection refused
09:34:07.330 [ERROR] IO Exception: Connection refused
09:34:07.330 [ERROR] IO Exception: Connection refused
09:34:07.333 [ERROR] IO Exception: Connection refused
09:34:07.334 [ERROR] IO Exception: Connection refused
09:34:07.336 [ERROR] IO Exception: Connection refused
09:34:07.337 [WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
09:34:07.339 [WARNING] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
09:34:07.330 [ERROR] IO Exception: Connection refused
09:34:07.330 [ERROR] IO Exception: Connection refused
09:34:07.340 [ERROR] IO Exception: Connection refused
09:34:07.340 [ERROR] IO Exception: Connection refused
09:34:07.334 [ERROR] IO Exception: Connection refused
09:34:07.343 [ERROR] IO Exception: Connection refused
09:34:07.343 [ERROR] IO Exception: Connection refused
09:34:07.347 [ERROR] No documents exist

Unable to continue dependency-check analysis.
09:34:07.353 [ERROR] IO Exception: Connection refused
09:34:07.354 [ERROR] IO Exception: Connection refused
09:34:07.355 [ERROR] IO Exception: Connection refused
09:34:07.362 [ERROR] IO Exception: Connection refused
09:34:07.362 [ERROR] IO Exception: Connection refused
09:34:07.375 [INFO] ------------------------------------------------------------------------
09:34:07.376 [INFO] Reactor Summary:
09:34:07.376 [INFO]
09:34:07.376 [INFO] XYZ base POM for Aspects and Aspects related projects FAILURE [  3.857 s]
09:34:07.376 [INFO] XYZ Logging ........................................ SKIPPED
09:34:07.376 [INFO] XYZ Check Weaving Maven Plugin ..................... SKIPPED
09:34:07.376 [INFO] XYZ Aspects ........................................ SKIPPED
09:34:07.377 [INFO] ------------------------------------------------------------------------
09:34:07.377 [INFO] BUILD FAILURE
09:34:07.377 [INFO] ------------------------------------------------------------------------
09:34:07.377 [INFO] Total time: 4.205 s
09:34:07.378 [INFO] Finished at: 2017-12-15T09:34:07+00:00
09:34:07.491 [INFO] Final Memory: 19M/345M
09:34:07.491 [INFO] ------------------------------------------------------------------------
09:34:07.493 [ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.0.2:check (default-cli) on project sharedpoms-aspects: Fatal exception(s) analyzing XYZ base POM for Aspects and Aspects related projects: Unable to continue dependency-check analysis.
09:34:07.494 [ERROR] Unable to download the NVD CVE data.
09:34:07.494 [ERROR] No documents exist
09:34:07.494 [ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:3.0.2:check (default-cli) on project sharedpoms-aspects: Fatal exception(s) analyzing XYZ base POM for Aspects and Aspects related projects
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal exception(s) analyzing XYZ base POM for Aspects and Aspects related projects
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.handleAnalysisExceptions(BaseDependencyCheckMojo.java:985)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:918)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:583)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: Unable to continue dependency-check analysis.
        Unable to download the NVD CVE data.
        No documents exist
        at org.owasp.dependencycheck.Engine.throwFatalExceptionCollection(Engine.java:1076)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:648)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:916)
        ... 23 more
09:34:07.504 [ERROR]
09:34:07.504 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
09:34:07.504 [ERROR]
09:34:07.504 [ERROR] For more information about the errors and possible solutions, please read the following articles:
09:34:07.504 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
When turning on debugging in maven, looking at URLs it's trying to access I'm able to curl them from the server this is running on.

**Comment by stevespringett** [comment]
If in an organization, does your org use a proxy server or firewall?  Does the proxy or firewall require authentication?

Are you using an internal mirror of the NVD?

What version of Java is being used when the Maven goal to perform the analysis is called?

**Comment by the-nw1-group** [comment]
The server doesn't have any explicit proxy settings and can generally see the internet. Its running iptables as it's firewall, but as I say I can manually download the files using CURL. I've also tried on my laptop (which connects direct to the internet), with the same version of Maven and Java, this is on Windows 7, and I get the same errors.

We're not using an internal mirror of the NVD.

Where using the following on both the server (Centos 7.4 Linux), and a Windows client (Windows 7)
```
mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
Maven home: /opt/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_60/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.18.2.el7.x86_64", arch: "amd64", family: "unix"
```
Thanks

**Comment by rickcoup** [comment]
I have the same error. I've put the proxy into the settings.xml. There is no internal NVD. Any update on this issue?
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:3.0.2:check (default-cli) on project XXX: Fatal exception(s) analyzing XXX
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal exception(s) analyzing en-webframeworkApp
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.handleAnalysisExceptions(BaseDependencyCheckMojo.java:985)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:918)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:583)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: Unable to continue dependency-check analysis.
	Unable to download the NVD CVE data.
	No documents exist
	at org.owasp.dependencycheck.Engine.throwFatalExceptionCollection(Engine.java:1076)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:648)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:916)
	... 23 more
```

**Comment by jeremylong** [comment]
To be able to assist more with this we would need to see the full log file (i.e. run `mvn -X ....`). You can trim out just the dependency-check portion.

Also - before capturing the log please delete `~/.m2/repository/org/owasp/dependency-check-data/`.

**Comment by the-nw1-group** [comment]
I'm back after the Christmas break, and it's "magically" started working this morning.

Thanks for all your help, but I can't explain why it wasn't working before, and now why it is.

**Comment by jeremylong** [comment]
Glad its working now - just reopen the issue if it happens again.
