### ISSUE TITLE
mirrored CVE files not work

### ISSUE THREAD

**Issue by rickcoup** [dependency-check/DependencyCheck#1042]
I've put the configuration into the plugin like below.:

>                     <cveUrl12Modified>http://repo/repository/thirdparty/org/owasp/nvdcve-Modified.xml.gz/2017/nvdcve-Modified.xml.gz-2017.gz</cveUrl12Modified>
>                     <cveUrl20Modified>http://repo/repository/thirdparty/org/owasp/nvdcve-2.0-Modified.xml.gz/2017/nvdcve-2.0-Modified.xml.gz-2017.gz</cveUrl20Modified>
>                     <cveUrl12Base>http://repo/repository/thirdparty/org/owasp/nvdcve/2017/nvdcve-2017.gz</cveUrl12Base>
>                     <cveUrl20Base>http://repo/repository/thirdparty/org/owasp/nvdcve-2.0/2017/nvdcve-2.0-2017.gz</cveUrl20Base>

Then I put the above four files into my Nexus with the corresponding URL.

I got the below error:
```
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:916)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:583)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Next Exception:
org.owasp.dependencycheck.data.update.exception.UpdateException: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:171)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:119)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importXML(ProcessTask.java:148)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:167)
	... 6 more
```

**Comment by stevespringett** [comment]
The format is incorrect.

Please use https://github.com/stevespringett/nist-data-mirror/ to mirror the NVD.

These are the default values that Dependency-Check uses.
```xml
<cveUrl12Modified>https://nvd.nist.gov/download/nvdcve-Modified.xml.gz</cveUrl12Modified>
<cveUrl20Modified>https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
<cveUrl12Base>https://nvd.nist.gov/download/nvdcve-%d.xml.gz</cveUrl12Base>
<cveUrl20Base>https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-%d.xml.gz</cveUrl20Base>
```

In your case, you may end up changing them to:
```xml
<cveUrl12Modified>https://repo/nvd-mirror/nvdcve-Modified.xml.gz</cveUrl12Modified>
<cveUrl20Modified>https://repo/nvd-mirror/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
<cveUrl12Base>https://repo/nvd-mirror/nvdcve-%d.xml.gz</cveUrl12Base>
<cveUrl20Base>https://repo/nvd-mirror/nvdcve-2.0-%d.xml.gz</cveUrl20Base>
```

**Comment by 19oos** [comment]
@rickcoup @stevespringett  
I alse mirrored the nvd  from https://github.com/stevespringett/nist-data-mirror 
According to  https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html  step 2, I tryed to config pom file (d:\mvn_repo\org\owasp\dependency-check-maven\3.1.1\dependency-check-maven-3.1.1.pom) , added the properties  cveUrl12Modified, cveUrl20Modified, cveUrl12Base, cveUrl20Base. But it is not working? Am I configed the wrong file? 
ps, I use the maven plugin to do the check with the cmd: mvn org.owasp:dependency-check-maven:check. 

```xml
<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-plugin-plugin</artifactId>
                <version>${version.maven-plugin-plugin}</version>
                <configuration>
                    <skipErrorNoDescriptorsFound>true</skipErrorNoDescriptorsFound>
                    <goalPrefix>dependency-check</goalPrefix>
					<cveUrl12Modified>http://127.0.0.1/nist-mirror/nvdcve-Modified.xml.gz</cveUrl12Modified>
					<cveUrl20Modified>http://127.0.0.1/nist-mirror/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
					<cveUrl12Base>http://127.0.0.1/nist-mirror/nvdcve-%d.xml</cveUrl12Base>
					<cveUrl20Base>http://127.0.0.1/nist-mirror/nvdcve-2.0-%d.xml</cveUrl20Base>
				</configuration>	
```

**Comment by jeremylong** [comment]
You have some invalid configuration options defined - not sure if that is causing an issue somehow.  Can you use:

```xml
<build>
  <plugins>
    <plugin>
       <groupId>org.owasp</groupId>
       <artifactId>dependency-check-maven</artifactId>
       <version>3.1.1</version>
       <configuration>
         <cveUrl12Modified>http://127.0.0.1/nist-mirror/nvdcve-Modified.xml.gz</cveUrl12Modified>
         <cveUrl20Modified>http://127.0.0.1/nist-mirror/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
         <cveUrl12Base>http://127.0.0.1/nist-mirror/nvdcve-%d.xml</cveUrl12Base>
         <cveUrl20Base>http://127.0.0.1/nist-mirror/nvdcve-2.0-%d.xml</cveUrl20Base>
       </configuration>
       <executions>
         <execution>
           <goals>
             <goal>check</goal>
           </goals>
         </execution>
       </executions>
     </plugin>
  </plugins>
</build>
```

Can you use the above configuration and provide the exact error message?  Preferably using the `-X` maven option and provide the section from the maven log that is specific to dependency-check.
