### ISSUE TITLE
Dependency check fails with error message "Archive file was not found"

### ISSUE THREAD

**Issue by bmuschko** [dependency-check/DependencyCheck#1061]
I recently integrated the plugin into the [Gradle build](https://github.com/gradle/gradle/blob/master/gradle/dependenciesCheck.gradle). The dependency check is run as [one of the steps in our CI build pipeline](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_DependenciesCheck&branch_Gradle_Check_Stage_BranchBuildAccept=master&tab=buildTypeStatusDiv).

### Reporting Bugs/Errors

Intermittently, I am encountering the following issue:

```
[11:48:42][Gradle failure report] Caused by: org.gradle.api.GradleException: One or more exceptions occurred during analysis
[11:48:42][Gradle failure report] 	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:111)
[11:48:42][Gradle failure report] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
[11:48:42][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[11:48:42][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[11:48:42][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[11:48:42][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
[11:48:42][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
[11:48:42][Gradle failure report] 	... 32 more
[11:48:42][Gradle failure report] Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[11:48:42][Gradle failure report] 	Archive file was not found.
[11:48:42][Gradle failure report] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
[11:48:42][Gradle failure report] 	at org.owasp.dependencycheck.Engine$analyzeDependencies$1.call(Unknown Source)
[11:48:42][Gradle failure report] 	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:78)
[11:48:42][Gradle failure report] 	... 45 more
```

Could you please give me hint on what the underlying issue might be? I saw that there also was an [issue with connection to the database](https://builds.gradle.org/viewLog.html?buildId=10292522&tab=buildResultsDiv&buildTypeId=Gradle_Check_DependenciesCheck) earlier. Could this potentially be an issue with concurrency?

```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: Unable to continue dependency-check analysis.
Unable to connect to the database
```

**Comment by jeremylong** [comment]
Being an intermittent bug - it certainly sounds like a concurrency issue. I'm not sure I can solve this immediately - I may need to improve the logging around that error message (i.e. which archive file is causing the issue) to try and figure out exactly what is going on.

**Comment by bmuschko** [comment]
Would be awesome to have a fix for it. Thanks for looking into it. If we get it working you have another big name on your list of users. 🎉

**Comment by jeremylong** [comment]
@bmuschko I've been thinking about this a bit more. If you increase the logging level to debug in Jenkins for `org.owasp.dependencycheck` (see the [Jenkins documentation](https://wiki.jenkins.io/display/JENKINS/Logging#Logging-LogsinJenkins) for more information). You will be able to see where temp files are being written (by default it is `System.getProperty("java.io.tmpdir")`). Is there any chance that other jobs running in Jenkins could be wiping out the temp directory?

**Comment by bmuschko** [comment]
Thanks for your response. We are using TeamCity but the effect should be the same.

>Is there any chance that other jobs running in Jenkins could be wiping out the temp directory?

I will look into that. Thanks for the hint. If I wanted to set it to some other directory than `java.io.tmpdir`, do I change that via `dependencyCheck.data.directory`?

**Comment by jeremylong** [comment]
@bmuschko sorry for the extremely delayed response - the temp directory would be changed via `temp.directory`.  In 3.1.1 I also added some debug logging that should assist in tracking the problem down.

**Comment by jeremylong** [comment]
Circling back to really old issues - a lot of changes have been made since this was reported. Is this still an issue?

**Comment by bmuschko** [comment]
I have no more access to the project. You can close the issue if nobody else is running into it anymore.
