### ISSUE TITLE
could not connect to Central search. Analysis failed. version 3.1.0

### ISSUE THREAD

**Issue by sinvinsin** [dependency-check/DependencyCheck#1081]
P[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 5 tries.
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:288)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name
 matching search.maven.org found.
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:140)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:266)
        
Any Help Appreciated ,

**Comment by stevespringett** [comment]
Check https://jeremylong.github.io/DependencyCheck/data/tlsfailure.html

Use the Oracle Java distribution if possible. 

If that does not work:
- Are you behind a proxy server?
- Is authentication required?
- Does the proxy or firewall perform SSL/TLS termination?
- Is Maven Central blocked? (Common for orgs that have an internal Nexus or Artifactory)

**Comment by jeremylong** [comment]
It appears Central has changed the query structure so that it no longer requires quotes. See https://github.com/jeremylong/dependency-check-gradle/issues/69#issuecomment-360519698.

ODC v3.1.1 will be release shortly.

**Comment by stevespringett** [comment]
Didn't Central change this just a few months ago - now changing back? Perhaps we should account for both in case they keep on changing their mind.

**Comment by sinvinsin** [comment]
Hi Jermy,

Tried using the latest release as well

dependency-check-3.1.1-release\dependency-check\bin>dependency-check.bat -proxyserver 111.111.111.111 -proxyport 8080 --project "TEST" --scan "D:\SXCQWERT-web-1.1" --out "D:\SXCQWERT-web-1.1\"
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (281 ms)
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (1 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (1 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 5 tries.
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:288)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(Unknown Source)
        at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at java.base/sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at java.base/sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at java.base/sun.security.ssl.Handshaker.processRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:140)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:266)

I use JDK-9.0.1
Behind Proxy but have used proxy username and proxy port

**Comment by jeremylong** [comment]
@sinvinsin I apologize - I mixed your issue with a different issue with Central. It appears that you are facing an issue with the TLS connection as the above stack trace has:

```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: 
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: 
unable to find valid certification path to requested target
```

It appears your keystore does not contain the necessary certs to successfully connect to Central. Take a look at this repo: https://github.com/jeremylong/InstallCert. It is a cloned repo that provides a tool to install the necessary certificates in a Java keystore.  Does that solve the problem?

**Comment by mceli2** [comment]
@jeremylong, I'm seeing this same issue. I checked the readme instructions for InstallCert but not sure what is the access server for Central:
Access server, and retrieve certificate (accept default certificate 1)
java InstallCert [host]:[port]
Please advise. Thank you!

**Comment by jeremylong** [comment]
The base url for Central can be found here:
 https://github.com/jeremylong/DependencyCheck/blob/aed1ec976fc0b28e1313a1a4ba5bdb25a70a8d50/core/src/main/resources/dependencycheck.properties#L84

So the install cert would be:
```
java InstallCert search.maven.org:443
```
