### ISSUE TITLE
Error opening db2 jar

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1099]
Hi

Im having problems when analysing a db2 dependency in bug bounty program i am running.

 Looks like dependency check is unable to open the jars related to db2

Here is the log:

2018-02-08 10:16:50,685 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:430
DEBUG - 
org.owasp.dependencycheck.analyzer.exception.ArchiveExtractionException: java.util.zip.ZipException: invalid block type
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:527)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:406)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:250)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:272)

Have you seen this before?

Thanks

**Comment by jeremylong** [comment]
I have not seen the error before - is the JAR available online somewhere?  Can you unzip the JAR using 7zip or some other archive tool without errors?
