### ISSUE TITLE
NullPointerException in NodePackageAnalyzer

### ISSUE THREAD

**Issue by alexanderfloh** [dependency-check/DependencyCheck#1106]
When running the Gradle scanner (3.1.1) on our build I'm getting the following exception:
```
13:56:37.580 [WARN] [org.owasp.dependencycheck.AnalysisTask] An unexpected error occurred during analysis of '<tempdir>\dctempccda668a-46de-4794-a1f1-d0054e31f996\check8100855058401610347tmp\325\package-lock.json' (Node.js Package Analyzer): null
13:56:37.580 [DEBUG] [org.owasp.dependencycheck.AnalysisTask] 
java.lang.NullPointerException
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:189)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Unfortunately it seems that the files are cleaned up automatically so I can't post the offending file.

**Comment by jeremylong** [comment]
I see exactly where the problem is in the code and it is an easy fix. However, I have a couple of questions:

1. Does you application use Node.js or is this something that is just part of the build?
2. The package-lock.json file is contained within an archive (zip, jar, etc.) that is included in your build. Any chance you could figure out where the package-lock.json is coming from?
