### ISSUE TITLE
Dependency check Jenkins plugin Download failed exception

### ISSUE THREAD

**Issue by PrahathessRengasamy** [dependency-check/DependencyCheck#1174]
I am running jenkins in a docker container on a kubernetes pod and I get into this exception every time
would like to know  what is going wrong and how to fix it  
```
Commit message: "test"
First time build. Skipping changelog.
[DependencyCheck] OWASP Dependency-Check Plugin v3.1.1
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = test
[DependencyCheck]  -scanPath = /*jar
[DependencyCheck]  -outputDirectory = /var/jenkins_home/workspace/test
[DependencyCheck]  -dataDirectory = /var/jenkins_home
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nspAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -tempPath = /var/jenkins_home
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.update.exception.UpdateException
[DependencyCheck] Cause: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
[DependencyCheck] Message: Unable to download the NVD CVE data.
[DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download the NVD CVE data.
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:130)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:889)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
[DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
[DependencyCheck] 	at hudson.model.Run.execute(Run.java:1735)
[DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
[DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
[DependencyCheck] 	at hudson.model.Executor.run(Executor.java:405)
[DependencyCheck] Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveLastModifiedDates(NvdCveUpdater.java:460)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveCurrentTimestampsFromWeb(NvdCveUpdater.java:402)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:319)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:117)
[DependencyCheck] 	... 19 more
[DependencyCheck] Caused by: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
[DependencyCheck] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[DependencyCheck] 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveLastModifiedDates(NvdCveUpdater.java:455)
[DependencyCheck] 	... 22 more
[DependencyCheck] Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
[DependencyCheck] 	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:293)
[DependencyCheck] 	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:235)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:507)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:480)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: HEAD request returned a non-200 status code
[DependencyCheck] 	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:273)
[DependencyCheck] 	... 7 more
[DependencyCheck] 
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.NoDataException
[DependencyCheck] Message: No documents exist
[DependencyCheck] org.owasp.dependencycheck.exception.NoDataException: No documents exist
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:1068)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:646)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
[DependencyCheck] 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.build(Build.java:206)
[DependencyCheck] 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
[DependencyCheck] 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
[DependencyCheck] 	at hudson.model.Run.execute(Run.java:1735)
[DependencyCheck] 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
[DependencyCheck] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
[DependencyCheck] 	at hudson.model.Executor.run(Executor.java:405)
[DependencyCheck] 
Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE
[DependencyTrack] Publishing artifact to Dependency-Track
[DependencyTrack] The specified artifact does not exist
Finished: FAILURE
Page generated: Mar 30, 2018 6:25:37 PM UTCREST APIJenkins ver. 2.60.3
```

**Comment by stevespringett** [comment]
Duplicate of #1171

**Comment by Prahathess-Rengasamy-ck** [comment]
How do you suggest I fix it in my jenkins plugin ?

**Comment by stevespringett** [comment]
Go to Jenkins global config and tell the plugin to use the NVD mirror. You won't actually be using a mirror, you'll just be correcting the URLs.

Using a mirror of the NVD is however a best practice and would certainly recommend it. But for a quick fix, just pretend like you're mirroring to correct the URLs.

**Comment by PrahathessRengasamy** [comment]
Awesome thank you so much appreciate the quick response :)

**Comment by jeremylong** [comment]
A fix will be pushed soon for this...

**Comment by jeremylong** [comment]
Closing this ticket - please see #1171
