### ISSUE TITLE
Exception in thread "main"  NullPointerException

### ISSUE THREAD

**Issue by wisec** [dependency-check/DependencyCheck#118]
Tested on : 
java version "1.6.0_37"

Dependency check Version: 1.2.0  
downloaded from OWASP page.
Issue:
bin/dependency-check.sh  -h 
Exception in thread "main" java.lang.NullPointerException
    at org.owasp.dependencycheck.utils.Settings.getString(Settings.java:464)
    at org.owasp.dependencycheck.cli.CliParser.printHelp(CliParser.java:449)
    at org.owasp.dependencycheck.App.run(App.java:93)
    at org.owasp.dependencycheck.App.main(App.java:61)

Same using Jre 1.7.0_51

Thanks.

**Comment by jeremylong** [comment]
Thanks, this was reported. Complete release checking issue on my part. This
is a very easy to fix bug and I will be publishing a patched version this
evening.

Sorry about this.

--Jeremy

**Comment by jeremylong** [comment]
This has been patched and the updated CLI can be downloaded here: http://dl.bintray.com/jeremy-long/owasp/dependency-check-1.2.0.1-release.zip

**Comment by wisec** [comment]
Thanks Jeremy,
very much appreciated!
