### ISSUE TITLE
I want to change the database to MYSQL

### ISSUE THREAD

**Issue by Kantha4security** [dependency-check/DependencyCheck#1358]
I downloaded the command line utility from the OWASP page and able to use. 

However, I want to change the database to MYSQL community edition. I tried of using the instructions from https://jeremylong.github.io/DependencyCheck/data/database.html. I installed the MYSQL community edition and initialized the database using the SQL scripts provided. Now, I'm no clue, how to proceed from here. 

I would like to request you to help me by giving some instructions or redirecting me to detailed resources.

Thank you

**Comment by stevespringett** [comment]
Once the database is initialized, execute Dependency-Check like normal, except you'll supply the additional database params.

If you're using the Maven plugin, the docs are in the link you provided. Refer to the configuration for the ODC module you're trying to execute.

https://jeremylong.github.io/DependencyCheck/modules.html

For example, if you're using the CLI, use the following command-line args that are documented here: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

- connectionString
- dbDriverName
- dbDriverPath
- dbPassword
- dbUser

**Comment by Kantha4security** [comment]
Hi @stevespringett,

Thank you for your reply.

Below is the command that I used to connect to the modified MYSQL using ODBC driver with dependency-check.bat.

" _C:\ThirdParty\dependency-check>bin\dependency-check.bat  -project Testing --out new_test.html --format HTML --scan "C:\dependency-check\ThirdParty\1234\apk321.jar" --connectionString dependency --dbDriverName "MYSQL ODBC 8.0 Unicode Driver" --dbDriverPath "C:\Program Files\MySQL\Connector ODBC 8.0\myodbc8w.dll" --dbUser "****" --dbPassword "******" --log odc.log_ "

I'm not able to load the database driver, below is the log file.

DEBUG - Loading driver 'MYSQL ODBC 8.0 Unicode Driver'
2018-07-01 21:02:41,062 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:122
DEBUG - Loading driver from: C:\Program Files\MySQL\Connector ODBC 8.0\myodbc8w.dll
2018-07-01 21:02:41,075 org.owasp.dependencycheck.data.nvdcve.DriverLoader:159
**DEBUG - Unable to load database driver 'MYSQL ODBC 8.0 Unicode** 
nable to load database driver 'MYSQL ODBC 8.0 Unicode Driver'
java.lang.ClassNotFoundException: MYSQL ODBC 8.0 Unicode Driver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:148)
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:134)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:123)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:230)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:228)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:198)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:949)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:891)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
	at org.owasp.dependencycheck.App.runScan(App.java:255)
	at org.owasp.dependencycheck.App.run(App.java:184)
	at org.owasp.dependencycheck.App.main(App.java:69)
2018-07-01 21:02:41,075 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:128
DEBUG - Unable to load database driver
org.owasp.dependencycheck.data.nvdcve.DriverLoadException: Unable to load database driver 'MYSQL ODBC 8.0 Unicode Driver'
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:160)
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:134)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:123)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:230)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:228)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:198)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:949)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:891)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
	at org.owasp.dependencycheck.App.runScan(App.java:255)
	at org.owasp.dependencycheck.App.run(App.java:184)
	at org.owasp.dependencycheck.App.main(App.java:69)
Caused by: java.lang.ClassNotFoundException: MYSQL ODBC 8.0 Unicode Driver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.owasp.dependencycheck.data.nvdcve.DriverLoader.load(DriverLoader.java:148)
	... 12 common frames omitted

**Comment by stevespringett** [comment]
You’re attempting to use an ODBC driver when DependencyCheck expects a JDBC driver. 

https://dev.mysql.com/downloads/connector/j/

**Comment by Kantha4security** [comment]
@stevespringett 

Thank you, I'm able to use in CLI

**Comment by stevespringett** [comment]
Glad it’s working :-)
