### ISSUE TITLE
jenkins build error

### ISSUE THREAD

**Issue by rajkumarkanjo** [dependency-check/DependencyCheck#1415]
FailedConsole Output
Started by user admin
Building in workspace C:\Program Files (x86)\Jenkins\workspace\My NVD Data
[DependencyCheck] OWASP Dependency-Check Plugin v3.3.0
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = My NVD Data
[DependencyCheck]  -outputDirectory = C:\Program Files (x86)\Jenkins\workspace\My NVD Data
[DependencyCheck]  -dataDirectory = /opt/NVDUpdate
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = false
[DependencyCheck]  -nodePackageAnalyzerEnabled = false
[DependencyCheck]  -nspAnalyzerEnabled = false
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = false
[DependencyCheck]  -pythonPackageAnalyzerEnabled = false
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = false
[DependencyCheck]  -assemblyAnalyzerEnabled = false
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
[DependencyCheck]  -centralAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = false
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = false
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = true
[DependencyCheck] Data directory created
[DependencyCheck] Performing NVD update only
[DependencyCheck] Unable to update the Dependency-Check database
Build step 'Invoke Dependency-Check NVD update only' changed build result to FAILURE
Finished: FAILURE

**Comment by stevespringett** [comment]
You need to enable Jenkins logging for 'org.owasp' to provide more details.

**Comment by drazul** [comment]
I get the same error.
I execute dependency check in two steps:
1- Only DB update
2- Execute dependency check without update

In the first step I get same error than @rajkumarkanjo 
In the second step I get following stacktrace

````
13:09:21 [DependencyCheck] Analyzing Dependencies
13:09:22 [DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
13:09:22 [DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.nvdcve.DatabaseException
13:09:22 [DependencyCheck] Cause: The database is read only [90097-196]
13:09:22 [DependencyCheck] Message: Unable to connect to the database
13:09:22 [DependencyCheck] org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the database
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:178)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:973)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:737)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
13:09:22 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
13:09:22 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
13:09:22 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
13:09:22 [DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
13:09:22 [DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
13:09:22 [DependencyCheck] 	at hudson.remoting.Request$2.run(Request.java:358)
13:09:22 [DependencyCheck] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
13:09:22 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:09:22 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
13:09:22 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
13:09:22 [DependencyCheck] 	at hudson.remoting.Engine$1$1.run(Engine.java:94)
13:09:22 [DependencyCheck] 	at java.lang.Thread.run(Thread.java:745)
13:09:22 [DependencyCheck] Caused by: org.h2.jdbc.JdbcSQLException: The database is read only [90097-196]
13:09:22 [DependencyCheck] 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
13:09:22 [DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:179)
13:09:22 [DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:155)
13:09:22 [DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:144)
13:09:22 [DependencyCheck] 	at org.h2.engine.Database.checkWritingAllowed(Database.java:1935)
13:09:22 [DependencyCheck] 	at org.h2.store.FileStore.checkWritingAllowed(FileStore.java:161)
13:09:22 [DependencyCheck] 	at org.h2.store.FileStore.write(FileStore.java:325)
13:09:22 [DependencyCheck] 	at org.h2.store.PageStore.writePage(PageStore.java:1369)
13:09:22 [DependencyCheck] 	at org.h2.store.PageLog.recover(PageLog.java:307)
13:09:22 [DependencyCheck] 	at org.h2.store.PageStore.recover(PageStore.java:1395)
13:09:22 [DependencyCheck] 	at org.h2.store.PageStore.openExisting(PageStore.java:368)
13:09:22 [DependencyCheck] 	at org.h2.store.PageStore.open(PageStore.java:289)
13:09:22 [DependencyCheck] 	at org.h2.engine.Database.getPageStore(Database.java:2490)
13:09:22 [DependencyCheck] 	at org.h2.engine.Database.open(Database.java:697)
13:09:22 [DependencyCheck] 	at org.h2.engine.Database.openDatabase(Database.java:276)
13:09:22 [DependencyCheck] 	at org.h2.engine.Database.<init>(Database.java:270)
13:09:22 [DependencyCheck] 	at org.h2.engine.Engine.openSession(Engine.java:64)
13:09:22 [DependencyCheck] 	at org.h2.engine.Engine.openSession(Engine.java:176)
13:09:22 [DependencyCheck] 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
13:09:22 [DependencyCheck] 	at org.h2.engine.Engine.createSession(Engine.java:137)
13:09:22 [DependencyCheck] 	at org.h2.engine.Engine.createSession(Engine.java:27)
13:09:22 [DependencyCheck] 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
13:09:22 [DependencyCheck] 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
13:09:22 [DependencyCheck] 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
13:09:22 [DependencyCheck] 	at org.h2.Driver.connect(Driver.java:69)
13:09:22 [DependencyCheck] 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
13:09:22 [DependencyCheck] 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
13:09:22 [DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:163)
13:09:22 [DependencyCheck] 	... 18 more
```

**Comment by jeremylong** [comment]
We would need the full debug log for the first error. See @stevespringett comment above.

**Comment by rajkumarkanjo** [comment]
Thanx for your reply @stevespringett  @jeremylong ..Whatever error i got from the jenkins console I have posted the same here..but i dunno why I am getting this error I checked all the configurations everything is fine only.

**Comment by stevespringett** [comment]
@rajkumarkanjo the Jenkins console does not have debug logging. You need to enable debug logging in Jenkins for org.owasp. That may provide more details about what's happening.

**Comment by drazul** [comment]
In my case the error was solved updating the OWASP Dependency-Check Plugin to v3.3.1

**Comment by stormof** [comment]
I've got almost the same error using v3.3.1 and older version:

[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1'
[DEBUG] Settings.getDataFile() - returning: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0'
[DEBUG] Data directory: /root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0
[DEBUG] Connection String: 'jdbc:h2:file:/root/.m2/repository/org/owasp/dependency-check-data/3.0/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;'
[DEBUG] locking for update
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1'
[DEBUG] Settings.getDataFile() - returning: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0'
[DEBUG] Lock file created (main) 638f6042385c6d50e0cb6fb0a2f4e589 @ 2018-08-20 09:53:36.318
[DEBUG] Loading driver 'org.h2.Driver'
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1'
[DEBUG] Settings.getDataFile() - returning: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0'
[DEBUG] Data directory: /root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0
[DEBUG] Connection String: 'jdbc:h2:file:/root/.m2/repository/org/owasp/dependency-check-data/3.0/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;'
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1'
[DEBUG] Settings.getDataFile() - returning: '/root/.m2/repository/org/owasp/dependency-check-utils/3.3.1/../../dependency-check-data/3.0'
[DEBUG] Need to create DB Structure: false
[DEBUG] Loading database connection
[DEBUG] Connection String: jdbc:h2:file:/root/.m2/repository/org/owasp/dependency-check-data/3.0/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;
[DEBUG] Database User: dcuser
[DEBUG] Unable to connect to the database
org.h2.jdbc.JdbcSQLException: File corrupted while reading record: "68503 of 59113". Possible solution: use the recovery tool [90030-196]
    at org.h2.message.DbException.getJdbcSQLException (DbException.java:345)
    at org.h2.message.DbException.get (DbException.java:179)
    at org.h2.message.DbException.get (DbException.java:155)
    at org.h2.store.PageStore.readPage (PageStore.java:1322)
    at org.h2.store.PageStore.getPage (PageStore.java:750)
    at org.h2.index.PageDataIndex.getPage (PageDataIndex.java:232)
    at org.h2.index.PageDataNode.getLastKey (PageDataNode.java:214)
    at org.h2.index.PageDataIndex.<init> (PageDataIndex.java:86)
    at org.h2.table.RegularTable.<init> (RegularTable.java:83)
    at org.h2.store.PageStore.addMeta (PageStore.java:1697)
    at org.h2.store.PageStore.readMetaData (PageStore.java:1628)
    at org.h2.store.PageStore.recover (PageStore.java:1406)
    at org.h2.store.PageStore.openExisting (PageStore.java:368)
    at org.h2.store.PageStore.open (PageStore.java:289)
    at org.h2.engine.Database.getPageStore (Database.java:2490)
``
    at org.h2.engine.Database.open (Database.java:697)
    at org.h2.engine.Database.openDatabase (Database.java:276)
    at org.h2.engine.Database.<init> (Database.java:270)
    at org.h2.engine.Engine.openSession (Engine.java:64)
    at org.h2.engine.Engine.openSession (Engine.java:176)
    at org.h2.engine.Engine.createSessionAndValidate (Engine.java:154)
    at org.h2.engine.Engine.createSession (Engine.java:137)
    at org.h2.engine.Engine.createSession (Engine.java:27)
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer (SessionRemote.java:354)
    at org.h2.jdbc.JdbcConnection.<init> (JdbcConnection.java:116)
    at org.h2.jdbc.JdbcConnection.<init> (JdbcConnection.java:100)
    at org.h2.Driver.connect (Driver.java:69)
    at java.sql.DriverManager.getConnection (DriverManager.java:664)
    at java.sql.DriverManager.getConnection (DriverManager.java:247)
    at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize (ConnectionFactory.java:163)
    at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection (ConnectionFactory.java:231)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.open (CveDB.java:226)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.<init> (CveDB.java:196)
    at org.owasp.dependencycheck.Engine.openDatabase (Engine.java:950)
    at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:892)
    at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase (Engine.java:716)
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:642)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1186)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:705)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356

**Comment by rajkumarkanjo** [comment]
Try in different network..sometimes it happens because of that

**Comment by stormof** [comment]
The problem was solved after deleting /root/.m2/repository/org/owasp/dependency-check-data/3.0/
But in this case I have to download db again every time.
