### ISSUE TITLE
Error while running dependency check

### ISSUE THREAD

**Issue by kunalsmile** [dependency-check/DependencyCheck#1427]
Please delete any un-needed section from the following issue template:

### Reporting Bugs/Errors
While scanning the code for dependency check I am getting the following error:
C:\Program Files\dependency-check\bin>dependency-check.bat --project Testing --out . --scan "E:\Projects\results2-pixpdq-module/**/*.jar"
Exception in thread "main" java.lang.NullPointerException
        at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1115)
        at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1135)
        at org.owasp.dependencycheck.App.runScan(App.java:259)
        at org.owasp.dependencycheck.App.run(App.java:184)
        at org.owasp.dependencycheck.App.main(App.java:69)

I am performing this scan on windows machine.

**Comment by jeremylong** [comment]
What version of dependency-check are you using? Can you add the `--log odc.log` parameter and provide the log file?

Also - in many cases the `Program Files` directory is protected - and ODC writes data to the directory
