### ISSUE TITLE
Failed to analyze dependency - Invalid header

### ISSUE THREAD

**Issue by rikatz** [dependency-check/DependencyCheck#1430]
This is a bug report.

I'm using DependencyCheck version 3.3.1, and while analyzing a WAR I've got an error analyzing a dependency inside it: nsdnsfix.jar.

Here is the log from the failed part:

```
WARN  - An error occurred while analyzing '/tmp/dctemp12acaa9b-9a81-432d-addf-450186dd3e11/check11596902027025943882tmp/1/public/pages/help/nsdnsfix.jar' (Jar Analyzer).
2018-08-08 18:42:51,990 org.owasp.dependencycheck.AnalysisTask:91
DEBUG -
org.owasp.dependencycheck.analyzer.exception.AnalysisException: A error occurred extracing evidence from spi-web.war: nsdnsfix.jar, analysis may be incomplete; please see the log for more details.
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzeDependency(JarAnalyzer.java:291)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: invalid header field name: javascript.id
        at java.base/java.util.jar.Attributes.read(Attributes.java:435)
        at java.base/java.util.jar.Manifest.read(Manifest.java:250)
        at java.base/java.util.jar.Manifest.<init>(Manifest.java:69)
        at java.base/java.util.jar.JarFile.getManifestFromReference(JarFile.java:415)
        at java.base/java.util.jar.JarFile.getManifest(JarFile.java:401)
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.parseManifest(JarAnalyzer.java:747)
        at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzeDependency(JarAnalyzer.java:274)
        ... 7 common frames omitted
```

Thanks

**Comment by jeremylong** [comment]
This was fixed with #1024, yes the error still occurs and is logged because the JAR file contains an invalid manifest - not much I can do about that. The analysis completes to the best of our ability whereas previously the scan would crash under these conditions.  See the results when I run the CLI:

```
$ ./dependency-check.sh --project test -o . -s ~/Downloads/nsdnsfix.jar 
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (21 ms)
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Aug 14, 2018 7:32:24 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Comments.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
[WARN] An error occurred while analyzing '/Users/jeremy/Downloads/nsdnsfix.jar' (Jar Analyzer).
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (2 seconds)
[ERROR] A error occurred extracing evidence from nsdnsfix.jar, analysis may be incomplete; please see the log for more details.
```

The log file still contains the stack trace you posted above. This is so you know something went wrong - but the issue is out of our control as the JAR has an invalid manifest.
