### ISSUE TITLE
Docker problem with h2 database

### ISSUE THREAD

**Issue by thecampagnards** [dependency-check/DependencyCheck#1449]
Hello,

I'm using owasp/dependency-check:3.3.1 on gitlab-ci

```yaml
dependency:
    stage: report
    image:
        name: owasp/dependency-check:3.3.1
        entrypoint: [""]
    before_script:
    script:
        - /usr/share/dependency-check/bin/dependency-check.sh
            --project IterHotel
            -format=ALL
            --proxyserver="${PROXY_HOST}"
            --proxyport="${PROXY_PORT}"
            --suppression=$CI_PROJECT_DIR/dependency_check_suppressions.xml
            --scan=$CI_PROJECT_DIR/dependency-check
    artifacts:
        paths:
            - dependency-check-report.html
```

When I launch the scan on my gitlab runner or locally I have an error, which seems to be a problem when it's trying to connect to a database.

## Log

On local 

```sh
2018-08-20 15:42:45,297 org.owasp.dependencycheck.analyzer.NexusAnalyzer:137
DEBUG - Nexus analyzer disabled, using Central instead
2018-08-20 15:42:45,303 org.owasp.dependencycheck.utils.Settings:839
DEBUG - Settings.getDataFile() - file: '/usr/share/dependency-check/data'
2018-08-20 15:42:45,304 org.owasp.dependencycheck.utils.Settings:1071
DEBUG - Data directory: /usr/share/dependency-check/data
2018-08-20 15:42:45,305 org.owasp.dependencycheck.utils.Settings:1087
DEBUG - Connection String: 'jdbc:h2:file:/usr/share/dependency-check/data/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;'
2018-08-20 15:42:45,329 org.owasp.dependencycheck.Engine:889
DEBUG - locking for update
2018-08-20 15:42:45,330 org.owasp.dependencycheck.utils.Settings:839
DEBUG - Settings.getDataFile() - file: '/usr/share/dependency-check/data'
2018-08-20 15:42:45,334 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:42:45.331)
2018-08-20 15:42:55,337 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:42:55.336)
2018-08-20 15:43:05,338 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:43:05.338)
2018-08-20 15:43:15,340 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:43:15.34)
2018-08-20 15:43:25,342 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:43:25.342)
2018-08-20 15:43:35,344 org.owasp.dependencycheck.utils.H2DBLock:148
DEBUG - Sleeping thread main (0d5d07975b9297fe0abd9429bb701532) for 10 seconds because an exclusive lock on the database could not be obtained (2018-08-20 15:43:35.344)
```

On gitlab-ci
```sh
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist

Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to obtain an exclusive lock on the H2 database to perform updates
[ERROR] No documents exist
```

## "Fix"

When I add the flag `--data /foo` to the cmd it's working. Is it expected ?

Thanks,
Konstantin

**Comment by MaroonBeret** [comment]
Hi @thecampagnards,

Finally someone with the exact same problem!
I'm also ignoring the entrypoint, else it doesn't even get to my script commands.
Frankly your "--data /foo" entry is not fixing my problem. 

When adding your data entry, I'm getting a Nullpointer.
Got any more tips for this issue?

This is what my gitlab ci job and logs look like:

```
owasp_dep_check:
  stage: security
  image: 
    name: owasp/dependency-check:3.3.1
    entrypoint: [""]
  allow_failure: false
  entrypoint: 
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh 
      --project "Testing" 
      --scan "." 
      --data /foo
```
```
Exception in thread "main" java.lang.NullPointerException
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1115)
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1135)
	at org.owasp.dependencycheck.App.runScan(App.java:259)
	at org.owasp.dependencycheck.App.run(App.java:184)
	at org.owasp.dependencycheck.App.main(App.java:69)
```

**Comment by thecampagnards** [comment]
@MaroonBeret This is my full job conf:

```yaml
dependency:
    stage: report
    image:
        name: owasp/dependency-check
        entrypoint: [""]
    before_script:
        - mkdir data
        - mkdir dependency-check
        - ...
    script:
        - /usr/share/dependency-check/bin/dependency-check.sh
            --project ...
            -format=ALL
            --proxyserver="${PROXY_HOST}"
            --proxyport="${PROXY_PORT}"
            --suppression=$CI_PROJECT_DIR/dependency_check_suppressions.xml
            --scan=$CI_PROJECT_DIR/dependency-check
            --out=$CI_PROJECT_DIR/dependency-check
            --data=$CI_PROJECT_DIR/data
    artifacts:
        paths:
            - "dependency-check/dependency-check-*"
```

Maybe it can help you.

**Comment by MaroonBeret** [comment]
@thecampagnards Thanks a lot, the before_script code did the trick!
