### ISSUE TITLE
Failed to read results from the Node Security Project (NspAnalyzer)

### ISSUE THREAD

**Issue by damianszczepanik** [dependency-check/DependencyCheck#1461]
I have updated Jenkins plugin from 3.2.1. to 3.3.1 and it stopped working due to:

```
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Could not connect to Node Security Platform
[DependencyCheck] Message: Failed to read results from the Node Security Project (NspAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the Node Security Project (NspAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NspAnalyzer.analyzeDependency(NspAnalyzer.java:225)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Could not connect to Node Security Platform
```

Configuration was left unchanged and it stays as:
```
                dependencyCheckAnalyzer datadir: '',
                        hintsFile: '',
                        includeCsvReports: false,
                        includeHtmlReports: true,
                        includeJsonReports: false,
                        includeVulnReports: false,
                        isAutoupdateDisabled: false,
                        outdir: '',
                        scanpath: '',
                        skipOnScmChange: false,
                        skipOnUpstreamChange: false,
                        suppressionFile: "${WORKSPACE}/config/suppressions.xml",
                        zipExtensions: ''
```

I've tried to switch off this analyzer but looks like for NSP there is no switcher https://jenkins.io/doc/pipeline/steps/dependency-check-jenkins-plugin/#-dependencycheckanalyzer-%20invoke%20dependency-check%20analysis

So the question is what has changed from between minor versions that the plugin has stopped working? And how to manage with little effort.

**Comment by stevespringett** [comment]
Enabling/disabling analyzers is a Jenkins global configuration. It cannot be done on a per-build basis.
