### ISSUE TITLE
MS-SQL DB - ERROR - Database schema does not match this version of dependency-check

### ISSUE THREAD

**Issue by SteveParini** [dependency-check/DependencyCheck#1483]
I downloaded the latest version available (3.3.1)

initialized the db using:
https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/data/initialize_mssql.sql
Checked the content of dependency-check-core-3.3.1.jar\data looks the same that can be found on the GitHub link above.

also about the dbStetements.properties that can be found here:
https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/resources/data
I see there are specific properties for every db but MS-SQL server.. does it mean the first without any specificaiton is the one for MS-SQL? or am I missing something?

found that following a different thread on the same error name but relative to a MySQL db (https://github.com/jeremylong/DependencyCheck/issues/804) 

I'm trying to execute:
.\dependency-check.bat --updateonly -l .\command-line-log.txt

I assume this is the command to download the CPE data and set it inside the DB .. 

```
DEBUG - Loading driver 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
2018-09-11 09:29:26,108 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:123
DEBUG - Loading driver from: "C:\Program Files\Microsoft JDBC Driver 6.2 for SQL Server\sqljdbc_6.2\enu\mssql-jdbc-6.2.2.jre7.jar"
2018-09-11 09:29:26,192 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:154
DEBUG - Loading database connection
2018-09-11 09:29:26,192 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:155
DEBUG - Connection String: jdbc:sqlserver://localhost;databaseName=DependencyChecker;integratedSecurity=true
2018-09-11 09:29:26,192 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:156
DEBUG - Database User: dcuser
2018-09-11 09:29:26,658 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:192
DEBUG - 
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Invalid application database schema
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.ensureSchemaVersion(ConnectionFactory.java:426)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:190)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:950)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:892)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:871)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:377)
	at org.owasp.dependencycheck.App.run(App.java:162)
	at org.owasp.dependencycheck.App.main(App.java:69)
2018-09-11 09:29:26,658 org.owasp.dependencycheck.App:167
ERROR - Database schema does not match this version of dependency-check
```

I'm trying to use integratedSecurity=true could this be a problem?
I'm asking because I found no mention of such authentication method in DC documentation. 

thanks in advance

**Comment by jeremylong** [comment]
On the database can you run:

```sql
SELECT value FROM properties
```

And post the results?

**Comment by SteveParini** [comment]
yep--> 3.3.1

**Comment by jeremylong** [comment]
I'm not asking what version of ODC you are running.  I am asking you to run `SELECT value FROM properties` on the database.  If this returns 3.3.1 - then that is the obvious problem as the current database schema is 3.0. See https://github.com/jeremylong/DependencyCheck/blob/354fef169487788aa2a515aa49c5efd45040c08a/core/src/main/resources/data/initialize_mssql.sql#L36

Rerun the (unmodified) initialize_mysql.sql script.
