### ISSUE TITLE
ClassNotFoundException IOFileFilter with Maven 3.5.3

### ISSUE THREAD

**Issue by sfuhrm** [dependency-check/DependencyCheck#1555]
When verifying my artifact with Apache Maven 3.5.3,  I get a 

```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.filefilter.IOFileFilter
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 41 more
```

The check plugin is used like this:

```xml
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>3.3.4</version>
                <configuration>
                    <cveValidForHours>12</cveValidForHours>
                    <failBuildOnCVSS>4</failBuildOnCVSS>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

The maven output can be found [here](https://gist.github.com/sfuhrm/d28e37f28f991d282602dd988ec2a2d6)

Any recommendations?

**Comment by sfuhrm** [comment]
This error came due to a broken JAR in my .m2 cache - sorry.
