### ISSUE TITLE
[ERROR - null] Analysis task was cancelled

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1556]
## from Log:

2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?debug)
2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?minimatch)
2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?tough-cookie)
2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?request)
2018-11-11 21:01:47,270 org.owasp.dependencycheck.Engine:1092
**ERROR - null**

**Analysis task was cancelled.**
2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?http-proxy-agent)
2018-11-11 21:01:47,271 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?tough-cookie)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?https-proxy-agent)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?concat-stream)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?lodash)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?cryptiles)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.Engine:1093
**DEBUG - 
java.util.concurrent.CancellationException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:767)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:671)
	at org.owasp.dependencycheck.App.runScan(App.java:250)
	at org.owasp.dependencycheck.App.run(App.java:184)
	at org.owasp.dependencycheck.App.main(App.java:69)**
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?debug)
2018-11-11 21:01:47,272 org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer:286
DEBUG - IdentifiersMatch=false (package-lock.json, package-lock.json?minimatch)
...

**Comment by jeremylong** [comment]
1. What version of dependency-check are you using?
2. Is the project you are scanning open source? (i.e. is it possible to download and attempt to recreate the issue on our side?)

**Comment by githubhs17** [comment]
1. we are always using the latest version of the docker image (docker pull owasp/dependency-check)
2. No open souirce, download not possible

**Comment by markdenihan** [comment]
@jeremylong @stevespringett I'm seeing a very similar issue to this. Should it stay nested here or should I create a new one?

I get a null message as well followed with a java.util.concurrent.CancellationException stack trace;
```
16:25:28 [DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
16:25:28 [DependencyCheck] Executing Dependency-Check with the following options:
16:25:28 [DependencyCheck]  -name = product_dependency_scan_x.x.x
16:25:28 [DependencyCheck]  -scanPath = /home/user/directory/workspace/product_dependency_scan_x.x.x
16:25:28 [DependencyCheck]  -outputDirectory = /home/user/directory/workspace/product_dependency_scan_x.x.x/target
16:25:28 [DependencyCheck]  -dataDirectory = /home/user/directory/dependencycheck-db
16:25:28 [DependencyCheck]  -suppressionFile = /home/user/directory/workspace/product_dependency_scan_x.x.x/dependency_check/suppressions.xml
16:25:28 [DependencyCheck]  -hintsFile = /home/user/directory/workspace/product_dependency_scan_x.x.x/dependency_check/hints.xml
16:25:28 [DependencyCheck]  -dataMirroringType = NIST CPE/CVE
16:25:28 [DependencyCheck]  -cveUrl12Modified = http://up-to-date.internal.mirror.int/downloads/nist/nvdcve-modified.xml.gz
16:25:28 [DependencyCheck]  -cveUrl20Modified = http://up-to-date.internal.mirror.int/downloads/nist/nvdcve-2.0-modified.xml.gz
16:25:28 [DependencyCheck]  -cveUrl12Base = http://up-to-date.internal.mirror.int/downloads/nist/nvdcve-%d.xml.gz
16:25:28 [DependencyCheck]  -cveUrl20Base = http://up-to-date.internal.mirror.int/downloads/nist/nvdcve-2.0-%d.xml.gz
16:25:28 [DependencyCheck]  -isQuickQueryTimestampEnabled = true
16:25:28 [DependencyCheck]  -jarAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -nodePackageAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -nodeAuditAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -retireJsAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -composerLockAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -pythonPackageAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
16:25:28 [DependencyCheck]  -rubyGemAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -archiveAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -assemblyAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -nuspecAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -centralAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -nexusAnalyzerEnabled = false
16:25:28 [DependencyCheck]  -artifactoryAnalyzerEnabled = false
16:25:28 [DependencyCheck]  -autoconfAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -cmakeAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -opensslAnalyzerEnabled = true
16:25:28 [DependencyCheck]  -tempPath = /home/user/directory/tmp
16:25:28 [DependencyCheck]  -showEvidence = true
16:25:28 [DependencyCheck]  -formats = XML HTML 
16:25:28 [DependencyCheck]  -autoUpdate = false
16:25:28 [DependencyCheck]  -updateOnly = false
16:25:28 [DependencyCheck] Scanning: /home/user/directory/workspace/product_dependency_scan_x.x.x
16:27:18 [DependencyCheck] Analyzing Dependencies
16:51:41 [DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
16:51:41 [DependencyCheck] Exception Caught: java.util.concurrent.CancellationException
16:51:41 [DependencyCheck] Message: null
16:51:41 [DependencyCheck] java.util.concurrent.CancellationException
16:51:41 [DependencyCheck] 	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
16:51:41 [DependencyCheck] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
16:51:41 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:767)
16:51:41 [DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:671)
16:51:41 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
16:51:41 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
16:51:41 [DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
16:51:41 [DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
16:51:41 [DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
16:51:41 [DependencyCheck] 	at hudson.remoting.Request$2.run(Request.java:336)
16:51:41 [DependencyCheck] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
16:51:41 [DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:51:41 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:51:41 [DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:51:41 [DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
16:51:41 [DependencyCheck] 
16:51:48 Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE
```

The Jenkins system logs do not help with zoning in on what might be going wrong;
```
Jan 14, 2019 2:00:27 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Started
Jan 14, 2019 2:00:30 PM org.owasp.dependencycheck.analyzer.ArchiveAnalyzer extractFiles
WARNING: Exception extracting archive 'cb-never-called-1.0.1.tgz'.
Jan 14, 2019 2:00:53 PM org.owasp.dependencycheck.analyzer.ArchiveAnalyzer extractFiles
WARNING: Exception extracting archive 'cb-never-called-1.0.1.tgz'.
Jan 14, 2019 2:00:56 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Archive Analyzer (28 seconds)
Jan 14, 2019 2:00:56 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished File Name Analyzer (0 seconds)
Jan 14, 2019 2:01:04 PM org.owasp.dependencycheck.analyzer.JarAnalyzer collectClassNames
WARNING: Unable to open jar file 'invalid-jnet.jar'.
Jan 14, 2019 2:01:04 PM org.owasp.dependencycheck.analyzer.JarAnalyzer collectClassNames
WARNING: Unable to open jar file 'README.invalid.jar'.
Jan 14, 2019 2:01:17 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Jar Analyzer (21 seconds)
Jan 14, 2019 2:01:44 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Central Analyzer (27 seconds)
Jan 14, 2019 2:01:44 PM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: ----------------------------------------------------
Jan 14, 2019 2:01:44 PM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.
Jan 14, 2019 2:01:44 PM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: ----------------------------------------------------
Jan 14, 2019 2:01:44 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Python Distribution Analyzer (0 seconds)
Jan 14, 2019 2:01:45 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Python Package Analyzer (0 seconds)
Jan 14, 2019 2:01:45 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Autoconf Analyzer (0 seconds)
Jan 14, 2019 2:01:45 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished OpenSSL Source Analyzer (0 seconds)
Jan 14, 2019 2:01:45 PM org.owasp.dependencycheck.analyzer.NodePackageAnalyzer analyzeDependency
WARNING: Analyzing `/home/user/directory/workspace/product_dependency_scan_x.x.x/install/target/sub-product-x.x.x/npm-shrinkwrap.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
Jan 14, 2019 2:01:45 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Node.js Package Analyzer (0 seconds)
Jan 14, 2019 2:03:54 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Dependency Merging Analyzer (128 seconds)
Jan 14, 2019 2:03:54 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Version Filter Analyzer (0 seconds)
Jan 14, 2019 2:03:54 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Hint Analyzer (0 seconds)
Jan 14, 2019 2:03:54 PM org.owasp.dependencycheck.analyzer.CPEAnalyzer open
INFO: Created CPE Index (0 seconds)
Jan 14, 2019 2:03:54 PM org.owasp.dependencycheck.analyzer.CPEAnalyzer prepareAnalyzer
INFO: Skipping CPE Analysis for npm
Jan 14, 2019 2:03:57 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished CPE Analyzer (3 seconds)
Jan 14, 2019 2:03:57 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished False Positive Analyzer (0 seconds)
Jan 14, 2019 2:03:58 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished NVD CVE Analyzer (1 seconds)
Jan 14, 2019 2:03:59 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Node Audit Analyzer (0 seconds)
Jan 14, 2019 2:04:19 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished RetireJS Analyzer (20 seconds)
Jan 14, 2019 2:04:20 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Vulnerability Suppression Analyzer (1 seconds)
Jan 14, 2019 2:24:20 PM org.owasp.dependencycheck.Engine throwFatalExceptionCollection
SEVERE: null

Analysis task was cancelled.
```

**Comment by markdenihan** [comment]
Through a process of elimination this problem is happening in my above example due to the RetireJS analyser.

**Comment by markdenihan** [comment]
@jeremylong Do you need any more information for this issue?

**Comment by jeremylong** [comment]
Sorry for the delay. As you are mirroring the NVD your build system likely can't reach out to the github to pull down the retireJS repository (located here: https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json).  We just added (within the last few days) the ability to easily configure this URL.

When 5.0.0 (or possible 5.0.0-m3) is released you should be able to configure the retireJS analyzer's URL and resolve the above problem.
