### ISSUE TITLE
dependency-check.bat Could not connect to Central search in the intranet

### ISSUE THREAD

**Issue by TomZhou2006** [dependency-check/DependencyCheck#1593]
###The company needs to perform security detection on the Jar package, but **it cannot connect to the** ###**external network**.  so i find DepandencyCheck.
###First of all, I use the tool to detect on the external network computer, download the data and related ###files, the project can be detected normally; 
      **dependency-check.bat** --project Testing --out . --scan [path to jar files to be scanned]
###then put the tool with all the files on the intranet  for detection, and an error occurs, as follows:

[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[ERROR] Unable to resolve domain 'nvd.nist.gov'
[WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (3 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:332)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:225)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: search.maven.org
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:140)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:310)
	... 8 common frames omitted
[WARN] An error occurred while analyzing 'E:\DependencyCheck\cli\target\release\repo\org\apache\lucene\lucene-queries\7.5.0\lucene-queries-7.5.0.jar' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:332)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:225)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: search.maven.org
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:140)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:310)
	... 8 common frames omitted
[WARN] An error occurred while analyzing 

anyone who can help me? thanks

**Comment by TomZhou2006** [comment]
[WARN] An error occurred while analyzing 'E:\DependencyCheck\cli\target\release\repo\org\apache\lucene\lucene-queryparser\7.5.0\lucene-queryparser-7.5.0.jar' (Central Analyzer).
[INFO] Finished Central Analyzer (283 seconds)
[INFO] Finished Assembly Analyzer (10 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (58 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (62 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (2 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (366 seconds)
[ERROR] Unable to download the NVD CVE data.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.

**Comment by jeremylong** [comment]
After updating the data from the Internet - if you then go into an offline mode you would need to add the `noupdate` and `disableCentral` flags:

```
dependency-check.bat --project Testing --noupdate --disableCentral --out . --scan [path to jar files to be scanned]
```

**Comment by TomZhou2006** [comment]
thanks, u


> After updating the data from the Internet - if you then go into an offline mode you would need to add the `noupdate` and `disableCentral` flags:
> 
> ```
> dependency-check.bat --project Testing --noupdate --disableCentral --out . --scan [path to jar files to be scanned]
> ```
thanks, and another question:
db file is enough?  Is it necessary to download files suffixed with xml.gz, such as vdcve-modified.xml.gz, and then execute the specified parameter？

**Comment by jeremylong** [comment]
For mirroring the NVD I would suggest using https://github.com/stevespringett/nist-data-mirror.  Depending on which version of ODC you are using you either need all of the xml.gz files (for both schema 1.1 and 2.0) or you need the *.json.gz and *.meta files.  The nist-data-mirror is capable of pulling both.
