### ISSUE TITLE
Could not connect to Node Audit API: 503 No backends available

### ISSUE THREAD

**Issue by markdenihan** [dependency-check/DependencyCheck#1679]
Running dependency check v4.0.2 on a package-lock.json via Jenkins fails with the attached console logs / system logs

Jenkins slave/master are able to communicate with the registry.npmjs.org/-/npm/v1/security/audits API and get 200 responses.

Looks like the dependency check plugin just gets 503 errors. 

```
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = dc_job
[DependencyCheck]  -scanPath = /home/ausernamehere/thingthatbuilds/workspace/dc_job/target
[DependencyCheck]  -outputDirectory = /home/ausernamehere/thingthatbuilds/workspace/dc_job
[DependencyCheck]  -dataDirectory = /home/ausernamehere/thingthatbuilds/dependencycheck-db
[DependencyCheck]  -suppressionFile = /home/ausernamehere/thingthatbuilds/workspace/dc_job/tests/security/dependency-check/suppressions.xml
[DependencyCheck]  -dataMirroringType = NIST CPE/CVE
[DependencyCheck]  -cveUrl12Modified = http://internal.mirror.int/downloads/nist/nvdcve-modified.xml.gz
[DependencyCheck]  -cveUrl20Modified = http://internal.mirror.int/downloads/nist/nvdcve-2.0-modified.xml.gz
[DependencyCheck]  -cveUrl12Base = http://internal.mirror.int/downloads/nist/nvdcve-%d.xml.gz
[DependencyCheck]  -cveUrl20Base = http://internal.mirror.int/downloads/nist/nvdcve-2.0-%d.xml.gz
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = true
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = false
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -bundleAuditPath = /usr/lib64/ruby/gems/2.1.0/gems/bundler-audit-0.6.0/bin/bundler-audit
[DependencyCheck]  -tempPath = /home/ausernamehere/thingthatbuilds/tmp
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML VULN 
[DependencyCheck]  -autoUpdate = false
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: /home/ausernamehere/thingthatbuilds/workspace/dc_job/target
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Could not connect to Node Audit API
[DependencyCheck] Message: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Could not connect to Node Audit API
[DependencyCheck] 	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
[DependencyCheck] 	... 7 more
[DependencyCheck] 
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Could not connect to Node Audit API
[DependencyCheck] Message: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Could not connect to Node Audit API
[DependencyCheck] 	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
[DependencyCheck] 	... 7 more
[DependencyCheck] 
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Could not connect to Node Audit API
[DependencyCheck] Message: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Could not connect to Node Audit API
[DependencyCheck] 	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
[DependencyCheck] 	... 7 more
[DependencyCheck] 
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Cause: Could not connect to Node Audit API
[DependencyCheck] Message: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Could not connect to Node Audit API
[DependencyCheck] 	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
[DependencyCheck] 	... 7 more
[DependencyCheck] 
Build step 'Invoke Dependency-Check analysis' changed build result to FAILURE
```

```
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.Engine executeAnalysisTasks
Starting Node Audit Analyzer
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.Engine getExecutorService
Parallel processing with up to 4 threads: Node Audit Analyzer.
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:57:56 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:58:03 PM FINE org.owasp.dependencycheck.data.nodeaudit.NpmAuditParser parse
Parsing JSON node
Jan 11, 2019 2:58:03 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:58:03 PM FINE org.owasp.dependencycheck.data.nodeaudit.NpmAuditParser parse
Parsing JSON node
Jan 11, 2019 2:58:03 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:58:04 PM FINE org.owasp.dependencycheck.data.nodeaudit.NpmAuditParser parse
Parsing JSON node
Jan 11, 2019 2:58:04 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:58:06 PM FINE org.owasp.dependencycheck.data.nodeaudit.NpmAuditParser parse
Parsing JSON node
Jan 11, 2019 2:58:06 PM FINE org.owasp.dependencycheck.AnalysisTask call
Begin Analysis of '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer)
Jan 11, 2019 2:58:15 PM FINE org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch submitPackage
Could not connect to Node Audit API. Received response code: 503 No backends available
Jan 11, 2019 2:58:15 PM FINE org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer analyzeDependency
Error reading dependency or connecting to NPM Audit API
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 11, 2019 2:58:15 PM WARNING org.owasp.dependencycheck.AnalysisTask call
An error occurred while analyzing '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer).
Jan 11, 2019 2:58:15 PM FINE org.owasp.dependencycheck.AnalysisTask call
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
Caused: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch submitPackage
Could not connect to Node Audit API. Received response code: 503 No backends available
Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer analyzeDependency
Error reading dependency or connecting to NPM Audit API
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 11, 2019 2:58:16 PM WARNING org.owasp.dependencycheck.AnalysisTask call
An error occurred while analyzing '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer).
Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.AnalysisTask call
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
Caused: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch submitPackage
Could not connect to Node Audit API. Received response code: 503 No backends available
Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer analyzeDependency
Error reading dependency or connecting to NPM Audit API
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 11, 2019 2:58:16 PM WARNING org.owasp.dependencycheck.AnalysisTask call
An error occurred while analyzing '/home/ausernamehere/thingthatbuilds/workspace/dc_job/target/pathomitted/package-lock.json' (Node Audit Analyzer).
Jan 11, 2019 2:58:16 PM FINE org.owasp.dependencycheck.AnalysisTask call
java.io.IOException: Could not connect to Node Audit API
	at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:137)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
Caused: org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to read results from the NPM Audit API (NodeAuditAnalyzer); the analyzer is being disabled and may result in false negatives.
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:223)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stevespringett** [comment]
The plugin uses the Jenkins proxy configuration which is independent from the configuration of the OS. Testing connectivity on one doesn't mean the other will work. Ensure Jenkins (and the Java runtime) is configured property to access the Internet. Also, there are global configuration parameters for proxy

**Comment by markdenihan** [comment]
@stevespringett You're right, that is the root cause of this problem. Thanks for the info
