### ISSUE TITLE
"SEVERE: No documents exist..... unable to continue" and  SAXParser error

### ISSUE THREAD

**Issue by mcgyver5** [dependency-check/DependencyCheck#169]
Hi!  Thanks for providing this tool.  It is sorely needed and will really help application security.  

I am debugging this error and I'm not sure what to do next:

My version:  dependency-check-1.2.5-release (on Windows)

 I got `SEVERE: No documents exist  Unable to continue dependency-check analysis` during "doUpdates".
The outcome is that I got incomplete results (no reported vulnerabilities) even when I ran the scan against a lib directory with known vulnerable jars.  

From the logs:

```
Nov 17, 2014 10:35:24 AM org.owasp.dependencycheck.Engine doUpdates
WARNING: Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
Nov 17, 2014 10:35:24 AM org.owasp.dependencycheck.Engine doUpdates
FINE: Unable to update details for org.owasp.dependencycheck.data.update.NvdCveUpdater
org.owasp.dependencycheck.data.update.exception.UpdateException: org.xml.sax.SAXParseException; systemId: file:/C:/Users/grinchon/AppData/Local/Temp/cve_1_2_2010_7370766266292394489.xml; lineNumber: 2; columnNumber: 2; The markup in the document following the root element must be well-formed.
    at org.owasp.dependencycheck.data.update.task.ProcessTask.processFiles(ProcessTask.java:172)
    at org.owasp.dependencycheck.data.update.task.ProcessTask.call(ProcessTask.java:118)
    at org.owasp.dependencycheck.data.update.task.ProcessTask.call(ProcessTask.java:47)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/grinchon/AppData/Local/Temp/cve_1_2_2010_7370766266292394489.xml; lineNumber: 2; columnNumber: 2; The markup in the document following the root element must be well-formed.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$TrailingMiscDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at org.owasp.dependencycheck.data.update.task.ProcessTask.importXML(ProcessTask.java:146)
    at org.owasp.dependencycheck.data.update.task.ProcessTask.processFiles(ProcessTask.java:164)
    ... 6 more

Nov 17, 2014 10:35:33 AM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.
Nov 17, 2014 10:35:33 AM org.owasp.dependencycheck.Engine analyzeDependencies
FINE: null
org.owasp.dependencycheck.exception.NoDataException: No documents exist
    at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:503)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:315)
    at org.owasp.dependencycheck.App.runScan(App.java:119)
    at org.owasp.dependencycheck.App.run(App.java:96)
    at org.owasp.dependencycheck.App.main(App.java:63)
```

**Comment by jeremylong** [comment]
Please upgrade to 1.2.6 - which was released on 11/16/2014. If the issue persists please let us know.
