### ISSUE TITLE
Jenkins taking lot of time to build in analyzing dependencies

### ISSUE THREAD

**Issue by chakreshkolluru** [dependency-check/DependencyCheck#1708]
[DependencyCheck]  -scanPath = 
[DependencyCheck]  -outputDirectory = 
[DependencyCheck]  -dataDirectory = /
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = false
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = false
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = false
[DependencyCheck]  -pythonPackageAnalyzerEnabled = false
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = false
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = false
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = false
[DependencyCheck]  -archiveAnalyzerEnabled = false
[DependencyCheck]  -assemblyAnalyzerEnabled = false
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = false
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = false
[DependencyCheck]  -nuspecAnalyzerEnabled = false
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = false
[DependencyCheck]  -cmakeAnalyzerEnabled = false
[DependencyCheck]  -opensslAnalyzerEnabled = false
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Data directory created
[DependencyCheck] Scanning: 
[DependencyCheck] Analyzing Dependencies

It is taking 1 hour to run build . I don't know what is the issue. Can you please help me to resolve this issue. As it is wasting lot of time.

**Comment by stevespringett** [comment]
* Utilize an NVD mirror to prevent re-downloading all the time
* Use a shared data directory to prevent the creation/maintenance of per-job data directories (the default)
* Disable autoUpdate on individual jobs
* Create a single, blocking job that performs the autoUpdate on the shared data directory

Doing the above will nearly eliminate all unnecessary and time-consuming overhead.

**Comment by nsaud01** [comment]
I'm trying to set the directory in which I have my NVD updates going (`-dataDirectory = /var/jenkins_home/workspace/nvd_update/dependency-check-data`) for the `dependencyCheckAnalyzer`, however I'm receiving this error:

````
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Dependency Check)
[Pipeline] dependencyCheckAnalyzer
19:27:53 [DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = fms-it-test
[DependencyCheck]  -scanPath = /home/fmsadm/workspace/nsaud/fms-it-test
[DependencyCheck]  -outputDirectory = /home/fmsadm/workspace/nsaud/fms-it-test
[DependencyCheck]  -dataDirectory = /var/jenkins_home/workspace/nvd_update/dependency-check-data
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML VULN JSON 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: /home/fmsadm/workspace/nsaud/fms-it-test
Seen 1,011 remote branches
 > git show-ref --tags -d # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f150fe16df4ee6f1800892355ccc296b19f94f6b
 > git rev-list --no-walk f150fe16df4ee6f1800892355ccc296b19f94f6b # timeout=10
 > git rev-list --no-walk f150fe16df4ee6f1800892355ccc296b19f94f6b # timeout=10
 > git rev-list --no-walk f150fe16df4ee6f1800892355ccc296b19f94f6b # timeout=10
[Pipeline] dependencyCheckPublisher
19:27:59 [DependencyCheck] Skipping publisher since build result is FAILURE
[Pipeline] archiveArtifacts
19:27:59 Skipped archiving because build is not successful
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Prepare)
[Pipeline] sh
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.nvdcve.DatabaseException
[DependencyCheck] Cause: Unable to create the h2 data directory '/var/jenkins_home/workspace/nvd_update/dependency-check-data'
[DependencyCheck] Message: Unable to retrieve the database connection string
[DependencyCheck] org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to retrieve the database connection string
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:141)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:950)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:892)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:716)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[DependencyCheck] 	at hudson.remoting.Request$2.run(Request.java:369)
[DependencyCheck] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: java.io.IOException: Unable to create the h2 data directory '/var/jenkins_home/workspace/nvd_update/dependency-check-data'
[DependencyCheck] 	at org.owasp.dependencycheck.utils.Settings.getH2DataDirectory(Settings.java:1159)
[DependencyCheck] 	at org.owasp.dependencycheck.utils.Settings.getConnectionString(Settings.java:1102)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:136)
[DependencyCheck] 	... 18 more
[DependencyCheck] 
````

Any guidance would be greatly appreciated.
