### ISSUE TITLE
Ananlysis being cancelled after approx 20 minutes

### ISSUE THREAD

**Issue by mjdavies** [dependency-check/DependencyCheck#1728]
Hi Everyone

I'm using the 4.0.2 Jenkins Plugin and getting an error.

When I run exactly the same code on a duplicate of the machine(built with ansible and terraofrm) the analysis completes in about 3 minutes.

There may have been some setup or configuration steps taken on the server that doesn't work, but it's used by alot of people so I'm having alot of trouble tracking it down.

Here's the pipeline code I'm using

```
pipeline {
    agent { label "master" }
    stages {
        stage("scan public") {
            steps {
                dependencyCheckAnalyzer datadir: '/var/jenkins_home/owasp/updates',
                hintsFile: '', 
                includeCsvReports: false, 
                includeVulnReports: false, 
                includeHtmlReports: false, 
                includeJsonReports: false, 
                isAutoupdateDisabled: true, 
                outdir: '', 
                scanpath: '/var/jenkins_home/appcode', 
                skipOnScmChange: false, 
                skipOnUpstreamChange: false, 
                suppressionFile: '', 
                zipExtensions: ''

                dependencyCheckPublisher canComputeNew: false, 
                failedTotalHigh: "1", 
                failedTotalNormal: "4", 
                failedTotalLow: "100"

                archiveArtifacts allowEmptyArchive: true, 
                artifacts: '**/dependency-check-report.xml', 
                onlyIfSuccessful: true
            }

        }
    }
}
```

And here's the error that I get from the pipeline

```
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: java.util.concurrent.CancellationException
[DependencyCheck] Message: null
[DependencyCheck] java.util.concurrent.CancellationException
[DependencyCheck] 	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
[DependencyCheck] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:767)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:671)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:206)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
[DependencyCheck] 	at hudson.security.ACL.impersonate(ACL.java:290)
[DependencyCheck] 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
[DependencyCheck] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
```

Here's the error from the logging side

```
Feb 05, 2019 9:20:31 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Started
Feb 05, 2019 9:20:31 AM org.owasp.dependencycheck.analyzer.ArchiveAnalyzer extractFiles
WARNING: Exception extracting archive 'cb-never-called-1.0.1.tgz'.
Feb 05, 2019 9:20:31 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Archive Analyzer (0 seconds)
Feb 05, 2019 9:20:32 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished File Name Analyzer (0 seconds)
Feb 05, 2019 9:20:32 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Jar Analyzer (0 seconds)
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Central Analyzer (2 seconds)
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: ----------------------------------------------------
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.analyzer.AssemblyAnalyzer prepareFileTypeAnalyzer
SEVERE: ----------------------------------------------------
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Python Distribution Analyzer (0 seconds)
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Python Package Analyzer (0 seconds)
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Autoconf Analyzer (0 seconds)
Feb 05, 2019 9:20:35 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Node.js Package Analyzer (0 seconds)
Feb 05, 2019 9:21:06 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Dependency Merging Analyzer (30 seconds)
Feb 05, 2019 9:21:06 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Version Filter Analyzer (0 seconds)
Feb 05, 2019 9:21:07 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Hint Analyzer (1 seconds)
Feb 05, 2019 9:21:11 AM org.owasp.dependencycheck.analyzer.CPEAnalyzer open
INFO: Created CPE Index (3 seconds)
Feb 05, 2019 9:21:11 AM org.owasp.dependencycheck.analyzer.CPEAnalyzer prepareAnalyzer
INFO: Skipping CPE Analysis for npm
Feb 05, 2019 9:21:12 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished CPE Analyzer (5 seconds)
Feb 05, 2019 9:21:13 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished False Positive Analyzer (0 seconds)
Feb 05, 2019 9:21:13 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished NVD CVE Analyzer (0 seconds)
Feb 05, 2019 9:21:13 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Node Audit Analyzer (0 seconds)
00:00  INFO: Vulnerability found: jquery below 3.0.0-beta1
00:00  INFO: Vulnerability found: jquery below 2.2.0
00:05  INFO: Vulnerability found: angularjs below 1.5.0-rc2
00:05  INFO: Vulnerability found: angularjs below 1.6.3
00:05  INFO: Vulnerability found: angularjs below 1.6.3
00:05  INFO: Vulnerability found: angularjs below 1.6.5
00:16  INFO: Vulnerability found: moment.js below 2.11.2
00:16  INFO: Vulnerability found: moment.js below 2.11.2
00:16  INFO: Vulnerability found: moment.js below 2.11.2
00:39  INFO: Vulnerability found: jquery below 1.9.0b1
00:39  INFO: Vulnerability found: jquery below 1.12.0
00:43  INFO: Vulnerability found: jquery below 3.0.0-beta1
00:43  INFO: Vulnerability found: jquery below 2.2.0
Feb 05, 2019 9:21:57 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished RetireJS Analyzer (44 seconds)
Feb 05, 2019 9:21:59 AM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Finished Vulnerability Suppression Analyzer (1 seconds)
Feb 05, 2019 9:41:59 AM org.owasp.dependencycheck.Engine throwFatalExceptionCollection
SEVERE: null

Analysis task was cancelled.
```

Does anyone have any ideas what I'm doing wrong, or if there's any more information you need me to supply, please say.

Thanks in advance

Matt

**Comment by stevespringett** [comment]
Does Jenkins debug logging on org.owasp provide any additional information?

**Comment by jeremylong** [comment]
There is a configured timeout of 20 minutes; see 
https://github.com/jeremylong/DependencyCheck/blob/49e00c81f0ee4f02027803132d7c4d70163efe33/core/src/main/resources/dependencycheck.properties#L27

I've never seen an analysis take that long. You can over-ride the timeout by setting the `odc.analysis.timeout` as an environment variable and setting the value greater then 20.

**Comment by mjdavies** [comment]
Thanks @jeremylong and @stevespringett for getting back to me.

@jeremylong 
Thanks for digging out the timeout, I was searching for the seconds value in the codebase, didn't think to check for the minutes.  So at least we know the mechanism behind it timing out.

@stevespringett 
"Does Jenkins debug logging on org.owasp provide any additional information?"

No, unfortunately.  The most logs I've got are the ones provided above, the org.owasp logs just stops at the timeout.

I get a lot of these messages in the logs, but not sure if they're a problem or not.

```
IdentifiersMatch=false (floor-year.js, package.json)
Feb 17, 2019 6:58:29 PM FINE org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer cpeIdentifiersMatch
```

What is completely nuts is that I've just tried to run it again on the duplicate machine with plenty of RAM, to check that the logs correspond with the Live machine, and it's now doing the same thing on the duplicate machine, and timing out!!

I'm going to try and repeat the process and see if I can duplicate the error.  

Destroy VM, rebuild VM, configure with ansible, create H2 database first time, scan the project, then scan the project again.

Has this shed any light on a possible cause for you both?

Thanks again for all your help with this.

**Comment by mjdavies** [comment]
ok, bit more information, I think we may be getting closer to working this out

Both of the jenkins installs are docker containers

If I bounce the container on the duplicate machine, it starts to work again.

**Comment by mjdavies** [comment]
Ok, I now have a repeatable failure process on both machines, and a repeatable success process on both machines.

## Working Procedure
1. Delete any log recorders in jenkins, that are monitoring org.owasp in the jenkins system logs.
2. Restart the service/container running jenkins
3. Run the pipeline above to scan the app code

Re-running the pipeline will succeed every time

## Breaking procedure
1. Follow the steps in the working procedure
2. Create a log recorder in Jenkins to monitor org.owasp and catch ALL logs
3. Run the pipeline above

The pipeline will fail with the logging output that is higher up in this issue, and will continue to fail on reruns until the log recorder is deleted and the container is restarted.

Any ideas?

I'm leaning towards how jenkins is running inside a container now, how it manages logs, how we're binding folders from the host machine to the container, etc etc.  Lot's of variables in that lot.

**Comment by stevespringett** [comment]
Not a Dependency-Check issue and it doesn't seem to be a Jenkins issue. The logs can be big, especially for large projects. I'd recommend looking into the container and filesystem setup.

I know Jenkins running in a container with Dependency-Check works, as I've done it - lots of disposable containers that get spun up when needed and killed when not. I don't know how our admins handled persistent storage on these containers though. So I don't have any specific advice.

**Comment by mjdavies** [comment]
Thanks @stevespringett 

I'm sure dependency check does work in a container, I am using it myself in other projects.  I suspect as you've pointed out there's an issue with the filesystem setup inside the containers that is causing a problem.

Feel free to close this down.
