### ISSUE TITLE
No documents exist

### ISSUE THREAD

**Issue by jpochat** [dependency-check/DependencyCheck#174]
Hi
We have "No documents exist" issue with Dependency Check Maven plugin 1.2.7:

Dec 11, 2014 10:08:07 AM org.owasp.dependencycheck.Engine analyzeDependencies
FINE: null
org.owasp.dependencycheck.exception.NoDataException: No documents exist
      at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:527)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:347)
       at org.owasp.dependencycheck.maven.DependencyCheckMojo.executeDependencyCheck(DependencyCheckMojo.java:348)
       at org.owasp.dependencycheck.maven.DependencyCheckMojo.executeDependencyCheck(DependencyCheckMojo.java:310)
       at org.owasp.dependencycheck.maven.DependencyCheckMojo.performExecute(DependencyCheckMojo.java:549)
       at org.owasp.dependencycheck.maven.ReportAggregationMojo.execute(ReportAggregationMojo.java:214)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
      at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
   at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
      at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
   at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Any idea?
Thanks in advance.

**Comment by jeremylong** [comment]
This exception occurs when the local copy of the NVD is not present. The easiest way to get this exception is to download a new copy of the command line tool and run the following:

```
bin\dependency-check.bat -n -a t -s repo -o .
```

Because the -n argument is specified it does not attempt to update the local data from nvd.nist.gov. The tool needs to run at least once with the updates enabled (and any necessary proxy information).

The other way this error shows up is when updates are allowed, but the system is not online or is not correctly configured to utilize the proxy (if required). However, in this case you should have seen another warning earlier in the log indicating that the data from the NVD could not be downloaded and it should have provided a few suggestions on how to resolve the issue.

Does that help solve your problem?

--Jeremy

**Comment by jpochat** [comment]
Sorry for noise, issue was due to our internal CI environment which didn't have access to public NVD.
Thanks.

**Comment by jeremylong** [comment]
no worries - one thing I know people have done is setup a server with access to the Internet and mirror an internal copy of the NVD files on the internal network. I should write some documentation on various types of setups like this...  more on the todo list ;)

--Jeremy
