### ISSUE TITLE
NullPointerException in org.owasp.dependencycheck.App.determineReturnCode(App.java:296)

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1746]
4.0.2: Pulling from owasp/dependency-check
. . .
Status: Image is up to date for owasp/dependency-check:4.0.2
. . .
+ docker run . . .
[INFO] Checking for updates
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - Modified  (2051 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (1667 ms)
[INFO] Begin database maintenance.
[INFO] End database maintenance.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (13033 ms)
[INFO] Analysis Started
[WARN] Exception extracting archive 'cb-never-called-1.0.1.tgz'.
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Assembly Analyzer (0 seconds)
. . .
[INFO] Finished Node.js Package Analyzer (1 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Node Audit Analyzer (23 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (1 seconds)
[INFO] Analysis Complete (29 seconds)
Exception in thread "main" java.lang.NullPointerException
	at org.owasp.dependencycheck.App.determineReturnCode(App.java:296)
	at org.owasp.dependencycheck.App.runScan(App.java:272)
	at org.owasp.dependencycheck.App.run(App.java:184)
	at org.owasp.dependencycheck.App.main(App.java:69)

In the log file there is no more information aboutthis error:

. . .
2019-02-20 10:20:44,260 org.owasp.dependencycheck.Engine:674
INFO  - Finished Node.js Package Analyzer (1 seconds)
2019-02-20 10:20:44,710 org.owasp.dependencycheck.Engine:674
INFO  - Finished Dependency Merging Analyzer (0 seconds)
2019-02-20 10:20:44,727 org.owasp.dependencycheck.Engine:674
INFO  - Finished Version Filter Analyzer (0 seconds)
2019-02-20 10:20:44,915 org.owasp.dependencycheck.Engine:674
INFO  - Finished Hint Analyzer (0 seconds)
2019-02-20 10:20:46,954 org.owasp.dependencycheck.analyzer.CPEAnalyzer:217
INFO  - Created CPE Index (2 seconds)
2019-02-20 10:20:46,955 org.owasp.dependencycheck.analyzer.CPEAnalyzer:192
INFO  - Skipping CPE Analysis for npm
2019-02-20 10:20:47,131 org.owasp.dependencycheck.Engine:674
INFO  - Finished CPE Analyzer (2 seconds)
2019-02-20 10:20:47,154 org.owasp.dependencycheck.Engine:674
INFO  - Finished False Positive Analyzer (0 seconds)
2019-02-20 10:20:47,174 org.owasp.dependencycheck.Engine:674
INFO  - Finished NVD CVE Analyzer (0 seconds)
2019-02-20 10:21:10,768 org.owasp.dependencycheck.Engine:674
INFO  - Finished Node Audit Analyzer (23 seconds)
2019-02-20 10:21:11,170 org.owasp.dependencycheck.Engine:674
INFO  - Finished Vulnerability Suppression Analyzer (0 seconds)
2019-02-20 10:21:12,225 org.owasp.dependencycheck.Engine:674
INFO  - Finished Dependency Bundling Analyzer (1 seconds)
2019-02-20 10:21:12,245 org.owasp.dependencycheck.Engine:688
INFO  - Analysis Complete (29 seconds)

**Comment by kand617** [comment]
I am seeing this too! Any solution?

**Comment by torstenbeuck0815** [comment]
Hi, I just tried to develop a fix for this issue and found that it is already fixed in the code. Only the release here: https://github.com/jeremylong/DependencyCheck/archive/v5.0.0-M1.zip resp. https://github.com/jeremylong/DependencyCheck/archive/v5.0.0-M1.tar.gz
does not contain it. Maybe someone could start a build?
