### ISSUE TITLE
Unhelpful errors from Downloader

### ISSUE THREAD

**Issue by jglick** [dependency-check/DependencyCheck#176]
A user of the Jenkins plugin bundling 1.2.0 has been seeing sporadic network errors such as

```
… org.owasp.dependencycheck.data.update.task.DownloadTask call
FINE: null
org.owasp.dependencycheck.utils.DownloadFailedException: Error saving downloaded file.
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:126)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:59)
    at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:186)
    at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:40)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:185)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.net.www.MeteredStream.read(MeteredStream.java:134)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:2582)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:2577)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:122)
    ... 8 more
```

on certain machines, although `dependency-check.sh` is claimed to work.

It is hard to tell from this code ([source](https://github.com/jeremylong/DependencyCheck/blob/81d8a1bfd65d562a909a4ddd8588b4bf45e25973/dependency-check-utils/src/main/java/org/owasp/dependencycheck/utils/Downloader.java#L126)) what might have gone wrong. The wrapper exception does not indicate which URL is being downloaded (`url`), or whether the stream is being decompressed (`encoding`), or what file is being saved (`outputPath`), or how much content had been successfully read (sum of `bytesRead`), or what the proxy settings were. Without that information, there is no way to try to reproduce the network error outside the tool, for example using `jrunscript` to construct an equivalent download via `HttpURLConnection`.

**Comment by jeremylong** [comment]
The error messages have been improved (this is actually a broader issue and there are other exceptions in the code that could be vague and not very helpful to users or developers). Thanks for pointing this specific one out - as download issues happened occasionally (especially in versions prior to 1.2.7). However, changes to hosting at the NVD have allowed me to improve the download process (they now provide compressed versions of the files and those are now being used).

The error message improvements have been pushed to 1.2.8-SNAPSHOT. A full release of 1.2.8 will be completed within the next few days.
