### ISSUE TITLE
DownloaderIntegrationTest failing

### ISSUE THREAD

**Issue by hansjoachim** [dependency-check/DependencyCheck#177]
I run into the following test errors when attempting to build dependency-check(-utils):

```
$ mvn clean install -Dtest=DownloaderIntegrationTest
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Dependency-Check Utils 1.2.8-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dependency-check-utils ---
[INFO] Deleting /home/ubuntu/DependencyCheck/dependency-check-utils/target
[INFO] 
[INFO] --- cobertura-maven-plugin:2.6:clean (default) @ dependency-check-utils ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ dependency-check-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/DependencyCheck/dependency-check-utils/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dependency-check-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 46 source files to /home/ubuntu/DependencyCheck/dependency-check-utils/target/classes
[WARNING] /home/ubuntu/DependencyCheck/dependency-check-utils/src/main/java/org/owasp/dependencycheck/org/apache/tools/ant/util/FileUtils.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/ubuntu/DependencyCheck/dependency-check-utils/src/main/java/org/owasp/dependencycheck/org/apache/tools/ant/util/FileUtils.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ dependency-check-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ dependency-check-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/ubuntu/DependencyCheck/dependency-check-utils/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ dependency-check-utils ---
[INFO] Surefire report directory: /home/ubuntu/DependencyCheck/dependency-check-utils/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.owasp.dependencycheck.utils.DownloaderIntegrationTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 10.963 sec <<< FAILURE! - in org.owasp.dependencycheck.utils.DownloaderIntegrationTest
testGetLastModified(org.owasp.dependencycheck.utils.DownloaderIntegrationTest)  Time elapsed: 4.836 sec  <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
    at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
    at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
    at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
    at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
    at sun.security.validator.Validator.getInstance(Validator.java:179)
    at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
    at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:937)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:872)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:185)
    at org.owasp.dependencycheck.utils.DownloaderIntegrationTest.testGetLastModified(DownloaderIntegrationTest.java:51)

testFetchFile(org.owasp.dependencycheck.utils.DownloaderIntegrationTest)  Time elapsed: 5.837 sec  <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz; unable to connect.
    at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
    at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
    at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
    at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
    at sun.security.validator.Validator.getInstance(Validator.java:179)
    at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
    at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:937)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:872)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:95)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:59)
    at org.owasp.dependencycheck.utils.DownloaderIntegrationTest.testFetchFile(DownloaderIntegrationTest.java:44)


Results :

Tests in error: 
  DownloaderIntegrationTest.testGetLastModified:51 » DownloadFailed Error making...
  DownloaderIntegrationTest.testFetchFile:44 » DownloadFailed Error downloading ...

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

Fwiw, running `wget https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz` works fine.

It looks like it has problems with the HTTPS certificate for some reason, so I wonder whether this is supposed to work out of the box or if I need to add the certificate manually.

Attempting to build dd9ccbb5828791b5cea8c2c04d2ad0ac2f022163 with openjdk 8u40~b09-1 on Ubuntu Vivid. (Also tried with openjdk7 with same result.)

**Comment by jeremylong** [comment]
Thanks for the bug report - but I have a couple of questions. First, are you on a network that requires a proxy to be setup/enabled? Second, if you downloaded the compiled version of the [command line interface](https://bintray.com/jeremy-long/owasp/dependency-check/1.2.7/view) - can it be executed successfully?

Regards,

Jeremy

**Comment by hansjoachim** [comment]
> First, are you on a network that requires a proxy to be setup/enabled? 

No. 

> Second, if you downloaded the compiled version of the command line interface - can it be executed successfully?

No, it seems to fail as well.

```
$ sh dependency-check.sh -a test -s . -l log.txt
Dec 28, 2014 4:38:32 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Checking for updates
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
INFO: If you are behind a proxy you may need to configure dependency-check to use the proxy.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Check for updates complete
Dec 28, 2014 4:38:41 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.
```

I assume updating CVE-data etc should work in any random directory regardless of whether I can scan anything in it or not.

Contents of log.txt

```
Dec 28, 2014 4:38:32 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Checking for updates
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
INFO: If you are behind a proxy you may need to configure dependency-check to use the proxy.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Check for updates complete
Dec 28, 2014 4:38:41 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.
ubuntu@ubuntu:~/Downloads/dependency-check-1.2.7-release/bin$ less log.txt 
ubuntu@ubuntu:~/Downloads/dependency-check-1.2.7-release/bin$ cat log.txt 
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setString
FINE: Setting: data.directory='/home/ubuntu/Downloads/dependency-check-1.2.7-release/data'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: autoupdate='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.jar.enabled='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.archive.enabled='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nuspec.enabled='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.assembly.enabled='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nexus.enabled='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nexus.proxy='true'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading driver: org.h2.Driver
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: '/home/ubuntu/Downloads/dependency-check-1.2.7-release/data'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings getConnectionString
FINE: Connection String: 'jdbc:h2:file:/home/ubuntu/Downloads/dependency-check-1.2.7-release/data/cve.2.9;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: '/home/ubuntu/Downloads/dependency-check-1.2.7-release/data'
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Need to create DB Structure: false
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading database connection
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Connection String: jdbc:h2:file:/home/ubuntu/Downloads/dependency-check-1.2.7-release/data/cve.2.9;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;
Dec 28, 2014 4:38:28 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Database User: dcuser
Dec 28, 2014 4:38:32 PM org.owasp.dependencycheck.analyzer.CentralAnalyzer checkEnabled
FINE: Enabling the Central analyzer
Dec 28, 2014 4:38:32 PM org.owasp.dependencycheck.analyzer.NexusAnalyzer checkEnabled
FINE: Nexus analyzer disabled, using Central instead
Dec 28, 2014 4:38:32 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Checking for updates
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
INFO: If you are behind a proxy you may need to configure dependency-check to use the proxy.
Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
FINE: null
org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:188)
    at org.owasp.dependencycheck.data.update.UpdateableNvdCve.add(UpdateableNvdCve.java:96)
    at org.owasp.dependencycheck.data.update.StandardUpdate.retrieveCurrentTimestampsFromWeb(StandardUpdate.java:273)
    at org.owasp.dependencycheck.data.update.StandardUpdate.updatesNeeded(StandardUpdate.java:204)
    at org.owasp.dependencycheck.data.update.StandardUpdate.<init>(StandardUpdate.java:91)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:48)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:473)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:342)
    at org.owasp.dependencycheck.App.runScan(App.java:180)
    at org.owasp.dependencycheck.App.run(App.java:101)
    at org.owasp.dependencycheck.App.main(App.java:67)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:178)
    ... 10 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
    at sun.security.validator.Validator.getInstance(Validator.java:179)
    at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
    at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:937)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:872)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    ... 15 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
    at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
    at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
    at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
    ... 27 more

Dec 28, 2014 4:38:40 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Check for updates complete
Dec 28, 2014 4:38:41 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.
Dec 28, 2014 4:38:41 PM org.owasp.dependencycheck.Engine analyzeDependencies
FINE: null
org.owasp.dependencycheck.exception.NoDataException: No documents exist
    at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:527)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:347)
    at org.owasp.dependencycheck.App.runScan(App.java:180)
    at org.owasp.dependencycheck.App.run(App.java:101)
    at org.owasp.dependencycheck.App.main(App.java:67)

Dec 28, 2014 4:38:42 PM org.owasp.dependencycheck.data.nvdcve.CveDB finalize
FINE: Entering finalize
Dec 28, 2014 4:38:42 PM org.owasp.dependencycheck.data.nvdcve.CveDB finalize
FINE: Entering finalize
Dec 28, 2014 4:38:42 PM org.owasp.dependencycheck.data.nvdcve.CveDB finalize
FINE: Entering finalize
```

**Comment by jeremylong** [comment]
Researching this problem the issue maybe with the ca certs - see this [stackoverflow answer](http://stackoverflow.com/a/15409993/1995422). As wget works I'm assuming the ca-certs are installed. However, I'm not sure if the JDK is using the correct certs. The suggested solution was to ensure that the ca-cert package is installed and then to set the system property javax.net.ssl.trustStore to the correct path:

``` shell
 -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacert
```

Can you see if that solves the issue?  If it does I will update the error messages indicating possible solutions to the problem.

Thanks!

Jeremy

**Comment by hansjoachim** [comment]
No that doesn't work, but I think we're on to something here. I've been experimenting back and forth with various things, and thought I'd take a look at whether Java knows any certificates at all, and it doesn't.

```
$ keytool -list -keystore /etc/ssl/certs/java/cacerts 
Enter keystore password:  

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 0 entries
```

As I mentioned I was running on Ubuntu Vivid, and this looks like an Ubuntu bug so I'll follow it up there. I don't really know why something went wrong because it doesn't look like the jdk nor ca-certificates-java packages has changed recently.

So it doesn't like the bug here is in DependencyCheck, sorry about that.

A small note at the end though. Among other things, I've been comparing against building on Ubuntu 14.10 where I didn't have this problem. Though later in the build cycle I've hit `HintAnalyzerTest` in dependency-check-core which will consistently fail with an AssertionError: null on line 99. Have you seen this before? I might file a follow-up on that one, but for the meantime I'll doublecheck my dev environment to check whether something else might be causing the failure.

**Comment by jeremylong** [comment]
I've just added some more reporting to the Downloader to help users know about this problem.

Regarding the HintAnalyzerTest assertion failing on line 99 - I've never seen this. The only thing I can think of is that the optional test dependencies guice or spring core were not downloaded possibly...

**Comment by hansjoachim** [comment]
> I've just added some more reporting to the Downloader to help users know about this problem.

Thanks. I ended up filing [bug 1406483](https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1406483) in Launchpad on this issue. As you can see, depending on how you install these packages you may end up with Java without any certificates. That's rather odd, but seems like there were some similar issues like it in the past.

> Regarding the HintAnalyzerTest assertion failing on line 99 - I've never seen this. The only thing I can think of is that the optional test dependencies guice or spring core were not downloaded possibly...

When I tried debugging it, it looked like the assertFalse(x.contains(y)) on that line failed because x actually contained y. I don't really know why this would be the case and shortly after my editor refused to start debug mode so I didn't learn anything more. Anyways...
I was running all of this in a virtual machine, so at this point I rolled back and installed openjdk-7-jdk instead. Haven't seen any test failures or problems since, so it might be something jdk8-specific or something obscure I was able to trigger.
I can look some more into this in the future, though for the mean time I at least have a dev environment where it builds successfully. So I might submit some small patches in the near future.
