### ISSUE TITLE
Errors during DB load

### ISSUE THREAD

**Issue by CarlInglis** [dependency-check/DependencyCheck#1774]
v 5.0.0-M1

```01:10:30  [INFO] Download Complete for NVD CVE - Modified  (1361 ms)
01:10:30  [WARN] Unable to save property 'NVD CVE 2004' with a value of '1550826213000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2004  (224429 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2003
01:10:30  [WARN] Unable to save property 'NVD CVE 2003' with a value of '1550913336000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2003  (120305 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2005
01:10:30  [WARN] Unable to save property 'NVD CVE 2002' with a value of '1550654459000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2002  (487477 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2006
01:10:30  [WARN] Unable to save property 'NVD CVE 2005' with a value of '1550913287000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2005  (472959 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2007
01:10:30  [WARN] Unable to save property 'NVD CVE 2006' with a value of '1550913156000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2006  (753054 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2008
01:10:30  [WARN] Unable to save property 'NVD CVE 2007' with a value of '1551171105000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2007  (710564 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2009
01:10:30  [WARN] Unable to save property 'NVD CVE 2008' with a value of '1551170897000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2008  (989086 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2010
01:10:30  [WARN] Unable to save property 'NVD CVE 2009' with a value of '1551170669000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2009  (768471 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2012
01:10:30  [WARN] Unable to save property 'NVD CVE 2010' with a value of '1550912347000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2010  (1467811 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2011
01:10:30  [WARN] Unable to save property 'NVD CVE 2012' with a value of '1550911772000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2012  (1704685 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2013
01:10:30  [WARN] Unable to save property 'NVD CVE 2011' with a value of '1550912120000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2011  (3150254 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2014
01:10:30  [WARN] Unable to save property 'NVD CVE 2013' with a value of '1550911549000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2013  (3306057 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2015
01:10:30  [WARN] Unable to save property 'NVD CVE 2014' with a value of '1551170497000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2014  (1204029 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2016
01:10:30  [WARN] Unable to save property 'NVD CVE 2015' with a value of '1551170247000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2015  (837819 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2019
01:10:30  [WARN] Unable to save property 'NVD CVE 2019' with a value of '1551168083000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2019  (67480 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2017
01:10:30  [WARN] Unable to save property 'NVD CVE 2016' with a value of '1551170003000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2016  (794561 ms)
01:10:30  [INFO] Processing Started for NVD CVE - 2018
01:10:30  [WARN] Unable to save property 'NVD CVE 2017' with a value of '1551169671000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2017  (1076138 ms)
01:10:30  [INFO] Processing Started for NVD CVE - Modified
01:10:30  [WARN] Unable to save property 'NVD CVE Modified' with a value of '1551214963000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - Modified  (65180 ms)
01:10:30  [WARN] Unable to save property 'NVD CVE 2018' with a value of '1551168912000' to the database
01:10:30  [INFO] Processing Complete for NVD CVE - 2018  (705343 ms)
01:10:30  [WARN] Unable to save property 'NVD CVE Modified' with a value of '1551214963000' to the database
01:10:30  [INFO] Begin database maintenance.
01:10:30  [ERROR] An unexpected SQL Exception occurred; please see the verbose log for more details.
01:10:30  [INFO] End database maintenance.
01:10:30  [WARN] Unable to save property 'NVD CVE Checked' with a value of '1551229824025' to the database
01:10:30  [WARN] Unable to save property 'CurrentEngineRelease' with a value of '5.0.0.m1' to the database
01:10:30  [WARN] Unable to save property 'VersionCheckOn' with a value of '1551229824030' to the database
01:10:30  [INFO] Check for updates complete (9558609 ms)```

There appear to be a number of issues above - unfortunately we are about to cut code for a release of the project today and this could delay the release. Is the best thing to do to roll back to v4.0.1 and disable our version checking code?

I will re-run with verbose logging on and attach that to this issue.

**Comment by CarlInglis** [comment]
Unfortunately due to time pressure I've had to roll us back to 4.0.2. I do still have the DB from above.

I've noticed that 4.0.2 is giving me 

[WARN] Unable to save property 'NVD CVE 2003' with a value of '1550913335000' to the database
[WARN] Unable to save property 'NVD CVE 2004' with a value of '1550826211000' to the database

etc. in the log file. Since they're warnings, I'm gonna ignore them for now. It looks to me as if the issue is related to adding to the property table. I did notice that the init script refers to the table as "properties", but the update script refers to "Properties" - leading me to believe that this may be a case sensitivity issue.

We're running mySQL v5.6.40 on an Amazon RDS instance.

**Comment by CarlInglis** [comment]
I might have an answer to the issue of case sensitive table names: https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html

This would also explain the errors seen in 5.0.0-M1.

I will try to get some time allocated for me to investigate this; is there a flag I can pass to the script to make it dump the SQL commands it's using?

**Comment by CarlInglis** [comment]
```WARN  - Unable to save property 'NVD CVE 2017' with a value of '1551257309000' to the database
2019-02-27 12:46:33,642 org.owasp.dependencycheck.data.nvdcve.CveDB:491
DEBUG - 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE dependencycheck.save_property does not exist
        at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.saveProperty(CveDB.java:476)
        at org.owasp.dependencycheck.data.nvdcve.DatabaseProperties.save(DatabaseProperties.java:126)
        at org.owasp.dependencycheck.data.nvdcve.DatabaseProperties.save(DatabaseProperties.java:114)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:169)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:119)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by CarlInglis** [comment]
I can only assume that I cocked up initialising the DB somehow... 

Yeah, it looks like I didn't add the procedure. That's what I get for doing it manually. I've added the procedure now.

I'm gonna redo our recovery documentation to make sure it's clear how to rebuild the db if need be. 

I'll close this ticket, but leave it here in case others have the same problem.
