### ISSUE TITLE
Jenkins concurrent builds result in "Database may be already in use" error

### ISSUE THREAD

**Issue by deathcoder** [dependency-check/DependencyCheck#1841]
Hi i have multiple project running the Dependency-Check plugin on the same jenkins server, to save up space they all use the same
dataDirectory, my problem is that when the plugin is running at the same time in multiple project i get the following error:
```
[DependencyCheck] OWASP Dependency-Check Plugin v4.0.2
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = master
[DependencyCheck]  -scanPath = /home/jenkins/workspace/sample_master
[DependencyCheck]  -outputDirectory = /home/jenkins/workspace/sample_master
[DependencyCheck]  -dataDirectory = /home/jenkins/owasp-nvd
[DependencyCheck]  -suppressionFile = /home/jenkins/workspace/sample_master/owasp/suppression.xml
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -proxyServer = *.*.*.*
[DependencyCheck]  -proxyPort = 800
[DependencyCheck]  -nonProxyHosts = kubernetes
[DependencyCheck] kubernetes.default
[DependencyCheck] localhost
[DependencyCheck] *.local
[DependencyCheck] *.svc
[DependencyCheck] 127.0.0.1
[DependencyCheck] 10.*
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodePackageAnalyzerEnabled = true
[DependencyCheck]  -nodeAuditAnalyzerEnabled = true
[DependencyCheck]  -retireJsAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = false
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -msBuildProjectAnalyzerEnabled = true
[DependencyCheck]  -nuGetConfigAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -artifactoryAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML
[DependencyCheck]  -autoUpdate = false
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: /home/jenkins/workspace/sample_master
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] Skipping publisher since build result is FAILURE
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.nvdcve.DatabaseException
[DependencyCheck] Cause: Database may be already in use: "Locked by another process: /home/jenkins/owasp-nvd/dc.lock.db". Possible solutions: close all other connection(s); use the server mode [90020-196]
[DependencyCheck] Message: Unable to connect to the database
[DependencyCheck] org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the database
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:178)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:950)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:737)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:172)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:103)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[DependencyCheck] 	at hudson.remoting.Request$2.run(Request.java:369)
[DependencyCheck] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)
[DependencyCheck] Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: "Locked by another process: /home/jenkins/owasp-nvd/dc.lock.db". Possible solutions: close all other connection(s); use the server mode [90020-196]
[DependencyCheck] 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:179)
[DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:155)
[DependencyCheck] 	at org.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:460)
[DependencyCheck] 	at org.h2.store.FileLock.lockFile(FileLock.java:352)
[DependencyCheck] 	at org.h2.store.FileLock.lock(FileLock.java:135)
[DependencyCheck] 	at org.h2.engine.Database.open(Database.java:662)
[DependencyCheck] 	at org.h2.engine.Database.openDatabase(Database.java:276)
[DependencyCheck] 	at org.h2.engine.Database.<init>(Database.java:270)
[DependencyCheck] 	at org.h2.engine.Engine.openSession(Engine.java:64)
[DependencyCheck] 	at org.h2.engine.Engine.openSession(Engine.java:176)
[DependencyCheck] 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
[DependencyCheck] 	at org.h2.engine.Engine.createSession(Engine.java:137)
[DependencyCheck] 	at org.h2.engine.Engine.createSession(Engine.java:27)
[DependencyCheck] 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
[DependencyCheck] 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
[DependencyCheck] 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
[DependencyCheck] 	at org.h2.Driver.connect(Driver.java:69)
[DependencyCheck] 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[DependencyCheck] 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:163)
[DependencyCheck] 	... 18 more
[DependencyCheck]
```

I think i can probably fix this by correctly configuring the -connectionString,

so far i tried:
- `jdbc:h2:file:%s;AUTOCOMMIT=ON;AUTO_SERVER=TRUE;`

  but it fails with this error: `Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod ==
 SERIALIZED || fileLockMethod == FS || inMemory)" [50100-196]`
- `jdbc:h2:file:%s;AUTOCOMMIT=ON;` which seems to work

Since this problem doesn't happen often i'm not sure that this actually worked
can you please confirm or suggest a configuration that would work for multiple concurrent builds?

**Comment by stevespringett** [comment]
If autoUpdate and updateOnly are both set to false (as is the case with the stacktrace you posted) there should be no reason to have a lock. All jobs should have both of these flags set to false and there should be a single job (which blocks all other dependency-check jobs) that performs the updateOnly.

Is this the case?

**Comment by deathcoder** [comment]
Hi @stevespringett, sorry for the late reply, you are correct, 
we are are using that configuration,
in case anyone ends up here i'll add that we actually ended up using the following `-connectionString jdbc:h2:file:%s;AUTOCOMMIT=ON;FILE_LOCK=NO;`

i think this can be closed
