### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space (RetireJS Analyzer)

### ISSUE THREAD

**Issue by ixnet** [dependency-check/DependencyCheck#1865]
**Describe the bug**
RetireJS Analyzer fails with exception

 **Version of dependency-check used** 

The problem occurs using version v5.0.0-M2 CLI
 **Log file** 
https://gist.github.com/ixnet/0f246e584b5f85657e05748a9da1f581

**To Reproduce**
Launching scan with this command
`dependency-check.bat -s "bla\bla" --project bla --suppression false_positives.xml  -f XML --out bla.xml`
And then error occurs

`sources\Inputmask\Inputmask\misc\phone-alias\src\phone-codes\phone-us.js' (RetireJS Analyzer): Java heap space
[ERROR]
java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringCoding$StringDecoder.decode(Unknown Source)
        at java.lang.StringCoding.decode(Unknown Source)
        at java.lang.StringCoding.decode(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at com.h3xstream.retirejs.repo.ScannerFacade.scanScript(ScannerFacade.java:123)
        at org.owasp.dependencycheck.analyzer.RetireJsAnalyzer.analyzeDependency(RetireJsAnalyzer.java:231)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

**Expected behavior**
I expect scan without errors

**Additional context**

**Comment by jeremylong** [comment]
Any chance phone-us.js is available so we can test?

**Comment by jeremylong** [comment]
The solution for this problem has been found.  Please see #1969
