### ISSUE TITLE
Plugin fails in maven with lucene errors ?

### ISSUE THREAD

**Issue by yoavsreb98p6** [dependency-check/DependencyCheck#1882]
Hello.

When running the plugin I see the below output.
Is there any workaround ?
I'm using 5.0.0-M2 version.

Thanks!

```
[WARNING] An error occurred querying the CPE data. See the log for more details.
[INFO] Unable to parse: product (server^3 scaladsl^3 akka\/http\/scaladsl\/server\ ...

: too many boolean clauses
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:118)
	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.parseQuery(CpeMemoryIndex.java:286)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:396)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:258)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:678)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:136)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:114)
	at org.apache.lucene.queryparser.classic.QueryParserBase.getBooleanQuery(QueryParserBase.java:668)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:316)
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
	... 11 more
```

**Comment by jeremylong** [comment]
Any chance you could tell me what the coordinates (group, artifact, version) of the JAR file causing this issue?  Looks like something related to akka http scaladsl.

**Comment by yoavsreb98p6** [comment]
--- dependency-check-maven:5.0.0-M2:check (default) @

**Comment by yoavsreb98p6** [comment]
If u mean what is the dependency that it scanned, I think it's NewRelic  - Java agent 4.11.0 (https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-4110)
@jeremylong

**Comment by jeremylong** [comment]
I just tests this using the latest build and I am unable to reproduce the error.  We have upgrade lucene - so that may have resolved this issue between the 5.0.0-M2 and the 5.0.0-SNAPSHOT (which I'm hoping to release this week).

**Comment by yoavsreb98p6** [comment]
I will test it on the new version once it's out.
Thank you!

**Comment by wilx** [comment]
I am hitting this too. I am running the aggregate goal of the Maven plugin version 5.2.1. It appears that the query contains a lot of redundant words:

```
00:34:10.633 org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'product:(ppk\-tibco\-bw\-agent Mark JobEnd Tracer Hc2 Tibco EMS Backend Tracer Hc2 WebServices Server NameFormatter com.wily.soaextension.tibcobw.multithread.blame.nameformatter.FrontendNameFormatter activity extended Tracer Introscope\-Agent Task Blame Tracer Hc2 soaextension^2 Activity Error tracer Hc2 tibcobw\-agent^2 SOAP Client Correlation Tracer IntroscopeSOAExtensionForTibco^2 HTTPWebServFrontNameFormatter ActivityExtendedXiNodeTracer correlation BoundaryOnly Tracing Service 99.99.nextgen_fixes com.wily.soaextension.tibcobw.webservice.nameformatter.WebServiceBackendNameFormatter Frontend Remove Tracer Hc2 Subprocess finish Tracer Hc2 Spawned Process Correlation Tracer com.wily.soaextension.tibcobw.naming.BWNameService SOAP Server Correlation Tracer Hc2 activity rv WebServices Server NameFormatter hc Task Tracer Hc2 Process NameFormatter Tibco Frontend Marker Hc2 TibcoBW^2 MultiBoundary Service tibcobw^2 WebServiceDetectionTracer RV TransportNameFormatter ca.apm.powerpack.tibcobw Job Creator HTTP Server Correlation Tracer WebServices Client NameFormatter hc JMSExtendedServerNameFormatter Subprocess Nameformatter ReqExeCreationTracer Hawk Tracer WebServices ClientOP NameFormatter hc com.wily.soaextension.tibcobw.jms.nameformatter.JMSExtendedServerNameFormatter SOAP Fault Tracer Hc2 HttpServletRequestTracer nameformatter^23 WebServices BlamePoint Tracer Hc2 webservice ActivityExtendedFormatter 42 JMSSendCorrelationTracer Tracer TibcoBW^2 Agent Service tibcobw^2 EMS Backend Nameformatter EMSExtendedBackendFormatter WebServices Client NameFormatter Mark JobError Tracer Hc2 jms JMS Client Correlation Tracer JobPool Creator HProcess NameFormatter com.ca.apm.powerpack.tibcobw HGroupAction Nameformatter RV QueueNameFormatter JMSReceiveCorrelationTracer Tracer HTask nameformatter ActivityGroupNameFormatterField multithread Tibco Complementary Backend Tracer Hc2 BW Agent Name Service tracer^38 com.wily.soaextension.tibcobw.activity.nameformatter.ActivityGroupNameFormatterField Job Creator Correlation Tracer Hc2 naming hawk Called Backend Tracer Hc2 WebServiceBackendNameFormatter WebServices NameFormatter JobCourierTracerEnhanced Tracer Frontend Nameformatter Process Correlation Tracer Client SOAP Fault Tracer Hc2 backend http\:\/\/maven.apache.org Job Service WebServiceSettingTracer Hawk Service Subprocess start Tracer Hc2 tibcobw^2 HTTP Client Correlation Tracer BootstrapTracer wily com.wily.soaextension.tibcobw.webservice.nameformatter.HTTPWebServiceFrontendNameFormatter WebServiceConsumerTracer JMS Server Correlation Tracer Hc2 IntroscopeSOAExtensionForTibcoBusinessWorks PowerPack for Introscope Agent "\-" TibcoBWAgentExt WebServices ServerOp NameFormatter hc service^5 BW_SERVICE HAWK_SERVICE HAWK_TRACER SERVER_FORMATTER HSERVER_FORMATTER HOSERVER_FORMATTER CLIENT_FORMATTER HCLIENT_FORMATTER HOCLIENT_FORMATTER WS_FORMATTER PROC_FORMATTER HPROC_FORMATTER HTASK_FORMATTER rvTransportNF rvQueueNF SUBPROC_NF JOB_SERVICE JOB_CREATOR_TRACER JOBPOOL_CREATOR_TRACER processcortracer HGROUPACTION_NF httpclientcorrtracer httpservercorrtracer soapclientcorrtracer jmsclientcorrtracer spawnedcorrtracer EMS_BACKEND mbbs\-service frontendnameformatter WS_BP_HC2_TRACER WSF_HC2_TRACER CF_HC2_TRACER PROCRM_HC2_TRACER PROCERR_HC2_TRACER TASK_HC2_TRACER STARTSUBPROC_HC2_TRACER ENDSUBPROC_HC2_TRACER ACTERROR_HC2_TRACER TASKBLAME_HC2_TRACER soapservercorrhc2tracer jmsservercorrhc2tracer jobcreatorcorhc2tracer calledbackendhc2tracer frontendremovehc2tracer frontendhc2marker tibcobackendhc2tracer tibcoemshc2tracer jobcouriertracerenhanced activityextended jmsrcvtracer EXEMS_FORMATTER jmssendtracer actformatter jmsnameformatter websettingtracer webdetectiontracer) AND vendor:(Mark JobEnd Tracer Hc2 ppk\-tibco\-bw\-agent Tibco EMS Backend Tracer Hc2 WebServices Server NameFormatter com.wily.soaextension.tibcobw.multithread.blame.nameformatter.FrontendNameFormatter activity extended Tracer Introscope\-Agent Task Blame Tracer Hc2 soaextension^2 Activity Error tracer Hc2 tibcobw\-agent^2 SOAP Client Correlation Tracer IntroscopeSOAExtensionForTibco^2 HTTPWebServFrontNameFormatter ActivityExtendedXiNodeTracer correlation BoundaryOnly Tracing Service 99.99.nextgen_fixes com.wily.soaextension.tibcobw.webservice.nameformatter.WebServiceBackendNameFormatter Frontend Remove Tracer Hc2 Subprocess finish Tracer Hc2 Spawned Process Correlation Tracer com.wily.soaextension.tibcobw.naming.BWNameService SOAP Server Correlation Tracer Hc2 activity rv WebServices Server NameFormatter hc Task Tracer Hc2 Process NameFormatter Tibco Frontend Marker Hc2 TibcoBW^2 MultiBoundary Service tibcobw^2 WebServiceDetectionTracer ca.apm.powerpack.tibcobw RV TransportNameFormatter Job Creator HTTP Server Correlation Tracer WebServices Client NameFormatter hc JMSExtendedServerNameFormatter Subprocess Nameformatter ReqExeCreationTracer Hawk Tracer WebServices ClientOP NameFormatter hc com.wily.soaextension.tibcobw.jms.nameformatter.JMSExtendedServerNameFormatter SOAP Fault Tracer Hc2 HttpServletRequestTracer nameformatter^23 WebServices BlamePoint Tracer Hc2 webservice ActivityExtendedFormatter 42 JMSSendCorrelationTracer Tracer TibcoBW^2 Agent Service tibcobw^2 EMS Backend Nameformatter EMSExtendedBackendFormatter WebServices Client NameFormatter Mark JobError Tracer Hc2 jms JMS Client Correlation Tracer JobPool Creator HProcess NameFormatter com.ca.apm.powerpack.tibcobw^2 HGroupAction Nameformatter RV QueueNameFormatter JMSReceiveCorrelationTracer Tracer HTask nameformatter ActivityGroupNameFormatterField multithread Tibco Complementary Backend Tracer Hc2 BW Agent Name Service tracer^38 com.wily.soaextension.tibcobw.activity.nameformatter.ActivityGroupNameFormatterField Job Creator Correlation Tracer Hc2 naming hawk Called Backend Tracer Hc2 WebServiceBackendNameFormatter WebServices NameFormatter JobCourierTracerEnhanced Tracer Frontend Nameformatter Process Correlation Tracer Client SOAP Fault Tracer Hc2 backend http\:\/\/maven.apache.org Job Service WebServiceSettingTracer Hawk Service Subprocess start Tracer Hc2 tibcobw^2 HTTP Client Correlation Tracer BootstrapTracer wily^2 com.wily.soaextension.tibcobw.webservice.nameformatter.HTTPWebServiceFrontendNameFormatter WebServiceConsumerTracer JMS Server Correlation Tracer Hc2 IntroscopeSOAExtensionForTibcoBusinessWorks PowerPack for Introscope Agent "\-" TibcoBWAgentExt WebServices ServerOp NameFormatter hc service^5 BW_SERVICE HAWK_SERVICE HAWK_TRACER SERVER_FORMATTER HSERVER_FORMATTER HOSERVER_FORMATTER CLIENT_FORMATTER HCLIENT_FORMATTER HOCLIENT_FORMATTER WS_FORMATTER PROC_FORMATTER HPROC_FORMATTER HTASK_FORMATTER rvTransportNF rvQueueNF SUBPROC_NF JOB_SERVICE JOB_CREATOR_TRACER JOBPOOL_CREATOR_TRACER processcortracer HGROUPACTION_NF httpclientcorrtracer httpservercorrtracer soapclientcorrtracer jmsclientcorrtracer spawnedcorrtracer EMS_BACKEND mbbs\-service frontendnameformatter WS_BP_HC2_TRACER WSF_HC2_TRACER CF_HC2_TRACER PROCRM_HC2_TRACER PROCERR_HC2_TRACER TASK_HC2_TRACER STARTSUBPROC_HC2_TRACER ENDSUBPROC_HC2_TRACER ACTERROR_HC2_TRACER TASKBLAME_HC2_TRACER soapservercorrhc2tracer jmsservercorrhc2tracer jobcreatorcorhc2tracer calledbackendhc2tracer frontendremovehc2tracer frontendhc2marker tibcobackendhc2tracer tibcoemshc2tracer jobcouriertracerenhanced activityextended jmsrcvtracer EXEMS_FORMATTER jmssendtracer actformatter jmsnameformatter websettingtracer webdetectiontracer)': too many boolean clauses
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:118)
00:34:10.633 	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.parseQuery(CpeMemoryIndex.java:287)
00:34:10.633 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:398)
00:34:10.633 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:260)
00:34:10.633 	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:699)
00:34:10.633 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
00:34:10.633 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
00:34:10.633 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
00:34:10.633 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:34:10.633 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:34:10.633 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:34:10.633 	at java.lang.Thread.run(Thread.java:748)
00:34:10.633 Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
00:34:10.633 	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:114)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParserBase.getBooleanQuery(QueryParserBase.java:668)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:316)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
00:34:10.633 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
00:34:10.633 	... 11 more
```

**Comment by wilx** [comment]
Maybe something like this could be hacked into a new version of DependencyCheck so that we can at least try to get our setups working?

```diff
diff --git a/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java b/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java
index b58f1cf5c..229546e95 100644
--- a/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java
+++ b/core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java
@@ -44,6 +44,7 @@ import org.apache.lucene.analysis.CharArraySet;
 import org.apache.lucene.document.Document;
 import org.apache.lucene.index.CorruptIndexException;
 import org.apache.lucene.queryparser.classic.ParseException;
+import org.apache.lucene.search.BooleanQuery;
 import org.apache.lucene.search.Query;
 import org.apache.lucene.search.ScoreDoc;
 import org.apache.lucene.search.TopDocs;
@@ -85,6 +86,12 @@ import us.springett.parsers.cpe.values.Part;
 @ThreadSafe
 public class CPEAnalyzer extends AbstractAnalyzer {
 
+    static {
+        BooleanQuery.setMaxClauseCount(
+            Integer.parseUnsignedInt(
+                System.getProperty("CPEAnalyzer.BooleanQuery.setMaxClauseCount", "1024")));
+    }
+
     /**
      * The Logger.
      */
```
