### ISSUE TITLE
Severe: No documents exists using Cli

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#195]
Hi,
We have "No documents exist" error with dependency-check-cli version dependency-check-1.2.8-release:

Jan 30, 2015 3:53:34 PM org.owasp.dependencycheck.data.update.Engine doUpdates
INFO: Checking for updates
Jan 30, 2015 3:53:56 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data;the results may not include the most recent CPE/CVEs from the NVD.
Jan 30, 2015 3:53:56 PM org.owasp.dependencycheck.data.update.NvdCveUpdater update
INFO: If you are behind a proxy you may need to configure dependency-check to use the proxy
Jan 30, 2015 3:54:18 PM org.owasp.dependencycheck.Engine doUpdates
INFO: Check for updates complete
Jan 30, 2015 3:54:18 PM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.

I have checked proxy settings and allowed dependency check to use proxy services.
Still unable to figure the problem.

Any ideas?
Thank you

**Comment by jeremylong** [comment]
The issue entirely revolves around the error downloading the NVD data from NIST as seen in the warning:

WARNING: Unable to download the NVD CVE data;the results may not include the most recent CPE/CVEs from the NVD.

Can you add the `--log dc.log` to the command line and post the log file so that we can see more detail about what is going on?

--Jeremy

**Comment by ghost** [comment]
@jeremylong Apologize for late reply. Below are the details on the log file.

Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setString
FINE: Setting: data.directory='C:\Users\ramasai\Documents\dependency-check-1.2.8-release\bin..\data'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: autoupdate='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.jar.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.archive.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nuspec.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.assembly.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.central.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nexus.enabled='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings setBoolean
FINE: Setting: analyzer.nexus.proxy='true'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading driver: org.h2.Driver
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: 'C:\Users\ramasai\Documents\dependency-check-1.2.8-release\bin..\data'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings getConnectionString
FINE: Connection String: 'jdbc:h2:file:C:\Users\ramasai\Documents\dependency-check-1.2.8-release\data\cve.2.9;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: 'C:\Users\ramasai\Documents\dependency-check-1.2.8-release\bin..\data'
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Need to create DB Structure: false
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading database connection
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Connection String: jdbc:h2:file:C:\Users\ramasai\Documents\dependency-check-1.2.8-release\data\cve.2.9;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;
Feb 02, 2015 9:32:11 AM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Database User: dcuser
Feb 02, 2015 9:32:12 AM org.owasp.dependencycheck.analyzer.CentralAnalyzer checkEnabled
FINE: Enabling the Central analyzer
Feb 02, 2015 9:32:12 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer checkEnabled
FINE: Nexus analyzer disabled, using Central instead
Feb 02, 2015 9:32:12 AM org.owasp.dependencycheck.Engine doUpdates
INFO: Checking for updates
Feb 02, 2015 9:32:34 AM org.owasp.dependencycheck.data.update.NvdCveUpdater update
WARNING: Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
Feb 02, 2015 9:32:34 AM org.owasp.dependencycheck.data.update.NvdCveUpdater update
INFO: If you are behind a proxy you may need to configure dependency-check to use the proxy.
Feb 02, 2015 9:32:34 AM org.owasp.dependencycheck.data.update.NvdCveUpdater update
FINE: null
org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:195)
    at org.owasp.dependencycheck.data.update.UpdateableNvdCve.add(UpdateableNvdCve.java:96)
    at org.owasp.dependencycheck.data.update.StandardUpdate.retrieveCurrentTimestampsFromWeb(StandardUpdate.java:273)
    at org.owasp.dependencycheck.data.update.StandardUpdate.updatesNeeded(StandardUpdate.java:204)
    at org.owasp.dependencycheck.data.update.StandardUpdate.<init>(StandardUpdate.java:91)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:48)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:478)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:347)
    at org.owasp.dependencycheck.App.runScan(App.java:180)
    at org.owasp.dependencycheck.App.run(App.java:101)
    at org.owasp.dependencycheck.App.main(App.java:67)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:185)
    ... 10 more

Feb 02, 2015 9:32:35 AM org.owasp.dependencycheck.data.update.EngineVersionCheck update
FINE: Begin Engine Version Check
Feb 02, 2015 9:32:35 AM org.owasp.dependencycheck.data.update.EngineVersionCheck update
FINE: Last checked: 0
Feb 02, 2015 9:32:35 AM org.owasp.dependencycheck.data.update.EngineVersionCheck update
FINE: Now: 1422891155158
Feb 02, 2015 9:32:35 AM org.owasp.dependencycheck.data.update.EngineVersionCheck update
FINE: Current version: 1.2.8
Feb 02, 2015 9:32:35 AM org.owasp.dependencycheck.data.update.EngineVersionCheck shouldUpdate
FINE: Checking web for new version.
Feb 02, 2015 9:32:56 AM org.owasp.dependencycheck.data.update.EngineVersionCheck getCurrentReleaseVersion
FINE: unable to retrieve current release version of dependency-check
java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at org.owasp.dependencycheck.data.update.EngineVersionCheck.getCurrentReleaseVersion(EngineVersionCheck.java:193)
    at org.owasp.dependencycheck.data.update.EngineVersionCheck.shouldUpdate(EngineVersionCheck.java:131)
    at org.owasp.dependencycheck.data.update.EngineVersionCheck.update(EngineVersionCheck.java:97)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:478)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:347)
    at org.owasp.dependencycheck.App.runScan(App.java:180)
    at org.owasp.dependencycheck.App.run(App.java:101)
    at org.owasp.dependencycheck.App.main(App.java:67)

Feb 02, 2015 9:32:56 AM org.owasp.dependencycheck.data.update.EngineVersionCheck shouldUpdate
FINE: Current Release: 
Feb 02, 2015 9:32:56 AM org.owasp.dependencycheck.data.update.EngineVersionCheck shouldUpdate
FINE: Upgrade not needed
Feb 02, 2015 9:32:56 AM org.owasp.dependencycheck.Engine doUpdates
INFO: Check for updates complete
Feb 02, 2015 9:32:57 AM org.owasp.dependencycheck.Engine analyzeDependencies
SEVERE: No documents exist

Unable to continue dependency-check analysis.
Feb 02, 2015 9:32:57 AM org.owasp.dependencycheck.Engine analyzeDependencies
FINE: null
org.owasp.dependencycheck.exception.NoDataException: No documents exist
    at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:541)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:352)
    at org.owasp.dependencycheck.App.runScan(App.java:180)
    at org.owasp.dependencycheck.App.run(App.java:101)
    at org.owasp.dependencycheck.App.main(App.java:67)

Thank you,
Sai

**Comment by ghost** [comment]
@jeremylong sorry for trouble. It was a proxy set up error. I have figured out how to pass dependency-check through the proxy. It has downloaded all the latest data from NVD CVE. 

Thank you

**Comment by jeremylong** [comment]
Glad you solved the problem. However, i am sure others have the same
problem but don't ask. Would a different error message have helped you more?

Jeremy

**Comment by ghost** [comment]
The same prob that I have mentioned, the problem with proxy settings. I gave proxy server and proxy port details along the cli. The application passed through proxy and downloaded NVD CVE data.

But I am having trouble analyzing the work structure of this application. Can I reopen the issue and shoot questions here. I appreciate your help 

Sai

**Comment by jeremylong** [comment]
I would prefer questions about analyzing a specific project structure go to the [google group](https://groups.google.com/forum/#!forum/dependency-check).

**Comment by maorgo** [comment]
Weird. Having same issue.

> [WARN] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
> [INFO] Check for updates complete (2645 ms)
> [ERROR] No documents exist
> 
> Unable to continue dependency-check analysis.

Of course, I used the --proxyserver and --proxyport at the cli parameters.

for some reason, the log doesn't get created (with root permissions). I think it doesn't even get that far.
I use it on a docker container. On the host itself in works perfectly, but for some reason on a docker container in freaks out.
Any ideas?

Thank you!

**Comment by jeremylong** [comment]
Have you looked at other examples of people containerizing dependency-check?

https://hub.docker.com/r/deepfenceio/deepfence_depcheck/
https://github.com/jeremylong/DependencyCheck/blob/master/Dockerfile
