### ISSUE TITLE
[ERROR] Failed to request component-reports

### ISSUE THREAD

**Issue by mistermania** [dependency-check/DependencyCheck#2017]
When running a scan on my project, I faced a "Failed to request component-reports" after the scan.

```
+ ./dependency-check/bin/dependency-check.sh -o report-dependency-check --scan .
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2003  (748 ms)
[INFO] Download Started for NVD CVE - 2004
[INFO] Processing Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2002  (983 ms)
[INFO] Download Started for NVD CVE - 2005
[INFO] Download Complete for NVD CVE - 2004  (1285 ms)
[INFO] Download Started for NVD CVE - 2006
[INFO] Download Complete for NVD CVE - 2005  (1238 ms)
[INFO] Download Started for NVD CVE - 2007
[INFO] Download Complete for NVD CVE - 2007  (1203 ms)
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2006  (1443 ms)
[INFO] Download Started for NVD CVE - 2009
[INFO] Download Complete for NVD CVE - 2008  (1450 ms)
[INFO] Download Started for NVD CVE - 2010
[INFO] Download Complete for NVD CVE - 2009  (1720 ms)
[INFO] Download Started for NVD CVE - 2011
[INFO] Processing Complete for NVD CVE - 2003  (4930 ms)
[INFO] Processing Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2010  (1272 ms)
[INFO] Download Started for NVD CVE - 2012
[INFO] Download Complete for NVD CVE - 2011  (1895 ms)
[INFO] Download Started for NVD CVE - 2013
[INFO] Download Complete for NVD CVE - 2013  (939 ms)
[INFO] Download Started for NVD CVE - 2014
[INFO] Download Complete for NVD CVE - 2012  (2859 ms)
[INFO] Download Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2014  (1110 ms)
[INFO] Download Started for NVD CVE - 2016
[INFO] Download Complete for NVD CVE - 2015  (1040 ms)
[INFO] Download Started for NVD CVE - 2017
[INFO] Download Complete for NVD CVE - 2017  (1192 ms)
[INFO] Download Started for NVD CVE - 2018
[INFO] Download Complete for NVD CVE - 2016  (2210 ms)
[INFO] Download Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2018  (1577 ms)
[INFO] Download Complete for NVD CVE - 2019  (1991 ms)
[INFO] Processing Complete for NVD CVE - 2002  (7692 ms)
[INFO] Processing Started for NVD CVE - 2004
[INFO] Processing Complete for NVD CVE - 2004  (4465 ms)
[INFO] Processing Started for NVD CVE - 2005
[INFO] Processing Complete for NVD CVE - 2005  (5665 ms)
[INFO] Processing Started for NVD CVE - 2007
[INFO] Processing Complete for NVD CVE - 2007  (5666 ms)
[INFO] Processing Started for NVD CVE - 2006
[INFO] Processing Complete for NVD CVE - 2006  (6278 ms)
[INFO] Processing Started for NVD CVE - 2008
[INFO] Processing Complete for NVD CVE - 2008  (6420 ms)
[INFO] Processing Started for NVD CVE - 2009
[INFO] Processing Complete for NVD CVE - 2009  (8121 ms)
[INFO] Processing Started for NVD CVE - 2010
[INFO] Processing Complete for NVD CVE - 2010  (11283 ms)
[INFO] Processing Started for NVD CVE - 2011
[INFO] Processing Complete for NVD CVE - 2011  (46501 ms)
[INFO] Processing Started for NVD CVE - 2013
[INFO] Processing Complete for NVD CVE - 2013  (10885 ms)
[INFO] Processing Started for NVD CVE - 2012
[INFO] Processing Complete for NVD CVE - 2012  (13252 ms)
[INFO] Processing Started for NVD CVE - 2014
[INFO] Processing Complete for NVD CVE - 2014  (9144 ms)
[INFO] Processing Started for NVD CVE - 2015
[INFO] Processing Complete for NVD CVE - 2015  (7136 ms)
[INFO] Processing Started for NVD CVE - 2017
[INFO] Processing Complete for NVD CVE - 2017  (9075 ms)
[INFO] Processing Started for NVD CVE - 2016
[INFO] Processing Complete for NVD CVE - 2016  (7658 ms)
[INFO] Processing Started for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2018  (9332 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Processing Complete for NVD CVE - 2019  (3028 ms)
[INFO] Download Started for NVD CVE - Modified
[INFO] Download Complete for NVD CVE - Modified  (627 ms)
[INFO] Processing Started for NVD CVE - Modified
[INFO] Processing Complete for NVD CVE - Modified  (662 ms)
[INFO] Begin database maintenance
[INFO] End database maintenance (24913 ms)
[INFO] Begin database defrag
[INFO] End database defrag (9466 ms)
[INFO] Check for updates complete (221008 ms)
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (7 seconds)
[ERROR] ----------------------------------------------------
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.
[ERROR] ----------------------------------------------------
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
*****
[INFO] Finished RetireJS Analyzer (0 seconds)
[WARN] An error occurred while analyzing '********' (Sonatype OSS Index Analyzer).
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (15 seconds)
[ERROR] Failed to request component-reports
```

My problem is the last error which come from nowhere.

I'm using the version 5.0.0 of the CLI.
I saw some issues for maven but it seems they have been resolved with the last release, so I can't explain that.

I'm running the CLI inside a docker container with nodeJS v10.15.1.

An idea of how to fix it ?

**Comment by roddy** [comment]
I had this problem as well starting today, but via Maven, and I was able to "resolve" it temporarily on my side by disabling the Sonatype OSS Index Analzyer.

**Comment by albuch** [comment]
Same issue here happening last night: https://travis-ci.org/albuch/sbt-dependency-check/jobs/549950041
From the SBT Plugin:
```
[pool-5-thread-2] INFO org.owasp.dependencycheck.analyzer.CentralAnalyzer - Central analyzer disabled
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Checking for updates
[pool-5-thread-2] INFO org.owasp.dependencycheck.data.update.NvdCveUpdater - Skipping NVD check since last check was within 4 hours.
[pool-5-thread-2] INFO org.owasp.dependencycheck.data.update.RetireJSDataSource - Skipping RetireJS update since last update was within 24 hours.
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Check for updates complete (26 ms)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Analysis Started
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Archive Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished File Name Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Jar Analyzer (0 seconds)
[pool-5-thread-2] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------
[pool-5-thread-2] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.
[pool-5-thread-2] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Dependency Merging Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Version Filter Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Hint Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.analyzer.CPEAnalyzer - Created CPE Index (3 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished CPE Analyzer (4 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished False Positive Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished NVD CVE Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished RetireJS Analyzer (0 seconds)
[pool-16-thread-1] WARN org.owasp.dependencycheck.AnalysisTask - An error occurred while analyzing '/home/travis/.ivy2/cache/org.codehaus.mojo/animal-sniffer-annotations/jars/animal-sniffer-annotations-1.17.jar' (Sonatype OSS Index Analyzer).
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Sonatype OSS Index Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Vulnerability Suppression Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Finished Dependency Bundling Analyzer (0 seconds)
[pool-5-thread-2] INFO org.owasp.dependencycheck.Engine - Analysis Complete (7 seconds)
[error] Failed creating report: One or more exceptions occurred during analysis:
[error] 	Failed to request component-reports
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Failed to request component-reports
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:699)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:532)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3$$anonfun$apply$5.apply(DependencyCheckPlugin.scala:296)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3$$anonfun$apply$5.apply(DependencyCheckPlugin.scala:294)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.net$vonbuchholtz$sbt$dependencycheck$DependencyCheckPlugin$$withEngine(DependencyCheckPlugin.scala:552)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3.apply(DependencyCheckPlugin.scala:294)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3.apply(DependencyCheckPlugin.scala:253)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jeremylong** [comment]
Unfortunately - when an external service is reporting a 500 error there is not much the dependency-check code can do other than report the service is failing.  It appears to be back up and running again.
