### ISSUE TITLE
NullPointerException in AssemblyAnalyzer.analyzeDependency()

### ISSUE THREAD

**Issue by mdesousa** [dependency-check/DependencyCheck#2025]
We are getting NullPointerException in assemblies in our project
The problem occurs using version 5.0.0 of the cli

See below the error message and stack trace, thanks.

```
[WARN] An unexpected error occurred during analysis of 'MyAssembly.dll' (Assembly A
nalyzer): null
[ERROR]
java.lang.NullPointerException: null
        at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.analyzeDependency(AssemblyAnalyzer.java:250)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by jeremylong** [comment]
This was fixed along with #2000 and #1848.
