### ISSUE TITLE
Dependency Check on NodeJS Project: NullPointerException on cvssToSonarQubeSeverity

### ISSUE THREAD

**Issue by rafaels-dev** [dependency-check/DependencyCheck#2056]
**Describe the bug**
I've a Node.js project and I'd like to check dependency for keep it up to date without vulnerabilities. I'm generating report [dependency-check-report.zip](https://github.com/jeremylong/DependencyCheck/files/3374913/dependency-check-report.zip) using Command Line and sending to sonar using sonar-scanner cli.
On SonarQube Scaner execution, I got this error:
```
java.lang.NullPointerException
	at org.sonar.dependencycheck.base.DependencyCheckUtils.cvssToSonarQubeSeverity(DependencyCheckUtils.java:43)
	at org.sonar.dependencycheck.DependencyCheckSensor.addIssue(DependencyCheckSensor.java:80)
	at org.sonar.dependencycheck.DependencyCheckSensor.addIssues(DependencyCheckSensor.java:189)
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:250)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:408)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:403)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Exited with code 1
```

** Version of dependency-check used **
Node.js 10.15.3
SonarQube Scanner 3.3.0.1492-linux
SonarQube 7.6 (build 21501)
SonarQube - Dependency Check Plugin: sonar-dependency-check-plugin-1.2.1.jar
SonarQube - Javascript Plugin: sonar-javascript-plugin-5.2.1.7778.jar
DependencyCheck Command Line CLI: 5.1.0

** Log file **
[Gist File](https://gist.github.com/rcschettino/532235766e97557390ef889bab0697a4)
[sonar-project.properties](https://gist.github.com/rcschettino/5ae7f715ef50c211bd5ca9a9d0c855d1)

**To Reproduce**
```
dependency-check.sh -f HTML -f XML -s . -o ./reports/ --disableAssembly
sonar-scanner -X -Dsonar.login=${SONAR_USER} -Dsonar.password=${SONAR_PASSWORD} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.projectVersion=$(node -p -e "require('./package.json').version")
```

**Expected behavior**
Execute `sonar-scanner` without error.

**Additional context**
If I remove dependency check plugin from SonarQube, sonar-scanner works fine, without this error

.

**Comment by jeremylong** [comment]
I do not believe this bug is in dependency-check.  The NPE is in the dependency-check-sonar plugin. Please open a ticket with the plugin: https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/issues/new/choose

Initial guess - there are two places a "CVSS" score may appear in the XML output: for CVSSv2 there is the `cvssScore` and for CVSSv3 there is the `baseScore`. However, there is no gaurentee (per the schema) that a vulnerability will have a CVSSv2 or CVSSv3 score - it might have one, both, or none. In the cases where no CVSS score exists and we only have a "severity" (high, medium, low).  But even then, the base severity reported is from the external tool that dependency-check is wrapping (such as bundler-audit, npm audit, retireJS, etc.) and it may not directly map to high, medium, low.
