### ISSUE TITLE
Malformed URL for local NVD store

### ISSUE THREAD

**Issue by rjohnsonIWS** [dependency-check/DependencyCheck#2059]
**Problem**  
Updated to 5.1.0 and now CLI throws a page not found exception caused by a malformed URL.  If this is a simple case of using a different kind of URL to specify, I sure can't find the right on.

** Here is the command used **
$ ~/Projects/Sonar/dependency-check/bin/dependency-check.sh --project foo_server --scan ./**/* --format XML --cveUrlModified http://192.168.20.203/Data/ --cveUrlBase http://192.168.20.203/Data/

** Response -- issue highlighted **
[INFO] Checking for updates
[ERROR] Unable to download meta file: http://192.168.20.20meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: http://192.168.20.20meta
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:359)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:401)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:121)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:915)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:717)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:652)
	at org.owasp.dependencycheck.App.runScan(App.java:248)
	at org.owasp.dependencycheck.App.run(App.java:179)
	at org.owasp.dependencycheck.App.main(App.java:74)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'http://192.168.20.20meta'
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:115)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:352)
	... 8 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file http://192.168.20.20meta; unable to connect.
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:238)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:138)
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:110)
	... 9 common frames omitted
Caused by: java.net.**_UnknownHostException: 192.168.20.20meta_**
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:178)
	... 11 common frames omitted
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: http://192.168.20.20meta
[ERROR] No documents exist

** Version of dependency-check used **
5.1.0
We just updated from 5.0 to see if it fixed a similar issue of being unable to find data but only when calling the script from a testing vm.

Actual file info:
18411535    Jul 10 08:11     dependency-check-5.1.0-release.zip

**Comment by rjohnsonIWS** [comment]
Cockpit error:
needed to add:  /nvdcve-1.0-modified.json.gz
