### ISSUE TITLE
NullPointerException in AssemblyAnalyzer.analyzeDependency()

### ISSUE THREAD

**Issue by mdesousa** [dependency-check/DependencyCheck#2074]
We are getting NullPointerException in assemblies in our project
The problem occurs using version 5.1.1 of the cli. It looks similar to #2025, but this one happens in a different line of code. Also, #2025 used to fail for many assemblies and most errors have disappeared in 5.1.1... just this one remains.

See below the error message and stack trace, thanks.
```
[WARN] An unexpected error occurred during analysis of 'MyAssembly.dll' (Assembly Analyzer): null
[ERROR]
java.lang.NullPointerException: null
        at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.analyzeDependency(AssemblyAnalyzer.java:234)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by jeremylong** [comment]
Sorry about that.  I need to build up a better set of .net assemblies to analyze as part of my test cases.

**Comment by mdesousa** [comment]
No problem... the one that ran into this issue is actually in nuget: https://www.nuget.org/packages/chilkat-win32/9.5.0.76. The assembly is \lib\net20\ChilkatDotNet2.dll.
