### ISSUE TITLE
RetireJS Analyzer fails

### ISSUE THREAD

**Issue by nhtones** [dependency-check/DependencyCheck#2079]
**Describe the bug**
Running RetireJS Analyzer reports fail to initialise.  Verbose log indicates an error parsing JSON data file.

JS resources within project are embedded within application library using WebJars.

** Version of dependency-check used **
dependency check 5.1.1 running from Jenkins via plugin

** Log file **
DEBUG - Initializing RetireJS Analyzer
2019-07-17 16:06:39,028 org.owasp.dependencycheck.utils.Settings:902
DEBUG - Settings.getDataFile() - file: '/home/jenkins/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dep-check-5.1.1/data'
2019-07-17 16:06:39,036 org.owasp.dependencycheck.Engine:850
ERROR - Unexpected exception occurred initializing RetireJS Analyzer.
2019-07-17 16:06:39,037 org.owasp.dependencycheck.Engine:851
DEBUG - 
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at com.h3xstream.retirejs.repo.VulnerabilitiesRepositoryLoader.loadFromInputStream(VulnerabilitiesRepositoryLoader.java:106)
	at org.owasp.dependencycheck.analyzer.RetireJsAnalyzer.prepareFileTypeAnalyzer(RetireJsAnalyzer.java:179)
	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:837)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:673)
	at org.owasp.dependencycheck.App.runScan(App.java:251)
	at org.owasp.dependencycheck.App.run(App.java:183)
	at org.owasp.dependencycheck.App.main(App.java:80)
2019-07-17 16:06:39,038 org.owasp.dependencycheck.Engine:836

**To Reproduce**
Running against latest NVD definitions run an dependency check analysis.

**Expected behavior**
RetireJS analyzer performs analysis on JS resources within project

**Additional context**
Disabling the analyzer allows dependency check to complete successfully.

**Comment by jeremylong** [comment]
Can you delete `/home/jenkins/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dep-check-5.1.1/data/jsrepository.json` and try re-running dependency-check? It appears that the file is corrupted on your system.

**Comment by nhtones** [comment]
Hi many thanks, I removed the JSON file and it has recreated a valid file and the dependency check runs as expected
