### ISSUE TITLE
No lock file Generated with --noupdate

### ISSUE THREAD

**Issue by jordankoehn** [dependency-check/DependencyCheck#2089]
On version 4.X.X there was a lock file created when updating the db, as well as when reading from it. Now on 5.1.0 there is only a lock file created when updating the db. 

If multiple jobs in jenkins are using the same db (without updating) one may fail if the db is in use. My workaround is to have my ant dependency-check step wait if a lock file exist. On the newest version I needed to modify my ant task to create and delete a lock file since none is created by dependency-check.

**Comment by jeremylong** [comment]
The lock file name changed from 4.x to 5.x - it is now called `odc.update.lock`.  I just verified on my system that I am seeing the lock file created when a new database created and when the database is updating.

The issue with failures when multiple jobs were accessing the same data file should have been resolved in the 4.x or earlier release. If the lock file is present ODC will wait until the lock is removed.  The process as it stands today is:

1. ODC will check if the lock exists; if it is not present it will create a lock file
   a. ODC will spin-wait until the lock is clear and it is able to create a lock for itself
2. ODC will, if configured update the databse
3. ODC will make a temporary copy of the database
4. ODC will release the lock
5. ODC will use the temporary copy for the analysis
6. ODC will delete the temporary copy of the database

You should not have to do anything special to prevent two or more instances running at the same time.

**Comment by jordankoehn** [comment]
Thanks for getting back to me. I see that there is a lock created when updating the database. What I am referring to is when autoUpdate=false and multiple builds are reading from the db at the same time I get the following error, "The file is locked: nio:/data/vulnerabilitydb/odc.mv.db".

`org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
	at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:758)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:736)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:652)
	at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1565)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Next Exception:
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
	at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:757)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:736)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:652)
	at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1565)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the database
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:178)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:387)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:357)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1013)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:731)
	... 44 more
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:163)
	... 49 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/data/vulnerabilitydb/odc.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	... 66 more`

**Comment by RyanMcC** [comment]
I'm also having the same problem with the cli. As a test dataset, I'm using WebGoat 6.0.1. After grabbing the database with `dependency-check-5.1.0\bin\dependency-check.bat --updateonly`, I can reproduce consistently by running ~8 concurrent instances of `dependency-check-5.1.0\bin\dependency-check.bat --project wg --scan wg --format XML --out dc-1.xml --log dc-1.log --noupdate`. Usually at least a couple will fail and say
```
[ERROR] One or more fatal errors occurred
[ERROR] Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
```

Here's the full log of one of the instances that failed [dc-6.log](https://github.com/jeremylong/DependencyCheck/files/3428402/dc-6.log)

**Comment by jeremylong** [comment]
Thank you for pointing this out.  Apparently, with the `--noupdate` option things go awry with multiple connections.  I'll have to move some code around to solve this problem.  However, if you can by removing the `--noupdate` from your call to ODC you will not see the failures.  This will incur a very minimal "check" for updates - but will then correctly execute.
