### ISSUE TITLE
Dependency check maven plugin doesn't report Node vulnerabilities along with Jars

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2136]
We have requirement to run dependency check maven plugin against maven's multi-module project containing both Jar and JavaScript files. Maven Plugin should be able to scan these files and provide consolidated report with vulnerabilities.

Is it currently achievable with the plugin?
If yes, please let me know the solution or you can give any related suggestion /workaround to it.

Currently, we could see only solution to get a complete audit is by running both the maven plugin and the standalone CLI on source code which will consume more time and resource.

Please help with your suggestions/ideas.

**Comment by jeremylong** [comment]
You need to configure the `scanSet` to include the node modules. See the configuration documentation here: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

**Comment by Anshu2405** [comment]
Hi ,

Thanks for your reply. I have tried scanSet option and its failing due to below error.

scanSet value : {Path}/frontend-maven-plugin/frontend-maven-plugin/src/it/example project/

Test project : https://github.com/eirslett/frontend-maven-plugin

ERROR - 

END ANALYSIS
----------------------------------------------------
[^[[1;34mINFO^[[m] Analysis Complete (762 seconds)
[^[[1;36mDEBUG^[[m] Initializing Velocity, Calling init()...
[^[[1;36mDEBUG^[[m] Starting Apache Velocity v2.0
[^[[1;36mDEBUG^[[m] Default Properties resource: org/apache/velocity/runtime/defaults/velocity.properties
[^[[1;36mDEBUG^[[m] ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.FileResourceLoader
[^[[1;36mDEBUG^[[m] FileResourceLoader: adding path '.'
[^[[1;36mDEBUG^[[m] initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Stop
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Define
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Break
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Evaluate
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[^[[1;36mDEBUG^[[m] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[^[[1;36mDEBUG^[[m] Created '20' parsers.
[^[[1;36mDEBUG^[[m] "velocimacro.library.path" is not set. Trying default library: velocimacros.vtl
[^[[1;36mDEBUG^[[m] Default library velocimacros.vtl not found. Trying old default library: VM_global_library.vm
[^[[1;36mDEBUG^[[m] Old default library VM_global_library.vm not found.
[^[[1;36mDEBUG^[[m] allowInline = true: VMs can be defined inline in templates
[^[[1;36mDEBUG^[[m] allowInlineToOverride = false: VMs defined inline may NOT replace previous VM definitions
[^[[1;36mDEBUG^[[m] allowInlineLocal = false: VMs defined inline will be global in scope if allowed.
[^[[1;36mDEBUG^[[m] autoload off: VM system will not automatically reload global library macros
[^[[1;36mDEBUG^[[m] added VM writeException: source=org.apache.velocity.Template@16da1abc
[^[[1;36mDEBUG^[[m] Deleting ALL temporary files from `/tmp/dctempc64259aa-a7ae-45a9-8748-006b174f3f18`

2019-08-07 06:48:04,479 ERROR - org.apache.maven.plugin.PluginExecutionException: Execution null of goal org.owasp:dependency-check-maven:5.2.1:check failed.
[^[[1;34mINFO^[[m] ^[[1m------------------------------------------------------------------------^[[m
[^[[1;34mINFO^[[m] ^[[1mReactor Summary:^[[m
[^[[1;34mINFO^[[m]
[^[[1;34mINFO^[[m] Frontend Plugins ................................... ^[[1;31mFAILURE^[[m [12:55 min]
[^[[1;34mINFO^[[m] frontend-plugin-core ............................... ^[[1;33mSKIPPED^[[m
[^[[1;34mINFO^[[m] Maven Frontend Plugin .............................. ^[[1;33mSKIPPED^[[m
[^[[1;34mINFO^[[m] ^[[1m------------------------------------------------------------------------^[[m
[^[[1;34mINFO^[[m] ^[[1;31mBUILD FAILURE^[[m
[^[[1;34mINFO^[[m] ^[[1m------------------------------------------------------------------------^[[m
[^[[1;34mINFO^[[m] Total time: 12:55 min
[^[[1;34mINFO^[[m] Finished at: 2019-08-07T06:48:04-07:00
[^[[1;34mINFO^[[m] Final Memory: 19M/264M
[^[[1;34mINFO^[[m] ^[[1m------------------------------------------------------------------------^[[m
[^[[1;31mERROR^[[m] Failed to execute goal 

Build Failed while executing owasp scan for Module : frontend-plugins^[[m
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal ${project}:${artifact}:${version}:${goal} failed:
Build Failed while executing owasp scan for Module : frontend-plugins
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[^[[1;31mERROR^[[m]
[^[[1;31mERROR^[[m]
[^[[1;31mERROR^[[m] For more information about the errors and possible solutions, please read the following articles:
[^[[1;31mERROR^[[m] ^[[1m[Help 1]^[[m http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[^[[1;36mDEBUG^[[m] Entering finalize


Also, the test project has multiple package.json .Is there any way I could pass multiple values in scanSet option.
./frontend-maven-plugin/src/it/yarn-integration/package.json
./frontend-maven-plugin/src/it/custom-install-directory/package.json
./frontend-maven-plugin/src/it/example project/package.json

Could you please look into the issue .

**Comment by Anshu2405** [comment]
Hi Team,

Could you please help us on this issue. We are not able to proceed further with our release as scanSet option is not working for us.

**Comment by jeremylong** [comment]
The scanSet is specified like this:

```
                    <scanSet>
                        <fileSet>
                            <directory>src/test</directory>
                        </fileSet>
                        <fileSet>
                            <directory>src/main</directory>
                        </fileSet>
                    </scanSet>
```
