### ISSUE TITLE
Go Project returned Sonatype OSS Index Analyzer : Failed to request component-reports

### ISSUE THREAD

**Issue by aidatulahmad** [dependency-check/DependencyCheck#2153]
Hi, 
I have performed a scan against a Go project using dependency check Jenkins plugin version 5.2.1. 
The following are the syntax that I used : 
`dependencyCheck additionalArguments: '--project GoProject --scan go-project --enableExperimental --format ALL -l odc.log', odcInstallation: '5.2.1'`

The job is failed and in the log file, the following error is returned : 
```
DEBUG - Connecting to: https://ossindex.sonatype.org/api/v3/component-report
2019-08-13 18:39:17,008 org.owasp.dependencycheck.analyzer.OssIndexAnalyzer:162
DEBUG - Error requesting component reports
java.lang.IllegalStateException: Result size mismatch; expected: 91, have: 35
	at com.google.common.base.Preconditions.checkState(Preconditions.java:676)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.doRequestComponentReports(OssindexClientImpl.java:208)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:170)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:217)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:153)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-08-13 18:39:17,008 org.owasp.dependencycheck.AnalysisTask:90
WARN  - An error occurred while analyzing '/usr/local/var/jenkins/workspace/dependency-check-golang/go-project/Gopkg.lock' (Sonatype OSS Index Analyzer).
2019-08-13 18:39:17,008 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/usr/local/var/jenkins/workspace/dependency-check-golang/go-project/Gopkg.lock' (Sonatype OSS Index Analyzer)
2019-08-13 18:39:17,009 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/usr/local/var/jenkins/workspace/dependency-check-golang/go-project/Gopkg.lock' (Sonatype OSS Index Analyzer)
2019-08-13 18:39:17,009 org.owasp.dependencycheck.AnalysisTask:91
DEBUG - 
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to request component-reports
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:164)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Result size mismatch; expected: 91, have: 35
	at com.google.common.base.Preconditions.checkState(Preconditions.java:676)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.doRequestComponentReports(OssindexClientImpl.java:208)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:170)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:217)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:153)
	... 7 common frames omitted
```

Note that: The issue does not occur when I performed a scan against PHP and JS project. 

Does anyone has encountered this issue?

**Comment by jdillon** [comment]
Looking into this a bit more, appears to be an issue with ODC GolangDepAnalyzer providing package-url #subpath for golang packages inside of a golang component/module, which OSSIndex may not be expecting or handling properly ATM.

**Comment by jeremylong** [comment]
@jdillon I had based the decision to use the subpath based on the examples given in [purl-spec](https://github.com/package-url/purl-spec): 

```
pkg:golang/google.golang.org/genproto#googleapis/api/annotations
```

**Comment by jdillon** [comment]
OSS Index has been updated to better cope with Package-URL that contain subpath.

**Comment by aidatulahmad** [comment]
The issue is no longer reproducible. Thanks!
