### ISSUE TITLE
Error with Java 11

### ISSUE THREAD

**Issue by rafaborrego** [dependency-check/DependencyCheck#2158]
Hi, we use dependency-check (v4) in multiple Java 8 applications but we are getting an
StringIndexOutOfBoundsException when we try to run it with Java 11. Is it supported?
Unfortunately I cannot upload the log as a gist due to proxy issues, but please find the relevant stack trace below.
Thanks

Error trace:
`java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
	at java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.lang.String.substring(String.java:1874)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.getJavaVersion(DependencyCheckExecutor.java:415)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:89)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)`

**Comment by mprins** [comment]
No, it's not going to work. V4 is no longer supported, please try a current release.

**Comment by rafaborrego** [comment]
Thanks, I have checked it and works fine with v5.
Best regards
