### ISSUE TITLE
NPE during gradle plugin check

### ISSUE THREAD

**Issue by cmuchinsky** [dependency-check/DependencyCheck#2165]
Hit the following NPE today using the `5.2.1` version of the gradle plugin. Same code was working yesterday, so I'm guessing it might be due to some changes in the cve data.

```
java.lang.NullPointerException
        at java.lang.String.regionMatches(String.java:1278)
        at org.owasp.dependencycheck.xml.suppression.SuppressionRule.lambda$process$1(SuppressionRule.java:495)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
        at org.owasp.dependencycheck.xml.suppression.SuppressionRule.process(SuppressionRule.java:495)
        at org.owasp.dependencycheck.analyzer.AbstractSuppressionAnalyzer.lambda$analyzeDependency$0(AbstractSuppressionAnalyzer.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.owasp.dependencycheck.analyzer.AbstractSuppressionAnalyzer.analyzeDependency(AbstractSuppressionAnalyzer.java:115)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wakingrufus** [comment]
I am still seeing this in 5.2.2:
```
java.lang.NullPointerException
        at java.lang.String.regionMatches(String.java:1278)
        at org.owasp.dependencycheck.xml.suppression.SuppressionRule.lambda$process$1(SuppressionRule.java:496)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
        at org.owasp.dependencycheck.xml.suppression.SuppressionRule.process(SuppressionRule.java:496)
        at org.owasp.dependencycheck.analyzer.AbstractSuppressionAnalyzer.lambda$analyzeDependency$0(AbstractSuppressionAnalyzer.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.owasp.dependencycheck.analyzer.AbstractSuppressionAnalyzer.analyzeDependency(AbstractSuppressionAnalyzer.java:115)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
