### ISSUE TITLE
Problem Utilizing Local Definitions

### ISSUE THREAD

**Issue by jorymorrison** [dependency-check/DependencyCheck#2167]
I've tried serveral permutations of the below command, all result in an error loading the metadata file....some including file://, file:///, no file: at all, quotes, single quotes, etc... Any ideas on how my usage is not correct?

`jory@PC:/c/Users/jory/owasp-azure-devops/dependency-check/bin$ ls -A1 ../NVD/nist-mirror/`

```
nvdcve-1.0-2002.json
nvdcve-1.0-2002.json.gz
nvdcve-1.0-2002.meta
nvdcve-1.0-2003.json
nvdcve-1.0-2003.json.gz
nvdcve-1.0-2003.meta
nvdcve-1.0-2004.json
nvdcve-1.0-2004.json.gz
nvdcve-1.0-2004.meta
nvdcve-1.0-2005.json
nvdcve-1.0-2005.json.gz
nvdcve-1.0-2005.meta
nvdcve-1.0-2006.json
nvdcve-1.0-2006.json.gz
nvdcve-1.0-2006.meta
nvdcve-1.0-2007.json
nvdcve-1.0-2007.json.gz
nvdcve-1.0-2007.meta
nvdcve-1.0-2008.json
nvdcve-1.0-2008.json.gz
nvdcve-1.0-2008.meta
nvdcve-1.0-2009.json
nvdcve-1.0-2009.json.gz
nvdcve-1.0-2009.meta
nvdcve-1.0-2010.json
nvdcve-1.0-2010.json.gz
nvdcve-1.0-2010.meta
nvdcve-1.0-2011.json
nvdcve-1.0-2011.json.gz
nvdcve-1.0-2011.meta
nvdcve-1.0-2012.json
nvdcve-1.0-2012.json.gz
nvdcve-1.0-2012.meta
nvdcve-1.0-2013.json
nvdcve-1.0-2013.json.gz
nvdcve-1.0-2013.meta
nvdcve-1.0-2014.json
nvdcve-1.0-2014.json.gz
nvdcve-1.0-2014.meta
nvdcve-1.0-2015.json
nvdcve-1.0-2015.json.gz
nvdcve-1.0-2015.meta
nvdcve-1.0-2016.json
nvdcve-1.0-2016.json.gz
nvdcve-1.0-2016.meta
nvdcve-1.0-2017.json
nvdcve-1.0-2017.json.gz
nvdcve-1.0-2017.meta
nvdcve-1.0-2018.json
nvdcve-1.0-2018.json.gz
nvdcve-1.0-2018.meta
nvdcve-1.0-2019.json
nvdcve-1.0-2019.json.gz
nvdcve-1.0-2019.meta
nvdcve-1.0-modified.json
nvdcve-1.0-modified.json.gz
nvdcve-1.0-modified.meta
```

`jory@PC:/c/Users/jory/owasp-azure-devops/dependency-check/bin$ sh dependency-check.sh -s ../../../Downloads/webgoat-src/ --cveUrlBase=file:///../NVD/nist-mirror/nvdcve-1.0-%d.json.gz --cveUrlModified=file:///../NVD/nist-mirror/nvdcve-1.0-modified.json.gz`

```[INFO] Checking for updates
[ERROR] Unable to download meta file: file:///../NVD/nist-mirror/nvdcve-1.0-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: file:///../NVD/nist-mirror/nvdcve-1.0-modified.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:347)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:385)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)
        at org.owasp.dependencycheck.App.runScan(App.java:251)
        at org.owasp.dependencycheck.App.run(App.java:183)
        at org.owasp.dependencycheck.App.main(App.java:80)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'file:/../NVD/nist-mirror/nvdcve-1.0-modified.meta'
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:115)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:340)
        ... 8 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, file ('file:/../NVD/nist-mirror/nvdcve-1.0-modified.meta') does not exist
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:130)
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:110)
        ... 9 common frames omitted
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: file:///../NVD/nist-mirror/nvdcve-1.0-modified.meta
[ERROR] No documents exist```

**Comment by mprins** [comment]
The code is trying to download using http, file URLs seem unsupported looking at the code. What makes you think it should work?

**Comment by jorymorrison** [comment]
I saw someone using `file://` [here](https://github.com/jeremylong/DependencyCheck/issues/620), albeit in a different context. 

I would prefer not to serve the NVD via HTTP. I wonder if there is a way to build the database based off of NVD files retrieved manually and point Dep Check at that database...

**Comment by aikebah** [comment]
@mprins The code is delusive in naming. [HttpResourceConnection](https://github.com/jeremylong/DependencyCheck/blob/master/utils/src/main/java/org/owasp/dependencycheck/utils/HttpResourceConnection.java#L113) handles the `file` protocol just fine.

@jorymorrison 
The issue is with Java's URL constructor. The code calls the [URL(java.lang.String)](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL(java.lang.String)) constructor, which, as documented, behaves as `URL(java.net.URL, java.lang.String)` with a `null` URL context. So the .. gets stripped yielding an effective URL of /NVD/..... which does not exist.

In case of a file-URL you still have to provide the full absolute URL to the content

i.e. the following should work fine:

```
jory@PC:/c/Users/jory/owasp-azure-devops/dependency-check/bin$ sh dependency-check.sh -s ../../../Downloads/webgoat-src/ --cveUrlBase=file:///c/Users/jory/owasp-azure-devops/dependency-check/bin/NVD/nist-mirror/nvdcve-1.0-%d.json.gz --cveUrlModified=file:///c/Users/jory/owasp-azure-devops/dependency-check/bin/NVD/nist-mirror/nvdcve-1.0-modified.json.gz
```

**Comment by jorymorrison** [comment]
Thank you very much for the explanation. l'll give the absolute path a try.
