### ISSUE TITLE
[DependencyCheck] [ERROR] No documents exist when using data path

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#2200]
Hi

Im using the newer version of jenkins dependency check plugin (5.0.2).  Im using a mirror for the NVD database, and apparently its not working well with this version

In version 4, i was setting this path as follows:

dependencyCheckAnalyzer([datadir: 'path/to/my/db/folder', isAutoupdateDisabled: True, ...])

In version 5, i have: 
dependencyCheck additionalArguments: '... --data path/to/my/db/folder --noupdate ....'

The error i have is this:

[DependencyCheck] [ERROR] Unable to continue dependency-check analysis.
[DependencyCheck] [ERROR] One or more fatal errors occurred
[DependencyCheck] [ERROR] No documents exist

Thanks

**Comment by jeremylong** [comment]
Try adding `--log odc.log` and then `archiveArtifacts odc.log`. You can then review the log to see what is going on.

**Comment by javixeneize** [comment]
Hi

It finds the file but apparently it cant open it correctly. It says db schema is 4.1, i dont know if we should be using a different schema for V5?

DEBUG - DB Schema: 4.1

DEBUG - Connection String: 'jdbc:h2:file:/tmp/dctemp46241448-dbad-47aa-b85d-6e85f04fa6bc/odc;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;ACCESS_MODE_DATA=r'
2019-09-23 11:37:50,500 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:154
DEBUG - Loading database connection
2019-09-23 11:37:50,501 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:155
DEBUG - Connection String: jdbc:h2:file:/tmp/dctemp46241448-dbad-47aa-b85d-6e85f04fa6bc/odc;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;ACCESS_MODE_DATA=r
2019-09-23 11:37:50,501 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:156
DEBUG - Database User: [REDACTED]
2019-09-23 11:37:50,879 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:421
DEBUG - DC Schema: 4.1
2019-09-23 11:37:50,879 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:422
DEBUG - DB Schema: 4.1
2019-09-23 11:37:50,894 org.owasp.dependencycheck.data.nvdcve.CveDB:369
DEBUG - Database product: h2
2019-09-23 11:37:50,968 org.owasp.dependencycheck.utils.H2DBLock:224
DEBUG - Lock released (main) 8aa1ef299632b1c1872d328de15be58e @ 2019-09-23 11:37:50.968
2019-09-23 11:37:50,969 org.owasp.dependencycheck.Engine:1165
ERROR - Unable to continue dependency-check analysis.
2019-09-23 11:37:50,971 org.owasp.dependencycheck.Engine:1166
DEBUG - 
org.owasp.dependencycheck.exception.NoDataException: No documents exist
	at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:1150)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:657)
	at org.owasp.dependencycheck.App.runScan(App.java:251)
	at org.owasp.dependencycheck.App.run(App.java:183)
	at org.owasp.dependencycheck.App.main(App.java:80)
2019-09-23 11:37:51,285 org.owasp.dependencycheck.App:199
ERROR - One or more fatal errors occurred
2019-09-23 11:37:51,285 org.owasp.dependencycheck.App:205
ERROR - No documents exist
2019-09-23 11:37:51,286 org.owasp.dependencycheck.App:206
DEBUG - unexpected error
org.owasp.dependencycheck.exception.NoDataException: No documents exist
	at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:1150)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:657)
	at org.owasp.dependencycheck.App.runScan(App.java:251)
	at org.owasp.dependencycheck.App.run(App.java:183)
	at org.owasp.dependencycheck.App.main(App.java:80)
2019-09-23 11:37:51,286 org.owasp.dependencycheck.utils.Settings:668
DEBUG - Deleting ALL temporary files from `/tmp/dctemp46241448-dbad-47aa-b85d-6e85f04fa6bc`
2019-09-23 11:37:51,292 org.owasp.dependencycheck.App:81
DEBUG - Exit code: -13

**Comment by jeremylong** [comment]
You are using the `--noupdate` flag and there is no data in the database.  As such, dependency-check cannot continue.

**Comment by javixeneize** [comment]
There’s data in the dB. I use it in dependency check v4. Do I need a different dB for this new version?

**Comment by jeremylong** [comment]
Version 5 uses a different database schema than 4.
