### ISSUE TITLE
NPE in Engine.

### ISSUE THREAD

**Issue by mebigfatguy** [dependency-check/DependencyCheck#2212]
**Describe the bug**
We run a ton of jenkins jobs in a dockered environment and part of the job is running dependency check ant.

We occasionally get NPEs as follows (altho most times it works fine).

 /scratch/gbuacme/workspace/jenkins/workspace/Acme_Continuous/projects/devtasks/build.xml:398: java.lang.NullPointerException

[2019-09-24T10:43:44.244Z] 	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1247)

[2019-09-24T10:43:44.244Z] 	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1201)

[2019-09-24T10:43:44.244Z] 	at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1543)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)

[2019-09-24T10:43:44.244Z] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)

[2019-09-24T10:43:44.244Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-09-24T10:43:44.244Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Task.perform(Task.java:348)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Target.execute(Target.java:435)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)

[2019-09-24T10:43:44.244Z] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

** Version of dependency-check used **
5.2.1
** Log file **
I'll try to find the appropriate ones

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jeremylong** [comment]
With 5.2.2 - the volume declaration was corrected (see #2199). I saw some odd things in previous usage of ODC - and the volume declaration may have been the root cause of some of the oddities.

**Comment by mebigfatguy** [comment]
same issue with 5.2.2.

**Comment by aikebah** [comment]
@mebigfatguy Can you confirm the following:
I expect in the the logs of a failing job

> Unable to update 1 or more Cached Web DataSource, using local  data instead. Results may not include recent vulnerabilities.

And do your ant jobs run with failOnError set to false?

**Comment by aikebah** [comment]
@jeremylong Should we 'try to continue with an open database', or should we fully fail?

Currently code will close the database and throw an UpdateException (hence the NullPointer)
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/src/main/java/org/owasp/dependencycheck/Engine.java#L864-L868
 
And then just issue a warning
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/src/main/java/org/owasp/dependencycheck/Engine.java#L663-L667

Causing ensureDataExists to throw a NoDataException
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/src/main/java/org/owasp/dependencycheck/Engine.java#L1065-L1067
Which triggers the Engine to throw a fatal exception
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/src/main/java/org/owasp/dependencycheck/Engine.java#L597-L599
Which is checked for fatality in de maven plugin
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1616
the CLI
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/cli/src/main/java/org/owasp/dependencycheck/App.java#L256
the Agent
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/core/src/main/java/org/owasp/dependencycheck/agent/DependencyCheckScanAgent.java#L976
but not the Ant plugin
https://github.com/jeremylong/DependencyCheck/blob/f9b4f4136ec4c4e4d1d944faa64a3c8880794616/ant/src/main/java/org/owasp/dependencycheck/taskdefs/Check.java#L1706-L1713

The message however indicates that the intention is to 'continue with whatever we happen to have available locally', so I would expect that the database would be re-opened in read-only mode before throwing the UpdateException (if remainOpen is true of course)
