### ISSUE TITLE
Jenkins plugin not pulling jsrepository.json with java-11-openjdk

### ISSUE THREAD

**Issue by jmorte1** [dependency-check/DependencyCheck#2251]
I have been having an issue running OWASP 5.2.2 through the jenkins plugin. From what I have found the issue lies with the version of java. Basically when retire.js attempts to update jsrepository.json I get errors and the file is replaced, but empty. Through strace I found it was complaining about java. I downgraded to java 8 and it successfully updated. However I need java 11 for my build. Please see the below error and any help is much appreciated as I haven't found any solutions online.
```
DEBUG - Attempting retrieval of https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
2019-10-09 07:38:22,025 org.owasp.dependencycheck.Engine:925
ERROR - Failed to initialize the RetireJS repo
org.owasp.dependencycheck.data.update.exception.UpdateException: Failed to initialize the RetireJS repo
        at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:151)
        at org.owasp.dependencycheck.data.update.RetireJSDataSource.update(RetireJSDataSource.java:97)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)
        at org.owasp.dependencycheck.App.runScan(App.java:251)
        at org.owasp.dependencycheck.App.run(App.java:183)
        at org.owasp.dependencycheck.App.main(App.java:80)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to copy 'https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json' to '/home/zcompile/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/OWASP_Dependency_Check_5.2.2/data/jsrepository.json'
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:91)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:68)
        at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:149)
        ... 7 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:238)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:138)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:87)
        ... 9 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:178)
        ... 11 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 17 common frames omitted
```

**Comment by jeremylong** [comment]
My initial guess is that there is a cert missing in cacerts.

**Comment by jmorte1** [comment]
That's what I thought too, but I checked and added certs from the repo that were missing, still had the same result. I'm not that well versed with Java, is there a way to tell what certs it's looking for specifically or a way to get a more verbose debug?

**Comment by jmorte1** [comment]
I tried setting it up as a local repo on my machine and am still having issues. I can curl the file as the user who runs the job, but it fails to get the repo with a 400 error. The jsrepository.json file has read permissions for other and is also owned by the user running the dependency check...

**Comment by mprins** [comment]
You might want to try and disable TLS v1.3, it seems unstable in java 11

e.g.. https://webtide.com/openjdk-11-and-tls-1-3-issues/

As for debugging, I think this might help: https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html
