### ISSUE TITLE
Dependency-check 5.x unable to download db

### ISSUE THREAD

**Issue by voyasas** [dependency-check/DependencyCheck#2328]
We were using 4.x plugin for jenkins and all the sudden we are having issue downloading the db update. Upgraded to 5.2 but got a different error. 

Here is the pipeline syntax:
 sh 'mkdir target'
dependencycheck additionalArguments: '--project NewProj --scan ./ --data dependency-check-nvd-db --out target/dependency-check-report.xml --format XML --log /tmp/dependency-check.log --noupdate', odcInstallation: 'dependency-check-5.2.4'
	
Here is the error message:
***
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:347)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:385)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:921)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:723)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:653)
        at org.owasp.dependencycheck.App.runScan(App.java:251)
        at org.owasp.dependencycheck.App.run(App.java:183)
        at org.owasp.dependencycheck.App.main(App.java:80)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta'
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:115)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:340)

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

***
I can manually download the file using wget on the same server without issue. I also tried to import the cert (zscalar cert?) to the keystore but still same thing. Tried 5.1, 5.2.x same error.

Finally I tried mirroring the db then use the "noupdate" option, but it doesn't recognized any of the local db files:

[DependencyCheck] [ERROR] Unable to continue dependency-check analysis.
[DependencyCheck] [ERROR] One or more fatal errors occurred
[DependencyCheck] [ERROR] No documents exist

I am stuck. Any suggestion?

**Comment by argeualcantara** [comment]
Your database is probably outdated with the version 4.x.
Try removing the --noupdate flag

**Comment by voyasas** [comment]
thanks for the comment. the reason i used noupdate was because i can't get passed the cert issue with the update option. Even after imported the cert from  https://nvd.nist.gov into the keystore I am still getting the following errors:

DEBUG - Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2010.xml.gz
2019-11-14 14:48:42,201 org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever:509
DEBUG - Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz
2019-11-14 14:48:42,201 org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever:509
DEBUG - Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2006.xml.gz
2019-11-14 14:48:42,202 org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever:509
DEBUG - Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz
2019-11-14 14:48:42,808 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - Available Protocols:
2019-11-14 14:48:42,809 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:287
DEBUG - TLSv1
2019-11-14 14:48:42,809 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:287
DEBUG - TLSv1.1
2019-11-14 14:48:42,809 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:287
DEBUG - TLSv1.2
2019-11-14 14:48:43,392 org.owasp.dependencycheck.utils.Downloader:279
ERROR - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2004.xml.gz: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is:
        java.security.cert.CertPathValidatorException: The certificate issued by EMAILADDRESS=support@zscaler.com, CN=Zscaler Root CA, OU=Zscaler Inc., O=Zscaler Inc., L=San Jose, ST=California, C=US is not trusted; internal cause is:
        java.security.cert.CertPathValidatorException: Certificate chaining error
2019-11-14 14:48:43,392 org.owasp.dependencycheck.utils.Downloader:279
ERROR - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is:
        java.security.cert.CertPathValidatorException: The certificate issued by EMAILADDRESS=support@zscaler.com, CN=Zscaler Root CA, OU=Zscaler Inc., O=Zscaler Inc., L=San Jose, ST=California, C=US is not trusted; internal cause is:
        java.security.cert.CertPathValidatorException: Certificate chaining error
2019-11-14 14:48:43,392 org.owasp.dependencycheck.utils.Downloader:279
ERROR - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is:
        java.security.cert.CertPathValidatorException: The certificate issued by EMAILADDRESS=support@zscaler.com, CN=Zscaler Root CA, OU=Zscaler Inc., O=Zscaler Inc., L=San Jose, ST=California, C=US is not trusted; internal cause is:

**Comment by jeremylong** [comment]
The XML data feeds from NIST have been retired since Oct 9th, 2019. Please upgrade to ODC 5.2.4.

5.0.0 moved from using the XML data feeds to using the JSON data feeds. See the release notes: https://github.com/jeremylong/DependencyCheck/blob/master/RELEASE_NOTES.md#version-500-m1-2019-02-17

**Comment by TobiX** [comment]
> java.security.cert.CertPathValidatorException: The certificate issued by EMAILADDRESS=support@zscaler.com, CN=Zscaler Root CA, OU=Zscaler Inc., O=Zscaler Inc., L=San Jose, ST=California, C=US is not trusted

@voyasas You seem to have an TLS intercepting proxy in your network. If you trust that proxy, you need to add its certificate to your trust store. If you don't trust that proxy, you need to find ways to get around it. This is not a problem the DependencyCheck project can help you with - please talk to your IT department.
