### ISSUE TITLE
Owasp 4.0.2 NVD DB(dc.h2.db) update is failing

### ISSUE THREAD

**Issue by sharanya321** [dependency-check/DependencyCheck#2336]
HI ,
I am running scanowasp goal for my maven project using owasp-4.0.2.But the NVD DB update is failing with below error,

INFO] Central analyzer disabled
[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[WARNING] An exception occurred downloading NVD CVE - 2002
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2003
[WARNING] An exception occurred downloading NVD CVE - 2003
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2004
[WARNING] An exception occurred downloading NVD CVE - 2004
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2005
[WARNING] An exception occurred downloading NVD CVE - 2005
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2006
[WARNING] An exception occurred downloading NVD CVE - 2006
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2007
[WARNING] An exception occurred downloading NVD CVE - 2007
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2008
[WARNING] An exception occurred downloading NVD CVE - 2008
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2009
[WARNING] An exception occurred downloading NVD CVE - 2009
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2010
[WARNING] An exception occurred downloading NVD CVE - 2010
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2011
[WARNING] An exception occurred downloading NVD CVE - 2011
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2012
[WARNING] An exception occurred downloading NVD CVE - 2012
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2013
[WARNING] An exception occurred downloading NVD CVE - 2013
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2014
[WARNING] An exception occurred downloading NVD CVE - 2014
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2015
[WARNING] An exception occurred downloading NVD CVE - 2015
Some CVEs may not be reported.
[INFO] Download Started for NVD CVE - 2016
.
.
.
with --debug option I get the below details error logs,
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2006.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2016.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2012.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2013.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2015.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2017.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[DEBUG] Temporary directory is `/var/folders/_2/vphjwft90qj253rkdm737bdr0000gn/T/dctempfee93835-6cfc-42df-9fcc-d46a7519358d`
[INFO] Download Started for NVD CVE - 2002
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.xml.gz complete
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2002.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2002.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2002
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.owasp.dependencycheck.utils.ExtractionUtil.extractGzip(ExtractionUtil.java:289)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:162)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Download Started for NVD CVE - 2003
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz complete
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2003.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2003.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2003
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.owasp.dependencycheck.utils.ExtractionUtil.extractGzip(ExtractionUtil.java:289)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:162)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Download Started for NVD CVE - 2004
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2004.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2004.xml.gz complete
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2004.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2004.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2004
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.owasp.dependencycheck.utils.ExtractionUtil.extractGzip(ExtractionUtil.java:289)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:162)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Download Started for NVD CVE - 2005
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz complete
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2005.xml.gz
[DEBUG] Download of https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-2005.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2005
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.owasp.dependencycheck.utils.ExtractionUtil.extractGzip(ExtractionUtil.java:289)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:162)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[DEBUG] Thread was interrupted during download
[INFO] Download Started for NVD CVE - 2006
[DEBUG] Attempting download of https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2006.xml.gz
[DEBUG] Lock released (main) 1cd31597b7f5efce3f8ce1c42a633281 @ 2019-11-20 16:17:51.017

.
.
.
It would be great if you could provide me a way to fix this issue.

**Comment by jeremylong** [comment]
ODC 4.x is no longer supported - primarily because the NVD deprecated the XML data feeds that were being used.  As of ODC 5.0.0 we use the JSON data feeds.  Please consider upgrading to 5.2.4.

**Comment by sharanya321** [comment]
Thank you!
