### ISSUE TITLE
NullPointerException in NpmPayloadBuilder.java:94

### ISSUE THREAD

**Issue by HEllRZA** [dependency-check/DependencyCheck#2361]
## A NullPointerException occured during NPM Scan in NpmPayloadBuilder.java:94

https://github.com/jeremylong/DependencyCheck/blob/40c5860fafd6e0199125652626e3da10f59a3665/core/src/main/java/org/owasp/dependencycheck/data/nodeaudit/NpmPayloadBuilder.java#L93-L94

Seems to me that, `dependencies == null`. There is no "dependencies" key package-lock.json.
When adding ` "dependencies": {}` to package-lock.json the error does not occur.

### Log
``` yml
[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] Analyzing `/home/user/code/some_package/package-lock.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[INFO] Finished Node.js Package Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] An unexpected error occurred during analysis of '/home/user/code/some_package/package-lock.json' (Node Audit Analyzer): null
[ERROR] java.lang.NullPointerException: null
	at org.owasp.dependencycheck.data.nodeaudit.NpmPayloadBuilder.build(NpmPayloadBuilder.java:94)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzePackage(NodeAuditAnalyzer.java:269)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:179)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Finished Node Audit Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (1 seconds)
```
### package-lock.json
``` yml
{
  "name": "some_package",
  "version": "1.0.0",
  "lockfileVersion": 1
}
```

### package-lock.json (no error occurs!)
``` yml
{
  "name": "some_package",
  "version": "1.0.0",
  "dependencies": {},
  "lockfileVersion": 1
}
```

### package.json
``` yml
{
  "name": "some_package",
  "version": "1.0.0",
  "description": "The package description",
  "private": true,
  "main": "app.js",
  "scripts": {},
  "author": "Mr Smith",
  "license": "APACHE",
  "dependencies": {},
  "repository": {
    "type": "git",
    "url": "https://$USER@bitbucket.org/some/package.git"
  }
}

```

**Comment by HEllRZA** [comment]
:thumbsup:
