### ISSUE TITLE
any way to disable getting component-report?

### ISSUE THREAD

**Issue by kkao88** [dependency-check/DependencyCheck#2371]
We're running into an issue at the end when we run this plugin on our jenkins instance, because our jenkins instance doesn't have connectivity to the outside internet (we;re using modified locations for cveUrls). since this is when all the dependencies have already been scanned, is there a way to skip this step?

[DEBUG] Connecting to: https://ossindex.sonatype.org/api/v3/component-report
[DEBUG] Error requesting component reports
java.net.SocketTimeoutException: connect timed out

org.owasp.dependencycheck.analyzer.exception.AnalysisException: Failed to request component-reports
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:164)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out

**Comment by jeremylong** [comment]
If running in an offline mode you would need to add the following configuration to disable to OSS Index Analyzer.  Note - this analyzer will report vulnerabilities that are not found in the NVD - but it requires sending the package URL (e.g. GAV) for your dependencies to Sonatypes OSS Index service and a list of known vulnerable components will be returned to dependency-check.

```xml
<configuration>
   <ossindexAnalyzerEnabled>false</ossindexAnalyzerEnabled>
</configuration>
```

**Comment by kkao88** [comment]
thank you
