### ISSUE TITLE
OWASPv5.2.4 is failing due to java.io.FileNotFoundException during vulnerability analysis

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2417]
**Describe the bug**
OWASP 5.2.4 cli is failing during due to java.io.FileNotFoundException while scanning Node project. 

** Version of dependency-check used **
5.2.4

** Log file **
[WARN] Failed to load entry: /home/OWASP/data/oss_cache/49/42/4942941f20b8b7ea1660828b806966c7f85ae0d2
java.io.FileNotFoundException: /homeOWASP/data/oss_cache/49/42/4942941f20b8b7ea1660828b806966c7f85ae0d2 (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.sonatype.ossindex.service.client.util.FileLocker.lock(FileLocker.java:57)
	at org.sonatype.ossindex.service.client.util.FileLocker.readLock(FileLocker.java:81)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.loadEntry(DirectoryCache.java:173)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.getIfPresent(DirectoryCache.java:117)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:150)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:217)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:153)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[WARN] Failed to load entry: ../home/OWASP/data/oss_cache/4b/7c/4b7c3a8c7a11da65249a42cac077bc1752f16d92
java.io.FileNotFoundException: /home//OWASP/data/oss_cache/4b/7c/4b7c3a8c7a11da65249a42cac077bc1752f16d92 (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.sonatype.ossindex.service.client.util.FileLocker.lock(FileLocker.java:57)
	at org.sonatype.ossindex.service.client.util.FileLocker.readLock(FileLocker.java:81)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.loadEntry(DirectoryCache.java:173)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.getIfPresent(DirectoryCache.java:117)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:150)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:217)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:153)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Is there any resource leak happening from OWASP code where files are not closed properly? Or if there is any open files limit which we need to take care while running OWASP?

We are testing in linux machine where open file limit is 1024.

$ ulimit -n 
open files                      (-n) 1024

**Comment by mprins** [comment]
> java.io.FileNotFoundException: /homeOWASP/data/oss_cache/49/42/4942941f20b8b7ea1660828b806966c7f85ae0d2 (Too many open files)

typically means just that; the OS is denying more resources (file handles) to the user running the tool.
NB. 1024 is a normal value for a regular user on linux

the stack trace indicates this origin:

https://github.com/sonatype/ossindex-public/blob/63b4717c08acf8f7d9c8b8a689e69d37c25071d5/client/src/main/java/org/sonatype/ossindex/service/client/util/FileLocker.java#L51-L75

**Comment by jeremylong** [comment]
I believe I figured out what is causing this - but I will need someone to validate when we push 5.3.0 in the next few days.

**Comment by caperutxa** [comment]
Hi @jeremylong Keep me in touch about that. I checked. Works nicely

Thanks

**Comment by jeremylong** [comment]
Thanks for validating!
