### ISSUE TITLE
Encounter 'unable to connect' issue when running mvn install even with the proxy configured.

### ISSUE THREAD

**Issue by willpowerforever** [dependency-check/DependencyCheck#242]
I am running in office network. I have setup the proxy in maven and import required certificate to my java keystore. Then, when I run mvn install, it is failed at DownloaderIntegrationTest. Is there anything else I need to configure? 

See error below:

Running org.owasp.dependencycheck.utils.DownloaderIntegrationTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.312 sec <<< FAILURE! - in org.owasp.dependencycheck.utils.DownloaderIntegrationTest
testGetLastModified(org.owasp.dependencycheck.utils.DownloaderIntegrationTest)  Time elapsed: 0.303 sec  <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP HEAD request.
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:581)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:434)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:219)
    at org.owasp.dependencycheck.utils.DownloaderIntegrationTest.testGetLastModified(DownloaderIntegrationTest.java:51)

testFetchFile(org.owasp.dependencycheck.utils.DownloaderIntegrationTest)  Time elapsed: 0 sec  <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz; unable to connect.
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:581)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:434)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:101)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:64)
    at org.owasp.dependencycheck.utils.DownloaderIntegrationTest.testFetchFile(DownloaderIntegrationTest.java:44)

**Comment by blaksec** [comment]
Ran into the same issue. Unless you reallycare for those tests, try with -DskipTests.  Otherwise configure java opts to pass proxy details.

**Comment by willpowerforever** [comment]
Hi gchorny,

Thanks for your reply! 

I configured http proxy settings in JAVA OPTS, but still encounter the same issue.
export JAVA_OPTS="-Dhttp.proxyHost=proxy.xxxxx.com -Dhttp.proxyPort=8080"

Anything wrong?

**Comment by blaksec** [comment]
That didn't work for me either. 

You can try modifying the JAVACMD variable inside dependency-check.sh appending your proxy details to the 'java' command as such:

JAVACMD="$JAVA_HOME/bin/java -Dhttp.proxyHost=<proxyIP> -Dhttp.proxyPort=<proxyPort> -Dhttps.proxyHost=<proxyIP> -Dhttps.proxyPort=<proxyPort>"

For additional debugging options use 'mvn -X' which what exactly is failing.

**Comment by willpowerforever** [comment]
OK. Thanks! I use -DskipTests. It worked well. : -)
