### ISSUE TITLE
DependencyCheck call exception MojoExecutor.execute if found CVE

### ISSUE THREAD

**Issue by patsevanton** [dependency-check/DependencyCheck#2439]
**Describe the bug**
DependencyCheck call exception MojoExecutor.execute if found CVE

**Version of dependency-check used**
maven plugin 5.3.0

**Project**
https://gitlab.com/anton_patsev/OWASP-Java

**Log file**
https://gitlab.com/anton_patsev/OWASP-Java/-/jobs/409871621

**To Reproduce**
fork and press Retry

**.gitlab-ci.yml**
https://gitlab.com/anton_patsev/OWASP-Java/blob/master/.gitlab-ci.yml

**Exception**
```
 See the dependency-check report for more details.
 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.checkForFailure(BaseDependencyCheckMojo.java:2064)
 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:1530)
 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:824)
 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
 	... 20 more
```

**Comment by jeremylong** [comment]
ODC version 3.3.1 is no longer supported. Please upgrade to 5.3.0:

https://gitlab.com/anton_patsev/OWASP-Java/blob/master/pom.xml#L15-17

Also, this is expected behavior depending on your configuration. Vulnerable components were identified -  I believe 3.3.1 by default failed the build. This is configurable: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

**Comment by patsevanton** [comment]
OWASP-Java is special repository for demo DependencyCheck
