### ISSUE TITLE
NullPointerException in NpmPayloadBuilder.java:129

### ISSUE THREAD

**Issue by selangley-wa** [dependency-check/DependencyCheck#2441]
**Describe the bug**

Error logged during analysis of a package-lock.json file:

[WARN] An unexpected error occurred during analysis of 'C:\VSTS\Repo\BudgetSubmittal\Presentation\ABR.Web\bin\Debug\netcoreapp3.0\package-lock.json' (Node Audit Analyzer): null
[ERROR]
java.lang.NullPointerException: null
        at org.owasp.dependencycheck.data.nodeaudit.NpmPayloadBuilder.build(NpmPayloadBuilder.java:129)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.legacyAnalysis(NodeAuditAnalyzer.java:356)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:188)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

**Version of dependency-check used**

Dependency-Check Core version 5.3.0

executed via a Windows 10 cmd prompt.

**Comment by jeremylong** [comment]
I just added a null check - but I was hoping you might be able to provide the `package.json` and `package-lock.json` files?  If you can't provide the files - can you run `npm audit` successfully?

**Comment by selangley-wa** [comment]
When I ran the command there was no package.json file in that particular directory.  There was a very simple package-lock.json file with these contents:

```
{
  "lockfileVersion": 1
}

```

**Comment by jeremylong** [comment]
Thanks.  the NPE has been fixed - but the analysis will still fail...
