### ISSUE TITLE
Dependency check fails with nullpointer in case jar file does not have a pom.properties

### ISSUE THREAD

**Issue by ca-stefan-cordes** [dependency-check/DependencyCheck#2533]
**Describe the bug**
When analysing mule-spring-module-1.3.2-mule-plugin.jar 
( https://repository.mulesoft.org/nexus/content/repositories/public/org/mule/modules/mule-spring-module/1.3.2/mule-spring-module-1.3.2-mule-plugin.jar )
with dependecy check version 5.3.1 a nullpointer appears.

```
java.lang.NullPointerException: null
	at org.owasp.dependencycheck.xml.pom.Model.processProperties(Model.java:314)
	at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzePOM(JarAnalyzer.java:410)
	at org.owasp.dependencycheck.analyzer.JarAnalyzer.analyzeDependency(JarAnalyzer.java:290)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Reason is that the jar
META-INF\maven\org.mule.modules\mule-spring-module\
contains a pom.xml but no pom.properties 
(ok, not really maven conform but dependencyCheck should continue working)

**Version of dependency-check used**
The problem occurs using version 5.3.1 of the cli

**Log file**
https://gist.github.com/ca-stefan-cordes/d7e1e07bf1de3fb0f71621948d66c1f7

**To Reproduce**
1. Copy https://repository.mulesoft.org/nexus/content/repositories/public/org/mule/modules/mule-spring-module/1.3.2/mule-spring-module-1.3.2-mule-plugin.jar to the target directory
2. run dependency check
3. See error

**Expected behavior**
No error ;-)

**Additional context**
With dependency-check-5.1.0 error does not come up.

**Comment by ca-stefan-cordes** [comment]
Thank you.
