### ISSUE TITLE
"Incorrect syntax near 'e'" SQLServerException during the MSSQL database maintenance

### ISSUE THREAD

**Issue by marcinradacz** [dependency-check/DependencyCheck#2545]
Hi,
I tried to setup a SQL Server database as a centralized database. Unfortunately I've got an exception in the section 'INFO  - Begin database maintenance':

DEBUG - 
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'e'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:471)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.cleanupDatabase(CveDB.java:1605)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:322)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:936)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:737)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:667)
	at org.owasp.dependencycheck.App.runScan(App.java:254)
	at org.owasp.dependencycheck.App.run(App.java:186)
	at org.owasp.dependencycheck.App.main(App.java:81)
2020-03-19 12:14:08,573 org.owasp.dependencycheck.Engine:939

I checked locally, that the problem was with the **dbStatements_microsoft sql server.properties** file, where i needed to add a modified version of **UPDATE_ECOSYSTEM2** statement:

`UPDATE_ECOSYSTEM2=UPDATE e SET e.ecosystem = NULL FROM cpeEntry e WHERE e.id IN (SELECT DISTINCT entry.id FROM vulnerability v INNER JOIN software s ON v.id = s.cveid INNER JOIN cpeEntry r ON s.cpeentryid=r.id INNER JOIN cpeEntry entry ON r.part = entry.part AND r.vendor = entry.vendor AND r.product = entry.product WHERE description like '%bindings%' AND r.ecosystem is not null AND entry.ecosystem is not null UNION ALL SELECT z.id FROM cpeEntry z WHERE z.ecosystem is not null AND z.vendor = 'apache' AND z.product = 'zookeeper')`

After that i compiled the project and executed Dependency-Check once again. This time everything went ok.

**Version of dependency-check used**
The problem occurs using version 5.3.1 of the CLI

**Comment by mprins** [comment]
see also #2521 (postgresql)
