### ISSUE TITLE
Getting ERROR "No Document Exists" when running command line check

### ISSUE THREAD

**Issue by yangsenss** [dependency-check/DependencyCheck#2552]
@jeremylong 
Hi Jeremy,
I configure local NVE mirror using command line.
1.  Here is the command i'm running
 
/dependency-check/bin/dependency-check.sh 
 -s $PWD/ 
 --log /data/dc.log 
 -f HTML 
 -o $PWD/ 
 --project testCheck 
 --cveUrl20Modified http://10.10.10.101:8081/nexus/content/repositories/Nvd/nvdcve-1.0-modified.json.gz  
 --cveUrl20Base http://10.10.10.101:8081/nexus/content/repositories/Nvd/nvdcve-1.0-%d.json.gz  
 --cveUrl12Modified http://10.10.10.101:8081/nexus/content/repositories/Nvd/nvdcve-1.0-modified.json	 
 --cveUrl12Base http://10.10.10.101:8081/nexus/content/repositories/Nvd/nvdcve-1.0-%d.json.gz
2.  Here is the log 
2020-03-24 17:02:28,918 org.owasp.dependencycheck.data.update.nvd.DownloadTask:184
INFO  - Download Complete for NVD CVE - Modified  (304 ms)
2020-03-24 17:02:28,919 org.owasp.dependencycheck.data.update.nvd.ProcessTask:163
INFO  - Processing Started for NVD CVE - Modified
2020-03-24 17:02:28,928 org.owasp.dependencycheck.Engine:676
WARN  - Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
2020-03-24 17:02:28,932 org.owasp.dependencycheck.Engine:678
DEBUG - Update Error
org.owasp.dependencycheck.data.update.exception.UpdateException: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:170)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:118)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:45)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1761)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1799)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:156)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importXML(ProcessTask.java:147)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:166)
        ... 6 common frames omitted
2020-03-24 17:02:28,933 org.owasp.dependencycheck.Engine:911
ERROR - No documents exist

Could you tell me how to resolve the problem ?

**Comment by jeremylong** [comment]
You are referencing pre 5.x parameters. You need to use `--cveUrlBase` and `--cveUrlModified` as documented here: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
