### ISSUE TITLE
Unable to create data file used for report aggregation

### ISSUE THREAD

**Issue by wyfdabao** [dependency-check/DependencyCheck#257]
HI I used the following maven command, and the exception has occured, anyone can tell me solution.

mvn org.owasp:dependency-check-maven:1.2.9:aggregate -DreportFormat=ALL  -DlogFile=./dependency-check.log -q

mvn --version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T04:58:10+08:00)
Maven home: /root/tools/apache-maven-3.2.3
Java version: 1.6.0_25, vendor: Sun Microsystems Inc.
Java home: /usr/java/jdk1.6.0_25/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-220.el6.x86_64", arch: "amd64", family: "unix"

WARNING: Unable to create data file used for report aggregation; if report aggregation is being used the results may be incomplete.
Jun 18, 2015 1:47:25 PM org.owasp.dependencycheck.maven.BaseDependencyCheckMojo writeDataFile
FINE: /workspace/workspace/MOW-SIT-OWASP/target/dependency-check.ser (No such file or directory)
java.io.FileNotFoundException: /workspace/workspace/MOW-SIT-OWASP/target/dependency-check.ser (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.writeDataFile(BaseDependencyCheckMojo.java:957)
        at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:232)
        at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:213)
        at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:71)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:361)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by jeremylong** [comment]
Just to help me confirm where this bug is - I am guessing that when you ran the aggregate the following directory was not created?

 /workspace/workspace/MOW-SIT-OWASP/target

--Jeremy

**Comment by jeremylong** [comment]
Received no additional information on this - I am assuming it was fixed with the 1.3.0 release. Please re-open if you continue to have this issue.
