### ISSUE TITLE
When using local repository, depscan failes with invalid package URL

### ISSUE THREAD

**Issue by childnode** [dependency-check/DependencyCheck#2572]
**Describe the bug**
```
repositories {
    flatDir {
        dirs 'libs'
    }
}
dependencies {
    implementation(name: 'localartifact-1.2.3', ext: 'aar') {
        because 'somehow'
    }
}

```

lets fails `:dependencyCheckAnalyze` with
```
Invalid Package-URL: pkg:maven/localartifact-1.2.3@
org.sonatype.goodies.packageurl.InvalidException: pkg:maven/localartifact-1.2.3@
	at org.sonatype.goodies.packageurl.PackageUrlParser.parse(PackageUrlParser.java:113)
	at org.sonatype.goodies.packageurl.PackageUrl.parse(PackageUrl.java:293)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.parsePackageUrl(OssIndexAnalyzer.java:169)
	at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.lambda$requestReports$1(OssIndexAnalyzer.java:190)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
```

**Version of dependency-check used**
gradle
```
plugins {
    id "org.owasp.dependencycheck" version "5.3.2.1"
}
```

**Comment by jeremylong** [comment]
I'm confused a little - is it failing or just logging the warning?  Because the stacktrace indicates a line that just logs the exception:

https://github.com/jeremylong/DependencyCheck/blob/b666317cd39d4e78bd06e6a1d1b3c9aa61f484af/core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java#L168-L173

I agree this needs to be fixed - I jus want to make sure that there isn't something else going on.  Did a report get generated?

**Comment by childnode** [comment]
No build fails and there is no report
