### ISSUE TITLE
[ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.

### ISSUE THREAD

**Issue by striker88** [dependency-check/DependencyCheck#2641]
**Describe the bug**
I am getting this error message:
[ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.

**Version of dependency-check used**
The problem occurs using version X.X.X of the ____ (cli, gradle plugin, maven plugin, etc.)
I am using Jenkins plugin for dependency check version 5.3.2
I am passing the following arguments to the dependency check:
--disableAssembly  true
--disableNodeJS  true

**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by kyrogue** [comment]
Facing same issue too

**Comment by vilvo** [comment]
Same here.

**Comment by jeremylong** [comment]
Any chance someone can provide a sample project, a log file, etc.?

**Comment by vilvo** [comment]
> Any chance someone can provide a sample project, a log file, etc.?

Is this of any help?

```
2020-09-03 10:32:58,864 org.owasp.dependencycheck.App:208
ERROR - Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
2020-09-03 10:32:58,865 org.owasp.dependencycheck.App:209
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:209)
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:133)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzePackage(NodeAuditAnalyzer.java:303)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:186)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-03 10:32:58,865 org.owasp.dependencycheck.utils.Settings:722
DEBUG - Deleting ALL temporary files from `/tmp/dctempa6bf8001-496e-495a-b4d6-bcbac6b1bf0f`
2020-09-03 10:32:58,884 org.owasp.dependencycheck.App:82
DEBUG - Exit code: -14
```

**Comment by jeremylong** [comment]
Unfortunately no. However, if you add `--log odc.log` you can generate the full log file.

**Comment by jeremylong** [comment]
Specifically, there is a section that lists what is sent for analysis. Unfortunately, it is not clearly labelled in the log - but it is generated by:

```java
                LOGGER.debug("----------------------------------------");
                LOGGER.debug("----------------------------------------");
                LOGGER.debug(packageJson.toString());
                LOGGER.debug("----------------------------------------");
                LOGGER.debug("----------------------------------------");
```

**Comment by vilvo** [comment]
Thanks for your comments. My issue turned out to come from package-lock.json which was generated from yarn.lock with synp. It used to work but broke with dependency changes to fix CVEs.

**Comment by jeremylong** [comment]
What was the specific problem with the generated package-lock.json?

**Comment by vilvo** [comment]
> What was the specific problem with the generated package-lock.json?

We could not conclude - it broke in our CI but I could not reproduce it locally. CI is Drone-based, high volume disposable build envs. Generated `package-lock.json` are already gone but I've got a full, packed log line if you're interested.

Fix was to drop `synp` and generate `package-lock.json` for scan with npm directly from `package.json` rather than through `yarn && synp`. Yarn is still used for build. In addition, `dependency-check` parameters we adjusted according to [your recommendation](https://github.com/jeremylong/DependencyCheck/issues/2482#issuecomment-603755623).

**Comment by Sysobas** [comment]
Hey guys,

Locally the error does not occur, but when I run it in a controlled environment, it bursts the error

DEBUG - Invalid payload submitted to Node Audit API. Received response code: 400 Bad Request
2020-09-21 19:47:36,170 org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer:326
ERROR - NodeAuditAnalyzer failed on /owaspdc/package-lock.json
2020-09-21 19:47:36,170 org.owasp.dependencycheck.AnalysisTask:90
WARN  - An error occurred while analyzing '/owaspdc/package-lock.json' (Node Audit Analyzer).
2020-09-21 19:47:36,171 org.owasp.dependencycheck.AnalysisTask:91
DEBUG -
org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:209)
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:133)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzePackage(NodeAuditAnalyzer.java:304)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:187)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-09-21 19:47:36,172 org.owasp.dependencycheck.Engine:708

and 

ERROR - Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
2020-09-21 19:49:48,420 org.owasp.dependencycheck.App:209
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:209)
        at org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:133)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzePackage(NodeAuditAnalyzer.java:304)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:187)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-09-21 19:49:48,420 org.owasp.dependencycheck.utils.Settings:747
DEBUG - Deleting ALL temporary files from `/tmp/dctemp3ef3dd9b-53c2-489a-ad32-a9555ede4021`
2020-09-21 19:49:48,447 org.owasp.dependencycheck.App:82
DEBUG - Exit code: -14

The controlled environment machine has free internet access!

this was extracted from the --log odc.log

Can anyone help solve this?

**Comment by jeremylong** [comment]
@Sysobas What package manager are you using?

**Comment by Sysobas** [comment]
I am using package 6.0.1

**Comment by ssthom** [comment]
Using 6.0.3 seeing the same error. I am using synp to generate the lock file from yarn's lock file. Here is the Node Audit Analyzer section of the debug log.

[owaspDebug.log](https://github.com/jeremylong/DependencyCheck/files/5752524/owaspDebug.log)

**Comment by jeremylong** [comment]
At the moment yarn.lock is still not supported.  The work around of using `synp` works for many. However, the output from synp does not appear to match what npm itself creates. Some specific examples:

- In the yarn/synp example output provided by @ssthom there are sha1 digests whereas using npm itself we get sha-512. I doubt this is the cause of the error though.
- yarn/synp appears to provided nested dependencies - whereas using npm these are flattened:

**using yarn/synp**
```json
        "@apollo/client": {
            "version": "3.3.6",
            "integrity": "sha1-81lkYwgWfzjVvEmN/CNEyIhAAJM=",
            "requires": {
                "@graphql-typed-document-node/core": "^3.0.0",
                "@types/zen-observable": "^0.8.0",
                "@wry/context": "^0.5.2",
                "@wry/equality": "^0.3.0",
                "fast-json-stable-stringify": "^2.0.0",
                "graphql-tag": "^2.11.0",
                "hoist-non-react-statics": "^3.3.2",
                "optimism": "^0.13.1",
                "prop-types": "^15.7.2",
                "symbol-observable": "^2.0.0",
                "ts-invariant": "^0.6.0",
                "tslib": "^1.10.0",
                "zen-observable": "^0.8.14"
            },
            "dependencies": {
                "symbol-observable": {
                    "version": "2.0.3",
                    "integrity": "sha1-W1IdPQekPDUQVfpDuDVbYtM/0Wo="
                }
            }
        }
```

**using npm**
```json
        "@apollo/client": {
            "version": "3.3.6",
            "integrity": "sha512-XSm/STyNS8aHdDigLLACKNMHwI0qaQmEHWHtTP+jHe/E1wZRnn66VZMMgwKLy2V4uHISHfmiZ4KpUKDPeJAKqg==",
            "requires": {
                "@graphql-typed-document-node/core": "^3.0.0",
                "@types/zen-observable": "^0.8.0",
                "@wry/context": "^0.5.2",
                "@wry/equality": "^0.3.0",
                "fast-json-stable-stringify": "^2.0.0",
                "graphql-tag": "^2.11.0",
                "hoist-non-react-statics": "^3.3.2",
                "optimism": "^0.13.1",
                "prop-types": "^15.7.2",
                "symbol-observable": "^2.0.0",
                "ts-invariant": "^0.6.0",
                "tslib": "^1.10.0",
                "zen-observable": "^0.8.14"
            }
        },
        "symbol-observable": {
            "version": "2.0.3",
            "integrity": "sha512-sQV7phh2WCYAn81oAkakC5qjq2Ml0g8ozqz03wOGnx9dDlG1de6yrF+0RAzSJD8fPUow3PTSMf2SAbOGxb93BA=="
        }
```

As always - PRs are welcome. In the meantime I would suggest using `yarn audit` - which in reality will likely give the exact same results as using the current version of ODC.

**Comment by ssthom** [comment]
@jeremylong Taking an initial look at what it would take to support yarn. Would I just need to update [NpmPayloadBuilder.java](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/java/org/owasp/dependencycheck/data/nodeaudit/NpmPayloadBuilder.java#L104) with different logic depending on the lockfile type and add `yarn.lock` to the file filter

**Comment by ssthom** [comment]
@jeremylong Any guesses to when 6.0.6 is going to be released?

**Comment by jeremylong** [comment]
relatively soon - likely this weekend.

**Comment by sindhuhack** [comment]
Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
exception: org.owasp.dependencycheck.analyzer.exception.SearchException: Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:209)
org.owasp.dependencycheck.data.nodeaudit.NodeAuditSearch.submitPackage(NodeAuditSearch.java:133)
org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzePackage(NodeAuditAnalyzer.java:188)
org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:145)
org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by natewallis** [comment]
Hi - did anyone ever fix this?  I am running into the same issue as of today.  `npm audit` works fine, but this fails.  I also have open Internet Access... 

Update:  @jeremylong  I just fixed this myself by downgrading my npm version on my dependency checker system to match that of the project.  npm 8.1.0 -> npm 6.14.17

When using the later version of NPM it wanted to regenerated my package-lock.json to the new schema, not sure how this messes with the system, but it scans ok now...

**Comment by itsecforu** [comment]
the same issue :-( 
@nwallis Can you please tell me more about how to do this?

**Comment by pagadalacs** [comment]
in our case, removed some duplicate deps and did some clean ups. In our  dependencies in package.json, We had duplicates in devdependencies and dependencies. that helped.

**Comment by AshleyEke** [comment]
I'm still getting this issue. I'm not using yarn or synp and it's not consistent across projects. I have 2 and the package lock was built with npm 9.5.0, one works fine and the other doesn't. The full log is below for the one that doesn't. Also, running `npm audit` works just fine.

[dependency-check.log](https://github.com/jeremylong/DependencyCheck/files/11000521/dependency-check.log)

**Comment by shehrozayazz** [comment]
I encountered a similar issue and found a simple solution: deleting both the node_modules directory and the package-lock.json file, then running `npm install` to regenerate everything from scratch. This approach did the trick for me. Give it a shot and see if it helps!

**Comment by Gunjan-2002** [comment]
In Jenkins Global Tools Configuration, add NodeJs version of 10.19.0. This solved my issue. Initially i added the latest version, I think you should try it for other versions too. But in my case i use NodeJs 10.19.0
