### ISSUE TITLE
Potential regression issue with database maintenance phase and MariaDB

### ISSUE THREAD

**Issue by driador** [dependency-check/DependencyCheck#2643]
**Describe the bug** what the bug is.

Attempting a first run to mirror the NVD results in an error during the maintenance phase:

2020-05-14 23:52:12,409 org.owasp.dependencycheck.App:166
ERROR - Unexpected SQL Exception
org.owasp.dependencycheck.data.update.exception.UpdateException: Unexpected SQL Exception
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:324)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:936)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:903)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:385)
        at org.owasp.dependencycheck.App.run(App.java:164)
        at org.owasp.dependencycheck.App.main(App.java:81)
Caused by: java.sql.SQLException: (conn=68) You can't specify target table 'cpeEntry' for update in FROM clause
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:262)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:176)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.cleanupDatabase(CveDB.java:1468)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:322)
        ... 6 common frames omitted

**Version of dependency-check used**
I am using v5.3.2-cli, downloaded earlier today on a RHEL 7 server with MariaDB v5.5.65

**Log file**
https://gist.github.com/driador/cc3e77a7ed45b07a9e64da61d812fc7e

**To Reproduce**
1. Initialize DB using provided sql file:  mysql -u root < initialize_mysql.sql
2. Run shell script:
./bin/dependency-check.sh --connectionString="jdbc:mariadb://localhost:3306/dependencycheck" --dbDriverName org.mariadb.jdbc.Driver --dbUser dcuser --dbPassword secret --updateonly --cveValidForHours 0 --propertyfile dbStatements_mariadb.properties --log odc.log
3. wait...
4. Error!

**Expected behavior**
Initial (and subsequent) runs of updateonly should not error.

**Comment by xuxinping** [comment]
me too

**Comment by marky-mark** [comment]
Have to keep adding "set sql_safe_updates=0" and then rerun it....very annoying

**Comment by jeremylong** [comment]
This should be resolved with the performance updates being implemented in 6.0.0.  See line 212 in https://github.com/jeremylong/DependencyCheck/blob/a3f5cd9d2aa4ca072a6b40080da37fd573e6d46d/core/src/main/resources/data/initialize_mysql.sql#L200-L213
