### ISSUE TITLE
Customizing data directory and cveUrl's, execution fails the first two times

### ISSUE THREAD

**Issue by twh270** [dependency-check/DependencyCheck#2670]
I have a custom configuration for the data directory and cveUrl's. The data directory is initially empty; the first two times I run `./gradlew dependencyCheckAnalyze` it fails. The third and subsequent times, it succeeds. 

In my build.gradle I have:

```
dependencyCheck {
        cve {
            urlBase="file:///${nistDataDirectory}/nvdcve-1.1-%d.json.gz"
            urlBase="file:///${nistDataDirectory}/nvdcve-1.1-modified.json.gz"
            print "Using ${urlBase}"
        }
        data {
            directory = "${nistDataDirectory}/nist/db"
        }
}
```

I'm using the nist-data-mirrror to populate the `nist/` directory with the CVE's.

The `nist/db` directory is initially empty. The first two times I run `./gradlew dependencyCheckAnalyze` it fails; the third and subsequent times, it succeeds. 

Not sure if I've misconfigured something or this is defect. I'm assuming the former, I can't imagine what I'm doing is that uncommon (we're running this as part of a pipeline build and trimming off several minutes is pretty valuable). What are we missing?

Here are errors for the first two runs (trimmed):

**First run:**
```
java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 85"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 85"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)

...
...

Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 85"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)

```

**Second run:**
```
java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 476"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 476"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)

...
...

Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE) VALUES 476"; SQL statement:
INSERT INTO vulnerability (cve, description, cvssV2Score, cvssV2AccessVector, cvssV2AccessComplexity, cvssV2Authentication, cvssV2ConfidentialityImpact, cvssV2IntegrityImpact, cvssV2AvailabilityImpact, cvssV2Severity, cvssV3AttackVector, cvssV3AttackComplexity, cvssV3PrivilegesRequired, cvssV3UserInteraction, cvssV3Scope, cvssV3ConfidentialityImpact, cvssV3IntegrityImpact, cvssV3AvailabilityImpact, cvssV3BaseScore, cvssV3BaseSeverity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
```

**Comment by pawelantczak** [comment]
You have two ```urlBase``` and non ```urlModified```.
