### ISSUE TITLE
SAXParseException while parsing DependencyCheck-Report.xml

### ISSUE THREAD

**Issue by busybeaver** [dependency-check/DependencyCheck#27]
Hi,

I get the following SAXParseException while running the Maven plugin (via Jenkins). Both have the version 1.0.2:

```
18:30:20 [DependencyCheck] Parsing of file /var/lib/jenkins/jobs/build_project/workspace/target/DependencyCheck-Report.xml failed due to an exception:
18:30:20 
18:30:20 org.xml.sax.SAXParseException; lineNumber: 8262; columnNumber: 40; The entity "eacute" was referenced, but not declared.
18:30:20    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1236)
18:30:20    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:628)
18:30:20    at org.apache.commons.digester.Digester.parse(Digester.java:1916)
18:30:20    at org.jenkinsci.plugins.DependencyCheck.parser.ReportParser.parse(ReportParser.java:97)
18:30:20    at hudson.plugins.analysis.core.AbstractAnnotationParser.parse(AbstractAnnotationParser.java:53)
18:30:20    at hudson.plugins.analysis.core.FilesParser.parseFile(FilesParser.java:306)
18:30:20    at hudson.plugins.analysis.core.FilesParser.parseFiles(FilesParser.java:264)
18:30:20    at hudson.plugins.analysis.core.FilesParser.parserCollectionOfFiles(FilesParser.java:215)
18:30:20    at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:184)
18:30:20    at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:31)
18:30:20    at hudson.FilePath.act(FilePath.java:905)
18:30:20    at hudson.FilePath.act(FilePath.java:878)
18:30:20    at org.jenkinsci.plugins.DependencyCheck.DependencyCheckPublisher.perform(DependencyCheckPublisher.java:128)
18:30:20    at hudson.plugins.analysis.core.HealthAwarePublisher.perform(HealthAwarePublisher.java:144)
18:30:20    at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:333)
18:30:20    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
18:30:20    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:802)
18:30:20    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:774)
18:30:20    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:974)
18:30:20    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:724)
18:30:20    at hudson.model.Run.execute(Run.java:1617)
18:30:20    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:499)
18:30:20    at hudson.model.ResourceController.execute(ResourceController.java:88)
18:30:20    at hudson.model.Executor.run(Executor.java:237)
18:30:20 
18:30:20 [DependencyCheck] Computing warning deltas based on reference build #466
```

The line where the exception occurs looks like (excerpt from the _DependencyCheck-Report.xml_):

```
<evidence>
    <source>Manifest</source>
    <name>Bundle-Vendor</name>
    <value>Andr&eacute; Rou&eacute;l</value>
</evidence>
```

The "problematic" line is the content of the `value` tag. The _evidence_ is part of the [UADetector](http://uadetector.sourceforge.net/) library by André Rouél. So the parsing seems to have issues with (french) special characters...

I think the problem is, that escaping `é` to `&eacute;` is valid in HTML, but not valid in XML. Therefore, the SAX parser fails. So while creating the _DependencyCheck-Report.xml_ file, an `é` should probably be encoded as `&#233;`. See: [numeric character reference](http://en.wikipedia.org/wiki/Numeric_character_reference)...

**Comment by jeremylong** [comment]
This has been fixed in 1.0.3-SNAPSHOT and I am in the process of doing some
final testing and I will release 1.0.3.

--Jeremy

**Comment by busybeaver** [comment]
Fantastic! Thanks for the quick reply...

**Comment by jeremylong** [comment]
Version 1.0.3 has been released. The jenkins plugin has not been updated yet (steve will get to this soon). However, if you use the 1.0.3 maven plugin to produce an XML file that is consumed by Jenkins 1.0.2 - everything should work okay.

--Jeremy
