### ISSUE TITLE
No such method error : dependency-check-ant - 5.3.2 and 5.1.1 

### ISSUE THREAD

**Issue by rreddyv-tibco** [dependency-check/DependencyCheck#2735]
I'm using owasp for last one year using ANT configuration and it works well but recently I'm seeing below error.
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.createTables(ConnectionFactory.java:320)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:183)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:231)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:286)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:256)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1059)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:926)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:737)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:667)
        at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1685)
        at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1642)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

**Comment by jeremylong** [comment]
This looks like a classpath issue - or possibly a JAR version conflict. The 6.0.0 release will change from using `IOUtils` to `com.google.common.io.Resources`.

**Comment by rreddyv-tibco** [comment]
Hi @jeremylong Thanks for reply, Yes that was the issue. I have identified and fixed but forget to close the issue. Thanks
