### ISSUE TITLE
cmd " dependency-check.sh  --cveUrlModified " error , Autoupdate is disabled and the database does not exist

### ISSUE THREAD

**Issue by logerror** [dependency-check/DependencyCheck#2752]
my cmd is : 

`/dependency-check.sh -l log -n --cveUrlModified file:///opt/db_packages/nvdcve-1.1-modified.json.gz --cveUrlBase file:///opt/db_packages/nvdcve-1.1-2020.json.gz -s /opt/jars/`

err message is ：

```
2020-08-18 14:48:42,278 org.owasp.dependencycheck.App:202
ERROR - One or more fatal errors occurred
2020-08-18 14:48:42,279 org.owasp.dependencycheck.App:208
ERROR - Autoupdate is disabled and the database does not exist
2020-08-18 14:48:42,280 org.owasp.dependencycheck.App:209
DEBUG - unexpected error
org.owasp.dependencycheck.exception.NoDataException: Autoupdate is disabled and the database does not exist
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:749)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:667)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
2020-08-18 14:48:42,280 org.owasp.dependencycheck.App:82

```

**Comment by logerror** [comment]
the file  nvdcve-1.1-modified.json.gz  ,  nvdcve-1.1-2020.json.gz  is generated by project   https://github.com/stevespringett/nist-data-mirror/

**Comment by logerror** [comment]
the version i used is : ```
./dependency-check.sh -version
Dependency-Check Core version 5.3.2
```

**Comment by jeremylong** [comment]
You've disabled the autoupdate feature by adding `-n` you must run the update with the supplied files from the NVD (and you should probably move the RetireJS file locally as well - see the default location on the [CLI configuration page](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)).

Lastly, the option for the NVD base should contain a `%d` instead of the year:  

```
--cveUrlBase file:///opt/db_packages/nvdcve-1.1-%d.json.gz
```
