### ISSUE TITLE
Running with ANT task does not work anymore (Unable to connect to the dependency-check database)

### ISSUE THREAD

**Issue by kozi** [dependency-check/DependencyCheck#2812]
**Describe the bug**

Got the following exception when using version 6.0.1 ANT task.

```shell
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Unable to connect to the dependency-check database
```
There is no existing database before the start.
I am extracting the ZIP archive at runtime and after that i start the dependency check with the ant task.

With version 5.3.2 everything worked fine.

**Comment by kozi** [comment]
### Complete log

```shell
PS C:\Users\???\workspace\???> .\build.bat dependency-check
Buildfile: C:\Users\???\workspace\???\build.xml
Trying to override old definition of datatype resources

dependency-check-init:
    [unzip] Expanding: C:\Users\???\workspace\???\lib\dependency-check-ant-6.0.1-release.zip into C:\Users\???\workspace\???\lib

dependency-check:
[dependency-check] SLF4J: Class path contains multiple SLF4J bindings.
[dependency-check] SLF4J: Found binding in [jar:file:/C:/Users/???/workspace/???/lib/dependency-check-ant/dependency-check-ant.jar!/org/slf4j/impl/StaticLoggerBinder
.class]
[dependency-check] SLF4J: Found binding in [jar:file:/C:/Users/???/workspace/???/lib/dependency-check-ant/lib/dependency-check-ant-6.0.1.jar!/org/slf4j/impl/StaticLo
ggerBinder.class]
[dependency-check] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[dependency-check] SLF4J: Actual binding is of type [org.owasp.dependencycheck.ant.logging.AntLoggerFactory]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCacheManager getUnconfiguredInstance
[dependency-check] INFORMATION: Instance is null, returning unconfigured instance
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.utils.threadpool.ThreadPoolManager loadConfig
[dependency-check] INFORMATION: thread_pool.default PoolConfiguration = useBoundary = [false] boundarySize = [2000] maximumPoolSize = [150] minimumPoolSize = [4] keepAliveTime = [300
000] whenBlockedPolicy = [RUN] startUpSize = [4]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCacheManager doConfigure
[dependency-check] INFORMATION: Setting default auxiliaries to ODC
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCacheManager doConfigure
[dependency-check] INFORMATION: setting defaultCompositeCacheAttributes to [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUsagePattern =
 UPDATE, spoolChunkSize = 2 ]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCacheManager doConfigure
[dependency-check] INFORMATION: setting defaultElementAttributes to [ IS_LATERAL = false, IS_SPOOL = true, IS_REMOTE = false, IS_ETERNAL = false, MaxLifeSeconds = 86400, IdleTime = 1
800, CreateTime = 1600096415291, LastAccessTime = 1600096415291, getTimeToLiveSeconds() = 86399, createTime = 1600096415291 ]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.memory.AbstractDoubleLinkedListMemoryCache initialize
[dependency-check] INFORMATION: initialized MemoryCache for POM
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCache <init>
[dependency-check] INFORMATION: Constructed cache with name [POM] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUs
agePattern = UPDATE, spoolChunkSize = 2 ]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseCacheEventLogger
[dependency-check] INFORMATION: No cache event logger defined for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseElementSerializer
[dependency-check] INFORMATION: Using standard serializer [org.apache.commons.jcs.utils.serialization.StandardSerializer@13e344d] for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.utils.threadpool.ThreadPoolManager loadConfig
[dependency-check] INFORMATION: thread_pool.disk_cache_event_queue PoolConfiguration = useBoundary = [false] boundarySize = [2000] maximumPoolSize = [150] minimumPoolSize = [4] keepA
liveTime = [300000] whenBlockedPolicy = [RUN] startUpSize = [4]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeFileSystem
[dependency-check] INFORMATION: Region [POM] Cache file root directory: C:\Users\???\workspace\???\lib\dependency-check-ant\data\5.0\cache
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeKeyMap
[dependency-check] INFORMATION: Region [POM] Set maxKeySize to: '1000000'
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache <init>
[dependency-check] INFORMATION: Region [POM] Indexed Disk Cache is alive.
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.memory.AbstractDoubleLinkedListMemoryCache initialize
[dependency-check] INFORMATION: initialized MemoryCache for NODEAUDIT
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.engine.control.CompositeCache <init>
[dependency-check] INFORMATION: Constructed cache with name [NODEAUDIT] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1,
diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseCacheEventLogger
[dependency-check] INFORMATION: No cache event logger defined for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:35 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseElementSerializer
[dependency-check] INFORMATION: Using standard serializer [org.apache.commons.jcs.utils.serialization.StandardSerializer@28261e8e] for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeFileSystem
[dependency-check] INFORMATION: Region [NODEAUDIT] Cache file root directory: C:\Users\???\workspace\???\lib\dependency-check-ant\data\5.0\cache
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeKeyMap
[dependency-check] INFORMATION: Region [NODEAUDIT] Set maxKeySize to: '1000000'
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache <init>
[dependency-check] INFORMATION: Region [NODEAUDIT] Indexed Disk Cache is alive.
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.engine.memory.AbstractDoubleLinkedListMemoryCache initialize
[dependency-check] INFORMATION: initialized MemoryCache for CENTRAL
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.engine.control.CompositeCache <init>
[dependency-check] INFORMATION: Constructed cache with name [CENTRAL] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, di
skUsagePattern = UPDATE, spoolChunkSize = 2 ]
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseCacheEventLogger
[dependency-check] INFORMATION: No cache event logger defined for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.AuxiliaryCacheConfigurator parseElementSerializer
[dependency-check] INFORMATION: Using standard serializer [org.apache.commons.jcs.utils.serialization.StandardSerializer@d737b89] for auxiliary [jcs.auxiliary.ODC]
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeFileSystem
[dependency-check] INFORMATION: Region [CENTRAL] Cache file root directory: C:\Users\???\workspace\???\lib\dependency-check-ant\data\5.0\cache
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache initializeKeyMap
[dependency-check] INFORMATION: Region [CENTRAL] Set maxKeySize to: '1000000'
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache <init>
[dependency-check] INFORMATION: Region [CENTRAL] Indexed Disk Cache is alive.
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseRegions
[dependency-check] INFORMATION: Parsed regions [POM, NODEAUDIT, CENTRAL]
[dependency-check] Sep 14, 2020 5:13:36 PM org.apache.commons.jcs.engine.control.CompositeCacheManager doConfigure
[dependency-check] INFORMATION: Finished configuration in 763 ms.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.event.ElementEventQueue dispose
[dependency-check] INFORMATION: Element event queue destroyed: org.apache.commons.jcs.engine.control.event.ElementEventQueue@5d8bafa9
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [NODEAUDIT] fromRemote [false]
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [NODEAUDIT] auxiliary [NODEAUDIT]
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [NODEAUDIT] put 0 into auxiliary NODEAUDIT
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache run
[dependency-check] INFORMATION: No longer waiting for event queue to finish: Pooled Cache Event Queue
[dependency-check] Working = true
[dependency-check] Alive = false
[dependency-check] Empty = true
[dependency-check] Queue Size = 0
[dependency-check] Queue Capacity = 2147483647
[dependency-check] Pool Size = 0
[dependency-check] Maximum Pool Size = 150
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache dispose
[dependency-check] INFORMATION: In dispose, destroying event queue.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [NODEAUDIT] Saving keys to: NODEAUDIT, key count: 0
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [NODEAUDIT] Finished saving keys.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache disposeInternal
[dependency-check] INFORMATION: Region [NODEAUDIT] Shutdown complete.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [NODEAUDIT] disposing of memory cache.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.memory.AbstractMemoryCache dispose
[dependency-check] INFORMATION: Memory Cache dispose called.
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [CENTRAL] fromRemote [false]
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [CENTRAL] auxiliary [CENTRAL]
[dependency-check] Sep 14, 2020 5:13:39 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [CENTRAL] put 0 into auxiliary CENTRAL
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache run
[dependency-check] INFORMATION: No longer waiting for event queue to finish: Pooled Cache Event Queue
[dependency-check] Working = true
[dependency-check] Alive = false
[dependency-check] Empty = true
[dependency-check] Queue Size = 0
[dependency-check] Queue Capacity = 2147483647
[dependency-check] Pool Size = 0
[dependency-check] Maximum Pool Size = 150
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache dispose
[dependency-check] INFORMATION: In dispose, destroying event queue.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [CENTRAL] Saving keys to: CENTRAL, key count: 0
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [CENTRAL] Finished saving keys.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache disposeInternal
[dependency-check] INFORMATION: Region [CENTRAL] Shutdown complete.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [CENTRAL] disposing of memory cache.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.memory.AbstractMemoryCache dispose
[dependency-check] INFORMATION: Memory Cache dispose called.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [POM] fromRemote [false]
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [POM] auxiliary [POM]
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [POM] put 0 into auxiliary POM
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache run
[dependency-check] INFORMATION: No longer waiting for event queue to finish: Pooled Cache Event Queue
[dependency-check] Working = true
[dependency-check] Alive = false
[dependency-check] Empty = true
[dependency-check] Queue Size = 0
[dependency-check] Queue Capacity = 2147483647
[dependency-check] Pool Size = 0
[dependency-check] Maximum Pool Size = 150
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.AbstractDiskCache dispose
[dependency-check] INFORMATION: In dispose, destroying event queue.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [POM] Saving keys to: POM, key count: 0
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache saveKeys
[dependency-check] INFORMATION: Region [POM] Finished saving keys.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache disposeInternal
[dependency-check] INFORMATION: Region [POM] Shutdown complete.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
[dependency-check] INFORMATION: In DISPOSE, [POM] disposing of memory cache.
[dependency-check] Sep 14, 2020 5:13:40 PM org.apache.commons.jcs.engine.memory.AbstractMemoryCache dispose
[dependency-check] INFORMATION: Memory Cache dispose called.

BUILD FAILED
C:\Users\???\workspace\???\build.xml:791: One or more exceptions occurred during analysis:
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Unable to connect to the dependency-check database
        at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:781)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:747)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:670)
        at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1685)
        at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1642)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Next Exception:
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to connect to the dependency-check database
        at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:780)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:747)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:670)
        at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1685)
        at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1642)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to create the database structure
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:185)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:230)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:266)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:236)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1047)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:923)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:740)
        ... 19 more
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to create database schema
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.createTables(ConnectionFactory.java:332)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:182)
        ... 25 more
Caused by: java.lang.IllegalArgumentException: resource data/initialize.sql not found.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.io.Resources.getResource(Resources.java:195)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.createTables(ConnectionFactory.java:319)
        ... 26 more

Total time: 6 seconds
PS C:\Users\????\workspace\???>
```

**Comment by jeremylong** [comment]
A change was made to resolve a similar issue with gradle (https://github.com/jeremylong/DependencyCheck/issues/2509):
https://github.com/jeremylong/DependencyCheck/commit/567fc6afca16b03a61498863ddbe6e735b25bd15#diff-9fecc011417ac1d5701a6e0be5c1c02aL319-R319

Apparently Resouce.getResource(String) is not working given the classpath, etc. in some implementations...  

I'll include a fix to revert to the old mechanism if the new mechanism fails.

**Comment by jeremylong** [comment]
This will be included in the next release.
