### ISSUE TITLE
Scanning Spring Boot startup script including WAR doesn't work

### ISSUE THREAD

**Issue by drwetter** [dependency-check/DependencyCheck#2829]
**Describe the bug**

Upon scanning I get not results. 

**Log file**

```
org.owasp.dependencycheck.analyzer.exception.ArchiveExtractionException: java.util.zip.ZipException: Unexpected record signature: 0X622F2123
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:561)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:416)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:258)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:240)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.zip.ZipException: Unexpected record signature: 0X622F2123
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:286)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:435)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:541)
        ... 10 common frames omitted
2020-09-21 21:01:30,755 org.owasp.dependencycheck.Engine:708
INFO  - Finished Archive Analyzer (0 seconds)
2020-09-21 21:01:30,755 org.owasp.dependencycheck.Engine:858
DEBUG - Initializing Ruby Bundle Audit Analyzer
2020-09-21 21:01:30,755 org.owasp.dependencycheck.Engine:710
DEBUG - Skipping Ruby Bundle Audit Analyzer (not enabled)
2020-09-21 21:01:30,756 org.owasp.dependencycheck.Engine:858
DEBUG - Initializing File Name Analyzer
2020-09-21 21:01:30,756 org.owasp.dependencycheck.Engine:793
DEBUG - Starting File Name Analyzer
2020-09-21 21:01:30,756 org.owasp.dependencycheck.Engine:841
DEBUG - Parallel processing with up to 8 threads: File Name Analyzer.
2020-09-21 21:01:30,757 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of 'REDACTED.war' (File Name Analyzer)
2020-09-21 21:01:30,759 org.owasp.dependencycheck.Engine:708
INFO  - Finished File Name Analyzer (0 seconds)
2020-09-21 21:01:30,760 org.owasp.dependencycheck.Engine:858
DEBUG - Initializing Jar Analyzer
2020-09-21 21:01:30,760 org.owasp.dependencycheck.Engine:793
DEBUG - Starting Jar Analyzer
2020-09-21 21:01:30,761 org.owasp.dependencycheck.Engine:841
DEBUG - Parallel processing with up to 8 threads: Jar Analyzer.
2020-09-21 21:01:30,761 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/dirkw/arbeit/msutor/dop1-vergleich/AI/depot_portal.war' (Jar Analyzer)
2020-09-21 21:01:30,783 org.owasp.dependencycheck.Engine:708
INFO  - Finished Jar Analyzer (0 seconds)
[..]
```

**Version of dependency-check used**

I used the binary distribution for 6.0.0 and 6.0.1 (as I for some reason I wasn't able to have a successful maven build.

**To Reproduce**

nothing special... see above. The file output are basically the stub files.

**Expected behavior**

That the project scans the WAR file supplied and spends more than 0 seconds on it, according to the output.

**Additional info**

It works when I unzip the war file and supply the directory as an argument. Then in the logfile I also see ``Unexpected record signature: 0X622F2123`` but the central analyzer gives some output 

```
[INFO] Finished Central Analyzer (58 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (43 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (1 seconds)
```

For comparison when scanning the WAR:

```
[INFO] Analysis Started
[WARN] Exception extracting archive 'depot_portal.war'.
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (3 seconds)
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (3 seconds)
```

**Comment by mprins** [comment]
There is something wrong with the war archive or one of the archives inside, at least your java runtime seems to think so by reporting an error. 

You might get better results using java 8 as that is the preferred platform.

**Comment by drwetter** [comment]
Ops, you're right. That was probably a bit too late yesterday.

``622F2123`` is ``b/!#`` that is reverse:

```
myprompt% head -1 REDACTED.war
#!/bin/bash
myprompt% 
```

It's a Spring Boot startup script :=/  I should have seen that if the output of unzip wasn't that lengthy (``8182 extra bytes at beginning or within zipfile  (attempting to process anyway)``. Similar as with polyglott files.

Unfortunately I can't relabel this from bug to feature request. But wouldn't it be great if this project could identify ``#!/bin/bash`` or ``#!/bin/sh`` in the header and e.g. then look for the ZIP marker ``PK``

**Comment by jeremylong** [comment]
Apparently we fix this for JAR files:

https://github.com/jeremylong/DependencyCheck/blob/34ea69b7d874767a71fc2c933d3c805b53b1c74b/core/src/main/java/org/owasp/dependencycheck/analyzer/ArchiveAnalyzer.java#L484-L485

I'll update this to include WARs.

**Comment by jeremylong** [comment]
This will be included in the next release.
