### ISSUE TITLE
Missing dbStatement  MERGE_CPE_ECOSYSTEM for OracleDB

### ISSUE THREAD

**Issue by Wonno** [dependency-check/DependencyCheck#2841]
**Describe the bug**
When using Oracle as database, since dependencycheck 6.1 an errors occurs.

**First analysis**
prepared Statement **MERGE_CPE_ECOSYSTEM** is missing in [dbStatements_oracle.properties](github.com/jeremylong/DependencyCheck/blob/2b0a88329d754e359b949087a397b98823a03aaf/core/src/main/resources/data/dbStatements_oracle.properties)

**Version of dependency-check used**
since dependency check 6.x

**Log file**
```
[ERROR] java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key MERGE_CPE_ECOSYSTEM
org.owasp.dependencycheck.data.nvdcve.DatabaseException: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key MERGE_CPE_ECOSYSTEM
        at org.owasp.dependencycheck.data.nvdcve.CveDB.prepareStatement(CveDB.java:361)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.prepareStatements(CveDB.java:330)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:271)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:236)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1047)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:923)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:385)
        at org.owasp.dependencycheck.App.run(App.java:164)
        at org.owasp.dependencycheck.App.main(App.java:81)
```

**To Reproduce**
1. Start with empty Oracle Database
2. Init DB using script: initialize_oracle.sql
3. Update version in properties version accordingly (e.g. 6.1)
4. Run dependency check using oracle with updateonly.
```
dependency-check.sh \
    --connectionString 'jdbc:oracle:thin:@oracle.company.tld:1521/owaspdb' \
    --dbDriverName oracle.jdbc.driver.OracleDriver \
    --dbDriverPath . \
    --dbUser myUSER	\
    --dbPassword 'myPA$$WORD' \
    --updateonly
```

**Expected behavior**
Pull data from the internet and populate DB

**Comment by jeremylong** [comment]
With the 6.0.0-6.0.2 we still do not support Oracle. See https://github.com/jeremylong/DependencyCheck/issues/2755 and the [Release Notes](https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-600-2020-09-07).

**Comment by jeremylong** [comment]
There is much more than just the missing merge statement.
