### ISSUE TITLE
Unable to download meta file

### ISSUE THREAD

**Issue by jkrow** [dependency-check/DependencyCheck#2860]
System throws error on all commands -(update, scan) for being unable to download meta file - error 404

"Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found"

**Version of dependency-check used**
Version 6.0.2 core version 5.2.2

[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:351)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:385)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:889)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:381)
	at org.owasp.dependencycheck.App.run(App.java:161)
	at org.owasp.dependencycheck.App.main(App.java:80)
Caused by: org.owasp.dependencycheck.utils.ResourceNotFoundException: Requested resource does not exists - received a 404
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:204)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:138)
	at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:110)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:340)
	... 7 common frames omitted
[dep.txt](https://github.com/jeremylong/DependencyCheck/files/5318760/dep.txt)

**Comment by albuch** [comment]
The NVD feed v1.0 was deprecated for a long period of time and was removed couple of days ago.
You should upgrade to a version of DependencyCheck >= 5.2.3. and check your configuration to point to the v1.1 of the feeds. See the Release notes of v5.2.3 https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-523-2019-11-11 
See #2850 #2824 etc.

**Comment by jkrow** [comment]
That worked. Thank you.
