### ISSUE TITLE
checking TGZ's warnings

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#2895]
**Describe the bug**
Fails to check NPM packages downloaded with `npm pack`, logs the warning:

> Archive contains a file (package/package.json) that would be extracted outside of the target directory.

**Version of dependency-check used**
The problem occurs using version 6.0.2 of the cli

**Log file**

Relevant chunks of log file for a randomly chosen package:

```$ grep stream-http- -A8 logs/dependency-check.log 
DEBUG - Found file /home/breenn/src/lmax/buck-all/lib/npm/s/stream-http-2.7.2.tgz
2020-10-15 04:06:03,604 org.owasp.dependencycheck.App:353
DEBUG - Found file /home/breenn/src/lmax/buck-all/lib/npm/s/stream-splicer-1.3.2.tgz
2020-10-15 04:06:03,604 org.owasp.dependencycheck.App:353
DEBUG - Found file /home/breenn/src/lmax/buck-all/lib/npm/s/stream-splicer-2.0.0.tgz
2020-10-15 04:06:03,604 org.owasp.dependencycheck.App:353
DEBUG - Found file /home/breenn/src/lmax/buck-all/lib/npm/s/strict-uri-encode-1.1.0.tgz
2020-10-15 04:06:03,604 org.owasp.dependencycheck.App:353
DEBUG - Found file /home/breenn/src/lmax/buck-all/lib/npm/s/string-width-1.0.2.tgz
--
DEBUG - Begin Analysis of '/home/breenn/src/lmax/buck-all/lib/npm/s/stream-http-2.7.2.tgz' (Archive Analyzer)
2020-10-15 04:06:08,066 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/breenn/src/lmax/buck-all/lib/npm/s/socket.io-adapter-0.5.0.tgz' (Archive Analyzer)
2020-10-15 04:06:08,066 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/breenn/src/lmax/buck-all/lib/npm/s/style-loader-0.13.2.tgz' (Archive Analyzer)
2020-10-15 04:06:08,066 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/breenn/src/lmax/buck-all/lib/npm/d/duplexer3-0.1.4.tgz' (Archive Analyzer)
2020-10-15 04:06:08,067 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of '/home/breenn/src/lmax/buck-all/lib/npm/i/ieee754-1.1.8.tgz' (Archive Analyzer)
--
DEBUG - Decompressing '/home/breenn/src/lmax/buck-all/build/analysis/dependency-check/../../../buck-out/dependency-check/tmp/dctemp92470648-4f9d-4ea9-aa2e-fb79dae11ee9/check789928729233768903tmp/4/stream-http-2.7.2.tar'
2020-10-15 04:06:08,083 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'postcss-modules-scope-1.1.0.tar'.
2020-10-15 04:06:08,083 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'consolify-2.2.0.tar'.
2020-10-15 04:06:08,083 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'capture-stack-trace-1.0.0.tar'.
2020-10-15 04:06:08,083 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'qs-6.3.2.tar'.
--
WARN  - Exception extracting archive 'stream-http-2.7.2.tar'.
2020-10-15 04:06:08,185 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:454
DEBUG - 
org.owasp.dependencycheck.analyzer.exception.ArchiveExtractionException: Archive contains a file (package/package.json) that would be extracted outside of the target directory.
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:548)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:420)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:258)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:280)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:240)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**To Reproduce**
1. download npm package with `npm pack stream-http@2.7.2` into project
2. run dependency check cli on project
3. warning logged on stdout
4. warning logged in log file

**Expected behavior**

TGZ is extracted and analysed.

**Additional context**
Set `-Dtemp.directory=/home/breenn/src/lmax/buck-all/build/analysis/dependency-check/../../../buck-out/dependency-check/tmp` as openjdk hard-codes `/tmp` which isn't large enough for our project.

**Comment by ghost** [comment]
Our command line:

```
JAVA_OPTS="${JAVA_OPTS-} -Dtemp.directory=${working_directory}/tmp" "${working_directory}/dependency-check/bin/dependency-check.sh" \
      --suppression $suppressionsFile \
      --format $format \
      --log "$log" \
      --project buck-all \
      --failOnCVSS 5 \
      --disableBundleAudit \
      --disableAssembly \
      --scan "${buck_dir}/exchange/**/*.js" \
      --scan "${buck_dir}/support/**/*.js" \
      --scan "${buck_dir}/ops/**/*.js" \
      --scan "${libs}/npm/**/*.tgz" \
      -o "logs/"```

**Comment by jeremylong** [comment]
I believe the issue is the non-normalized temp directory. Any chance you could test this with:

`-Dtemp.directory=/home/breenn/src/lmax/buck-all/buck-out/dependency-check/tmp`

**Comment by ghost** [comment]
That was it!
