### ISSUE TITLE
Owasp dependency check print lots of java.nio.file.NoSuchFileException, but build success. Is that a normal behaviour? 

### ISSUE THREAD

**Issue by wyjwl** [dependency-check/DependencyCheck#2964]
Failed to store entry: owasp-cache/oss_cache/58/75/58759287347fd683eb6586465a4c639c8e299a6d
java.nio.file.NoSuchFileException: owasp-cache/oss_cache/58/75/58759287347fd683eb6586465a4c639c8e299a6d
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.storeEntry(DirectoryCache.java:240)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.putAll(DirectoryCache.java:136)
        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:171)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:138)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Failed to store entry: owasp-cache/oss_cache/76/5a/765aecaac68cca54a29e3eebe28e481f4f60efe4
java.nio.file.NoSuchFileException: owasp-cache/oss_cache/76/5a/765aecaac68cca54a29e3eebe28e481f4f60efe4
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.storeEntry(DirectoryCache.java:240)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.putAll(DirectoryCache.java:136)
        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:171)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:138)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Failed to store entry: owasp-cache/oss_cache/ca/1f/ca1f07e32d1d6555da4722976663324770058778
java.nio.file.NoSuchFileException: owasp-cache/oss_cache/ca/1f/ca1f07e32d1d6555da4722976663324770058778
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.storeEntry(DirectoryCache.java:240)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.putAll(DirectoryCache.java:136)
        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:171)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:138)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Failed to store entry: owasp-cache/oss_cache/01/ec/01ec13d94b8bafe61aecca0ec1e21c54c0405da5
java.nio.file.NoSuchFileException: owasp-cache/oss_cache/01/ec/01ec13d94b8bafe61aecca0ec1e21c54c0405da5
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.storeEntry(DirectoryCache.java:240)
        at org.sonatype.ossindex.service.client.cache.DirectoryCache.putAll(DirectoryCache.java:136)
        at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:171)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.requestReports(OssIndexAnalyzer.java:198)
        at org.owasp.dependencycheck.analyzer.OssIndexAnalyzer.analyzeDependency(OssIndexAnalyzer.java:138)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

> Task :xxxxxxx-service:dependencyCheckAnalyze
Generating report for project xxxxxxx-service
Found 119 vulnerabilities in project xxxxxxx-service

There are like hundreds of this no such file exceptions. But it still can generate report successfully. 
Is this alright or not?

**Comment by mprins** [comment]
It seems a though your configuration is trying to store the cache in `owasp-cache/oss_cache` but it can't because that does not exist or can't be found. Since you have failed to provide any information about your config I'd say "yes that is normal" at least for your config.

**Comment by wyjwl** [comment]
I don't have any special configuration.
Thats all the configuration I apply in gradle:

plugins {
    id "org.owasp.dependencycheck"
}

dependencyCheck {
    data {
        directory = 'owasp-cache/'
    }
    autoUpdate = false
    outputDirectory = file("$project.buildDir/reports/owasp")
}

Then just run ./gradlew dependencyCheckAnalyze .

**Comment by jeremylong** [comment]
It is attempting to write information to `~/.gradle/dependency-check-data` - the error might happen if the disk is full or if the directory is read only.

Just out of curiosity - do you get the same thing if you don't use the gradle wrapper?

**Comment by wyjwl** [comment]
Yep, it is still the same when I use gradle dependencyCheckAnalyze.

**Comment by jeremylong** [comment]
I just noticed something - you have autoupdate disabled?  Does the data directory exist and contain an H2 database? Can you try:

```gradle
dependencyCheck {
data {
directory = 'owasp-cache/'
}
autoUpdate = true
outputDirectory = file("$project.buildDir/reports/owasp")
}
```

**Comment by wyjwl** [comment]
Yep, the data directory is already exist, everytime my pipeline will download the data into that directory from S3 and then next step is running dependency check(which will be much faster). So I don't think autoUpdate = false will cause any problem am I right?

**Comment by jeremylong** [comment]
Correct - the autoUpdate is not the issue. Instead of using a relative path for the data directory - any chance you could add a prefix of ${project.path} to make it an absolute path?
