### ISSUE TITLE
Class "org.owasp.dependencycheck.data.nvdcve.H2Functions" not found when using standalone H2

### ISSUE THREAD

**Issue by jakub-bochenski** [dependency-check/DependencyCheck#3033]
**Describe the bug**
I'm trying to use a standalone H2 database.
When trying to connect I'm getting an exception about missing H2Functions class.
```
[SNIP gradle stuff]
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        DatabaseException: Unable to connect to the dependency-check database
                caused by DatabaseException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Class "org.owasp.dependencycheck.data.nvdcve.H2Functions" not found; SQL statement:
CALL insert_software(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [90086-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:199)
        at org.h2.engine.FunctionAlias.loadClass(FunctionAlias.java:138)
        at org.h2.engine.FunctionAlias.load(FunctionAlias.java:114)
        at org.h2.engine.FunctionAlias.findJavaMethod(FunctionAlias.java:255)
        at org.h2.expression.function.JavaFunction.<init>(JavaFunction.java:34)
        at org.h2.command.Parser.readJavaFunction(Parser.java:3576)
        at org.h2.command.Parser.readFunction(Parser.java:3770)
        at org.h2.command.Parser.readTerm(Parser.java:4305)
        at org.h2.command.Parser.readFactor(Parser.java:3343)
        at org.h2.command.Parser.readSum(Parser.java:3330)
        at org.h2.command.Parser.readConcat(Parser.java:3305)
        at org.h2.command.Parser.readCondition(Parser.java:3108)
        at org.h2.command.Parser.readExpression(Parser.java:3059)
        at org.h2.command.Parser.parseCall(Parser.java:6480)
        at org.h2.command.Parser.parsePrepared(Parser.java:905)
        at org.h2.command.Parser.parse(Parser.java:843)
        at org.h2.command.Parser.parse(Parser.java:815)
        at org.h2.command.Parser.prepareCommand(Parser.java:738)
        at org.h2.engine.Session.prepareLocal(Session.java:657)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:278)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:183)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.owasp.dependencycheck.data.nvdcve.H2Functions
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:192)
        ... 21 more

                caused by JdbcSQLSyntaxErrorException: Class "org.owasp.dependencycheck.data.nvdcve.H2Functions" not found; SQL statement:
CALL insert_software(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [90086-199]
        at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:703)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:681)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:592)
        at org.owasp.dependencycheck.Engine$analyzeDependencies$1.call(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:89)
        ... 98 more
```

**Version of dependency-check used**
The problem occurs using version 6.0.3 of the gradle plugin
H2 version is 1.4.200 

**Log file**
```
2020-12-21T17:38:56.473+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] Loading driver 'org.h2.Driver'
2020-12-21T17:38:56.473+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] Loading database connection
2020-12-21T17:38:56.473+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] Connection String: jdbc:h2:tcp://172.17.0.3:9092/odc
2020-12-21T17:38:56.473+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] Database User: dcuser
2020-12-21T17:38:56.476+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] DC Schema: 5.0
2020-12-21T17:38:56.476+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory] DB Schema: 5.0
2020-12-21T17:38:56.493+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.CveDB] Database product: h2
```

**To Reproduce**
I use the following gradle build:
```
plugins {
    id("org.owasp.dependencycheck") version "6.0.3"
}

dependencyCheck {
    autoUpdate = false
    data(closureOf<org.owasp.dependencycheck.gradle.extension.DataExtension>  {
        connectionString = "jdbc:h2:tcp://172.17.0.3:9092/odc"
        driver = "org.h2.Driver"
        username = "dcuser"
        password = "DC-Pass1337!"
    })
}
```
**Expected behavior**
There is no exception and analysis runs. 

**Additional context**
I can run analysis on embedded DB without any problems. 
I've checked the connection to DB manually and it works.
I'm using an updated version of this Docker image to provide the DB https://github.com/zoomint/nvd-container-image/pull/1

**Comment by jeremylong** [comment]
The dependency-check-core JAR file would need to be on the classpath of the standalone H2 instance that is running in server mode.

**Comment by jakub-bochenski** [comment]
Thanks, adding that jar to classpath solves the issue
