### ISSUE TITLE
[ERROR] Unable to find the NVD CPE file to parse

### ISSUE THREAD

**Issue by daxin09pp** [dependency-check/DependencyCheck#3090]
hi, 
I used dependency-check-6.0.5 and mirrored NVD.I got an error when I started Dependent-Check to scan.The error is as follows:
```
C:\Users\Administrator\Downloads\dependency-check-6.0.5-release\dependency-check\bin>dependency-check.bat --project CBD -s C:\victor -o .\ --retireJsUrl http://10.x.x.x/jsrepository.json --cveUrlModified http://10.x.x.x/nvdcve-1.1-modified.json.gz --cveUrlBase http://10.x.x.x/nvdcve-1.1-%d.json.gz --suppression suppression.xml --disableAssembly --disableNuspec --disableNugetconf --disableMSBuild
[INFO] Checking for updates
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[INFO] Download Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2003  (32 ms)
[INFO] Download Started for NVD CVE - 2004
[INFO] Processing Started for NVD CVE - 2003
[INFO] Download Complete for NVD CVE - 2002  (79 ms)
[INFO] Download Started for NVD CVE - 2005
[INFO] Processing Started for NVD CVE - 2002
[INFO] Download Complete for NVD CVE - 2004  (63 ms)
[INFO] Download Started for NVD CVE - 2006
[INFO] Processing Started for NVD CVE - 2004
[INFO] Download Complete for NVD CVE - 2005  (63 ms)
[INFO] Download Started for NVD CVE - 2007
[INFO] Processing Started for NVD CVE - 2005
[INFO] Download Complete for NVD CVE - 2006  (78 ms)
[INFO] Download Started for NVD CVE - 2008
[INFO] Download Complete for NVD CVE - 2007  (78 ms)
[INFO] Download Started for NVD CVE - 2009
[INFO] Download Complete for NVD CVE - 2008  (93 ms)
[INFO] Download Started for NVD CVE - 2010
[INFO] Download Complete for NVD CVE - 2009  (78 ms)
[INFO] Download Started for NVD CVE - 2011
[INFO] Download Complete for NVD CVE - 2010  (94 ms)
[INFO] Download Started for NVD CVE - 2012
[INFO] Download Complete for NVD CVE - 2011  (63 ms)
[INFO] Download Started for NVD CVE - 2013
[INFO] Download Complete for NVD CVE - 2012  (94 ms)
[INFO] Download Started for NVD CVE - 2014
[INFO] Download Complete for NVD CVE - 2013  (172 ms)
[INFO] Download Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2014  (172 ms)
[INFO] Download Started for NVD CVE - 2016
[INFO] Download Complete for NVD CVE - 2015  (78 ms)
[INFO] Download Started for NVD CVE - 2017
[INFO] Download Complete for NVD CVE - 2016  (94 ms)
[INFO] Download Complete for NVD CVE - 2017  (110 ms)
[INFO] Download Started for NVD CVE - 2018
[INFO] Download Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2019  (139 ms)
[INFO] Download Complete for NVD CVE - 2018  (188 ms)
[INFO] Download Started for NVD CVE - 2020
[INFO] Download Started for NVD CVE - 2021
[INFO] Download Complete for NVD CVE - 2021  (31 ms)
[INFO] Download Complete for NVD CVE - 2020  (156 ms)
[INFO] Processing Complete for NVD CVE - 2003  (11063 ms)
[INFO] Processing Started for NVD CVE - 2006
[INFO] Processing Complete for NVD CVE - 2004  (17672 ms)
[INFO] Processing Started for NVD CVE - 2007
[INFO] Processing Complete for NVD CVE - 2005  (26672 ms)
[INFO] Processing Started for NVD CVE - 2008
[INFO] Processing Complete for NVD CVE - 2002  (29813 ms)
[INFO] Processing Started for NVD CVE - 2009
[INFO] Processing Complete for NVD CVE - 2006  (37469 ms)
[INFO] Processing Started for NVD CVE - 2010
[INFO] Processing Complete for NVD CVE - 2007  (36515 ms)
[INFO] Processing Started for NVD CVE - 2011
[INFO] Processing Complete for NVD CVE - 2009  (43968 ms)
[INFO] Processing Started for NVD CVE - 2012
[INFO] Processing Complete for NVD CVE - 2008  (60266 ms)
[INFO] Processing Started for NVD CVE - 2013
[INFO] Processing Complete for NVD CVE - 2010  (59984 ms)
[INFO] Processing Started for NVD CVE - 2014
[INFO] Processing Complete for NVD CVE - 2011  (59219 ms)
[INFO] Processing Started for NVD CVE - 2015
[INFO] Processing Complete for NVD CVE - 2012  (67422 ms)
[INFO] Processing Started for NVD CVE - 2017
[INFO] Processing Complete for NVD CVE - 2013  (64000 ms)
[INFO] Processing Started for NVD CVE - 2016
[INFO] Processing Complete for NVD CVE - 2015  (57031 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Processing Complete for NVD CVE - 2014  (62906 ms)
[INFO] Processing Started for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2016  (45609 ms)
[INFO] Processing Started for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2017  (63953 ms)
[INFO] Processing Started for NVD CVE - 2021
[INFO] Processing Complete for NVD CVE - 2021  (797 ms)
[ERROR] Error reading NVD JSON data: C:\Users\ADMINI~1\AppData\Local\Temp\2\dctemp40832655-4713-4ed9-8b54-79f25a001aa9\cve2020_2006991783368212397.json.gz
[INFO] Processing Complete for NVD CVE - 2019  (50609 ms)
[INFO] Processing Complete for NVD CVE - 2018  (50750 ms)
[ERROR] Unable to find the NVD CPE file to parse
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to find the NVD CPE file to parse
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:110)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end of ZLIB input stream (through reference chain: org.owasp.dependencycheck.data.nvd.json.DefCveItem["cv
e"]->org.owasp.dependencycheck.data.nvd.json.CVEJSON40Min11["description"]->org.owasp.dependencycheck.data.nvd.json.Description["description_data"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:363)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
        at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
        at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2007)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1174)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:99)
        ... 8 common frames omitted
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:225)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2406)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2491)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2471)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getValueAsString(UTF8StreamJsonParser.java:345)
        at com.fasterxml.jackson.module.afterburner.deser.SettableStringMethodProperty.deserializeAndSet(SettableStringMethodProperty.java:47)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:347)
        ... 21 common frames omitted
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to find the NVD CPE file to parse
[ERROR] No documents exist
```
Can you help me to see how to solve it?
Thanks!

**Comment by jeremylong** [comment]
Looks like the gz file was corrupted somehow.  I would download the 2020 file from your host and see if you can successfully exact the contained file.

**Comment by daxin09pp** [comment]
[nvdcve-1.1-2020.json.gz](https://github.com/jeremylong/DependencyCheck/files/5847005/nvdcve-1.1-2020.json.gz)
Thanks @jeremylong!
Can you help to see if this is any issue for the gz file? I have no problem unzipping this file.

**Comment by jeremylong** [comment]
The file seams fine. Any chance you are running out of disk space? Does this error happen every time?

**Comment by daxin09pp** [comment]
Yes, every time it will happen. 
The disk still has 3G of space, isn't that enough?
Thanks! @jeremylong

**Comment by jeremylong** [comment]
Honestly, I have no idea what is going on in your environment.

**Comment by jeremylong** [comment]
3G is more than enough.

**Comment by daxin09pp** [comment]
Do you need more information?
Thanks for your help anyway.
@jeremylong

**Comment by daxin09pp** [comment]
It will not report this error if I do not apply NVD mirroring. So it's my NVD mirroring problem?

**Comment by jeremylong** [comment]
That would be my guess.

**Comment by daxin09pp** [comment]
But it doesn't seem to have any problems, and only the 2020 NVD isn't working..

**Comment by daxin09pp** [comment]
Or maybe I should go to NVD mirrored GitHub and ask a question?
Thanks for your help anyway.

**Comment by SuperXiaoxiong** [comment]
I met the preblem too
```
[ERROR] Error reading NVD JSON data: /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz
[INFO] Processing Complete for NVD CVE - 2020  (8702 ms)
[INFO] Processing Complete for NVD CVE - 2021  (7265 ms)
[ERROR] Unable to find the NVD CVE file to parse
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to find the NVD CVE file to parse
```

the md5  int the cache dir is correct
data/nvdcache/nvdcve-1.1-2019.json.gz is  `5acdef494d234bcd7668e23dd38a413d`, that is same with other computer that work nice
but in the /tmp/ file is not correct `0ddcd2875161938fe842efe78a272f82` 
```
md5sum /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz 
0ddcd2875161938fe842efe78a272f82  /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz
```

**Comment by SuperXiaoxiong** [comment]
> I met the preblem too
> 
> ```
> [ERROR] Error reading NVD JSON data: /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz
> [INFO] Processing Complete for NVD CVE - 2020  (8702 ms)
> [INFO] Processing Complete for NVD CVE - 2021  (7265 ms)
> [ERROR] Unable to find the NVD CVE file to parse
> org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to find the NVD CVE file to parse
> ```
> 
> the md5 int the cache dir is correct data/nvdcache/nvdcve-1.1-2019.json.gz is `5acdef494d234bcd7668e23dd38a413d`, that is same with other computer that work nice but in the /tmp/ file is not correct `0ddcd2875161938fe842efe78a272f82`
> 
> ```
> md5sum /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz 
> 0ddcd2875161938fe842efe78a272f82  /tmp/dctemp2d813064-f013-40be-a4ec-5dd85e09c89e/cve2019_8995596810556646575.json.gz
> ```

I downgrade the version form Version 6.5.3 to 6.5.2 , and then work fine
emmm,

Maybe there is some cache that destory the process. because the dependency-check file is delete completely and then work fine
