### ISSUE TITLE
Parsing errors seen during Go-lang analysis

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#3091]
**Describe the bug**
CVEs are not reported for a few artifacts with errors seen in log.

**Version of dependency-check used**
6.0.5

**Log file**
2021-01-20 12:53:41,351 org.owasp.dependencycheck.App:224
ERROR - Error parsing stream
2021-01-20 12:53:41,351 org.owasp.dependencycheck.App:225
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
        at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:86)
        at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:62)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
        at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
        at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
        at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:438)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
        at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:128)
        at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
        ... 2 common frames omitted
2021-01-20 12:53:41,351 org.owasp.dependencycheck.App:224
ERROR - Error parsing stream
2021-01-20 12:53:41,351 org.owasp.dependencycheck.App:225
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
        at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:86)
        at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:62)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.json.stream.JsonParsingException: Invalid token=COLON at (line no=42, column no=8, offset=2061). Expected tokens are: [COMMA]
        at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
        at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
        at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:557)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
        at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:324)
        at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:164)
        at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:129)
        at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
        ... 2 common frames omitted

**Expected behavior**
Report should be clean without any errors.

**Comment by mprins** [comment]
tool appears to be complaining about a json file that is invalid, please check your inputs

**Comment by rofafor** [comment]
This looks identical to #3110

**Comment by jeremylong** [comment]
#3110 was closed by the reporter. If you can provide a test case that contains this issue please let us know.
