### ISSUE TITLE
ERROR - Exception occurred initializing Assembly Analyzer; GrokAssembly.dll is not working properly 

### ISSUE THREAD

**Issue by nellysn** [dependency-check/DependencyCheck#3104]
After upgrading Dependency-Check CLI from 5.3.2 to 6.0.5 in one of my Jenkins builds I am getting the following error. I have dotnet  2.1.701 installed.  Please suggest what might cause this error.

`2021-01-26 06:57:59,600 org.owasp.dependencycheck.utils.FileUtils:121
DEBUG - Temporary directory is `C:\Users\AUTO_M~1\AppData\Local\Temp\dctemp4412e160-a1fa-4ee5-9618-4c010d6e7ad0\dctemp747c3922-9e0d-4cea-bcac-3102d27b12d1`
2021-01-26 06:57:59,761 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:369
WARN  - An error occurred with the .NET AssemblyAnalyzer, please see the log for more details.
2021-01-26 06:57:59,762 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:370
DEBUG - GrokAssembly.dll is not working properly
2021-01-26 06:57:59,762 org.owasp.dependencycheck.Engine:783
ERROR - Exception occurred initializing Assembly Analyzer.
2021-01-26 06:57:59,767 org.owasp.dependencycheck.Engine:784
DEBUG - 
org.owasp.dependencycheck.exception.InitializationException: Could not execute .NET AssemblyAnalyzer
	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.prepareFileTypeAnalyzer(AssemblyAnalyzer.java:373)
	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:781)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:617)
	at org.owasp.dependencycheck.App.runScan(App.java:254)
	at org.owasp.dependencycheck.App.run(App.java:186)
	at org.owasp.dependencycheck.App.main(App.java:81)
2021-01-26 06:57:59,768 org.owasp.dependencycheck.Engine:780`

On a dev Windows 2016 machine with dotnet 5.0.102 I see warnings "Error from GrokAssembly" for some DLLs. 
What dotnet version should be used with Dependency-Check 6.0.5?
Does the "Error from GrokAssembly" warning for the log4net.dll file from the log below mean that this DLL is skipped by the Analyzer? 

`DEBUG - Begin Analysis of 'D:\MIQ_mLine\MobileIQSolution\MobileIQSettings\bin\x64\Release\Core.dll' (Assembly Analyzer)
2021-01-26 07:33:50,544 org.owasp.dependencycheck.AnalysisTask:86
DEBUG - Begin Analysis of 'D:\MIQ_mLine\MobileIQSolution\SetupCustomAction\bin\Release\**log4net.dll**' (Assembly Analyzer)
2021-01-26 07:33:50,703 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:154
WARN  - Error from GrokAssembly: `

**Comment by jeremylong** [comment]
I have dotnet core 3.1 installed.

**Comment by nellysn** [comment]
Thanks!

**Comment by miguelrivera** [comment]
Is there no support for dotnet 5?

**Comment by meghshyamgaur** [comment]
Does anyone know if OWASP Dependency check is compatible with .net framework 4.6.X+ 

I am also getting the same error when the OWASP dependecy check try to scan through the .net framework project. 
[ERROR] Could not execute .NET AssemblyAnalyzer

![Capture](https://user-images.githubusercontent.com/73338401/162995116-8c975e10-a982-4967-86f3-116f51fc148b.PNG)

**Comment by Illutax** [comment]
Here is a exception stack for such an error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:6.4.1:check (default) on project app: One or more exceptions occurred during dependency-check analysis
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:306)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: One or more exceptions occurred during dependency-check analysis
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1826)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:979)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        InitializationException: Could not execute .NET AssemblyAnalyzer
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:662)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1794)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:979)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

Update to latest 7.0.4 fixed it for me.

**Comment by jeremylong** [comment]
@meghshyamgaur if you are having an issue you should not post to a closed ticket. you need to have the dotnet core runtime 6 installed as the grok assembly is compiled to 6.0.0. You can still analyze assemblies for other runtimes and the .net framework.
