### ISSUE TITLE
CPE analyzer failing to initialize

### ISSUE THREAD

**Issue by stephpelletier** [dependency-check/DependencyCheck#3158]
My team and I started having this issue last week while using OWASP Dependency Check on our Azure DevOps pipeline. We are using version 6.0.2 but we've also tried 6.1.1 and we still have the same problem where the CPE analyzer crash when initializing. We have also tried to run the Dependency Check on different VMs but without success. We still get the same error. There was no major updates to the VMs when we started having this issue and no JVM update either.

The logs give us this stack trace of the exception causing the error

```
DEBUG - Initializing CPE Analyzer
2021-02-19 12:33:53,780 org.owasp.dependencycheck.Engine:794
ERROR - Unexpected exception occurred initializing CPE Analyzer.
2021-02-19 12:33:53,796 org.owasp.dependencycheck.Engine:795
DEBUG - 
java.lang.NoSuchMethodError: org.apache.lucene.codecs.lucene80.Lucene80DocValuesFormat.<init>(Lorg/apache/lucene/codecs/lucene80/Lucene80DocValuesFormat$Mode;)V
	at org.apache.lucene.codecs.lucene87.Lucene87Codec.<init>(Lucene87Codec.java:116)
	at org.apache.lucene.codecs.lucene87.Lucene87Codec.<init>(Lucene87Codec.java:103)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:128)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:159)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.buildIndex(AbstractMemoryIndex.java:204)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.open(AbstractMemoryIndex.java:128)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:221)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer(CPEAnalyzer.java:186)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:781)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:617)
	at org.owasp.dependencycheck.App.runScan(App.java:254)
	at org.owasp.dependencycheck.App.run(App.java:186)
	at org.owasp.dependencycheck.App.main(App.java:81)
2021-02-19 12:33:53,796 org.owasp.dependencycheck.Engine:780
```

What could cause the Lucene index to break like that?

**Comment by stephpelletier** [comment]
I've been able to replicate the issue on my local machine. Turns out that Azure DevOps keep the task in cache. When two different version of Dependency Check is used in the pipelines, the lib folder will be merge together. When that happen, Dependency Check will get confused with Lucene. I've tested that with both version, 6.0.2 and 6.1.1.

Step to reproduce:
- Copy the lib folder from 6.0.2 to 6.1.1 and skip the file replacement (This simulate ADO task overwriting the files)
- Run Dependency Check 6.1.1

I will create an issue on the Azure DevOps project so that different version are stored in different folder and avoid this issue.
