### ISSUE TITLE
java.lang.NullPointerException while scanning a dependency with org.owasp.dependencycheck 6.1.3

### ISSUE THREAD

**Issue by abhisheksr01** [dependency-check/DependencyCheck#3235]
**Describe the bug**
Started getting Null pointer exception after bumping the org.owasp.dependencycheck from **6.1.1** to **6.1.3**.
The exception is specifically occurring while analysing the latest stable version of pitest dependency 0.14.
Please find the below table to illustrate the issue:

| S.NO | Dependencheck version  | Pitest version | Result |
|:------|:-------------------------|:--------------|:-------------------------
| 1        |       6.1.1                              | 0.12                 | works fine                         |          
| 2       |       6.1.1                             | 0.14                  | works fine                         |
| 3       |       6.1.3                             | 0.12                  | works fine                         |
| 4       |       6.1.3                             | 0.14                  | Null Pointer Exception     |

**Version of dependency-check used**
org.owasp.dependencycheck: 6.1.3
gradlew: 6.8.3
java: 8

**Log file**
```
> Task :dependencyCheckAnalyze
Verifying dependencies for project companieshouse
Checking for updates and analyzing dependencies for vulnerabilities

An unexpected error occurred during analysis of '/Users/abhishekrajput/.gradle/caches/modules-2/files-2.1/org.pitest/pitest-junit5-plugin/0.14/d44159efa6807898d0a881bb6d0fb0f63a6f0ec2/pitest-junit5-plugin-0.14.jar' (CPE Analyzer): null

java.lang.NullPointerException
        at java.lang.String.endsWith(String.java:1449)
        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.lambda$null$3(CPEAnalyzer.java:380)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.lambda$addMajorVersionToTerms$5(CPEAnalyzer.java:383)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.addMajorVersionToTerms(CPEAnalyzer.java:378)
        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:279)
        at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:764)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

> Task :dependencyCheckAnalyze FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Analysis failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
2 actionable tasks: 1 executed, 1 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] 
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the GitHub repo:
   ```
   git clone https://github.com/abhisheksr01/spring-boot-microservice-best-practices.git
   ```
2. Checkout branch **dependencychecknpe**
    created a separate branch specifically for this issue.
    ```
    git checkout -t origin/dependencychecknpe
    ```

3. Execute dependency scan
    ```
    ./gradlew clean dependencyCheckAnalyze --scan
    ```

**Expected behaviour**
Should have executed successfully.

**Additional context**
In meantime, I was thinking if I can ignore this dependency maybe by adding it into suppression.xml. 

But obviously, that's not the right place. Is there another way how can I ignore this dependency (something like the way .gitignore works).

Thanks,

**Comment by jeremylong** [comment]
This will be with the 6.1.4 release.

**Comment by abhisheksr01** [comment]
Thanks @jeremylong for quick response.

Just for my understanding the exception occurred because the latest 6.1.3 release doesn't have pitest 0.14 in the known list & when it looks for that it returns null.

Do we have a way of saying ignore a specific dependency for scanning (apart from standard suprressing)? 

**Thanks for wonderful security tooling :)**
