### ISSUE TITLE
Exception occurred initializing Assembly Analyzer

### ISSUE THREAD

**Issue by anhuong** [dependency-check/DependencyCheck#3238]
### Reporting Bugs/Errors
[Dependency-check errors gist](https://gist.github.com/anhuong/781d99396bf08a0ebc786f07bd247642)

I have dotnet-sdk-3.1 installed in the docker image that I have dependency-check installed. However, the Assembly Analyzer continues to fail although in the direct console logs it doesn't show .NET failing but in the extended logs the below error is seen.

Version dependency-check: Dependency-Check Core version 6.1.1

```
ERROR - Exception occurred initializing Assembly Analyzer.
2021-03-05 20:17:29,456 org.owasp.dependencycheck.Engine:784
DEBUG -
org.owasp.dependencycheck.exception.InitializationException: Could not execute .NET AssemblyAnalyzer
	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.prepareFileTypeAnalyzer(AssemblyAnalyzer.java:372)
	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:781)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:617)
	at org.owasp.dependencycheck.App.runScan(App.java:254)
	at org.owasp.dependencycheck.App.run(App.java:186)
	at org.owasp.dependencycheck.App.main(App.java:81)
2021-03-05 20:17:29,456 org.owasp.dependencycheck.Engine:780
```

I have tried adding the `--dotnet` flag to no avail. In the gist linked to at the top, you can see the logs for running dependency-check, once with no flags and once with the `--dotnet` flag. However, the logs were over 20GBs each so I wasn't able to upload or even open the file. Instead, I parsed and looked for the word `ERROR` and copied the previous 25 lines and the following 25 lines from the error. 

When running, here are the direct console logs:
```
docker run --rm -v /a/workspace/dashboard_debug-dependency-check:/opt/app wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com/ghenkins-common-tools:0.0.2-23-g73c227c_jenkins-ai-foundation-ghenkins-common-add-dotnet- dependency-check --enableExperimental -f ALL -s . -o /scan-results --project model-mesh-dashboard --failOnCVSS 0 -l scan-results/log --yarn /usr/bin/yarn --dotnet /usr/bin/dotnet
08:27:45  Unable to find image 'wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com/ghenkins-common-tools:0.0.2-23-g73c227c_jenkins-ai-foundation-ghenkins-common-add-dotnet-' locally
08:27:46  0.0.2-23-g73c227c_jenkins-ai-foundation-ghenkins-common-add-dotnet-: Pulling from ghenkins-common-tools
08:27:46  6b536614e8f8: Pulling fs layer
.....
08:28:20  231eab45095c: Pull complete
08:28:20  Digest: sha256:6599c6e8e49f6f08238ad41c37492be8239285cf945cb29367ceb29633de72a9
08:28:20  Status: Downloaded newer image for wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com/ghenkins-common-tools:0.0.2-23-g73c227c_jenkins-ai-foundation-ghenkins-common-add-dotnet-
08:28:59  [INFO] Checking for updates
08:28:59  [INFO] Skipping NVD check since last check was within 4 hours.
08:28:59  [INFO] Skipping RetireJS update since last update was within 24 hours.
08:28:59  [INFO] Check for updates complete (248 ms)
08:28:59  [INFO] 
08:28:59  
08:28:59  Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.
08:28:59  
08:28:59  
08:28:59  [INFO] Analysis Started
08:28:59  [WARN] Exception extracting archive 'cb-never-called-1.0.1.tgz'.
08:28:59  [INFO] Finished Archive Analyzer (3 seconds)
08:28:59  [INFO] Finished File Name Analyzer (0 seconds)
08:28:59  [INFO] Finished Jar Analyzer (0 seconds)
08:29:07  [INFO] Finished Central Analyzer (7 seconds)
08:29:07  [INFO] Finished Assembly Analyzer (0 seconds)
08:29:07  [INFO] Finished Python Distribution Analyzer (0 seconds)
08:29:07  [INFO] Finished Python Package Analyzer (0 seconds)
08:29:07  [INFO] Finished Autoconf Analyzer (0 seconds)
08:29:07  [INFO] Finished OpenSSL Source Analyzer (0 seconds)
08:29:08  [WARN] dependency skipped: node module fsevents seems optional and not installed
08:29:08  [WARN] dependency skipped: node module fsevents seems optional and not installed
08:29:08  [INFO] Finished Node.js Package Analyzer (1 seconds)
08:29:08  [INFO] Finished PE Analyzer (0 seconds)
08:29:30  [INFO] Finished Dependency Merging Analyzer (21 seconds)
08:29:30  [INFO] Finished Version Filter Analyzer (0 seconds)
08:29:31  [INFO] Finished Hint Analyzer (0 seconds)
08:29:33  [INFO] Created CPE Index (2 seconds)
08:29:34  [INFO] Finished NPM CPE Analyzer (2 seconds)
08:29:36  [INFO] Created CPE Index (2 seconds)
08:29:44  [INFO] Finished CPE Analyzer (10 seconds)
08:29:44  [INFO] Finished False Positive Analyzer (0 seconds)
08:29:45  [INFO] Finished NVD CVE Analyzer (0 seconds)
08:29:46  [INFO] Finished Node Audit Analyzer (0 seconds)
08:29:46  [WARN] Provided path to `yarn` executable is invalid.
08:29:46  [INFO] Finished Yarn Audit Analyzer (0 seconds)
08:30:01  [INFO] Finished RetireJS Analyzer (13 seconds)
08:30:16  [INFO] Finished Sonatype OSS Index Analyzer (14 seconds)
08:30:16  [INFO] Finished Vulnerability Suppression Analyzer (1 seconds)
09:00:16  [ERROR] Analysis task was cancelled.
09:00:16  [ERROR] One or more fatal errors occurred
```

I saw there were similar issues where the Assembly Analyzer failed or .NET failed, but the main problems seemed to be related to if dotnet was installed at the correct version, which mine appears to be.

**Comment by jeremylong** [comment]
You need to use the `--dotnet path/to/dotnet` and ensure you are pointing to the executable (including the extension if there is one). You can also add `--log odc.log` and look at the top of the ODC execution where it prints out the settings used.

**Comment by anhuong** [comment]
Appreciate the prompt reply Jeremy. As I noted, I tried both with passing no flags and with using the `--dotnet path/to/dotnet` which I also verified in the docker image through running `which dotnet` to find the executable. Also note that I have been using the `--log` file to output an extended log. The command I've been running is:

```
  dependency-check --enableExperimental -f ALL \
  -s . -o /scan-results --project model-mesh-dashboard --failOnCVSS 0 -l scan-results/log \
  --dotnet /usr/bin/dotnet --yarn /usr/bin/yarn
``` 

The settings are so long and I'm not seeing a reference to dotnet...
```
2021-03-05 20:17:03,657 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: data.directory='/opt/dependency-check/data'
2021-03-05 20:17:03,663 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.experimental.enabled='true'
2021-03-05 20:17:03,663 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.jar.enabled='true'
2021-03-05 20:17:03,664 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.msbuildproject.enabled='true'
2021-03-05 20:17:03,664 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.archive.enabled='true'
2021-03-05 20:17:03,665 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.python.distribution.enabled='true'
2021-03-05 20:17:03,665 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.python.package.enabled='true'
2021-03-05 20:17:03,665 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.autoconf.enabled='true'
2021-03-05 20:17:03,666 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.pip.enabled='true'
2021-03-05 20:17:03,666 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.pipfile.enabled='true'
2021-03-05 20:17:03,666 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.cmake.enabled='true'
2021-03-05 20:17:03,666 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.nuspec.enabled='true'
2021-03-05 20:17:03,667 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.nugetconf.enabled='true'
2021-03-05 20:17:03,667 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.assembly.enabled='true'
2021-03-05 20:17:03,667 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.bundle.audit.enabled='true'
2021-03-05 20:17:03,667 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.mix.audit.enabled='true'
2021-03-05 20:17:03,668 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.openssl.enabled='true'
2021-03-05 20:17:03,668 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.composer.lock.enabled='true'
2021-03-05 20:17:03,668 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.golang.dep.enabled='true'
2021-03-05 20:17:03,668 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.golang.mod.enabled='true'
2021-03-05 20:17:03,669 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.node.package.enabled='true'
2021-03-05 20:17:03,669 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.node.audit.enabled='true'
2021-03-05 20:17:03,669 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.yarn.audit.enabled='true'
2021-03-05 20:17:03,670 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.node.audit.use.cache='true'
2021-03-05 20:17:03,670 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.retirejs.enabled='true'
2021-03-05 20:17:03,670 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.swift.package.manager.enabled='true'
2021-03-05 20:17:03,670 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.cocoapods.enabled='true'
2021-03-05 20:17:03,671 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.ruby.gemspec.enabled='true'
2021-03-05 20:17:03,671 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.central.enabled='true'
2021-03-05 20:17:03,671 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.central.use.cache='true'
2021-03-05 20:17:03,671 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.ossindex.enabled='true'
2021-03-05 20:17:03,671 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.ossindex.use.cache='true'
2021-03-05 20:17:03,673 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: junit.fail.on.cvss='0.0'
2021-03-05 20:17:03,673 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.nexus.proxy='true'
```

**Comment by jeremylong** [comment]
When I run 
```
/cli/target/release/bin/dependency-check.sh -l odc.log -s ./cli/target/release/lib -o . \
 --dotnet /usr/local/share/dotnet/dotnet --yarn /usr/bin/yarn
```
I get:

```
2021-04-13 07:06:58,805 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: data.directory='/Users/jeremy/Projects/DependencyCheck/cli/target/release/data'
2021-04-13 07:06:58,809 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.yarn.path='/usr/bin/yarn'
2021-04-13 07:06:58,810 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.jar.enabled='true'
2021-04-13 07:06:58,811 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: analyzer.msbuildproject.enabled='true'
```

I'm not sure what is going on with your container...
