### ISSUE TITLE
Not able to download latest version through Jenkins

### ISSUE THREAD

**Issue by niajthat** [dependency-check/DependencyCheck#3251]
There is something strange going on with Jenkins plugin which gets versions from bintray. It shows mis-spelled versions. It was working fine till v6.1.1.

![image](https://user-images.githubusercontent.com/73612953/113224058-6c26a900-923f-11eb-8532-568b9a9e5956.png)

Using any of them results in errors:
ERROR: Failed to download https://github.com/jeremylong/DependencyCheck/releases/download/version 6.1.4/dependency-check-ersion 6.1.4-release.zip from agent; will retry from master
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1157)
		at hudson.FilePath.act(FilePath.java:1146)
		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1002)
		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:938)
		at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.performInstallation(DependencyCheckInstaller.java:42)
		at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:69)
		at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
		at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:206)
		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation.forNode(DependencyCheckInstallation.java:66)
		at org.jenkinsci.plugins.DependencyCheck.DependencyCheckToolBuilder.perform(DependencyCheckToolBuilder.java:139)
		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/jeremylong/DependencyCheck/releases/download/version 6.1.4/dependency-check-ersion 6.1.4-release.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

**Comment by mprins** [comment]
as you could have read in the release notes 6.1.1 is the last release published to bintray: https://github.com/jeremylong/DependencyCheck/releases/tag/v6.1.2

for any other problems with the jenkins plugin please contact the jenkins pugin project that maintains and publishes the plugin, as noted in the docs: https://github.com/jeremylong/DependencyCheck#jenkins-plugin  (https://plugins.jenkins.io/dependency-check-jenkins-plugin/)

**Comment by niajthat** [comment]
Jenkins plugin is somehow pulling the version information from GitHub (as shown in screenshot), it just gets it incorrectly (has spaces in between).
https://issues.jenkins.io/browse/JENKINS-65286

**Comment by jeremylong** [comment]
The jenkins plugin is still seeking a new maintainer: https://github.com/jenkinsci/dependency-check-plugin#seeking-new-maintainer

Until this happens any fixes are likely not going to happen.

**Comment by one-random-dev** [comment]
@jeremylong the plugin has a way to pass a source link different than the bintray 
what currently is killing the automation is the difference between what the zip directory structure from bintray is, related to what the github release zip download.
inside the zip there is now a upper folder dependency-check, the jenkins plugin is expecting it to have the bin folder on the root of the zip.

for anyone looking for a quick fix for declarative pipelines as code (Jenkinsfile)  setup in Jenkins you can do this somewhat ugly workaround
1. go into the global tool configuration and declare the source as the direct download link of the zip on the github releases page 

![image](https://user-images.githubusercontent.com/49782782/117013540-e091b380-ace7-11eb-9e6e-448d1eaae2ac.png)
then just surround the step with a try catch 

`try{
  dependencyCheck additionalArguments: [additonal arguments required], odcInstallation: 'dependency-check-github-source'
  // this will fail and output 
  // [agent_source]/agent/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency-check-github-source/bin/dependency-check.sh
  // or
  // [agent_source]/agent/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency-check-github-source/bin/dependency-check.bat
  // not found... 
  // pick this path up and add missing dependency-check folder at zip target root level 
}catch(){
  if(isUnix()){
dep_check_sh='[agent_source]/agent/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency-check-github-source/dependency-check/bin/dependency-check.sh'
    bat "${env.dep_check_sh} [additional arguments required]"
  }else{
dep_check_bat='[agent_source]/agent/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency-check-github-source/dependency-check/bin/dependency-check.bat'
    bat "${env.dep_check_bat} [additonal arguments required]"

  }
}`

this will get you the same result and you can update the link in the jenkins global tools management UI
other than this I would advise to develop a custom way of handling this in Jenkins pipelines as this fix does not cover the UI based pipeline definitions (freestyle)
