### ISSUE TITLE
NPE in NvdCveUpdater.performUpdate

### ISSUE THREAD

**Issue by wilx** [dependency-check/DependencyCheck#3262]
**Describe the bug**
NPE in NvdCveUpdater.performUpdate.

**Version of dependency-check used**
The problem occurs using version 6.1.5 of the Maven plugin

**Log file**

```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:6.1.5:aggregate (default-cli) on project com.ca.apm.supertop: Execution default-cli of goal org.owasp:dependency-check-maven:6.1.5:aggregate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:6.1.5:aggregate (default-cli) on project com.ca.apm.supertop: Execution default-cli of goal org.owasp:dependency-check-maven:6.1.5:aggregate failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.owasp:dependency-check-maven:6.1.5:aggregate failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:307)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:860)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:667)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:593)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:1660)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:929)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        ... 20 more
```

**To Reproduce**

**Expected behavior**
No NPE.

**Comment by aikebah** [comment]
Do you still have the full log? A quick look at line 307 and the road towards it makes me suspect that there should be other errors reported before this NPE.

**Comment by aikebah** [comment]
Looks like there is an error just before your NPE on  downloading the CVE modified datastream

**Comment by wilx** [comment]
You are right, the job run with the error contained failed downloads like this:

```
15:34:21 [ERROR] Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz; received response code 503; Service Unavailable
15:34:21 [ERROR] Download Failed for NVD CVE - 2021
15:34:21 Some CVEs may not be reported. Reason: Download failed, unable to copy 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz' to 'D:\APMBUI~1.TEM\dctemp84a36166-49b9-4230-84af-7a2640adc13a\cve2021_3639338220744809960.json.gz'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz; unable to connect.
15:34:21 [ERROR] If you are behind a proxy you may need to configure dependency-check to use the proxy.
```

It did not reproduce on subesequent runs.
