### ISSUE TITLE
Golang Mod Analyzer exception

### ISSUE THREAD

**Issue by bretik** [dependency-check/DependencyCheck#3296]
**Describe the bug**
Golang Mod Analyzer fails on exception:

```
2021-04-19 10:51:43,907 org.owasp.dependencycheck.App:209
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error parsing stream
	at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:86)
	at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:62)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
	at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:438)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:128)
	at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
	... 2 common frames omitted
```

**Version of dependency-check used**

```
>dependency-check.bat -v
Dependency-Check Core version 6.1.5

>go version
go version go1.15.7 windows/amd64
```

**Log file**
https://gist.github.com/bretik/507b291675ed27a9a868a2fbaf0fe2fd

**To Reproduce**
Just run a scan with --enableExperimental

**Additional context**
go.mod attached in gist above

**Comment by fpytloun** [comment]
This seems to happen when there are missing credentials to fetch dependencies from 3rd party repositories. Unfortunately this can be seen only when running with debug output, eg.:

```
WARN  - Warnings from `go`: go: gopkg.domain.tld/codegen@v0.0.0-20210421234655-7130c2510d7c: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/713aaad437dc82f3e828bbae720e248535fd65c4140ac7f7ccfc6a1a82d0dd4f: exit st
atus 128:                                                                                                                                     
        fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled                                                    
             
```

**Comment by fpytloun** [comment]
Ok so my case is not the case of fetch failure. Attaching full debug and output of `go list -json -mod=mod -m all`
[golist.txt](https://github.com/jeremylong/DependencyCheck/files/6556374/golist.txt)
[depcheck-debug.log](https://github.com/jeremylong/DependencyCheck/files/6556435/depcheck-debug.log)

After long time of digging I found out that root cause is malformed `go.sum` after wrong rebase:
```
...
<<<<<<< Updated upstream
golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4 h1:Toz2IK7k8rbltAXwNAxKcn9OzqyNfMUhUNjz3sL0NMk=
=======
>>>>>>> Stashed changes
golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4/go.mod h1:TB2adYChydJhpapKDTa4BR/hXlZSLoq2Wpct/0txZ28=
golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
...
```
Unfortunately dependency-check gives no usable info in it's output so it's difficult to debug such issues.

**Comment by jeremylong** [comment]
Literally, the warning message:

```
WARN  - Warnings from `go`:...
```

Is the warning message you would get in your development environment if you ran `go list -json -mod=mod -m all`. I'm updating the code to include the warning message in the exception message.

For @bretic - the log file contains `WARN  - Warnings from `go`: go: updates to go.sum needed, disabled by -mod=readonly`.
