### ISSUE TITLE
Trying to register JCSAdminBean twice

### ISSUE THREAD

**Issue by dsvensson** [dependency-check/DependencyCheck#3303]
Using gradle 7 with dependencycheck 6.1.5, the following exception is printed when running dependencyCheckAnalyze:

```
> Task :dependencyCheckAnalyze
Could not register JMX bean.
javax.management.InstanceAlreadyExistsException: org.apache.commons.jcs:type=JCSAdminBean
        at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.commons.jcs.engine.control.CompositeCacheManager.initialize(CompositeCacheManager.java:271)
        at org.apache.commons.jcs.engine.control.CompositeCacheManager.getUnconfiguredInstance(CompositeCacheManager.java:218)
        at org.apache.commons.jcs.JCS.getCacheManager(JCS.java:162)
        at org.apache.commons.jcs.JCS.getInstance(JCS.java:205)
        at org.owasp.dependencycheck.data.cache.DataCacheFactory.getPomCache(DataCacheFactory.java:155)
```

The task finishes correctly however, so from a user POV it seems to be mostly a cosmetic issue.

**Comment by dsvensson** [comment]
Moved to the gradle plugin repository
