### ISSUE TITLE
[ERROR] java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ejayt** [dependency-check/DependencyCheck#3308]
**Describe the bug**
Ran docker.io/owasp/dependency-check:6.1.5. I think any scan will produce this error.
`[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.`

```
[INFO] Download Complete for NVD CVE - 2021  (6945 ms)
[INFO] Processing Started for NVD CVE - 2021
[ERROR] java.util.concurrent.ExecutionException: java.lang.NullPointerException
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:860)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:667)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:593)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:288)
        ... 7 common frames omitted
```

**Version of dependency-check used**
Using 6.1.6 snapshot and 6.1.5.

**Comment by ejayt** [comment]
I think this may be the same issue as #3307
