### ISSUE TITLE
org.owasp.dependencycheck.data.update.exception.UpdateException

### ISSUE THREAD

**Issue by networkandcode** [dependency-check/DependencyCheck#3314]
Hi OWASP stage in our Gradle CI pipeline seems failing and throws the following log, is anything related to network causing this. We are using Gradle 5 and Dependency check 6.0.2
```
Note: Recompile with -Xlint:deprecation for details.
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:email::address_module_project:email::address:1.896:*:*:*:*:perl:*:*
org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:email::address_module_project:email::address:1.896:*:*:*:*:perl:*:*
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:156)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:email::address_module_project:email::address:1.896:*:*:*:*:perl:*:*
	at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe(CveDB.java:1218)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.lambda$parseCpes$3(CveDB.java:1175)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpes(CveDB.java:1174)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:839)
	at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:101)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
	at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
	... 6 more
Caused by: us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid CPE (too many components): cpe:2.3:a:email::address_module_project:email::address:1.896:*:*:*:*:perl:*:*
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:225)
	at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:77)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe(CveDB.java:1208)
	... 13 more
Unable to continue dependency-check analysis.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckAnalyze'.
> Analysis failed.
```

**Comment by cestrian-sy** [comment]
Similar issue for different CPE on 5.3.2
```[DEBUG] Update Error
org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:ibm:sterling_connect:direct:4.1.0.0:*:*:*:*:unix:*:*
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles (ProcessTask.java:156)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:113)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:40)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:ibm:sterling_connect:direct:4.1.0.0:*:*:*:*:unix:*:*
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe (CveDB.java:1341)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.lambda$parseCpes$3 (CveDB.java:1298)
    at java.util.ArrayList.forEach (ArrayList.java:1249)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpes (CveDB.java:1297)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability (CveDB.java:880)
    at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse (NvdCveParser.java:99)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON (ProcessTask.java:139)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles (ProcessTask.java:152)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:113)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:40)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid CPE (too many components): cpe:2.3:a:ibm:sterling_connect:direct:4.1.0.0:*:*:*:*:unix:*:*
    at us.springett.parsers.cpe.CpeParser.parse23 (CpeParser.java:225)
    at us.springett.parsers.cpe.CpeParser.parse (CpeParser.java:77)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe (CveDB.java:1331)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.lambda$parseCpes$3 (CveDB.java:1298)
    at java.util.ArrayList.forEach (ArrayList.java:1249)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpes (CveDB.java:1297)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability (CveDB.java:880)
    at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse (NvdCveParser.java:99)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON (ProcessTask.java:139)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles (ProcessTask.java:152)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:113)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call (ProcessTask.java:40)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
[ERROR] Unable to continue dependency-check analysis.

Accompanied by
[DEBUG]
org.h2.jdbc.JdbcSQLNonTransientException: General error: "General error: ""java.lang.IllegalStateException: Writing to nio:/Users/auser/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db failed; length 69632 at 155013120 [1.4.199/2]"" [50000-199]" [50000-199]
    at org.h2.message.DbException.getJdbcSQLException (DbException.java:502)
    at org.h2.message.DbException.getJdbcSQLException (DbException.java:427)
    at org.h2.message.DbException.get (DbException.java:194)
    at org.h2.engine.Database.close (Database.java:1426)
    at org.h2.engine.Database.removeSession (Database.java:1381)
    at org.h2.engine.Session.close (Session.java:904)
    at org.h2.jdbc.JdbcConnection.close (JdbcConnection.java:456)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.close (CveDB.java:310)
    at org.owasp.dependencycheck.Engine.doUpdates (Engine.java:945)
    at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase (Engine.java:737)
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:667)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1557)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:848)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.h2.message.DbException: General error: "java.lang.IllegalStateException: Writing to nio:/Users/auser/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db failed; length 69632 at 155013120 [1.4.199/2]" [50000-199]
    at org.h2.message.DbException.get (DbException.java:194)
    at org.h2.message.DbException.convert (DbException.java:347)
    at org.h2.mvstore.db.MVTableEngine$1.uncaughtException (MVTableEngine.java:90)
    at org.h2.mvstore.MVStore.handleException (MVStore.java:2787)
    at org.h2.mvstore.MVStore.panic (MVStore.java:441)
    at org.h2.mvstore.MVStore.write (MVStore.java:937)
    at org.h2.mvstore.MVStore.storeNow (MVStore.java:1332)
    at org.h2.mvstore.MVStore.store (MVStore.java:1190)
    at org.h2.mvstore.MVStore.tryCommit (MVStore.java:1135)
    at org.h2.mvstore.MVStore.writeInBackground (MVStore.java:2763)
    at org.h2.mvstore.MVStore$BackgroundWriterThread.run (MVStore.java:3123)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Writing to nio:/Users/auser/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db failed; length 69632 at 155013120 [1.4.199/2]" [50000-199]
    at org.h2.message.DbException.getJdbcSQLException (DbException.java:502)
    at org.h2.message.DbException.getJdbcSQLException (DbException.java:427)
    at org.h2.message.DbException.get (DbException.java:194)
    at org.h2.message.DbException.convert (DbException.java:347)
    at org.h2.mvstore.db.MVTableEngine$1.uncaughtException (MVTableEngine.java:90)
    at org.h2.mvstore.MVStore.handleException (MVStore.java:2787)
    at org.h2.mvstore.MVStore.panic (MVStore.java:441)
    at org.h2.mvstore.MVStore.write (MVStore.java:937)
    at org.h2.mvstore.MVStore.storeNow (MVStore.java:1332)
    at org.h2.mvstore.MVStore.store (MVStore.java:1190)
    at org.h2.mvstore.MVStore.tryCommit (MVStore.java:1135)
    at org.h2.mvstore.MVStore.writeInBackground (MVStore.java:2763)
    at org.h2.mvstore.MVStore$BackgroundWriterThread.run (MVStore.java:3123)
Caused by: java.lang.IllegalStateException: Writing to nio:/Users/auser/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db failed; length 69632 at 155013120 [1.4.199/2]
    at org.h2.mvstore.DataUtils.newIllegalStateException (DataUtils.java:883)
    at org.h2.mvstore.DataUtils.writeFully (DataUtils.java:443)
    at org.h2.mvstore.FileStore.writeFully (FileStore.java:113)
    at org.h2.mvstore.MVStore.write (MVStore.java:935)
    at org.h2.mvstore.MVStore.storeNow (MVStore.java:1332)
    at org.h2.mvstore.MVStore.store (MVStore.java:1190)
    at org.h2.mvstore.MVStore.tryCommit (MVStore.java:1135)
    at org.h2.mvstore.MVStore.writeInBackground (MVStore.java:2763)
    at org.h2.mvstore.MVStore$BackgroundWriterThread.run (MVStore.java:3123)
Caused by: java.nio.channels.ClosedChannelException
    at sun.nio.ch.FileChannelImpl.ensureOpen (FileChannelImpl.java:110)
    at sun.nio.ch.FileChannelImpl.write (FileChannelImpl.java:758)
    at org.h2.store.fs.FileNio.write (FilePathNio.java:79)
    at org.h2.mvstore.DataUtils.writeFully (DataUtils.java:439)
    at org.h2.mvstore.FileStore.writeFully (FileStore.java:113)
    at org.h2.mvstore.MVStore.write (MVStore.java:935)
    at org.h2.mvstore.MVStore.storeNow (MVStore.java:1332)
    at org.h2.mvstore.MVStore.store (MVStore.java:1190)
    at org.h2.mvstore.MVStore.tryCommit (MVStore.java:1135)
    at org.h2.mvstore.MVStore.writeInBackground (MVStore.java:2763)
    at org.h2.mvstore.MVStore$BackgroundWriterThread.run (MVStore.java:3123)
[DEBUG] Lock released (main) 9ca213b4a3abcf3f4c1c23c21b9be174 @ 2021-04-22 13:02:09.227
[WARNING] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.```

**Comment by philipwhiuk** [comment]
Probably caused by https://twitter.com/NISTcyber/status/1384935382555537409

**Comment by denisw** [comment]
DependencyCheck started working again for me today. Seems like the issue was fixed on the NVD side.

**Comment by jeremylong** [comment]
This was resolved when the NVD corrected the data feeds.
