### ISSUE TITLE
Error: org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by kirivarnan** [dependency-check/DependencyCheck#3322]
Getting below exception: Tried latest v6.1.5.

[INFO] Processing Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2020  (3578 ms)
[INFO] Processing Started for NVD CVE - 2020
[INFO] Download Complete for NVD CVE - 2021  (3130 ms)
[INFO] Processing Started for NVD CVE - 2021
**[ERROR] java.util.concurrent.ExecutionException: java.lang.NullPointerException
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException**
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:298)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:125)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:860)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:667)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:593)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
**Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source)**
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:288)
        ... 7 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.owasp.dependencycheck.data.nvd.ecosystem.UrlEcosystemMapper.getEcosystem(UrlEcosystemMapper.java:68)
        at org.owasp.dependencycheck.data.nvd.ecosystem.CveEcosystemMapper.getEcosystem(CveEcosystemMapper.java:74)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:97)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] java.util.concurrent.ExecutionException: java.lang.NullPointerException
**[ERROR] No documents exist**

Anyone can help?

**Comment by mjeffrey** [comment]
Why don't you look at other issues before posting a new duplicate?

**Comment by kirivarnan** [comment]
Resolved now. Seems it was due to some network issues in NVD CVE. I encountered above issue yesterday. But, working fine today. no exceptions while updating now...
