### ISSUE TITLE
Error while using the Experimental Analyzer flag

### ISSUE THREAD

**Issue by udplume** [dependency-check/DependencyCheck#3362]
**Describe the bug**
Trying to use Experimental analyzers on a C/C++ code base . Don't have DotNet and Ruby installed hence disabled those analyzers

dependency-check.sh --enableExperimental --disableAssembly --disableBundle -l <log_file_name> --project <project_name> -o <filename> -s <dir>

**Version of dependency-check used**
Used from 6.1.5 and 6.1.6 cli

**Output / Log file**
Scan fails with output as follows when the --enableExperimental flag is used . Scan works ok if --enableExperimental flag is not used. 

[INFO] Analysis Started
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'testtar.tar'.
[WARN] Exception extracting archive 'unzip_bad_lzma_2.zip'.
[WARN] Exception extracting archive 'unzip_bad_lzma_1.zip'.
[WARN] Exception extracting archive 'unzip_bad_lzma_2.zip'.
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'sparse-formats.tar'.
[WARN] Exception extracting archive 'writer-big-long.tar'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[WARN] Exception extracting archive 'unzip_bad_lzma_1.zip'.
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[INFO] Finished Archive Analyzer (281 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (79 seconds)
[INFO] Finished Nuspec Analyzer (0 seconds)
[INFO] Finished MSBuild Project Analyzer (0 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Python Package Analyzer (11 seconds)
[INFO] Finished pip Analyzer (0 seconds)
[INFO] Finished Autoconf Analyzer (12 seconds)
[INFO] Finished OpenSSL Source Analyzer (0 seconds)
[ERROR] Analysis task was cancelled.
[ERROR] One or more fatal errors occurred

The log file created is huge , so did not inspect the whole log file

grep 'ERROR' <log_file>. (Only pasting the lines which started with the word ERROR and not the Debug lines which also had the word ERROR somewhere )

ERROR - Analysis task was cancelled.
ERROR - One or more fatal errors occurred

tail -100 <log_file>
Only saw 1 exception in this output. Again not pasting the entire output

DEBUG - 
java.util.concurrent.CancellationException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:731)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:631)
	at org.owasp.dependencycheck.App.runScan(App.java:254)
	at org.owasp.dependencycheck.App.run(App.java:186)
	at org.owasp.dependencycheck.App.main(App.java:81)

Not sure how to troubleshoot this.

**Comment by jeremylong** [comment]
My guess is that most, if not all errors, are around trying to extract files from the ZIP files. The only way to know for sure would be to see the full log.  In the log file right after the line `[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.` you should see the full stack trace written out regarding exactly what the error was.

**Comment by udplume** [comment]
Hi @jeremylong ,
                            Thank you for the response. Based on the log files I tried to identify the corresponding offending files. Some of the archives seen in the earlier log message eg. "[WARN] Exception extracting archive 'unzip_bad_lzma_2.zip'." were perhaps part of another archive themself. So I removed them temporarily from the directory being scanned so as to get a completely clean report. However, certain offending files / archives still exist and am unable to identify the correct files to exclude from the scan. 

The latest scan summary

[INFO] Analysis Started
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'sparse-formats.tar'.
[WARN] Exception extracting archive 'writer-big-long.tar'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[INFO] Finished Archive Analyzer (283 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (0 seconds)
[INFO] Finished Nuspec Analyzer (0 seconds)
[INFO] Finished MSBuild Project Analyzer (0 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Python Package Analyzer (10 seconds)
[INFO] Finished pip Analyzer (0 seconds)
[INFO] Finished Autoconf Analyzer (10 seconds)
[INFO] Finished OpenSSL Source Analyzer (0 seconds)

[ERROR] Analysis task was cancelled.
[ERROR] One or more fatal errors occurred

============

DEBUG - Extracting '/tmp/dctemp60083b42-4380-4d9a-b17a-21b874cffbda/check1275750169815533359tmp/2313/TutorialConfig.h.in'
2021-05-19 20:33:48,234 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'sparse-formats.tar'.
2021-05-19 20:33:48,234 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:454
DEBUG -
org.owasp.dependencycheck.analyzer.exception.ArchiveExtractionException: java.io.IOException: Truncated TAR archive
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:562)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:420)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:258)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:280)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:280)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:240)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Truncated TAR archive
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:878)
        at org.apache.commons.compress.utils.IOUtils.readFully(IOUtils.java:189)
        at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:121)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:354)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:799)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:541)
        ... 12 common frames omitted


=================

What I did earlier, is look at the [DEBUG] messages before the [WARN] message, and in most cases the debug message listed some archive file present the scanned directory. By removing some of these files from the scanned path, I was able to bring the number of exceptions thrown down from my previous message.

================
Now in case of "sparse-formats.tar" error / WARN message, several DEBUG messages before it refer to some files /tmp/ directly, so I am unable to get rid of these exceptions, even just for testing purposes. it is the similar case for all of the 8 WARN / Exceptions seen in this message above. 

Any suggestions on what should my next steps be ?

**Comment by udplume** [comment]
Another extract from log file

DEBUG - Extracting '/tmp/dctemp60083b42-4380-4d9a-b17a-21b874cffbda/check1275750169815533359tmp/2315/Step1/<redacted>'
2021-05-19 20:33:48,239 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:576
DEBUG - Extracting '/tmp/dctemp60083b42-4380-4d9a-b17a-21b874cffbda/check1275750169815533359tmp/2315/Step1/<redacted>'
2021-05-19 20:33:48,263 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN  - Exception extracting archive 'writer-big-long.tar'.
2021-05-19 20:33:48,264 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:454
DEBUG -
org.owasp.dependencycheck.analyzer.exception.ArchiveExtractionException: java.io.IOException: Error detected parsing the header
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:562)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:420)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:258)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:280)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:280)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:240)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error detected parsing the header
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:371)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:799)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:541)
        ... 12 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid byte 97 at offset 0 in 'ame/longname' len=12
        at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:143)
        at org.apache.commons.compress.archivers.tar.TarUtils.parseOctalOrBinary(TarUtils.java:173)
        at org.apache.commons.compress.archivers.tar.TarUtils.parseSparse(TarUtils.java:314)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1389)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:438)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:369)
        ... 14 common frames omitted

**Comment by jeremylong** [comment]
Honestly - if you are just excluding the offending files you don't have to exclude them. Just ignore these errors.  I'd be curious if there is an issue with the archives (as in they are actually broken in some way) or if ODC just isn't reading them correctly.

**Comment by udplume** [comment]
Hi @jeremylong ,
                           I excluded / removed the offending files as a temporary fix to atleast get some result or output. As of now the entire analysis fails, presumably because of these errors, and does not produce any results for this project. As seen in the console output I pasted above

=================
[INFO] Finished Autoconf Analyzer (10 seconds)
[INFO] Finished OpenSSL Source Analyzer (0 seconds)

**[ERROR] Analysis task was cancelled.
[ERROR] One or more fatal errors occurred**

=================

Hence I am unable to get any kind of results. My intention was to then work on each of those zip or archive files such as 'go-with-datadesc-sig.zip' and 'writer-big-long.tar' from there on. But for the last few remaining errors, I am unable to find the offending files, because the DEBUG messages in the Log file seem to be referring some files in the '/tmp' folder . I read through several of the DEBUG messages above the WARN message

for eg. 

========
....
**DEBUG - Extracting '/tmp/dctemp60083b42-4380-4d9a-b17a-21b874cffbda/check1275750169815533359tmp/2315/Step1/'
2021-05-19 20:33:48,239 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:576
DEBUG - Extracting '/tmp/dctemp60083b42-4380-4d9a-b17a-21b874cffbda/check1275750169815533359tmp/2315/Step1/'
2021-05-19 20:33:48,263 org.owasp.dependencycheck.analyzer.ArchiveAnalyzer:453
WARN - Exception extracting archive 'writer-big-long.tar'.**

========

I read several lines above this WARN line until I saw a DEBUG message which referred to a file inside the scanned directory rather than a /tmp location as seen above and assusmed that file might contain the 'writer-big-long.tar' and if I removed that file from the scanned directory it would make the error go away. This approach worked for some , as you can see 1st message on this issue, showed more errors . However this approach is not working for these last few remaining as seen below

**[INFO] Analysis Started
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'sparse-formats.tar'.
[WARN] Exception extracting archive 'writer-big-long.tar'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[WARN] Exception extracting archive 'go-with-datadesc-sig.zip'.
[WARN] Exception extracting archive 'go-no-datadesc-sig.zip'.
[WARN] Exception extracting archive 'nil-uid.tar'.
[INFO] Finished Archive Analyzer (283 seconds)**

**Comment by jeremylong** [comment]
I'm pretty sure the archive analyzer errors are a throwing you off as those should not be fatal errors. There is likely another error lower in the log. If there was a fatal error in the archive analyzer you wouldn't have even gotten to Autoconf or other analyzers.

**Comment by udplume** [comment]
Hi @jeremylong ,
                            I tried to investigate a little more

grep 'ERROR ' <log_file>
ERROR - Analysis task was cancelled.
ERROR - One or more fatal errors occurred

grep 'WARN ' <log_file>
WARN  - Exception extracting archive 'go-with-datadesc-sig.zip'.
WARN  - Exception extracting archive 'go-no-datadesc-sig.zip'.
WARN  - Exception extracting archive 'sparse-formats.tar'.
WARN  - Exception extracting archive 'writer-big-long.tar'.
WARN  - Exception extracting archive 'nil-uid.tar'.
WARN  - Exception extracting archive 'go-with-datadesc-sig.zip'.
WARN  - Exception extracting archive 'go-no-datadesc-sig.zip'.
WARN  - Exception extracting archive 'nil-uid.tar'.

Some Extract from the log file itself at the very end of the log file.

DEBUG - Group 1: QT_FOUND
2021-05-20 22:30:35,677 org.owasp.dependencycheck.analyzer.CMakeAnalyzer:260
DEBUG - Group 2: ${Qt4_FOUND}
2021-05-20 22:30:35,677 org.owasp.dependencycheck.analyzer.CMakeAnalyzer:263
DEBUG - Found 78 matches.
2021-05-20 23:00:31,944 org.owasp.dependencycheck.Engine:1086
ERROR - Analysis task was cancelled.
2021-05-20 23:00:31,951 org.owasp.dependencycheck.Engine:1087
DEBUG -
java.util.concurrent.CancellationException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.owasp.dependencycheck.Engine.executeAnalysisTasks(Engine.java:731)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:631)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
2021-05-20 23:00:31,952 org.owasp.dependencycheck.data.nvdcve.CveDB:295
DEBUG - Closing database
2021-05-20 23:00:31,952 org.owasp.dependencycheck.data.nvdcve.CveDB:297
DEBUG - Cache cleared
2021-05-20 23:00:31,952 org.owasp.dependencycheck.data.nvdcve.CveDB:299
DEBUG - Statments closed
2021-05-20 23:00:31,954 org.owasp.dependencycheck.data.nvdcve.CveDB:302
DEBUG - Connection closed
2021-05-20 23:00:31,954 org.owasp.dependencycheck.data.nvdcve.CveDB:311
DEBUG - Resources released
2021-05-20 23:00:31,954 org.owasp.dependencycheck.data.nvdcve.DriverLoader:57
DEBUG - Begin deregister driver
2021-05-20 23:00:31,954 org.owasp.dependencycheck.data.nvdcve.DriverLoader:59
DEBUG - End deregister driver
2021-05-20 23:00:32,466 org.owasp.dependencycheck.App:202
ERROR - One or more fatal errors occurred
2021-05-20 23:00:32,466 org.owasp.dependencycheck.utils.Settings:767
DEBUG - Deleting ALL temporary files from `/tmp/dctemp7d606935-cc28-4823-ab81-2cddbb168256`
2021-05-20 23:00:48,619 org.owasp.dependencycheck.App:82
DEBUG - Exit code: -13

I did not find any other Exception / Error inside the log file

**Comment by jeremylong** [comment]
How long does the analysis take before it fails? There is currently a 30 minute timer - in most cases if the analysis takes longer then that there is something wrong.  If it is taking longer then 30 minutes you can set your JAVA_OPTS to include `-Dodc.analysis.timeout=60` to increase the timeout to one hour.

**Comment by udplume** [comment]
Hi @jeremylong ,
                            It looks like the scan is mainly limited by the timeout limit. I tried scans with different timeouts and used the 'time' command to record the execution time

timeout=50

--------------

real    57m33.177s
user    151m25.540s
sys     1m9.764s

-------------------

timeout=90

--------------------

real    97m44.100s
user    281m14.276s
sys     1m12.524s

--------------------

Could this be because of code size or something. Below is a summary of 'cloc' tool output for the directory being scanned

Language                           files             blank            comment             code

------------------------------------------------------------------------------
SUM:                                230670        10528632         12392781        60694612

**Comment by udplume** [comment]
@jeremylong 
just wanted to check if you have any recommendations on how I could proceed on this to successfully scan the codebase I am trying to.

Thank you

**Comment by chadlwilson** [comment]
If this is still an issue, please comment and we can reopen.
