### ISSUE TITLE
Jenkins plugin attempts to download from a domain that does not allow downloads anymore

### ISSUE THREAD

**Issue by yossygit** [dependency-check/DependencyCheck#3367]
**Describe the bug**
Jenkins plugin attempts to download dependency check binaries from the following domain
https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip
https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip
This domain belongs to Jrog and it seems that they don't allow the usage of this domains for free artifacts storage
the following message is displayed when accessing their main domain : "Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th."
**Version of dependency-check used**
The problem occurs using version 6.1.1 jenkins plugin

**Log file**
Jenkins console output
Unpacking https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip to /home/ec2-user/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency_6.0.5 on jenkins driver compilation - suse12
ERROR: Failed to download https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip from agent; will retry from master
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins driver compilation - suse12
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1158)
		at hudson.FilePath.act(FilePath.java:1147)
		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1003)
		at hudson.FilePath.installIfNecessaryFrom(FilePath.java:939)
		at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.performInstallation(DependencyCheckInstaller.java:42)
		at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:69)
		at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
		at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:217)
		at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation.forNode(DependencyCheckInstallation.java:66)
		at org.jenkinsci.plugins.DependencyCheck.DependencyCheckToolBuilder.perform(DependencyCheckToolBuilder.java:139)
		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
		at hudson.model.Build$BuildExecution.build(Build.java:197)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
		at hudson.model.Run.execute(Run.java:1907)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1068)
	at hudson.FilePath$Unpack.invoke(FilePath.java:1037)
	at hudson.FilePath$Unpack.invoke(FilePath.java:1031)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3314)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
FATAL: Failed to install https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip to /home/ec2-user/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency_6.0.5
java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:412)
	at org.jvnet.robust_http_client.RetryableHttpStream.<init>(RetryableHttpStream.java:90)
Caused: java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.jvnet.robust_http_client.RetryableHttpStream.getStream(RetryableHttpStream.java:98)
	at org.jvnet.robust_http_client.RetryableHttpStream.<init>(RetryableHttpStream.java:91)
	at org.jvnet.robust_http_client.RetryableHttpStream.<init>(RetryableHttpStream.java:74)
	at hudson.ProxyConfiguration.getInputStream(ProxyConfiguration.java:330)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1012)
Caused: java.io.IOException: Failed to install https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.5-release.zip to /home/ec2-user/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency_6.0.5
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1026)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:939)
	at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
	at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.performInstallation(DependencyCheckInstaller.java:42)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:69)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:217)
	at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation.forNode(DependencyCheckInstallation.java:66)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckToolBuilder.perform(DependencyCheckToolBuilder.java:139)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[DependencyCheck] Collecting Dependency-Check artifact
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
 Help us localize this page
**To Reproduce**
1. Go to https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip

4. See error "Fordibben" (HTTP 403 error)

**Expected behavior**
The file will not be downloaded...

Proposed mitigation
The artifacts should be moved to other location and an update should be publised.
In fact it is a default domain that Jenkins plugin attempts to download from 
 https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.1-release.zip

**Comment by mprins** [comment]
bintray is dead, check the release notes and update your workflow to download from the new location

**Comment by yossygit** [comment]
@mprins  Should I use the extract from option in Jenkins plugin and specify this URL https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip?

I haven't seen anything else related...

**Comment by jeremylong** [comment]
Consider opening a ticket on the Jenkins owasp-dependency-check board: https://plugins.jenkins.io/dependency-check-jenkins-plugin/#issues

**Comment by wwuck** [comment]
This should be fixed in Jenkins now?

https://github.com/jenkins-infra/crawler/pull/101

**Comment by wwuck** [comment]
@jeremylong ref: https://github.com/jenkins-infra/crawler/pull/102#discussion_r629346715 considering that versions prior 6.1.6 are no longer supported and that bintray data will be deleted in the next few weeks, are there any plans to migrate the older release files from bintray to GitHub?

**Comment by jeremylong** [comment]
@wwuck - no there are no plans to migrate any old version to github. In fact, 6.1.6 is the only currently supported version of dependency-check.
