### ISSUE TITLE
mysql-connector-java-5.1.49-bin.jar causes exception in 6.2.0

### ISSUE THREAD

**Issue by MichaelGissingNC** [dependency-check/DependencyCheck#3413]
**Describe the bug**

An Exception is thrown related to the CPE analyzer when analyzing a directory with `mysql-connector-java-5.1.49-bin.jar` in it

I suspect it's because the CPE contains a slash `/`

```
[WARN] An error occurred querying the CPE data. See the log for more details.
[INFO] Unable to parse: product:(driver mysql_connector\/j^2 mysql_connector_j^2 mysql_connector/j^2 jdbc^2 mysql mysql_connectors^2) AND vendor:(oracle^2 jdbc^2 mysql^2 sun)
org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'product:(driver mysql_connector\/j^2 mysql_connector_j^2 mysql_connector/j^2 jdbc^2 mysql mysql_connectors^2) AND vendor:(oracle^2 jdbc^2 mysql^2 sun)': Lexical error at line 1, column 151.  Encountered: <EOF> after : "/j^2 jdbc^2 mysql mysql_connectors^2) AND vendor:(oracle^2 jdbc^2 mysql^2 sun)"
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.parseQuery(AbstractMemoryIndex.java:277)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:446)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:280)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:785)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 151.  Encountered: <EOF> after : "/j^2 jdbc^2 mysql mysql_connectors^2) AND vendor:(oracle^2 jdbc^2 mysql^2 sun)"
	at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1119)
	at org.apache.lucene.queryparser.classic.QueryParser.getToken(QueryParser.java:854)
	at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_3(QueryParser.java:668)
	at org.apache.lucene.queryparser.classic.QueryParser.jj_3_2(QueryParser.java:697)
	at org.apache.lucene.queryparser.classic.QueryParser.jj_2_2(QueryParser.java:653)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:281)
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
	... 11 common frames omitted
```

**Version of dependency-check used**

* Problem is **present** in the docker image `owasp/dependency-check:6.2.0`
* Problem is **not present** in the docker image `owasp/dependency-check:6.1.6`

**Log file**

https://gist.github.com/MichaelGissingNC/98549876b72b19b03adf47485a7006b5

**To Reproduce**

1. download `mysql-connector-java-5.1.49-bin.jar` https://mvnrepository.com/artifact/mysql/mysql-connector-java/5.1.49
2. scan current directory containing the file

**Expected behavior**

No exception

**Comment by alerat** [comment]
same as #3410 ?

**Comment by MichaelGissingNC** [comment]
@alerat looks like I'm really bad a searching issues today. Seems to be the same, yes. I just don't know how I missed it :disappointed:
