### ISSUE TITLE
dependencyCheckAnalyze Errors in gitlab-ci on Kotlin 1.4 

### ISSUE THREAD

**Issue by BrandonYates** [dependency-check/DependencyCheck#3417]
I am attempting to run the dependencyCheckAnalyze task in my Android project. 

I am running it on the following image.

`image: androidsdk/android-28:latest`

with the following configuration

Library CVE Checks:
  stage: cve
  script:
    \- ./gradlew --no-daemon dependencyCheckAnalyze --info
  when: manual

The task runs well in an Ubuntu linux terminal but when I run the above as part of the CI I get the following obscure error.

Analysis Started

An unexpected error occurred during analysis of '/builds/app/android/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.0/e5f0d669a77787ccbccd49c71b57bfd7b35faec4/kotlin-compiler-embeddable-1.4.0.jar' (Archive Analyzer): Malformed input or input contains unmappable characters: javaslang/?.class

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: javaslang/?.class
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:580)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:446)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:286)
	at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:268)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

\> Task :dependencyCheckAnalyze

My application is currently running Kotlin version 1.3.72 so Kotlin 1.4 must be a transitive dependency.

Is there a way to address this error through suppression or exclusion?

**Comment by mprins** [comment]
seems a duplicate of #1742

**Comment by BrandonYates** [comment]
I closed my particular issue by setting the LC_ALL environment variable. here is the new stage

Library CVE checks:
  stage: cve
  before_script:
    \- export LC_ALL=C.UTF-8
  script:
    \- ./gradlew --no-daemon dependencyCheckAnalyze --info
