### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by christophweser** [dependency-check/DependencyCheck#3499]
Hello,

I'm using this great peace of software as a Jenkins plugin.
Neither if I use Dependency Check 6.1.6 or 6.2.2 the error is the same.
I'm posting it here cause I guess it has nothing to do with Jenkins integration as the error persists when executing command via command line.

It has worked till yesterday and then out of a sudden this error arises.

Jenkins is running on Java 8, (Zulu 292, which is latest available. Before it was Build 252 but updating hasn't changed anything.)

I minimized the problem so I even see it when just updating the database with command line arguments: --updateonly --data d:\OWASP_Database

Stacktrace I see is:

FATAL: Failed to install https://github.com/jeremylong/DependencyCheck/releases/download/v6.2.2/dependency-check-6.2.2-release.zip to D:\Jenkins\tools\org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation\OWASP_6.2.2
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
Caused: sun.security.validator.ValidatorException: PKIX path building failed
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
Caused: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:348)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:286)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:156)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1409)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1315)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:439)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:410)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2739)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:974)
Caused: java.io.IOException: Failed to install https://github.com/jeremylong/DependencyCheck/releases/download/v6.2.2/dependency-check-6.2.2-release.zip to D:\Jenkins\tools\org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation\OWASP_6.2.2
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:1035)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:948)
	at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:78)
	at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.performInstallation(DependencyCheckInstaller.java:42)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:70)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:222)
	at org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation.forNode(DependencyCheckInstallation.java:66)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckToolBuilder.perform(DependencyCheckToolBuilder.java:139)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:21)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:808)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:516)
	at hudson.model.Run.execute(Run.java:1911)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
	
Any ideas for me? HIghly appreciated!

Chris

**Comment by mprins** [comment]
> Caused: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

fix your java setup; it doesn't know how to handle the certificate that Github uses for TLS/https

**Comment by christophweser** [comment]
Do you have an idea why it worked well for years and since yesterday not? 
(So I guess the java setup is not that wrong or do I don't get the point?)

**Comment by aikebah** [comment]
Gut feel: you have a re-encrypting proxy in between your Jenkins and the internet and your proxy's internal CA signing-certificate (expired and) got replaced. If so, the old signing-certificate of the proxy-CA was likely placed in your JVMs truststore, but the new one obviously isn't.

**Comment by jeremylong** [comment]
Depending on the exact cause of the error - this could be resolved with 6.4.1. Alternatively, if you are still seeing this issue please see https://github.com/jeremylong/DependencyCheck/issues/728#issuecomment-301240883
