### ISSUE TITLE
BaseDependencyCheckMojoTest errors with StringIndexOutOfBoundsException when running with a JVM > 1.8

### ISSUE THREAD

**Issue by aikebah** [dependency-check/DependencyCheck#3541]
**Describe the bug**
When running on a modern (>1.8) JVM version the test in BaseDependencyCheckMojoTest runs into a StringIndexOutOfBounds exception as Java changed version strategy to use a basic major version.

**Version of dependency-check used**
The problem occurs building the current main branch (version 6.2.3-SNAPSHOT)

**Log file**
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.108 s <<< FAILURE! - in org.owasp.dependencycheck.maven.BaseDependencyCheckMojoTest
[ERROR] testScanArtifacts(org.owasp.dependencycheck.maven.BaseDependencyCheckMojoTest)  Time elapsed: 0.894 s  <<< ERROR!
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojoTest.canRun(BaseDependencyCheckMojoTest.java:67)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojoTest.testScanArtifacts(BaseDependencyCheckMojoTest.java:101)
```

**To Reproduce**
1. Clone the repository
2. Run a full release-testing build `mvn -s settings.xml package verify -DreleaseTesting`
3. See error

**Expected behavior**
A successful build, where BaseDependencyCheckMojoTest is skipped as per the javadoc comment on the canRun method

**Additional context**
Build attempted with AdoptOpenJDK 15 as the active java version
```
aikebah@abu DependencyCheck % mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/local/share/java/maven3
Java version: 15, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by aikebah** [comment]
For reference the JEP that contains the java version scheme changes: http://openjdk.java.net/jeps/223

**Comment by aikebah** [comment]
In addition to the above error in our project there is also an issue in the integration tests (846-site-plugin) related to java version parsing

```
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.6:site (default-site) on project test-site-plugin: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.6:site failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-site-plugin:3.6:site: java.lang.ExceptionInInitializerError: null
...
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
    at java.lang.String.checkBoundsBeginEnd (String.java:3734)
    at java.lang.String.substring (String.java:1903)
    at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat (SystemUtils.java:1133)
    at org.apache.commons.lang.SystemUtils.<clinit> (SystemUtils.java:818)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.generateDocument (DefaultSiteRenderer.java:732)
    at org.apache.maven.plugins.site.render.CategorySummaryDocumentRenderer.renderDocument (CategorySummaryDocumentRenderer.java:175)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:337)
    at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:178)
    at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:132)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

```
