### ISSUE TITLE
dependency-check-purge ANT task doesn't seem to purge anything/everything?

### ISSUE THREAD

**Issue by jbeckers** [dependency-check/DependencyCheck#3568]
We're running dependency-check-ant on teamcity. I'm trying to upgrade from 5.3.2 to 6.2.2.

I read https://github.com/jeremylong/DependencyCheck#600-upgrade-notice so I added a dependency-check-purge ant target to our build scripts and ran this on all build agents.

Here's the ant debug output of the purge run:

```
[12:56:21] :		 [dependency-check-purge] owasp:dependency-check-purge
[12:56:21] :			 [owasp:dependency-check-purge] Finding class org.slf4j.impl.StaticLoggerBinder
[12:56:21] :			 [owasp:dependency-check-purge] Loaded from H:\System9\ivy-cache\org.owasp\dependency-check\jars\dependency-check-ant-6.2.2.jar org/slf4j/impl/StaticLoggerBinder.class

(...)

[12:56:21] :			 [owasp:dependency-check-purge] ResourceStream for dependencycheck.properties loaded from ant loader
[12:56:21] :			 [owasp:dependency-check-purge] Class java.lang.invoke.LambdaMetafactory loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Class java.util.function.Predicate loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Class java.util.function.Function loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Class java.util.stream.Stream loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Class java.util.stream.Collectors loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Class java.io.PrintWriter loaded from parent loader (parentFirst)
[12:56:21] :			 [owasp:dependency-check-purge] Properties loaded:

analyzer.cocoapods.enabled='true'
proxy.disableSchemas='true'
cve.url.modified.validfordays='7'
cve.url.base='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz'
analyzer.dependencybundling.enabled='true'
cve.url.original='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
odc.ecosystem.maxquerylimit.native='1000'
data.connection_string='jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;'
archive.scan.depth='3'
analyzer.cmake.enabled='true'
analyzer.pipfile.enabled='true'
odc.application.name='Dependency-Check Core'
analyzer.retirejs.repo.validforhours='24'
analyzer.node.package.enabled='true'
analyzer.pe.enabled='true'
analyzer.central.url='https://search.maven.org/solrsearch/select'
downloader.quick.query.timestamp='true'
analyzer.retirejs.repo.js.url='https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json'
analyzer.archive.enabled='true'
cpe.url='https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'
analyzer.ossindex.url='https://ossindex.sonatype.org'
analyzer.nvdcve.enabled='true'
analyzer.jar.enabled='true'
analyzer.cpe.enabled='true'
data.writelock.shutdownhook='org.owasp.dependencycheck.utils.WriteLockCleanupHook'
analyzer.central.query='%s?q=1:%s&wt=xml'
analyzer.bundle.audit.enabled='true'
analyzer.node.audit.use.cache='true'
analyzer.dependencymerging.enabled='true'
odc.settings.mask='.*password.*,.*token.*'
cpe.validfordays='30'
junit.fail.on.cvss='0'
central.content.url='https://search.maven.org/remotecontent?filepath='
analyzer.node.audit.url='https://registry.npmjs.org/-/npm/v1/security/audits'
odc.application.version='6.2.2'
analyzer.msbuildproject.enabled='true'
data.user='dcuser'
engine.version.url='https://jeremylong.github.io/DependencyCheck/current.txt'
analyzer.autoconf.enabled='true'
odc.autoupdate='true'
analyzer.cpesuppression.enabled='true'
analyzer.retirejs.enabled='true'
cve.check.validforhours='4'
analyzer.versionfilter.enabled='true'
analyzer.assembly.enabled='true'
cve.cpe.startswith.filter='cpe:2.3:a:'
analyzer.golang.dep.enabled='true'
odc.analysis.timeout='180'
analyzer.nexus.url='https://repository.sonatype.org/service/local/'
analyzer.hint.enabled='true'
analyzer.retired.enabled='false'
database.batchinsert.enabled='true'
analyzer.openssl.enabled='true'
analyzer.swift.package.manager.enabled='true'
analyzer.nuspec.enabled='true'
analyzer.central.retry.count='7'
analyzer.central.use.cache='true'
updater.nvdcve.enabled='true'
analyzer.mix.audit.enabled='true'
max.download.threads='2'
analyzer.central.enabled='true'
analyzer.python.distribution.enabled='true'
analyzer.nexus.enabled='false'
odc.reports.pretty.print='false'
analyzer.artifactory.enabled='false'
analyzer.retirejs.filternonvulnerable='false'
analyzer.ossindex.enabled='true'
analyzer.central.parallel.analysis='false'
analyzer.nexus.proxy='true'
cve.startyear='2002'
odc.ecosystem.maxquerylimit.default='100'
data.file_name='odc.mv.db'
nvd.newyear.grace.period='10'
downloader.tls.protocols='TLSv1.1,TLSv1.2,TLSv1.3'
analyzer.ruby.gemspec.enabled='true'
analyzer.composer.lock.enabled='true'
data.version='5.1'
analyzer.vulnerabilitysuppression.enabled='true'
data.directory='[JAR]/data'
analyzer.experimental.enabled='false'
analyzer.golang.mod.enabled='true'
analyzer.filename.enabled='true'
analyzer.ossindex.use.cache='true'
analyzer.python.package.enabled='true'
updater.versioncheck.enabled='true'
ecosystem.skip.cpeanalyzer='npm'
analyzer.pip.enabled='true'
analyzer.falsepositive.enabled='true'
analyzer.node.audit.enabled='true'
analyzer.yarn.audit.enabled='true'
analyzer.npm.cpe.enabled='true'
data.driver_name='org.h2.Driver'
database.batchinsert.maxsize='1000'
data.password='********'
analyzer.nugetconf.enabled='true'
cve.url.modified='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
[12:56:21] :			 [owasp:dependency-check-purge] ResourceStream for task.properties loaded from ant loader
[12:56:21] :			 [owasp:dependency-check-purge] Properties updated via merge:

analyzer.cocoapods.enabled='true'
proxy.disableSchemas='true'
cve.url.modified.validfordays='7'
cve.url.base='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz'
analyzer.dependencybundling.enabled='true'
cve.url.original='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
odc.ecosystem.maxquerylimit.native='1000'
data.connection_string='jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;'
archive.scan.depth='3'
analyzer.cmake.enabled='true'
analyzer.pipfile.enabled='true'
odc.application.name='Dependency-Check Core'
analyzer.retirejs.repo.validforhours='24'
analyzer.node.package.enabled='true'
analyzer.pe.enabled='true'
analyzer.central.url='https://search.maven.org/solrsearch/select'
downloader.quick.query.timestamp='true'
analyzer.retirejs.repo.js.url='https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json'
analyzer.archive.enabled='true'
cpe.url='https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'
analyzer.ossindex.url='https://ossindex.sonatype.org'
analyzer.nvdcve.enabled='true'
analyzer.jar.enabled='true'
analyzer.cpe.enabled='true'
data.writelock.shutdownhook='org.owasp.dependencycheck.utils.WriteLockCleanupHook'
analyzer.central.query='%s?q=1:%s&wt=xml'
analyzer.bundle.audit.enabled='true'
analyzer.node.audit.use.cache='true'
analyzer.dependencymerging.enabled='true'
odc.settings.mask='.*password.*,.*token.*'
cpe.validfordays='30'
junit.fail.on.cvss='0'
central.content.url='https://search.maven.org/remotecontent?filepath='
analyzer.node.audit.url='https://registry.npmjs.org/-/npm/v1/security/audits'
odc.application.version='6.2.2'
analyzer.msbuildproject.enabled='true'
data.user='dcuser'
engine.version.url='https://jeremylong.github.io/DependencyCheck/current.txt'
analyzer.autoconf.enabled='true'
odc.autoupdate='true'
analyzer.cpesuppression.enabled='true'
analyzer.retirejs.enabled='true'
cve.check.validforhours='4'
analyzer.versionfilter.enabled='true'
analyzer.assembly.enabled='true'
cve.cpe.startswith.filter='cpe:2.3:a:'
analyzer.golang.dep.enabled='true'
odc.analysis.timeout='180'
analyzer.nexus.url='https://repository.sonatype.org/service/local/'
analyzer.hint.enabled='true'
analyzer.retired.enabled='false'
database.batchinsert.enabled='true'
analyzer.openssl.enabled='true'
analyzer.swift.package.manager.enabled='true'
analyzer.nuspec.enabled='true'
analyzer.central.retry.count='7'
analyzer.central.use.cache='true'
updater.nvdcve.enabled='true'
analyzer.mix.audit.enabled='true'
max.download.threads='2'
analyzer.central.enabled='true'
analyzer.python.distribution.enabled='true'
analyzer.nexus.enabled='false'
odc.reports.pretty.print='false'
analyzer.artifactory.enabled='false'
analyzer.retirejs.filternonvulnerable='false'
analyzer.ossindex.enabled='true'
analyzer.central.parallel.analysis='false'
analyzer.nexus.proxy='true'
cve.startyear='2002'
odc.ecosystem.maxquerylimit.default='100'
data.file_name='odc.mv.db'
nvd.newyear.grace.period='10'
downloader.tls.protocols='TLSv1.1,TLSv1.2,TLSv1.3'
analyzer.ruby.gemspec.enabled='true'
analyzer.composer.lock.enabled='true'
data.version='5.1'
analyzer.vulnerabilitysuppression.enabled='true'
data.directory='data/5.0'
analyzer.experimental.enabled='false'
analyzer.golang.mod.enabled='true'
analyzer.filename.enabled='true'
analyzer.ossindex.use.cache='true'
analyzer.python.package.enabled='true'
updater.versioncheck.enabled='true'
ecosystem.skip.cpeanalyzer='npm'
analyzer.pip.enabled='true'
analyzer.falsepositive.enabled='true'
analyzer.node.audit.enabled='true'
analyzer.yarn.audit.enabled='true'
analyzer.npm.cpe.enabled='true'
data.driver_name='org.h2.Driver'
database.batchinsert.maxsize='1000'
data.password='********'
analyzer.nugetconf.enabled='true'
cve.url.modified='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
[12:56:21] :			 [owasp:dependency-check-purge] Finding class org.slf4j.helpers.MessageFormatter
[12:56:21] :			 [owasp:dependency-check-purge] Loaded from H:\System9\ivy-cache\org.slf4j\slf4j\jars\slf4j-api-1.7.5.jar org/slf4j/helpers/MessageFormatter.class
[12:56:21] :			 [owasp:dependency-check-purge] Class org.slf4j.helpers.MessageFormatter loaded from ant loader (parentFirst)

(...)

[12:56:21] :			 [owasp:dependency-check-purge] Cache directory purged
[12:56:21] :			 [owasp:dependency-check-purge] Settings.getDataFile() - file: 'C:\uz\Settings\owasp-database'
[12:56:21] :			 [owasp:dependency-check-purge] Finding class org.apache.commons.jcs.JCS
[12:56:21] :			 [owasp:dependency-check-purge] Loaded from H:\System9\ivy-cache\org.apache\commons-jcs\jars\commons-jcs-core-2.2.1.jar org/apache/commons/jcs/JCS.class
[12:56:21] :			 [owasp:dependency-check-purge] Class org.apache.commons.jcs.JCS loaded from ant loader (parentFirst)
[12:56:21] :	 [Step 1/1] Process exited with code 0
```

As you can see, we're using a custom dataDirectory="C:\uz\Settings\owasp-database"

Afterwards, dependency-check-update fails:

```
[12:59:01]E:		 [dependency-check] owasp:dependency-check-update (1s)
[12:59:01] :			 [owasp:dependency-check-update] Finding class org.slf4j.impl.StaticLoggerBinder
[12:59:01] :			 [owasp:dependency-check-update] Loaded from H:\System9\ivy-cache\org.owasp\dependency-check\jars\dependency-check-ant-6.2.2.jar org/slf4j/impl/StaticLoggerBinder.class

(...)

[12:59:01] :			 [owasp:dependency-check-update] ResourceStream for dependencycheck.properties loaded from ant loader
[12:59:01] :			 [owasp:dependency-check-update] Class java.lang.invoke.LambdaMetafactory loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Class java.util.function.Predicate loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Class java.util.function.Function loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Class java.util.stream.Stream loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Class java.util.stream.Collectors loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Class java.io.PrintWriter loaded from parent loader (parentFirst)
[12:59:01] :			 [owasp:dependency-check-update] Properties loaded:

analyzer.cocoapods.enabled='true'
proxy.disableSchemas='true'
cve.url.modified.validfordays='7'
cve.url.base='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz'
analyzer.dependencybundling.enabled='true'
cve.url.original='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
odc.ecosystem.maxquerylimit.native='1000'
data.connection_string='jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;'
archive.scan.depth='3'
analyzer.cmake.enabled='true'
analyzer.pipfile.enabled='true'
odc.application.name='Dependency-Check Core'
analyzer.retirejs.repo.validforhours='24'
analyzer.node.package.enabled='true'
analyzer.pe.enabled='true'
analyzer.central.url='https://search.maven.org/solrsearch/select'
downloader.quick.query.timestamp='true'
analyzer.retirejs.repo.js.url='https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json'
analyzer.archive.enabled='true'
cpe.url='https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'
analyzer.ossindex.url='https://ossindex.sonatype.org'
analyzer.nvdcve.enabled='true'
analyzer.jar.enabled='true'
analyzer.cpe.enabled='true'
data.writelock.shutdownhook='org.owasp.dependencycheck.utils.WriteLockCleanupHook'
analyzer.central.query='%s?q=1:%s&wt=xml'
analyzer.bundle.audit.enabled='true'
analyzer.node.audit.use.cache='true'
analyzer.dependencymerging.enabled='true'
odc.settings.mask='.*password.*,.*token.*'
cpe.validfordays='30'
junit.fail.on.cvss='0'
central.content.url='https://search.maven.org/remotecontent?filepath='
analyzer.node.audit.url='https://registry.npmjs.org/-/npm/v1/security/audits'
odc.application.version='6.2.2'
analyzer.msbuildproject.enabled='true'
data.user='dcuser'
engine.version.url='https://jeremylong.github.io/DependencyCheck/current.txt'
analyzer.autoconf.enabled='true'
odc.autoupdate='true'
analyzer.cpesuppression.enabled='true'
analyzer.retirejs.enabled='true'
cve.check.validforhours='4'
analyzer.versionfilter.enabled='true'
analyzer.assembly.enabled='true'
cve.cpe.startswith.filter='cpe:2.3:a:'
analyzer.golang.dep.enabled='true'
odc.analysis.timeout='180'
analyzer.nexus.url='https://repository.sonatype.org/service/local/'
analyzer.hint.enabled='true'
analyzer.retired.enabled='false'
database.batchinsert.enabled='true'
analyzer.openssl.enabled='true'
analyzer.swift.package.manager.enabled='true'
analyzer.nuspec.enabled='true'
analyzer.central.retry.count='7'
analyzer.central.use.cache='true'
updater.nvdcve.enabled='true'
analyzer.mix.audit.enabled='true'
max.download.threads='2'
analyzer.central.enabled='true'
analyzer.python.distribution.enabled='true'
analyzer.nexus.enabled='false'
odc.reports.pretty.print='false'
analyzer.artifactory.enabled='false'
analyzer.retirejs.filternonvulnerable='false'
analyzer.ossindex.enabled='true'
analyzer.central.parallel.analysis='false'
analyzer.nexus.proxy='true'
cve.startyear='2002'
odc.ecosystem.maxquerylimit.default='100'
data.file_name='odc.mv.db'
nvd.newyear.grace.period='10'
downloader.tls.protocols='TLSv1.1,TLSv1.2,TLSv1.3'
analyzer.ruby.gemspec.enabled='true'
analyzer.composer.lock.enabled='true'
data.version='5.1'
analyzer.vulnerabilitysuppression.enabled='true'
data.directory='[JAR]/data'
analyzer.experimental.enabled='false'
analyzer.golang.mod.enabled='true'
analyzer.filename.enabled='true'
analyzer.ossindex.use.cache='true'
analyzer.python.package.enabled='true'
updater.versioncheck.enabled='true'
ecosystem.skip.cpeanalyzer='npm'
analyzer.pip.enabled='true'
analyzer.falsepositive.enabled='true'
analyzer.node.audit.enabled='true'
analyzer.yarn.audit.enabled='true'
analyzer.npm.cpe.enabled='true'
data.driver_name='org.h2.Driver'
database.batchinsert.maxsize='1000'
data.password='********'
analyzer.nugetconf.enabled='true'
cve.url.modified='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
[12:59:01] :			 [owasp:dependency-check-update] ResourceStream for task.properties loaded from ant loader
[12:59:01] :			 [owasp:dependency-check-update] Properties updated via merge:

analyzer.cocoapods.enabled='true'
proxy.disableSchemas='true'
cve.url.modified.validfordays='7'
cve.url.base='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz'
analyzer.dependencybundling.enabled='true'
cve.url.original='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
odc.ecosystem.maxquerylimit.native='1000'
data.connection_string='jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;'
archive.scan.depth='3'
analyzer.cmake.enabled='true'
analyzer.pipfile.enabled='true'
odc.application.name='Dependency-Check Core'
analyzer.retirejs.repo.validforhours='24'
analyzer.node.package.enabled='true'
analyzer.pe.enabled='true'
analyzer.central.url='https://search.maven.org/solrsearch/select'
downloader.quick.query.timestamp='true'
analyzer.retirejs.repo.js.url='https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json'
analyzer.archive.enabled='true'
cpe.url='https://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'
analyzer.ossindex.url='https://ossindex.sonatype.org'
analyzer.nvdcve.enabled='true'
analyzer.jar.enabled='true'
analyzer.cpe.enabled='true'
data.writelock.shutdownhook='org.owasp.dependencycheck.utils.WriteLockCleanupHook'
analyzer.central.query='%s?q=1:%s&wt=xml'
analyzer.bundle.audit.enabled='true'
analyzer.node.audit.use.cache='true'
analyzer.dependencymerging.enabled='true'
odc.settings.mask='.*password.*,.*token.*'
cpe.validfordays='30'
junit.fail.on.cvss='0'
central.content.url='https://search.maven.org/remotecontent?filepath='
analyzer.node.audit.url='https://registry.npmjs.org/-/npm/v1/security/audits'
odc.application.version='6.2.2'
analyzer.msbuildproject.enabled='true'
data.user='dcuser'
engine.version.url='https://jeremylong.github.io/DependencyCheck/current.txt'
analyzer.autoconf.enabled='true'
odc.autoupdate='true'
analyzer.cpesuppression.enabled='true'
analyzer.retirejs.enabled='true'
cve.check.validforhours='4'
analyzer.versionfilter.enabled='true'
analyzer.assembly.enabled='true'
cve.cpe.startswith.filter='cpe:2.3:a:'
analyzer.golang.dep.enabled='true'
odc.analysis.timeout='180'
analyzer.nexus.url='https://repository.sonatype.org/service/local/'
analyzer.hint.enabled='true'
analyzer.retired.enabled='false'
database.batchinsert.enabled='true'
analyzer.openssl.enabled='true'
analyzer.swift.package.manager.enabled='true'
analyzer.nuspec.enabled='true'
analyzer.central.retry.count='7'
analyzer.central.use.cache='true'
updater.nvdcve.enabled='true'
analyzer.mix.audit.enabled='true'
max.download.threads='2'
analyzer.central.enabled='true'
analyzer.python.distribution.enabled='true'
analyzer.nexus.enabled='false'
odc.reports.pretty.print='false'
analyzer.artifactory.enabled='false'
analyzer.retirejs.filternonvulnerable='false'
analyzer.ossindex.enabled='true'
analyzer.central.parallel.analysis='false'
analyzer.nexus.proxy='true'
cve.startyear='2002'
odc.ecosystem.maxquerylimit.default='100'
data.file_name='odc.mv.db'
nvd.newyear.grace.period='10'
downloader.tls.protocols='TLSv1.1,TLSv1.2,TLSv1.3'
analyzer.ruby.gemspec.enabled='true'
analyzer.composer.lock.enabled='true'
data.version='5.1'
analyzer.vulnerabilitysuppression.enabled='true'
data.directory='data/5.0'
analyzer.experimental.enabled='false'
analyzer.golang.mod.enabled='true'
analyzer.filename.enabled='true'
analyzer.ossindex.use.cache='true'
analyzer.python.package.enabled='true'
updater.versioncheck.enabled='true'
ecosystem.skip.cpeanalyzer='npm'
analyzer.pip.enabled='true'
analyzer.falsepositive.enabled='true'
analyzer.node.audit.enabled='true'
analyzer.yarn.audit.enabled='true'
analyzer.npm.cpe.enabled='true'
data.driver_name='org.h2.Driver'
database.batchinsert.maxsize='1000'
data.password='********'
analyzer.nugetconf.enabled='true'
cve.url.modified='https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
[12:59:01] :			 [owasp:dependency-check-update] Finding class org.slf4j.helpers.MessageFormatter
[12:59:01] :			 [owasp:dependency-check-update] Loaded from H:\System9\ivy-cache\org.slf4j\slf4j\jars\slf4j-api-1.7.5.jar org/slf4j/helpers/MessageFormatter.class
[12:59:01] :			 [owasp:dependency-check-update] Class org.slf4j.helpers.MessageFormatter loaded from ant loader (parentFirst)

(...)

[12:59:02] :			 [owasp:dependency-check-update] DC Schema: 5.1
[12:59:02] :			 [owasp:dependency-check-update] DB Schema: 4.2
[12:59:02] :			 [owasp:dependency-check-update] Updating database structure
[12:59:02] :			 [owasp:dependency-check-update] Couldn't load Resource data/upgrade_4.2.sql
[12:59:02] :			 [owasp:dependency-check-update] Finding class org.owasp.dependencycheck.utils.DBUtils
[12:59:02] :			 [owasp:dependency-check-update] Loaded from H:\System9\ivy-cache\org.owasp\dependency-check\jars\dependency-check-core-6.2.2.jar org/owasp/dependencycheck/utils/DBUtils.class
[12:59:02] :			 [owasp:dependency-check-update] Class org.owasp.dependencycheck.utils.DBUtils loaded from ant loader (parentFirst)
[12:59:02] :			 [owasp:dependency-check-update] 
[12:59:02]E:			 [owasp:dependency-check-update] org.owasp.dependencycheck.data.nvdcve.DatabaseException: unable to upgrade the database schema - please run the dependency-check purge command to remove the existing database
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.updateSchema(DatabaseManager.java:422)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.ensureSchemaVersion(DatabaseManager.java:491)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:214)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.<init>(DatabaseManager.java:123)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:238)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:987)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:863)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:846)
	at org.owasp.dependencycheck.taskdefs.Update.execute(Update.java:372)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:352)
	at org.apache.tools.ant.Target.execute(Target.java:437)
	at org.apache.tools.ant.Target.performTasks(Target.java:458)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1406)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1377)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1261)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

[12:59:03]E:	 [Step 1/1] Error message is logged

(...)

[12:59:03]E:	 [Step 1/1] Process exited with code 1 (Step: Ant)
[12:59:03]E:	 [Step 1/1] Step Ant failed
```

When I revert to 5.3.2, dependency-check-update starts orking again.

Was (a part of) the database not purged correctly?
What is it that I'm missing here?

**Comment by jbeckers** [comment]
For reference, here's the ant targets:
```
    <target name="dependency-check-purge" depends="init,init-ivy" description="Dependency-Check purge">
        <ivy:cachepath organisation="org.owasp" module="dependency-check" revision="latest.integration" log="quiet"
                       inline="true" conf="default" pathid="dependency-checker.classpath" type="jar"/>
        <taskdef resource="dependency-check-taskdefs.properties"
                 uri="antlib:org.owasp" classpathref="dependency-checker.classpath"/>

        <owasp:dependency-check-purge dataDirectory="C:\uz\Settings\owasp-database"/>
    </target>

    <target name="dependency-check" depends="init,init-ivy">
        <ivy:cachepath organisation="org.owasp" module="dependency-check" revision="latest.integration" log="quiet"
                       inline="true" conf="default" pathid="dependency-checker.classpath" type="jar"/>
        <taskdef resource="dependency-check-taskdefs.properties"
                 uri="antlib:org.owasp" classpathref="dependency-checker.classpath"/>

        <owasp:dependency-check-update dataDirectory="C:\uz\Settings\owasp-database"/>
    </target>

```

**Comment by jbeckers** [comment]
I don't have full access to the build agents, but a coworker took this screenshot:
![afbeelding](https://user-images.githubusercontent.com/379626/128508951-4cf595dd-ce86-4f16-b492-3307f3a7366e.png)

The cache and oss_cache folders of our data directory were removed by the purge, but the files are intact.

The timestamp on oc.mv.db matches the last successfull dependency-check ant target run at 13:59.
The purge was at 14:11

Is this expected behaviour?

**Comment by jbeckers** [comment]
We moved the entire dataDirectory out of the way, and ran a dependency-check ant target.

This resulted in 
```
(...)
[owasp:dependency-check-update] java.lang.IllegalArgumentException: resource data/initialize.sql not found.
(...)
```
but the run seems to be successful.
Subsequent runs seem to be successful as well.

No new dc.h2.db file was created, but the other caches are there.
