### ISSUE TITLE
Dependency check CLI is hanging during scan.

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#3585]
**Describe the bug**
Dependency check CLI is hanging during scan.

**Version of dependency-check used**
v6.2.2

**Log file**
Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.

   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

💖 Sponsor: https://github.com/sponsors/jeremylong

[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Central Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
---------------------Scan is hanged here----------------------

**To Reproduce**
1. Download OWASP Dependency-check CLI v6.2.2.
2. Run ./dependency-check.sh  --project test -n -o OUTPUT_FOLDER -f ALL  -s INPUT_FOLDER

**Expected behavior**
Run should be completed successfully.

**Comment by jeremylong** [comment]
Please provide the actual log file produced by adding the `--log odc.log` to the CLI. Also, please provide some more context about the actual arguments used, what was being scanned?  We can't fix things when a bug reports says "it's broken" and doesn't provide any real details.

**Comment by antonmos** [comment]
I also ran into this issue. I am using dependency-check via https://github.com/rm-hull/lein-nvd so it is not easy for me to get the log. 
That said, I was able to workaround by deleting `jsrepository.json.lock` and `odc.update.lock` from `.m2/repository/org/owasp/dependency-check-utils/6.2.2/data/`

I also noticed that there was `odc.trace.db` file with this content:
```
2021-09-01 10:06:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: This store is closed [1.4.199/4]"; SQL statement:
SELECT DISTINCT vendor, product, ecosystem FROM cpeEcosystemCache [50000-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.DbException.convert(DbException.java:347)
        at org.h2.command.Command.executeQuery(Command.java:219)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.loadCpeEcosystemCache(CveDB.java:800)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.updateOrInsertVulnerability(CveDB.java:850)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:776)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:97)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: This store is closed [1.4.199/4]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
        at org.h2.mvstore.MVStore.checkOpen(MVStore.java:2634)
        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1087)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1025)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
        at org.h2.mvstore.tx.TransactionMap$TMIterator.fetchNext(TransactionMap.java:711)
        at org.h2.mvstore.tx.TransactionMap$TMIterator.next(TransactionMap.java:752)
        at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(MVPrimaryIndex.java:474)
        at org.h2.index.IndexCursor.next(IndexCursor.java:291)
        at org.h2.table.TableFilter.next(TableFilter.java:506)
        at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882)
        at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
        at org.h2.result.LazyResult.next(LazyResult.java:60)
        at org.h2.command.dml.Select.queryFlat(Select.java:742)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)
        at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)
        at org.h2.command.dml.Query.query(Query.java:435)
        at org.h2.command.dml.Query.query(Query.java:397)
        at org.h2.command.CommandContainer.query(CommandContainer.java:145)
        at org.h2.command.Command.executeQuery(Command.java:202)
        ... 15 more

```

**Comment by Anshu2405** [comment]
Issue was resolved after removing data files.

**Comment by antonmos** [comment]
Can you please reopen the ticket? 
Ideally, his situation should be handled gracefully without having to manually clean up files.

**Comment by fmarot** [comment]
Hello, I'm facing the same recurring issue since a few weeks with lock file .m2/repository/org/owasp/dependency-check-utils/6.4.1/../../dependency-check-data/5.0/odc.update.lock which seems to be left behind previous executions and prevents the subsequent ones to proceed.
If I activate debug logs I see :

```
[DEBUG] Sleeping thread BuilderThread 3 (1c697bfb81da59d8b96708c458496108) for 10 seconds because an exclusive lock on the database could not be obtained (2021-11-30 11:09:31.034)
[DEBUG] Sleeping thread BuilderThread 1 (033603cc94f4c42ad14334647e5c985b) for 10 seconds because an exclusive lock on the database could not be obtained (2021-11-30 11:09:36.828)
[DEBUG] Sleeping thread BuilderThread 3 (1c697bfb81da59d8b96708c458496108) for 10 seconds because an exclusive lock on the database could not be obtained (2021-11-30 11:09:41.034)
[DEBUG] Sleeping thread BuilderThread 1 (033603cc94f4c42ad14334647e5c985b) for 10 seconds because an exclusive lock on the database could not be obtained (2021-11-30 11:09:46.829)
```
If anybody has some more info or workaround, I would gladly take it

**Comment by fmarot** [comment]
A few additional info: the hang/freeze seems not reproducible on windows but only on Linux. For now I reproduce it 100% of the time with my project when I delete the database instead of reusing an existing DB. And on my CI the .m2 folder is deleted every night so everyday the dependency-check freezes.
Each times the problem happens for "NVD CVE - 2017".

**Comment by sharedprophet** [comment]
`rm -rf ~/.gradle/dependency-check-data` did not help for me until I changed back to plugin version 7.4.4. That version is able to complete successfully on my Intel MacBook Pro.
