### ISSUE TITLE
I am using CLI to run dependency check, while running I am getting the following issue 

### ISSUE THREAD

**Issue by anilmukkamala** [dependency-check/DependencyCheck#3588]
Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:349)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:387)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:873)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:187)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:342)
        ... 8 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:182)
        ... 9 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Unknown Source)
        at sun.security.ssl.TransportContext.fatal(Unknown Source)
        at sun.security.ssl.TransportContext.fatal(Unknown Source)
        at sun.security.ssl.TransportContext.fatal(Unknown Source)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
        at sun.security.ssl.SSLHandshake.consume(Unknown Source)
        at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at sun.security.ssl.SSLTransport.decode(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
        ... 11 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 27 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 33 common frames omitted
[INFO] Skipping RetireJS update since last update was within 24 hours.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
[ERROR] No documents exist

**Comment by anilmukkamala** [comment]
@jeremylong , can you please let me know which command for a workaround. I tried this ----dependency-check.bat --project "qualification" --scan C:\Users\anil.mukkamala\Downloads\geo-qualification-1.0.10.jar --cveUrlModified=http://mirror-url/nist/nvdcve-1.1-modified.json.gz --cveUrlBase=http://mirror-url/nist/nvdcve-1.1-%d.json.gz------ Issue still persists

Thanks

**Comment by mprins** [comment]
duplicate of #3499 (and [other tickets](https://github.com/jeremylong/DependencyCheck/issues?q=is%3Aissue+SSLHandshakeException) )

your Java setup (or possibly network/proxy setup) is broken, nothing we can do about that

**Comment by anilmukkamala** [comment]
Thank you for your comment, able to resolve the issue.

**Comment by ekarudianto** [comment]
> Thank you for your comment, able to resolve the issue.

How are you able to solve it ? I faced the same issue with my machine when trying to run `dependencyCheckAnalyze` command while it is working for my colleagues

**Comment by aikebah** [comment]
@ekarudianto As it works for your colleagues my gut feel would be (assuming your company has a re-encrypting proxy in the path to internet for antivirus/malware scanning) that they have already imported the proxy CA certificate in their truststore (as per my remark on the quoted issue: https://github.com/jeremylong/DependencyCheck/issues/3499#issuecomment-893490943)

Another item to check would be if you use the same Java version, as java uses its own CA-trust and that trust gets updated periodically, so if your Java version is much older it might be that a regular CA signing certificate was not yet in the truststore.

**Comment by anilmukkamala** [comment]
> > Thank you for your comment, able to resolve the issue.
> 
> How are you able to solve it ? I faced the same issue with my machine when trying to run `dependencyCheckAnalyze` command while it is working for my colleagues

I had issues with Java setup, uninstalled and installed Java and added certs to keystore again.

**Comment by ekarudianto** [comment]
> > > Thank you for your comment, able to resolve the issue.
> > 
> > 
> > How are you able to solve it ? I faced the same issue with my machine when trying to run `dependencyCheckAnalyze` command while it is working for my colleagues
> 
> I had issues with Java setup, uninstalled and installed Java and added certs to keystore again.

And how did you add the certs to keystore again if I may ask ? Apologies for asking a lot of questions

**Comment by anilmukkamala** [comment]
> > > > Thank you for your comment, able to resolve the issue.
> > > 
> > > 
> > > How are you able to solve it ? I faced the same issue with my machine when trying to run `dependencyCheckAnalyze` command while it is working for my colleagues
> > 
> > 
> > I had issues with Java setup, uninstalled and installed Java and added certs to keystore again.
> 
> And how did you add the certs to keystore again if I may ask ? Apologies for asking a lot of questions

You need to be on this path in cli "**C:\Program Files\Java\jre1.8.0_301\bin**"  and you can use this command to import 
**" keytool -importcert -noprompt -trustcacerts –alias give your certificate name -file "path where it is stored" -keystore "C:\Program Files\Java\jre1.8.0_301\lib\security\cacerts" -storepass**

**Comment by ekarudianto** [comment]
It works now thanks !
