### ISSUE TITLE
Severity missing in csv report file (only CVSSv3_BaseSeverity is present)

### ISSUE THREAD

**Issue by aubertaa** [dependency-check/DependencyCheck#3617]
**Is your feature request related to a problem? Please describe.**

Using csv reports to graph things and expose data to stakeholders (through PowerBI for instance), i've noticed that there are a lot of "N/A" values for "CVSSv3_BaseSeverity" field (around 56% in my case). Checking in json report file, i can see than there are 2 different fields related to severity:
- CVSSv3_BaseSeverity
- **Severity**

And it would be really nice to have also this second field in csv report file.

**Describe the solution you'd like**

Adding the "Severity" field in CSV report file, filled the same way than in json report. Checking the code, it seems that updating the csvReport.vsl template would fit the need :

additional field : "Severity"
value for this field (based on how value is filled in json report : 
`#if($vuln.UnscoredSeverity)#if($vuln.unscoredSeverity.equals("0.0"))"Unknown"#else$enc.csv($vuln.unscoredSeverity)#end#elseif($vuln.cvssV3 && $vuln.cvssV3.baseSeverity)$enc.csv($vuln.cvssV3.baseSeverity)#elseif($vuln.cvssV2 && $vuln.cvssV2.severity)$severity($vuln.cvssV2.severity)#end`

**Additional context**
I tried to open PR for this but i didn't succeed building the project on my workstation (probably caused by a cache or something leading to error _DatabaseException: Database schema does not match this version of dep..._ and i didn't find any way to avoid this.

Thanks for your help on having this missing information in CSV report files, i would really appreciate it !
Regards,

**Comment by aikebah** [comment]
@aubertaa regarding the error you mention in building the project: Assuming that you, like most of us, work with the default h2 database you should be able to resolve the issue with a one-time purge of your current database (which would trigger redownloading all of the NIST NVD feeds to rebuild the database during build)

`mvn org.owasp:dependency-check-maven:6.0.0:purge` should do the trick and allow you to subsequently build the project on your workstation.

Root cause would then be that the current database in you maven local repository (under org/owasp/dependency-check-data) was still from a 5.x version of DependencyCheck. See the 6.0.0 upgrade notice in this project's readme.

**Comment by aubertaa** [comment]
Thanks for your help but even after purge action, i get this : 

> 
> [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.47 s <<< FAILURE! - in org.owasp.dependencycheck.analyzer.RetireJsAnalyzerFiltersTest
> [ERROR] testFilters(org.owasp.dependencycheck.analyzer.RetireJsAnalyzerFiltersTest)  Time elapsed: 1.47 s  <<< ERROR!
> org.owasp.dependencycheck.data.nvdcve.DatabaseException: Database schema does not match this version of dependency-check
>         at org.owasp.dependencycheck.analyzer.RetireJsAnalyzerFiltersTest.testFilters(RetireJsAnalyzerFiltersTest.java:49)
> Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: unable to upgrade the database schema - please run the dependency-check purge command to remove the existing database
>         at org.owasp.dependencycheck.analyzer.RetireJsAnalyzerFiltersTest.testFilters(RetireJsAnalyzerFiltersTest.java:49)

Any other way to clean this cache or DB version somewhere ? (i'm on windows)
Thanks

**Comment by aubertaa** [comment]
@aikebah I tried to dig more, here is what i have:
* i purged using mvn purge target
* i purged also running bat file with option '--purge'

Here is what i have in terms of version of DB when check is done. I can't find where this "4.2" comes :-(

![image](https://user-images.githubusercontent.com/14087776/131860658-f815b5e9-fb8c-469b-9220-a9317943fe96.png)

Thanks for your help !
