### ISSUE TITLE
6.3.1 is not available in homebrew

### ISSUE THREAD

**Issue by pvegh** [dependency-check/DependencyCheck#3649]
Please update it

**Comment by mprins** [comment]
Homebrew is not maintained here. Please contact the publisher of https://formulae.brew.sh/formula/dependency-check

**Comment by jeremylong** [comment]
I have been working on the update to the formula in homebrew - but due to the test cases making repeated calls to the NVD the tests are getting timed out, I believe, due to rate limiting. I hope to have a solution to this soon,

**Comment by pvegh** [comment]
Thanks @jeremylong!
Maybe in the same step you can also fix/improve #3650 (JDK 11 vs 16)

**Comment by orschaef** [comment]
6.3.1 seems to be released for homebrew. So is the following error related to rate limiting when using the brew version? We are getting this error for quite some time on our CI server and also locally on our machine. We first thought it may be fixed with the latest version - but still experiencing the same issue. When heading over to https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta in the browser everything seems to be fine.

```
[INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
                at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:349)
                at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:401)
                at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
                at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:873)
                at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
                at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
                at org.owasp.dependencycheck.App.runScan(App.java:254)
                at org.owasp.dependencycheck.App.run(App.java:186)
                at org.owasp.dependencycheck.App.main(App.java:81)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta; unable to connect.
                at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:187)
                at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:342)
                ... 8 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta; unable to connect.
                at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
                at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
                at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:182)
                ... 9 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect timed out
                at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
                at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
                at java.base/java.net.Socket.connect(Socket.java:633)
                at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
                at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
                at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
                at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
                at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
                at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
                at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
                at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
                at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
                ... 11 common frames omitted
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
[ERROR] No documents exist
```

**Comment by jstephancc** [comment]
Got the same error as @orschaef .

Locally on OSX using dependency-check installed by homebrew v6.3.1 (6.3.2 not available)

The same on docker 6.3.2.

```
[INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:349)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:401)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:873)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
        at org.owasp.dependencycheck.App.runScan(App.java:254)
        at org.owasp.dependencycheck.App.run(App.java:186)
        at org.owasp.dependencycheck.App.main(App.java:81)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta; unable to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:187)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:342)
        ... 8 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:182)
        ... 9 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
        ... 11 common frames omitted
[WARN] A new version of dependency-check is available. Consider updating to version 6.3.2.
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.meta
[ERROR] No documents exist

```

**Comment by orschaef** [comment]
Currently I don't get this error anymore with 6.4.1. Since originally this thread was for providing 6.3.1 in homebrew I guess it can be closed.
