### ISSUE TITLE
An error occurred on Archive Analyzer

### ISSUE THREAD

**Issue by j0ck67** [dependency-check/DependencyCheck#3720]
[INFO] Analysis Started
[WARN] An unexpected error occurred during analysis of 'E:\dependency-check\bin\file.zip' (Archive Analyzer): Illegal char <?> at index 8: etc/doc/????????????.xlsx

[ERROR]
java.nio.file.InvalidPathException: Illegal char <?> at index 8: etc/doc/????????????.xlsx
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractArchive(ArchiveAnalyzer.java:543)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractFiles(ArchiveAnalyzer.java:416)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.extractAndAnalyze(ArchiveAnalyzer.java:258)
        at org.owasp.dependencycheck.analyzer.ArchiveAnalyzer.analyzeDependency(ArchiveAnalyzer.java:240)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jeremylong** [comment]
What version of ODC are you using. Can you provide the zip file or one that exhibits this behavior?

**Comment by j0ck67** [comment]
> What version of ODC are you using. Can you provide the zip file or one that exhibits this behavior?

Dependency-Check Core version 5.2.4
[file.zip](https://github.com/jeremylong/DependencyCheck/files/7342479/file.zip)

**Comment by mprins** [comment]
> Dependency-Check Core version 5.2.4

 please try to reproduce with a current release

 `/sql/02-╕Ў╨╘╗п╜┼▒╛/`  are you sure that is a valid filename on your Windows platform?
