### ISSUE TITLE
Could not connect to Central search

### ISSUE THREAD

**Issue by 20171003234** [dependency-check/DependencyCheck#3785]
centos7$ dependency-check --disableOssIndexCache --disableAssembly --cveUrlBase http://127.0.0.1:8888/nvdcve-1.1-2021.json.gz --cveUrlModified http://127.0.0.1:8888/nvdcve-1.1-2021.json.gz --retireJsUrl http://127.0.0.1:8888/jsrepository.json -s /app//lib -o /app//lib

[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:141)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:169)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted
	Suppressed: java.net.SocketException: 断开的管道 (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:401)
		... 20 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 17 common frames omitted

[Q]:Every time I rebuild nist-data-mirror-master, it connects to the central analyzer successfully.  Is there any solution to this situation? My server can't connect to https://search.maven.org/
Any Help Appreciated :）

**Comment by VersionThis** [comment]
Came here looking for this, as we encountered the same issue last night - watching.

**Comment by aikebah** [comment]
You need to disable the centralAnalyzer 

[--disableCentral](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)

If you happen to have a Nexus proxy locally 'on premise' reachable by your server you may want to enable that one instead if you happen to have artifacts from Maven repositories in use.

**Comment by 20171003234** [comment]
> You need to disable the centralAnalyzer
> 
> [--disableCentral](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)
> 
> If you happen to have a Nexus proxy locally 'on premise' reachable by your server you may want to enable that one instead if you happen to have artifacts from Maven repositories in use.

Thanks for your help!

**Comment by 20171003234** [comment]
你好，你的邮件我已经收到，如有急事可以打电话给我：15099953695
