### ISSUE TITLE
OWASP Dependency Check fails while accessing not found URL from Azure CI

### ISSUE THREAD

**Issue by milyas-salik** [dependency-check/DependencyCheck#3798]
Hi,

The plugin in Azure CI throws the below exception. It seems the dependency-check.bat file it's trying to access the URL (**https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json;**) which is not found.

Please do the need full urgently as it's failing many Azure CI Builds suddenly in Production.

Logs:
`
[ERROR] Failed to initialize the RetireJS repo
org.owasp.dependencycheck.data.update.exception.UpdateException: Failed to initialize the RetireJS repo
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:140)
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.update(RetireJSDataSource.java:89)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:875)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:680)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
	at org.owasp.dependencycheck.App.runScan(App.java:256)
	at org.owasp.dependencycheck.App.run(App.java:188)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to copy 'https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json' to 'D:\Agents\Tst\MyAgent\_work\_tool\owasp-dependency-check\6.4.0\x64\dependency-check\data\jsrepository.json'; Error downloading file https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json; unable to connect.
	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:135)
	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:74)
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:138)
	... 7 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json; unable to connect.
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
	at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:130)
	... 9 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:163)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
	... 11 common frames omitted
[INFO] Begin database defrag
[INFO] End database defrag (2672 ms)
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Failed to initialize the RetireJS repo
[ERROR] No documents exist`

**Comment by mprins** [comment]
That URL works for me, in any case that URL is outside the control of this project and not a bug

**Comment by nhumblot** [comment]
I suggest we add an error message providing the information it is not related to dependency-check but to a connection issue, like npm does it with `This is probably not a problem with npm`.

I'm volunteer to provide an update aiming this. @jeremylong  @aikebah :wave:, could you please assign me this issue if such change is ok for you?

**Comment by aikebah** [comment]
@milyas-salik The error (connection timeout) suggests as the most likely cause a firewall rule configured in your Azure CI envionment dropping outgoing traffic to the retirejs vulnerability list in github. Please consult with your Azure administrators (or disable the RetireJS analyzer on your scans) to resolve it.

**Comment by aikebah** [comment]
@nhumblot I think such a message could be beneficial yes. But would propose to do the change under a new feature-request issue rather than using this issue.

**Comment by jeremylong** [comment]
@nhumblot feel free to submit a PR!
