### ISSUE TITLE
different result before unzip and after

### ISSUE THREAD

**Issue by BodyCSoulN** [dependency-check/DependencyCheck#3850]
when i tried to detect a golang package, before i unzip it, there a some error of it:
```python
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[WARN] While analyzing `/test/gitlabhq__terraform-provider-gitlab__d979f03107ea4457230996c85d8fa1ba.zip/terraform-provider-gitlab-master/go.mod` `go` generated the following warnings:
go: updates to go.sum needed, disabled by -mod=readonly

[WARN] An error occurred while analyzing '/tmp/dctemp35c64d33-2b46-43c8-8a92-a6c6baf7ad18/check6969556760816251247tmp/1/terraform-provider-gitlab-master/go.mod' (Golang Mod Analyzer).
[INFO] Finished Golang Mod Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished NPM CPE Analyzer (2 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] Unable to determine Package-URL identifiers for 1 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (5 seconds)
[INFO] Writing report to: /test/../dependency-check-report.json
[ERROR] Error analyzing '/test/gitlabhq__terraform-provider-gitlab__d979f03107ea4457230996c85d8fa1ba.zip/terraform-provider-gitlab-master/go.mod'; Error parsing output from `go list -json -m all`
```
and the detected result is less than the unzipped one. 
there is no error when i unzipped it.
same situation happended when i detected a ruby package.
for ruby, the error before unzipped is:
```python
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Launching: [bundle-audit, version] from /tmp/dctemp3f4a786c-29ed-4ee4-b49e-af1ce7376b98
[WARN] Warnings from bundle-audit 
[INFO] Ruby Bundle Audit Analyzer is enabled and is using bundle-audit with version details: bundler-audit 0.9.0.1
. Note: It is necessary to manually run "bundle-audit update" occasionally to keep its database up to date.
[INFO] Disabled org.owasp.dependencycheck.analyzer.RubyBundlerAnalyzer to avoid noisy duplicate results.
[INFO] Disabled org.owasp.dependencycheck.analyzer.RubyGemspecAnalyzer to avoid noisy duplicate results.
[INFO] Launching: [bundle-audit, check, --verbose] from /tmp/dctemp3f4a786c-29ed-4ee4-b49e-af1ce7376b98/check11740117223523506881tmp/1/yaml_db-master
[WARN] Warnings from bundle-audit /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler.rb:289:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler.rb:285:in `root'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler.rb:309:in `app_cache'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:510:in `cache_path'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:24:in `initialize'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:90:in `new'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:90:in `from_lock'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/lockfile_parser.rb:120:in `parse_source'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/lockfile_parser.rb:76:in `block in initialize'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/lockfile_parser.rb:61:in `each'
        from /var/lib/gems/2.5.0/gems/bundler-2.2.33/lib/bundler/lockfile_parser.rb:61:in `initialize'
        from /var/lib/gems/2.5.0/gems/bundler-audit-0.9.0.1/lib/bundler/audit/scanner.rb:86:in `new'
        from /var/lib/gems/2.5.0/gems/bundler-audit-0.9.0.1/lib/bundler/audit/scanner.rb:86:in `initialize'
        from /var/lib/gems/2.5.0/gems/bundler-audit-0.9.0.1/lib/bundler/audit/cli.rb:70:in `new'
        from /var/lib/gems/2.5.0/gems/bundler-audit-0.9.0.1/lib/bundler/audit/cli.rb:70:in `check'
        from /var/lib/gems/2.5.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.5.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/2.5.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/2.5.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /var/lib/gems/2.5.0/gems/bundler-audit-0.9.0.1/bin/bundle-audit:10:in `<top (required)>'
        from /usr/local/bin/bundle-audit:23:in `load'
        from /usr/local/bin/bundle-audit:23:in `<main>'

[INFO] Finished Ruby Bundle Audit Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Python Distribution Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (2 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] Unable to determine Package-URL identifiers for 2 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (5 seconds)
```
what should i do?

**Comment by jeremylong** [comment]
I would suggest unzipping before analyzing?
