### ISSUE TITLE
SemverException checking dependencies of an NPM project

### ISSUE THREAD

**Issue by xin-hedera** [dependency-check/DependencyCheck#3972]
**Describe the bug**
When using v6.5.2 to check our NPM project, `SemverException` is thrown as detailed in the log file section.

**Version of dependency-check used**
The problem occurs using version 6.5.2 of the cli and  maven plugin.

**Log file**
```
[WARN] An unexpected error occurred during analysis of '/Users/xin/work/hedera-mirror-node/hedera-mirror-rest/package-lock.json' (Node Audit Analyzer): Invalid version (no major version): "^0.4.0"
[ERROR]
com.vdurmont.semver4j.SemverException: Invalid version (no major version): "^0.4.0"
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
	at org.owasp.dependencycheck.analyzer.AbstractNpmAnalyzer.determineVersionFromMap(AbstractNpmAnalyzer.java:535)
	at org.owasp.dependencycheck.analyzer.AbstractNpmAnalyzer.processResults(AbstractNpmAnalyzer.java:476)
	at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:151)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
**To Reproduce**
1. git clone --depth 1 https://github.com/hashgraph/hedera-mirror-node
2. cd hedera-mirror-node/hedera-mirror-rest && npm i
3. dependency-check.sh --out . --scan package-lock.json

**Expected behavior**
No SemverException

**Additional context**

**Comment by jeremylong** [comment]
See #3956.
