### ISSUE TITLE
ConcurrentModificationException in DependencyMergingAnalyzer.mergeDependencies

### ISSUE THREAD

**Issue by wlmitch** [dependency-check/DependencyCheck#3992]
**Describe the bug**
ConcurrentModificationException in DependencyMergingAnalyzer.mergeDependencies

**Version of dependency-check used**
```bash
$ dependency-check --version
Dependency-Check Core version 6.5.3
```

**Log file**
```text
[WARN] An unexpected error occurred during analysis of '/path/to/project/package-lock.json' (Node.js Package Analyzer): null
[ERROR] 
java.util.ConcurrentModificationException: null
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2765)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.owasp.dependencycheck.analyzer.DependencyMergingAnalyzer.mergeDependencies(DependencyMergingAnalyzer.java:155)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:419)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:265)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
[WARN] dependency skipped: node module fsevents seems optional and not installed
[INFO] Finished Node.js Package Analyzer (6 seconds)
```
**To Reproduce**

**Expected behavior**
No exception.

**Additional context**
N/A

**Comment by nfalco79** [comment]
could you release this? In production is happening too much (2 build per day fails)
