### ISSUE TITLE
ConcurrentModificationException often happens when merge analyzer

### ISSUE THREAD

**Issue by nfalco79** [dependency-check/DependencyCheck#4042]
**Describe the bug**
We run dependency check with Jenkins plugin using latest tool version. When we analyze our monorepository we get often build failure. Looking log the only exception we get that can cause exitCode != 0 of scan command is the following
> [DependencyCheck] [ERROR] 
[DependencyCheck] java.util.ConcurrentModificationException: null
[DependencyCheck] 	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2757)
[DependencyCheck] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.DependencyMergingAnalyzer.mergeDependencies(DependencyMergingAnalyzer.java:155)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:419)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:364)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:364)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:364)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:265)
[DependencyCheck] 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
[DependencyCheck] 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[DependencyCheck] 	at java.lang.Thread.run(Thread.java:748)

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the cli

**Log file**
Full log file [here](https://gist.github.com/nfalco79/1c2d07925a03be282239c34f85b3d71a)

**Additional context**
All options used:
--disablePyDist,
--disablePyPkg,
--disableMSBuild,
--disableYarnAudit,
--disableRetireJS,
--disableRubygems,
--disableBundleAudit,
--disableCocoapodsAnalyzer,
--disableSwiftPackageManagerAnalyzer,
--disableSwiftPackageResolvedAnalyzer,
--disableAutoconf,
--disableOpenSSL,
--disableCmake,
--disableArchive,
--disableJar,
--disableComposer,
--disableCpan,
--disableNuspec,
--disableNugetconf,
--disableAssembly,
--disableGolangDep,
--disableGolangMod,
--disableComposer,
--disableNodeAudit,
--disableOssIndex,
--nodePackageSkipDevDependencies,
--nodeAuditSkipDevDependencies,
--exclude=* */.m2/* *
--failOnCVSS=11,
--noupdate,
--project=dependency-check-report,
--dbDriverPath=.........,
--dbDriverName=org.postgresql.Driver,
--connectionString=........,
--dbUser= + DB_USER,
--dbPassword= + DB_PASSWORD,
--format=XML,
--format=JSON,
--prettyPrint

**Comment by nfalco79** [comment]
duplicates  #3992
