### ISSUE TITLE
About dependency check 5.2.2 updating vulnerability library 404

### ISSUE THREAD

**Issue by JessicaStart** [dependency-check/DependencyCheck#4083]
When updating vulnerability database data with 5.2.2, Error 404 is reported, and the page cannot be found. Is there any place that can be modified in cli mode
error massage
[INFO] Checking for updates
[ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:351)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:385)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:922)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:889)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:381)
        at org.owasp.dependencycheck.App.run(App.java:161)
        at org.owasp.dependencycheck.App.main(App.java:80)
Caused by: org.owasp.dependencycheck.utils.ResourceNotFoundException: Requested resource does not exists - received a 404
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:204)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:138)
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:110)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:340)
        ... 7 common frames omitted

**Comment by jeremylong** [comment]
Please see https://github.com/jeremylong/DependencyCheck/blob/main/SECURITY.md

Old versions of ODC are no longer supported.
