### ISSUE TITLE
Centralized Database error on Postgres: "Connection factory returned null from createConnection" 

### ISSUE THREAD

**Issue by brandon-pangilinan** [dependency-check/DependencyCheck#4087]
I am trying to test my update to OWASP DC from version 6.1.2 to 6.5.3 by running the cli command with the `-updateonly` flag and updating my centralized postgres database with the latest from NVD. This works when running version 6.1.2 and JDBC Driver 42.2.19. This does not work when running version 6.5.3 and either the latest version of JDBC or 42.2.19.

I have have my own dockerfile which builds the release and uses the `dependency-check.sh` as the entrypoint.  

When running 
```
dependency-check.sh --updateonly --connectionString "jdbc:postgresql://<NVD_Mirror>/dependencycheck" --dbUser <user> --dbPassword <pass> --cveUrlModified http://10.4.0.32/nvdcve-1.1-modified.json.gz --cveUrlBase http://10.4.0.32/nvdcve-1.1-%d.json.gz
```
I receive the following exception: 
```
Exception in thread "main" java.lang.IllegalStateException: Connection factory returned null from createConnection
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:376)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:106)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.getConnection(DatabaseManager.java:556)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.getProperties(CveDB.java:49[8](https://<internal_github>/shredder/owasp-dc-nist-data-mirror/runs/65013?check_suite_focus=true#step:4:8))
	at org.owasp.dependencycheck.data.nvdcve.DatabaseProperties.<init>(DatabaseProperties.java:[9](https://<internal_github>/shredder/owasp-dc-nist-data-mirror/runs/65013?check_suite_focus=true#step:4:9)4)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:250)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:999)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:865)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:847)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:390)
	at org.owasp.dependencycheck.App.run(App.java:[16](https://<internal-repo>/shredder/owasp-dc-nist-data-mirror/runs/65013?check_suite_focus=true#step:4:16)6)
	at org.owasp.dependencycheck.App.main(App.java:83)
Error: Process completed with exit code 1.
```

Even when running the CLI command with the `--noupdate` flag and pointing to the central DB, it will give the same exact error.

**Comment by jeremylong** [comment]
Where are you putting the database driver's JAR file?

**Comment by jeremylong** [comment]
While there were changes to the `ConnectionFactory` - the changes made shouldn't affect your execution: https://github.com/jeremylong/DependencyCheck/compare/v6.1.2...v6.5.3#diff-1bd6d053c4d3e4fd27267ae889d2f7b7fa257855e928959564295c1736e815d1R121

To ensure the driver is on the classpath of ODC - you should place it in the `plugins` directory. Otherwise you need to set the driver name and driver path as options in the command.

**Comment by brandon-pangilinan** [comment]
> Where are you putting the database driver's JAR file?

Thank you for the response, @jeremylong! I have my dockerfile placing the database driver JAR file like this 
```
    && cd /owasp/dependency-check/plugins \
    && wget --no-check-certificate https://jdbc.postgresql.org/download/postgresql-${jdbc_postgresql_driver_version}.jar \
    && ln -s postgresql-${jdbc_postgresql_driver_version}.jar postgresql.jar
```
And i've confirmed that the database driver JAR is indeed in the correct plugins folder 
![image](https://user-images.githubusercontent.com/99915475/154739404-a73f2d47-0d54-4822-b40b-6bf9ca2d4fac.png)

**Comment by aikebah** [comment]
My gut feel would be that your setup confuses the classloader/JDBC driver lookup logic by having the postgresql driver twice on the classpath - the actual jar with version as well as the versionless symlink to that jar (the shell-script instructs java to put all jar-files in the plugins folder onto the classpath).

I would advice to either remove the symlink (it's useless for the purpose of dependency-check.sh) or, if it's there for non-dependencycheck purposes, move the versioned library to another folder.

**Comment by brandon-pangilinan** [comment]
Hello @aikebah! When I removed the symlink command in the dockerfile and rebuilt the image,  and it yielded the same error as above. Is there a setting that I needed to enable in my postgres database that I was perhaps missing? I set it to be able to receive connections from the correct subnet. I'm also open to exploring a different type of database server if postgres isn't the most compatible type.

**Comment by aikebah** [comment]
@brandon-pangilinan Unfortunate that the duplication of the jar was not the root cause. To further debug the issue I think it would be wise to temporarily turn on verbose logging (if possible) by adding a well-chosen `--log <log filename>` [CLI-argument](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) to your dependency-check.sh invocation for a significantly larger amount of detail of what DependencyCheck does before it runs into the null-return.

**Comment by brandon-pangilinan** [comment]
Here is the log output when running the aforementioned command using OWASP DC 6.5.3, JDBC Driver 42.2.19, Postgres 11. Logs were clipped to improve readability:
```
root@f9a26339bdf1:/# cat dependency-check.log 
. . .
2022-02-18 22:08:40,575 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: data.connection_string='jdbc:postgresql://10.4.0.39:5432/dependencycheck'
2022-02-18 22:08:40,575 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: data.user='dcuser@ds9-tools'
2022-02-18 22:08:40,575 org.owasp.dependencycheck.CliParser:642
WARN  - dbPassword used on the command line, consider moving the password to a properties file using the key `data.password` and using the --propertyfile argument instead
2022-02-18 22:08:40,577 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: data.password='********'
2022-02-18 22:08:40,577 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: cve.url.base='http://10.4.0.32/nvdcve-1.1-%d.json.gz'
2022-02-18 22:08:40,582 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: cve.url.modified='http://10.4.0.32/nvdcve-1.1-modified.json.gz'
2022-02-18 22:08:40,583 org.owasp.dependencycheck.utils.Settings:906
DEBUG - Setting: odc.autoupdate='true'
2022-02-18 22:08:40,617 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Archive Analyzer
2022-02-18 22:08:40,619 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer File Name Analyzer
2022-02-18 22:08:40,645 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Jar Analyzer
2022-02-18 22:08:40,649 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Hint Analyzer
2022-02-18 22:08:40,658 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer CPE Analyzer
2022-02-18 22:08:40,662 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer False Positive Analyzer
2022-02-18 22:08:40,665 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Dependency Bundling Analyzer
2022-02-18 22:08:40,668 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Dependency Merging Analyzer
2022-02-18 22:08:40,670 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer NVD CVE Analyzer
2022-02-18 22:08:40,673 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Vulnerability Suppression Analyzer
2022-02-18 22:08:40,676 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Central Analyzer
2022-02-18 22:08:40,678 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nexus Analyzer
2022-02-18 22:08:40,680 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Artifactory Analyzer
2022-02-18 22:08:40,682 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nuspec Analyzer
2022-02-18 22:08:40,690 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nugetconf Analyzer
2022-02-18 22:08:40,697 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer MSBuild Project Analyzer
2022-02-18 22:08:40,702 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Assembly Analyzer
2022-02-18 22:08:40,750 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer OpenSSL Source Analyzer
2022-02-18 22:08:40,774 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Node.js Package Analyzer
2022-02-18 22:08:40,779 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Node Audit Analyzer
2022-02-18 22:08:40,782 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Yarn Audit Analyzer
2022-02-18 22:08:40,786 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Pnpm Audit Analyzer
2022-02-18 22:08:40,802 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer RetireJS Analyzer
2022-02-18 22:08:40,810 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Ruby Bundle Audit Analyzer
2022-02-18 22:08:40,832 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Version Filter Analyzer
2022-02-18 22:08:40,835 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Sonatype OSS Index Analyzer
2022-02-18 22:08:40,844 org.owasp.dependencycheck.utils.Settings:1107
DEBUG - Settings.getDataFile() - file: '/owasp/dependency-check/data'
2022-02-18 22:08:41,214 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:141
DEBUG - Loading driver 'org.h2.Driver'
2022-02-18 22:08:41,226 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:176
DEBUG - Loading database connection
2022-02-18 22:08:41,227 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:177
DEBUG - Connection String: jdbc:postgresql://10.4.0.39:5432/dependencycheck
2022-02-18 22:08:41,227 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:178
DEBUG - Database User: dcuser@ds9-tools
2022-02-18 22:08:42,316 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:239
DEBUG - Database product: postgresql
2022-02-18 22:08:42,506 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:486
DEBUG - DC Schema: 5.2
2022-02-18 22:08:42,507 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:487
DEBUG - DB Schema: 5.2
2022-02-18 22:08:42,553 org.owasp.dependencycheck.data.nvdcve.CveDB:260
DEBUG - Closing database
2022-02-18 22:08:42,554 org.owasp.dependencycheck.data.nvdcve.CveDB:262
DEBUG - Cache cleared
2022-02-18 22:08:42,554 org.owasp.dependencycheck.data.nvdcve.CveDB:265
DEBUG - Connection closed
2022-02-18 22:08:42,554 org.owasp.dependencycheck.data.nvdcve.CveDB:271
DEBUG - Resources released
2022-02-18 22:08:42,554 org.owasp.dependencycheck.data.nvdcve.DriverLoader:57
DEBUG - Begin deregister driver
2022-02-18 22:08:42,554 org.owasp.dependencycheck.data.nvdcve.DriverLoader:59
DEBUG - End deregister driver
```
Here are the logs of the aforementioned command, only this time using OWASP DC 6.5.3, JDBC Driver 42.2.19, Postgres 11. This time, the update worked as intended. I confirmed that both versions of the image had the JDBC driver jar appropriately named and stored in the plugins folder:
```
. . .
2022-02-18 22:22:22,375 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: data.connection_string='jdbc:postgresql://10.4.0.39:5432/dependencycheck'
2022-02-18 22:22:22,376 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: data.user='dcuser@ds9-tools'
2022-02-18 22:22:22,376 org.owasp.dependencycheck.CliParser:607
WARN  - dbPassword used on the command line, consider moving the password to a properties file using the key `data.password` and using the --propertyfile argument instead
2022-02-18 22:22:22,379 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: data.password='********'
2022-02-18 22:22:22,379 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: cve.url.base='http://10.4.0.32/nvdcve-1.1-%d.json.gz'
2022-02-18 22:22:22,379 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: cve.url.modified='http://10.4.0.32/nvdcve-1.1-modified.json.gz'
2022-02-18 22:22:22,380 org.owasp.dependencycheck.utils.Settings:856
DEBUG - Setting: odc.autoupdate='true'
2022-02-18 22:22:22,439 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Archive Analyzer
2022-02-18 22:22:22,441 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer File Name Analyzer
2022-02-18 22:22:22,487 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Jar Analyzer
2022-02-18 22:22:22,493 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Hint Analyzer
2022-02-18 22:22:22,504 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer CPE Analyzer
2022-02-18 22:22:22,511 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer False Positive Analyzer
2022-02-18 22:22:22,514 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Dependency Bundling Analyzer
2022-02-18 22:22:22,516 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Dependency Merging Analyzer
2022-02-18 22:22:22,517 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer NVD CVE Analyzer
2022-02-18 22:22:22,521 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Vulnerability Suppression Analyzer
2022-02-18 22:22:22,532 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Central Analyzer
2022-02-18 22:22:22,538 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nexus Analyzer
2022-02-18 22:22:22,539 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Artifactory Analyzer
2022-02-18 22:22:22,545 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nuspec Analyzer
2022-02-18 22:22:22,554 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Nugetconf Analyzer
2022-02-18 22:22:22,562 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer MSBuild Project Analyzer
2022-02-18 22:22:22,566 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Assembly Analyzer
2022-02-18 22:22:22,593 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer OpenSSL Source Analyzer
2022-02-18 22:22:22,609 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Node.js Package Analyzer
2022-02-18 22:22:22,612 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Node Audit Analyzer
2022-02-18 22:22:22,618 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Yarn Audit Analyzer
2022-02-18 22:22:22,631 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer RetireJS Analyzer
2022-02-18 22:22:22,635 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Ruby Bundle Audit Analyzer
2022-02-18 22:22:22,669 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Version Filter Analyzer
2022-02-18 22:22:22,672 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Sonatype OSS Index Analyzer
2022-02-18 22:22:22,679 org.owasp.dependencycheck.utils.Settings:1057
DEBUG - Settings.getDataFile() - file: '/owasp/dependency-check/data'
2022-02-18 22:22:23,174 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:124
DEBUG - Loading driver 'org.h2.Driver'
2022-02-18 22:22:23,201 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:157
DEBUG - Loading database connection
2022-02-18 22:22:23,201 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:158
DEBUG - Connection String: jdbc:postgresql://10.4.0.39:5432/dependencycheck
2022-02-18 22:22:23,201 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:159
DEBUG - Database User: dcuser@ds9-tools
2022-02-18 22:22:24,519 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:440
DEBUG - DC Schema: 5.0
2022-02-18 22:22:24,519 org.owasp.dependencycheck.data.nvdcve.ConnectionFactory:441
DEBUG - DB Schema: 5.2
2022-02-18 22:22:24,814 org.owasp.dependencycheck.data.nvdcve.CveDB:261
DEBUG - Database product: postgresql
2022-02-18 22:22:24,840 org.owasp.dependencycheck.Engine:851
INFO  - Checking for updates
2022-02-18 22:22:25,067 org.owasp.dependencycheck.data.update.NvdCveUpdater:366
DEBUG - starting getUpdatesNeeded() ...
2022-02-18 22:22:25,080 org.owasp.dependencycheck.utils.HttpResourceConnection:200
DEBUG - Attempting retrieval of http://10.4.0.32/nvdcve-1.1-modified.meta
2022-02-18 22:22:25,171 org.owasp.dependencycheck.data.update.NvdCveUpdater:181
DEBUG - #download   threads: 2
2022-02-18 22:22:25,171 org.owasp.dependencycheck.data.update.NvdCveUpdater:182
DEBUG - #processing threads: 2
2022-02-18 22:22:25,173 org.owasp.dependencycheck.utils.FileUtils:121
DEBUG - Temporary directory is `/tmp/dctemp7335e636-bff8-49a6-99e6-d3765c4f2ea5`
2022-02-18 22:22:25,185 org.owasp.dependencycheck.data.update.nvd.DownloadTask:124
INFO  - Download Started for NVD CVE - Modified
2022-02-18 22:22:25,187 org.owasp.dependencycheck.utils.HttpResourceConnection:200
DEBUG - Attempting retrieval of http://10.4.0.32/nvdcve-1.1-modified.json.gz
2022-02-18 22:22:25,208 org.owasp.dependencycheck.data.update.nvd.DownloadTask:139
INFO  - Download Complete for NVD CVE - Modified  (21 ms)
2022-02-18 22:22:25,213 org.owasp.dependencycheck.data.update.nvd.ProcessTask:149
INFO  - Processing Started for NVD CVE - Modified
2022-02-18 22:22:25,216 org.owasp.dependencycheck.data.update.nvd.NvdCveParser:84
DEBUG - Parsing cveModified_1794296390773633945.json.gz
2022-02-18 22:22:41,206 org.owasp.dependencycheck.data.update.nvd.ProcessTask:160
INFO  - Processing Complete for NVD CVE - Modified  (15993 ms)
2022-02-18 22:22:41,207 org.owasp.dependencycheck.data.nvdcve.CveDB:1407
INFO  - Begin database maintenance
2022-02-18 22:22:41,975 org.owasp.dependencycheck.data.nvdcve.CveDB:1429
INFO  - Cleaned up 1 orphaned NVD records
2022-02-18 22:22:41,975 org.owasp.dependencycheck.data.nvdcve.CveDB:1434
INFO  - End database maintenance (767 ms)
2022-02-18 22:22:41,984 org.owasp.dependencycheck.utils.Settings:1057
DEBUG - Settings.getDataFile() - file: '/owasp/dependency-check/data'
2022-02-18 22:22:41,984 org.owasp.dependencycheck.data.update.RetireJSDataSource:88
DEBUG - Begin RetireJS Update
2022-02-18 22:22:41,985 org.owasp.dependencycheck.utils.Settings:1057
DEBUG - Settings.getDataFile() - file: '/owasp/dependency-check/data'
2022-02-18 22:22:42,042 org.owasp.dependencycheck.utils.WriteLock:166
DEBUG - Lock file created (main) cb8799bc8a68ef73eebe195aee776fd4 @ 2022-02-18 22:22:42.042
2022-02-18 22:22:42,042 org.owasp.dependencycheck.data.update.RetireJSDataSource:136
DEBUG - RetireJS Repo URL: https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
2022-02-18 22:22:42,043 org.owasp.dependencycheck.utils.HttpResourceConnection:200
DEBUG - Attempting retrieval of https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:283
DEBUG - Available Protocols:
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - SSLv2Hello
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - SSLv3
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - TLSv1
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - TLSv1.1
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - TLSv1.2
2022-02-18 22:22:42,145 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:285
DEBUG - TLSv1.3
2022-02-18 22:22:42,317 org.owasp.dependencycheck.utils.WriteLock:238
DEBUG - Lock released (main) cb8799bc8a68ef73eebe195aee776fd4 @ 2022-02-18 22:22:42.317
2022-02-18 22:22:42,318 org.owasp.dependencycheck.data.nvdcve.CveDB:301
DEBUG - Closing database
2022-02-18 22:22:42,318 org.owasp.dependencycheck.data.nvdcve.CveDB:303
DEBUG - Cache cleared
2022-02-18 22:22:42,320 org.owasp.dependencycheck.data.nvdcve.CveDB:305
DEBUG - Statments closed
2022-02-18 22:22:42,320 org.owasp.dependencycheck.data.nvdcve.CveDB:308
DEBUG - Connection closed
2022-02-18 22:22:42,320 org.owasp.dependencycheck.data.nvdcve.CveDB:317
DEBUG - Resources released
2022-02-18 22:22:42,321 org.owasp.dependencycheck.data.nvdcve.DriverLoader:57
DEBUG - Begin deregister driver
2022-02-18 22:22:42,321 org.owasp.dependencycheck.data.nvdcve.DriverLoader:59
DEBUG - End deregister driver
2022-02-18 22:22:42,321 org.owasp.dependencycheck.Engine:874
INFO  - Check for updates complete (17480 ms)
2022-02-18 22:22:42,634 org.owasp.dependencycheck.utils.Settings:767
DEBUG - Deleting ALL temporary files from `/tmp/dctemp7335e636-bff8-49a6-99e6-d3765c4f2ea5`
2022-02-18 22:22:42,651 org.owasp.dependencycheck.App:82
DEBUG - Exit code: 0
```

**Comment by aikebah** [comment]
It's loading the H2 driver as you did not set/override the driver-name in your commandline (option `--dbDriverName`), so it will attempt loading the driver that's configured in the software, which is H2.

Nevertheless in your setup it will still use the PostgreSQL driver to build database connections (the H2 driver has no clue on how to open `jdbc:postgresl:...` database connection URLs, it only accepts `jdbc:h2:...` URLs. 

In the past (old JDBC versions before JDBC4) it was required to load the JDBC driver class to get it registered with the Java JDBC classes for resolution based on the JDBC-url. Modern JDBC (JDBC4 compliant drivers) uses a driver loading mechanism that no longer requires you to preload the driver-class prior to first usage of the corresponding JDBC URL scheme in a connection-URL.
As the Postgresql driver is a modern JDBC driver updated to use this new driver discovery mechanism it can work without loading its driver-class prior to the first use of the `jdbc:postgresql:...` JDBC connection-URL.

So this should work in either case (both with and without the override of the driver-name)

**Comment by aikebah** [comment]
Looking a bit more at the logic in the code I think the ommision of the dbDriverName is at the root-cause of your problems.
Having the H2 driver loaded has the side-effect of registering that driver to the database-connection pool.

You should be able to work around the issue by specifying `--dbDriverName=org.postgresql.Driver`

As currently specified in [external database usage documentation](https://jeremylong.github.io/DependencyCheck/data/database.html) you should always include the dbDriverName:

>The database driver will need to be specified using the dbDriver and if the driver is not already in the classpath the dbDriverPath options will need to be set (see the specific configuration options for Maven, Gradle, Ant, CLI, and Jenkins).

So this might count as a user-error, however I think we should try to improve DependencyCheck to no longer require this for JDBC4 compliant database drivers.

**Comment by brandon-pangilinan** [comment]
Good morning @aikebah! I'm delighted to inform you that explicitly including `--dbDriverName=org.postgresql.Driver` worked as intended, and will be sure to inform the rest of my colleagues of this finding. Thank you @jeremylong and @aikebah so much for the support!!
