### ISSUE TITLE
NullPointerException when processing node_modules 

### ISSUE THREAD

**Issue by pbielicki** [dependency-check/DependencyCheck#4089]
**Describe the bug**
Gradle build checking the dependencies fails miserably with the `NullPointerException`.

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the gradle plugin
It works OK using 6.5.2.1

**Log file**
In the output I see:
```
An unexpected error occurred during analysis of 'blahblah/package-lock.json' (Node.js Package Analyzer): null

java.util.ConcurrentModificationException
        at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2750)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.owasp.dependencycheck.analyzer.DependencyMergingAnalyzer.mergeDependencies(DependencyMergingAnalyzer.java:155)
        at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:419)
        at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:364)
        at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:265)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

and then the build fails with:

```
java.lang.NullPointerException
        at org.owasp.dependencycheck.exception.ExceptionCollection.nestedCauseList(ExceptionCollection.java:220)
        at org.owasp.dependencycheck.exception.ExceptionCollection.lambda$getMessage$2(ExceptionCollection.java:215)
        at org.owasp.dependencycheck.exception.ExceptionCollection.getMessage(ExceptionCollection.java:212)
        at org.gradle.internal.exceptions.DefaultMultiCauseException.printSingleCauseStackTrace(DefaultMultiCauseException.java:143)
        at org.gradle.internal.exceptions.DefaultMultiCauseException.printStackTrace(DefaultMultiCauseException.java:131)
```

These exceptions don't seem to be very helpful. I debugged the plugin and I caught it spitting NPE here:
![image](https://user-images.githubusercontent.com/1133099/154661219-c2717b97-177e-438d-9b65-67efec513349.png)

`jo.getBoolean("optional", false);` throws NPE as the `optional` field is not present. Not sure of the problem is in `org.glassfish.json.JsonObjectBuilderImpl`:
![image](https://user-images.githubusercontent.com/1133099/154660922-5495ceef-158a-4bf8-9d16-65b0e1b43561.png)

that is explicitly throwing NPE in this case.

**To Reproduce**

**Expected behavior**
No NPE and finish the processing.

**Additional context**

**Comment by aikebah** [comment]
Except for the fact that we're not calling `javax.json.JsonObject#getBoolean(String)`, but `javax.json.JsonObject#getBoolean(String, boolean)`, which is handling the NPE that you point to by returning the default value offered as a second parameter

![Screenshot 2022-02-18 at 17 47 12](https://user-images.githubusercontent.com/2175611/154726372-8f48737e-6088-4714-93cc-0c605dfba904.png)

So your analysis regarding the source of the NPE is wrong.

According to the stacktrace the NPE is at
at org.owasp.dependencycheck.exception.ExceptionCollection.nestedCauseList(ExceptionCollection.java:220)
where it is also logical that this can happen: at that line it's initializing a StringBuilder with the message of the Exception, which for various reasons known only to the creators of the exception may be `null` (as can be observed from the initial logged exception in your build):

> - _An unexpected error occurred during analysis of 'blahblah/package-lock.json' (Node.js Package Analyzer): **null**_ .

So the stacktrace is perfectly usable to obtain the root-cause: trying to initialize a StringBuilder with `null`.

**Comment by aikebah** [comment]
Although I must say that I would've expected the constructor of java.lang.StringBuilder as the first element in the stacktrace. But I cannot imagine the ExceptionCollection to hold a null-valued Throwable which would be the only other plausible cause of the NPE.

**Comment by aikebah** [comment]
@pbielicki Would you be able to share a project that exhibits the throwing of the `java.util.ConcurrentModificationException`? 

Because it's easy to fix the NPE in the next release, but that would still leave your project open to the initial ConcurrentModificationException, so I don't think just fixing the NPE would be any good to you.

**Comment by pbielicki** [comment]
@aikebah sorry for the late reply - I was off last week. 
I can't share the project as it's a closed-source. I plan to work on a reproducer but I don't think it will be something quick and obvious.

**Comment by aikebah** [comment]
@pbielicki If you happen to uncover the scenario under which the ConcurrentModificationException happens please comment to #4374 with your findings. The NPE will be fixed in our next release.
