### ISSUE TITLE
7.0.0 Incompatible with PostgreSQL

### ISSUE THREAD

**Issue by rpaasche** [dependency-check/DependencyCheck#4124]
After updating to 7.0.0 we receive the error "[ERROR] Database schema does not match this version of dependency-check"
but https://github.com/jeremylong/DependencyCheck/tree/main/core/src/main/resources/data dose not contain any new script

```
[ERROR] Database schema does not match this version of dependency-check
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Database schema does not match this version of dependency-check
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:217)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.<init>(DatabaseManager.java:123)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:242)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:995)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:868)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:850)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:390)
	at org.owasp.dependencycheck.App.run(App.java:166)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to check the database schema version
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.ensureSchemaVersion(DatabaseManager.java:505)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:214)
	... 8 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: ` character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.owasp.dependencycheck
```

**Comment by rpaasche** [comment]
The Problem is in core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java

The following change causes this Problem with postgres.
![image](https://user-images.githubusercontent.com/33899601/155999798-582a0e49-de1c-47d0-8b96-de412f0f3e61.png)

**Comment by rpaasche** [comment]
P.S.: Using PostgreSQL 11.12

**Comment by cedric-jonas-kisters** [comment]
I can confirm this issue with Postgres 14.2.
It occured also at least with the previous plugin version.

> The Problem is in core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java
> 
> The following change causes this Problem with postgres. ![image](https://user-images.githubusercontent.com/33899601/155999798-582a0e49-de1c-47d0-8b96-de412f0f3e61.png)

My analysis lead to the same conclusion, the grave accent is the issue here.

**Comment by alerat** [comment]
Same here with postgres 14.2

```
[ERROR]` Failed to execute goal org.owasp:dependency-check-maven:7.0.0:check (default-cli) on project dummy: Fatal exception(s) analyzing dummy: One or more exceptions occurred during analysis:
[ERROR] 	DatabaseException: Unable to connect to the dependency-check database
[ERROR] 		caused by DatabaseException: Database schema does not match this version of dependency-check
[ERROR] 		caused by DatabaseException: Unable to check the database schema version
[ERROR] 		caused by PSQLException: ERROR: syntax error at or near "FROM"
```

**Comment by alerat** [comment]
@jeremylong Did you plan to work on this issue ?

**Comment by rpaasche** [comment]
I plan to create a PR. It should be a simple fix by replacing the backticks with single qoutes.

**Comment by alerat** [comment]
> I plan to create a PR. It should be a simple fix by replacing the backticks with single qoutes.

Done

**Comment by rpaasche** [comment]
> > I plan to create a PR. It should be a simple fix by replacing the backticks with single qoutes.
> 
> Done

Thanks.
