### ISSUE TITLE
DependencyCheck 7.0.0 cannot process 'NVD CVE - 2018'

### ISSUE THREAD

**Issue by dg-gotayga** [dependency-check/DependencyCheck#4147]
**Description**
The DependencyCheck 7.0.0 cannot process 'NVD CVE - 2018'. The following error is found in the console log:
```
[INFO] Download Started for NVD CVE - 2018
[INFO] Download Complete for NVD CVE - 2018  (84323 ms)
[INFO] Processing Started for NVD CVE - 2018
[ERROR] Error reading NVD JSON data: C:\Users\<user>\AppData\Local\Temp\dctemp00d7e0b6-ba84-43d2-87d8-0e9f219d7c95\cve2018_6488503643792396677.json.gz
[INFO] Download Started for NVD CVE - 2019
[INFO] Download Complete for NVD CVE - 2019  (8106 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Processing Complete for NVD CVE - 2019  (2989 ms)
```

The final error looks like this:
[ERROR] Unable to find the NVD CVE file to parse
```
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to find the NVD CVE file to parse
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:105)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:276)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1797)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1782)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:962)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:284)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
        at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:96)
        ... 8 common frames omitted
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] Unable to find the NVD CVE file to parse
[ERROR] No documents exist
```

**Version of dependency-check used**
The problem occurs using version 7.0.0 of the cli. The version 6.5.3 does NOT have it.
Initially this issue was found in the Azure pipeline with the 'OWASP Dependency Check' task ver. 6.0.4 but it is reproduced locally on a Windows box as well.

**To Reproduce**
1. Download [DependencyCheck 7.0.0](https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.0/dependency-check-7.0.0-release.zip) and unpack.
2. Run the check against the ASP.Net Core 3.1 project: `C:\Code\dependency-check\bin\dependency-check.bat --project "AspNetCoreProject" --scan "C:\Code\AspNetCoreProject\AspNetCoreProject.csproj" --out "C:\Code\AspNetCoreProject\TestResults\dependency-check" --format HTML --failOnCVSS 8 --enableExperimental`

**Expected behavior**
After the 2nd step the 'dependency-check-report.html' is generated.

**Actual behavior**
The errors are in the console, the report is not generated.

**Comment by aikebah** [comment]
Looks like your datastream download was corrupted. Are you using a proxy in between? Looks like some infrastructure said that the download completed while in fact it timed out and was only partially delivered (download of 2018 stream taking 80+ seconds is absurd)

**Comment by dg-gotayga** [comment]
First time it was observed on March 1, 2022 in the Azure pipeline, today the same pipeline still displays the error. The pipeline runs by the agent in the Hetzner cloud.

In my local environment the NVD CVE items for all years are downloaded properly for the version 6.5.3. I have tested this in the fresh folder.

Was there any change in the 2018 database between releases? Or does the database depend on the release at all?

**Comment by aikebah** [comment]
There is no 2018 database, there is a single database that is generated from the year-by-year datastreams of the NIST National Vulnerability Database. The zlib error in the stacktrace you quoted indicates that the download dependencycheck got was corrupted (ending prematurely, is not a properly formatted gzip file).

Best try for you to resolve it is to purge the data from the 7.0.0 install and make it redownload from source:
bin\dependency-check.bat --purge --updateonly

**Comment by aikebah** [comment]
Last update of the 2018 datastream was on Feb 26, so the locally cached corrupt file will be re-used by DependencyCheck to process as there is no more-recent 2018 datastream available online at the NIST NVD

```
lastModifiedDate:2022-02-26T03:01:10-05:00
size:76730196
zipSize:4097868
gzSize:4097732
sha256:C60061BABD6FB343ECF4EFA2F83BCBED521A43B89DA77E9245A46CEE67496E79
```
metadata for the 2018 stream

**Comment by dg-gotayga** [comment]
Thank you!! Purging the database helped!

**Comment by WangJincheng4869** [comment]
如果用的是 maven 插件，那么找到 dependency-check-data 目录直接删除即可
![image](https://user-images.githubusercontent.com/41162158/221514565-ed0bd75f-fe71-4a8d-8e76-ef5572ab1ca4.png)
