### ISSUE TITLE
How to disable Central search?

### ISSUE THREAD

**Issue by itsecforu** [dependency-check/DependencyCheck#4198]
Hello, everyone!
I've run into this problem.
I use the scheduler to build an image and update the vulnerability database, then send it to the registry and use it in CI.

The task is performed as follows:

`/usr/share/dependency-check/bin/dependency-check.sh \ --data /data \ --out owasp/dependency-check-report \ --log depcheck.log \ --project "svc-disquad" \ --format "ALL" \ --nodeAuditSkipDevDependencies true \ --disableYarnAudit \ --noupdate \ --enableExperimental --scan download`

With a working internet connection on the runners it's OK.

When disconnecting the internet, errors appear:

```
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:[75](https://gitlab.dev002.local/devops/svd/sonar/-/jobs/1221345#L75)0)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:1[88](https://gitlab.dev002.local/devops/svd/sonar/-/jobs/1221345#L88))
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:1[89](https://gitlab.dev002.local/devops/svd/sonar/-/jobs/1221345#L89))
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:169)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted
[WARN] An error occurred while analyzing '/builds/devops/svd/sonar/download/project/gradle/wrapper/gradle-wrapper.jar' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.

```
I noticed flag --disableCentral, can it solve to work offline my task?

Or are there other alternative solutions?

**Comment by aikebah** [comment]
It can work to make your scan run in offline mode, but with a higher chance of false positive matches compared to a scenario where the CLI can connect to Maven Central to lookup the groupId/artifactId/version of jar-files by sha-hash.

**Comment by aikebah** [comment]
See also [documentation on the requirements regarding internet connectivity](https://jeremylong.github.io/DependencyCheck/data/index.html) 

If your CI is not connected to internet you need more than just disable centralAnalyzer. Also RetireJS analyzer is expecting live internet connectivity unless locally mirrored in your CI environment. And I think Node audit analyzer also requires internet access (not 100% sure, but fairly certain it's wrongfully not making a presence on that documentation page - to my knowledge node audit requires internet connectivity)

**Comment by itsecforu** [comment]
Thx for feedback. 
Which ports should I close for testing? 443 only?
