### ISSUE TITLE
NullPointerException occurred during package-lock.json analyze 

### ISSUE THREAD

**Issue by tbattisti** [dependency-check/DependencyCheck#4293]
**Describe the bug**
java.lang.NullPointerException occurred during analysis of a package-lock.json

**Version of dependency-check used**
7.0.4

**Log file**
<pre>
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (2 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[WARN] The Node Package Analyzer has been disabled; the resulting report will only contain the known vulnerable dependency - not a bill of materials for the node project.
[WARN] An unexpected error occurred during analysis of 'C:\Users\TBATTI~1\AppData\Local\Temp\dctemp39951aff-f90a-4c1e-ab61-f13070969377\check12744923193935695818tmp\1\depcheckFrontend\package-lock.json' (Node Audit Analyzer): Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
[ERROR]
java.lang.NullPointerException: Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
        at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
        at org.owasp.dependencycheck.data.nodeaudit.NpmPayloadBuilder.lambda$build$5(NpmPayloadBuilder.java:152)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
        at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:708)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.forEach(Collections.java:1630)
        at org.owasp.dependencycheck.data.nodeaudit.NpmPayloadBuilder.build(NpmPayloadBuilder.java:147)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.legacyAnalysis(NodeAuditAnalyzer.java:249)
        at org.owasp.dependencycheck.analyzer.NodeAuditAnalyzer.analyzeDependency(NodeAuditAnalyzer.java:148)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] Finished Node Audit Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (2 seconds)
[INFO] Writing report to: C:\Users\tbattisti\Desktop\testDepCheckFE\dependency-check-7.0.4-release\dependency-check\.\dependency-check-report.html
[ERROR] Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
</pre>

**To Reproduce**
1. Download and unzip dependencyCheck from  https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.4/dependency-check-7.0.4-release.zip
2. Download attacched [package-lock.zip](https://github.com/jeremylong/DependencyCheck/files/8389372/package-lock.zip)
3. Launch command from cmd `bin\dependency-check.bat --disableNodeJS --scan package-lock.zip`

**Comment by nhumblot** [comment]
NPE is triggered because of the following object inside the `dependencies` object:

```
    "node_modules/jest-resolve": {
      "dev": true,
      "optional": true,
      "peer": true
    },
```

These objects, if not containing a `version` field, should be ignored to prevent a NPE.

I am currently working on a fix. I will open a PR.

**Comment by johanhammar** [comment]
Sorry for commenting on a closed issue. I see this error in 7.4.0

`[WARNING] An unexpected error occurred during analysis of '<path>/package-lock.json' (Node.js Package Analyzer): Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
[ERROR]
java.lang.NullPointerException: Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString (JsonObjectBuilderImpl.java:257)
    at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies (NodePackageAnalyzer.java:383)
    at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency (NodePackageAnalyzer.java:270)
    at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze (AbstractAnalyzer.java:131)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:88)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:37)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)`

Do you want me to open a new issue?

**Comment by pk27734** [comment]
I'm seeing the same issue in 7.4.0.

```
[INFO] Finished Assembly Analyzer (0 seconds)
[WARN] An unexpected error occurred during analysis of 'D:\DFN_BuildAgent_2\_work\193\s\Source\package-lock.json' (Node.js Package Analyzer): null
[ERROR] 
java.lang.NullPointerException: null
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:383)
	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:270)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] Finished Node.js Package Analyzer (0 seconds)
```

**Comment by wangel13** [comment]
Same in version 7.4.1:

```
[ERROR] Cannot invoke "javax.json.JsonString.getString()" because the return value of "org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
```

**Comment by uwesinha** [comment]
Can confirm: running 7.4.1 from Jenkins gives me exactly the same stack trace as [in @pk27734's comment](https://github.com/jeremylong/DependencyCheck/issues/4293#issuecomment-1337318587).  AFAICS no version-less dependencies in _package-lock.json_.

**Comment by neilime** [comment]
@jeremylong the issue seems to still there for many of us, I guess it should be reopened.
Is there any chance to have a fix on it?

Thank you

**Comment by Jmaharman** [comment]
Yep, getting it too for a linked folder (as posted about in #1947), I get it on projects with linked packages.

"node_modules/utils": {
    "resolved": "packages/utils",
    "link": true
},

Does anyone know how to avoid the error? It scans all the dependencies, but the exception is always logged and makes you wonder whether it missed some dependencies.

**Comment by sladg** [comment]
Facing the same issue with version 7.4.2. Worked fine with 7.3.2 (version used before update).
Should this issue be re-opened or we moving to #1947 ?

**Comment by rturner-edjuster** [comment]
This issue still exists as per the comments above -- it was partially "fixed" with the changes associated with this issue, but it looks like there are other use cases. I've suggested a potential fix on #1947 .

**Comment by lgalvao** [comment]
I'm facing the same problem with version 7.4.4. Thanks for any help!

**Comment by Juraj956510** [comment]
The same problem is also in version 7.4.4. (7.3.2 is fine, but there is now problem with this issue https://github.com/jeremylong/DependencyCheck/issues/5220 which seems to be fixed only in the version 7.4.4).

**Comment by rturner-edjuster** [comment]
@lgalvao @Juraj956510 I have a PR open waiting for merging against Issue #1947 that should resolve that issue. I do not know when it will get released, but you may want to watch that issue as well.

**Comment by bohdantverdyi** [comment]
> I'm seeing the same issue in 7.4.0.
> 
> ```
> [INFO] Finished Assembly Analyzer (0 seconds)
> [WARN] An unexpected error occurred during analysis of 'D:\DFN_BuildAgent_2\_work\193\s\Source\package-lock.json' (Node.js Package Analyzer): null
> [ERROR] 
> java.lang.NullPointerException: null
> 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
> 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:383)
> 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:270)
> 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
> 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
> 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> [INFO] Finished Node.js Package Analyzer (0 seconds)
> ```

can confirm in version 7.4.4 the same issue

**Comment by alex-arzaghi** [comment]
I am getting the same error from 7.4.4 version

**Comment by uwesinha** [comment]
NPE still present in 8.0.0 😢 
```
 [WARN] An unexpected error occurred during analysis of '/mnt/data/jenkins-node/workspace/<my_project>/<my_project>_dep_check/frontend/package-lock.json' (Node.js Package Analyzer): null
 [ERROR] 
 java.lang.NullPointerException: null
 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:397)
 	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:270)
 	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
 	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:834)
 [INFO] Finished Node.js Package Analyzer (0 seconds)
```

**Comment by jeremylong** [comment]
@uwesinha can you provide an example so we can recreate the issue? Please open a new issue.

**Comment by bohdantverdyi** [comment]
> NPE still present in 8.0.0 😢
> 
> ```
>  [WARN] An unexpected error occurred during analysis of '/mnt/data/jenkins-node/workspace/<my_project>/<my_project>_dep_check/frontend/package-lock.json' (Node.js Package Analyzer): null
>  [ERROR] 
>  java.lang.NullPointerException: null
>  	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
>  	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:397)
>  	at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:270)
>  	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
>  	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
>  	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
>  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>  	at java.base/java.lang.Thread.run(Thread.java:834)
>  [INFO] Finished Node.js Package Analyzer (0 seconds)
> ```

Same issue

**Comment by rturner-edjuster** [comment]
@bohdantverdyi  @uwesinha What element on the lock file is it failing on? The protection I added was only for elements with 'link' set to 'true' -- maybe there is another situation where it occurs?

**Comment by rturner-edjuster** [comment]
Looking at the original example from @nhumblot, it looks like there is another use case than I fixed with a PR for #1947.

@jeremylong We still have #1947 open, which is a similar issue/crash. Maybe if I changed the check I added to instead of skipping just `link` entries, to skip all entries without `version`. I'm not sure if that risks not flagging issues/errors, but the point of DependencyCheck isn't really to validate the NPM files, so it's likely fairly safe to do such a thing (however, I'm not an expert on such, but it would be a better safeguard for potential future changes). I'm happy to make the change...

**Comment by rturner-edjuster** [comment]
#5318 has been raised which has the same stack trace as @uwesinha presented, which is different than this issue. @uwesinha @bohdantverdyi I suggest you track/follow that issue instead of this one, and they are different causes.

**Comment by rturner-edjuster** [comment]
> #5318 has been raised which has the same stack trace as @uwesinha presented, which is different than this issue. @uwesinha @bohdantverdyi I suggest you track/follow that issue instead of this one, and they are different causes.

Oops -- I made a mistake in my rushed analysis -- I use the wrong line number and it happened to line up with something very similar. This might be the same issue in some form...
