### ISSUE TITLE
Getting error while running dependencyCheckAggregate on gradle project

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [dependency-check/DependencyCheck#4372]
**Describe the bug**
Running the below command on the spring boot Gradle multi-module project. This seems to be a strange issue as earlier the same setup was working fine and today it has started to break.

`./gradlew dependencyCheckAggregate`

**Version of dependency-check used**
- Using "org.owasp.dependencycheck" plugin with version number - "7.0.4.1"
- Java/jdk version - 1.8

**Logfile**
Checking for updates and analyzing dependencies for vulnerabilities
Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:411)                                                          
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:356)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:464)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:133)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:683)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:609)
        at org.owasp.dependencycheck.Engine$analyzeDependencies$3.call(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unabl
e to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchContent(Downloader.java:187)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:382)
        ... 108 more
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; unable to connect.

**Expected behavior**
It should create the dependency check report for the vulnerabilities.

**Comment by beena-yatin-kanyal** [comment]
Code snippet from Gradle file below -
```
plugins {
    id "org.owasp.dependencycheck" version "7.0.4.1"
}

subprojects {
    apply plugin: "io.spring.dependency-management"
    apply plugin: "org.owasp.dependencycheck"
    dependencyCheck {
        outputDirectory = 'security-report'
        failOnError = true
    }
}
```

**Comment by mprins** [comment]
This is a network or upstream service error, nothing the tool can do anything about; it needs the vulnerability feeds/data.
See https://github.com/jeremylong/DependencyCheck/issues?q=is%3Aissue+DownloadFailedException

**Comment by beena-yatin-kanyal** [comment]
> This is a network or upstream service error, nothing the tool can do anything about; it needs the vulnerability feeds/data. See https://github.com/jeremylong/DependencyCheck/issues?q=is%3Aissue+DownloadFailedException

thanks @mprins is there a fix to it? I referred to the documentation shared above but seems like there is no concrete answer for the fix.

**Comment by aikebah** [comment]
@beena-yatin-kanyal You need to fix the network error, or mirror the NVD datastreams via other means to a location that your build environment can access and customize the CVE base/modified URLs.
