### ISSUE TITLE
CVE Url Modified with Apache Server

### ISSUE THREAD

**Issue by RaphaelDG** [dependency-check/DependencyCheck#441]
Hi,
I'm trying to configure dependency-check, for entreprise usage, so I need to mirroring the CVE data.

I think that i'm using the correct configuration in my POM.xml https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

<code>
<reporting>
 <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>1.3.3</version>
                <configuration>
                    <format>XML</format>
                    <cveValidForHours>0</cveValidForHours>
                    <cveUrl12Modified>http://localhost:8080/NVDdata/nvdcve-Modified.xml.gz</cveUrl12Modified>
                    <cveUrl20Modified>http://localhost:8080/NVDdata/nvdcve-2.0-Modified.xml.gz</cveUrl20Modified>
                    <cveUrl12Base>http://localhost:8080/NVDdata/nvdcve-%d.xml.gz</cveUrl12Base>
                    <cveUrl20Base>http://localhost:8080/NVDdata/nvdcve-2.0-%d.xml.gz</cveUrl20Base> 
                </configuration>
            </plugin>
            </plugins>
    </reporting></code>

I use a local tomcat server where the cve.xml.gz are stored and the files are downloaded correctly.

But i've got trouble:
<i>
[DEBUG] Setting: cve.url-1.2.modified='http://localhost:8080/NVDdata/nvdcve-Modified.xml.gz'
[DEBUG] Setting: cve.url-2.0.modified='http://localhost:8080/NVDdata/nvdcve-2.0-Modified.xml.gz'
[DEBUG] Setting: cve.url-1.2.base='http://localhost:8080/NVDdata/nvdcve-%d.xml.gz'
[DEBUG] Setting: cve.url-2.0.base='http://localhost:8080/NVDdata/nvdcve-2.0-%d.xml.gz'
[DEBUG] Setting: cve.check.validforhours='0'
[DEBUG] Loading driver: org.h2.Driver
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: 'C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-utils\1.3.3'
[DEBUG] Settings.getDataFile() - returning: 'C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-utils\1.3.3....\dependency-check-data\3.0'
[DEBUG] Connection String: 'jdbc:h2:file:C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-data\3.0\dc;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;'
[DEBUG] Settings.getDataFile() - file: '[JAR]/../../dependency-check-data/3.0'
[DEBUG] Settings.getDataFile() - transforming filename
[DEBUG] Settings.getDataFile() - jar file: 'C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-utils\1.3.3'
[DEBUG] Settings.getDataFile() - returning: 'C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-utils\1.3.3....\dependency-check-data\3.0'
[DEBUG] Need to create DB Structure: false
[DEBUG] Loading database connection
[DEBUG] Connection String: jdbc:h2:file:C:\Program Files\Eclipse_DEV\Integration\maven\repository\org\owasp\dependency-check-data\3.0\dc;FILE_LOCK=SERIALIZED;AUTOCOMMIT=ON;
[DEBUG] Database User: dcuser
[DEBUG] Enabling the Central analyzer
[DEBUG] Nexus analyzer disabled, using Central instead
[DEBUG] Begin Scanning: fwk01 ROOT project
[DEBUG] Checking root project, root, if updates have already been completed
[INFO] Checking for updates
[DEBUG] Database dialect: H2
[INFO] NVD CVE requires several updates; this could take a couple of minutes.
[INFO] Download Started for NVD CVE - 2002
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2.0-2002.xml.gz
[INFO] Download Started for NVD CVE - 2003
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2.0-2003.xml.gz
[INFO] Download Started for NVD CVE - 2004
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2.0-2004.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2.0-2003.xml.gz complete
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2003.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2003.xml.gz complete
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2.0-2002.xml.gz complete
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2002.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2.0-2004.xml.gz complete
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2004.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2002.xml.gz complete
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2004.xml.gz complete
[INFO] Download Complete for NVD CVE - 2003  (93 ms)
[INFO] Download Started for NVD CVE - 2005
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2.0-2005.xml.gz
[INFO] Processing Started for NVD CVE - 2003
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2.0-2005.xml.gz complete
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2005.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2005.xml.gz complete
[INFO] Download Complete for NVD CVE - 2002  (405 ms)
[INFO] Download Started for NVD CVE - 2006
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2.0-2006.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2.0-2006.xml.gz complete
[DEBUG] Attempting download of http://localhost:8080/NVDdata/nvdcve-2006.xml.gz
[DEBUG] Download of http://localhost:8080/NVDdata/nvdcve-2006.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2006
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.extractGzip(DownloadTask.java:274)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:202)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[DEBUG] Thread was interrupted during download
[INFO] Download Complete for NVD CVE - 2004  (515 ms)
[WARNING] An exception occurred downloading NVD CVE - 2004
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@31fa42da rejected from java.util.concurrent.ThreadPoolExecutor@253b0fd8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
    at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:641)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:214)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[INFO] Download Complete for NVD CVE - 2005  (437 ms)
[WARNING] An exception occurred downloading NVD CVE - 2005
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@153a25ac rejected from java.util.concurrent.ThreadPoolExecutor@253b0fd8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
    at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:641)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:214)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[WARNING] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[DEBUG] Unable to update details for org.owasp.dependencycheck.data.update.NvdCveUpdater
org.owasp.dependencycheck.data.update.exception.UpdateException: The download was interrupted; unable to complete the update
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:183)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:72)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:433)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:318)
    at org.owasp.dependencycheck.maven.Engine.analyzeDependencies(Engine.java:86)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:250)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:231)
    at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:65)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:422)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:404)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:228)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
    at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[DEBUG] 
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
    at org.h2.message.DbException.get(DbException.java:178)
    at org.h2.message.DbException.get(DbException.java:154)
    at org.h2.engine.Session.prepareLocal(Session.java:420)
    at org.h2.engine.Session.prepareCommand(Session.java:384)
    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
    at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
    at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:468)
    at org.owasp.dependencycheck.data.update.nvd.NvdCve20Handler.saveEntry(NvdCve20Handler.java:267)
    at org.owasp.dependencycheck.data.update.nvd.NvdCve20Handler.endElement(NvdCve20Handler.java:160)
    at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importXML(ProcessTask.java:150)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:162)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:116)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:45)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
</i>

It's look like there is a problem with the file extention, but all of my cve files directly from nvd.gov and I didnt modified extentions (xml.gz).

PS: Maven is volontary not configured to use proxies, the plugin didn't need to connect to the internet because cve file are locally stored.

Thanks in advance,
R.D

**Comment by jeremylong** [comment]
There is obviously something wrong with 'nvdcve-2006.xml.gz'. I would try re-downloading the file and/or manually inspecting the file.

--Jeremy

**Comment by RaphaelDG** [comment]
Thanks, the problem was soveld by reDownloading manualy the 'nvdcve-2006.xml.gz' for a local server usage.
No I'm trying on an online Apache Server and I've got GZIP format error.

I can manualy download  WORKING nvdcve files with the HTTP link but with the plugin it say that the files are not in format GZIP (they has been uploaded in GZIP format).

Here is the DEBUG:
<i>The URLS has been censored:</i>

<i>[DEBUG] Download of http://**_/**_/***/nvdcve/nvdcve-2003.xml.gz complete
[WARNING] An exception occurred downloading NVD CVE - 2003
Some CVEs may not be reported.
[DEBUG] Download Task Failed
java.util.zip.ZipException: Not in GZIP format
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.extractGzip(DownloadTask.java:274)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:202)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
</i>

**Comment by RaphaelDG** [comment]
I found the solution, the problem appear when CVE data are mirrored on an Apache server.

Have a look on Apache config file server:
<b>
    # AddEncoding allows you to have certain browsers uncompress
    # information on the fly. Note: Not all browsers support this.
    #
    AddEncoding x-compress .Z
    AddEncoding x-gzip .gz .tgz
</b>

Apache is default configured to unzip .gzip archive "on the fly".

After removed the line: <b>AddEncoding x-gzip .gz .tgz</b>, the plugin can corectly unzip CVE files beacause they are not already uncompressed.

<b><u>On an Apache server with default configuration, answer header look like:</u></b>
<i>HTTP/1.1 200 OK
Date: Tue, 19 Jan 2016 10:01:14 GMT
Server: Apache/2.4.9 (Win64) PHP/5.5.12
Last-Modified: Mon, 04 Jan 2016 10:08:32 GMT
ETag: "6b00e-5287f4da68ec8"
Accept-Ranges: bytes
Content-Length: 438286
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: application/x-gzip
<b>Content-Encoding: x-gzip</b></i> 

<b>After removed the line 'AddEncoding x-gzip .gz .tgz' in the Apache configuration file, answer header request look like:</b>
<i>
HTTP/1.1 200 OK
Date: Tue, 19 Jan 2016 12:32:03 GMT
Server: Apache/2.4.9 (Win64) PHP/5.5.12
Last-Modified: Mon, 04 Jan 2016 10:08:57 GMT
ETag: "d7ae0-5287f4f242723"
Accept-Ranges: bytes
Content-Length: 438286
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
Content-Type: application/x-gzip
</i>

Note that <b>Content-Encoding: x-gzip</b> does not appear in answer queries after modification of the configuration Apache file.
Maybe it can be great for next update that the plugin can make difference when CVE are gziped or already uncompressed or when a answer query contain '<b>Content-Encoding: x-gzip</b>' (which probably  want say that .gzip files will be uncompressed on the fly) ?

PS: I can upload the PCAP files that contain dialog packet between Dependency-check and Apache or Tomcat server.

**Comment by RaphaelDG** [comment]
Any other opinions?

**Comment by RaphaelDG** [comment]
It's look that with Apache default configuration when Apache send a compressed file, Apache auto-decompress it.
But the plugin force to add ".gz" to the downloaded file, so it make unreadable GZarchive for the plugin, will you correct it?

At
dependency-check-core\src\main\java\org\owasp\dependencycheck\data\update\nvd\DownloadTask.java
line 238

 private void extractGzip(File file) throws FileNotFoundException, IOException {
        final String originalPath = file.getPath();
        final File gzip = new File(originalPath + ".gz");
        if (gzip.isFile() && !gzip.delete()) {
            gzip.deleteOnExit();


When I supress the .gz on the downloaded file, it make a perfectly readable xml file.

**Comment by RaphaelDG** [comment]
It's look that with Apache default configuration when Apache send a compressed file, Apache auto-decompress it.
 But the plugin force to add ".gz" to the downloaded file, so it make unreadable GZarchive for the plugin, will you correct it? @jeremylong 

At
 dependency-check-core\src\main\java\org\owasp\dependencycheck\data\update\nvd\DownloadTask.java
 line 238

private void extractGzip(File file) throws FileNotFoundException, IOException {
 final String originalPath = file.getPath();
 final File gzip = new File(originalPath + ".gz");
 if (gzip.isFile() && !gzip.delete()) {
 gzip.deleteOnExit();

When I supress the .gz on the downloaded file, it make a perfectly readable xml file.

**Comment by jeremylong** [comment]
Just pushed a change where the file content is tested to see if it needs to be extracted. This will be included in the next release.

Thanks!

Jeremy
