### ISSUE TITLE
DependencyCheck 1.3.3 fails behind proxy server

### ISSUE THREAD

**Issue by erik-wramner** [dependency-check/DependencyCheck#446]
We are using the Maven plugin for dependency check behind a proxy server. Once upon a time it worked. The latest version fails.

If we run it with Maven's proxy configuration it fails in EngineVersionCheck#getCurrentReleaseVersion, which connects without bothering about the proxy. As that version check is non-essential perhaps it should just return the active version on errors? And it should use the configured proxy...

If we run with the standard Java proxy settings (mvn dependency-check:check -Dhttp.proxyHost=ourproxy.example.com -Dhttp.proxyPort=80) and Maven's proxy the version check succeeds, but Downloader#getLastModified fails. It does not seem to use any of the configured proxy servers and fails.

As most big companies use proxy servers this should affect other shops than ours. I'll see if I can put together a pull request, but the code seems to be connecting using different mechanisms in several places - I don't know when I'll get time to really delve into it.

**Comment by jeremylong** [comment]
I'm not sure why these are acting differently in your environment. If you look at the code all of the HTTP Connections are initiated by `org.owasp.dependencycheck.utils.URLConnectionFactory`. There have been occasional reports of this type of issue - but I haven't found a reason behind this.

For the getLastModified - is there anychance that your proxy is blocking HEAD requests? See issue #278. I haven't exposed this configuration to the other interfaces yet (it is only avaible in the gradle plugin).  If that solves the problem that might be the problem. Any chance you could test this theory?

**Comment by erik-wramner** [comment]
Not impossible. I think I can test on Wednesday, I'll keep you posted!

**Comment by TorstenR** [comment]
I think we have exactly the same problem. We have also a maven build and we are behind a proxy. When i use the goals purge and check i am getting the following exception:

```
org.owasp.dependencycheck.utils.DownloadFailedException:` Error making HTTP HEAD request.
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:246)
    at org.owasp.dependencycheck.data.update.nvd.UpdateableNvdCve.add(UpdateableNvdCve.java:94)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveCurrentTimestampsFromWeb(NvdCveUpdater.java:299)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:231)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:70)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:433)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:318)
    at org.owasp.dependencycheck.maven.Engine.analyzeDependencies(Engine.java:86)
    at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:83)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:375)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: HEAD request returned a non-200 status code
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:240)
```

This problem is already solved in the gradle plugin, right?

**Comment by erik-wramner** [comment]
I upgraded to 1.3.4 and it complains about the HEAD request with the exception above, so that is probably it. Perhaps the downloader could catch exceptions for getLastModified and assume that the document is old if the request fails? Better an unnecessary download than a failure!

Proxy servers are always a pain.

**Comment by jeremylong** [comment]
This change did not make it into 1.3.4. However, I think setting the system property like this would work:

```
mvn -Ddownloader.quick.query.timestamp=false verify
```

Not ideal. I'll look into making this auto attempt to do a GET instead of HEAD if the HEAD fails for the next release.

**Comment by jeremylong** [comment]
Patch was just pushed that should resolve this issue without having to change any arguments. Is anyone experiencing this problem able to confirm?

**Comment by erik-wramner** [comment]
Great, I will test it on Wednesday, I'm not behind the proxy until then.

**Comment by TorstenR** [comment]
When I use the 1.3.5-SNAPSHOT, I get the same error i've mentioned above. But the solution with the get-request (`downloader-quick.query.timestamp=false`) doesn't work at all (maybe our proxy is too hard ;)).

**Comment by erik-wramner** [comment]
I can confirm that 1.3.5-SNAPSHOT works for us now. It picks up the Maven proxy and successfully downloads the files.

**Comment by TorstenR** [comment]
Ok, I got my problem. I have used the old URL in my maven config....

Now get the following SSLException:

```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:236)
    ... 33 more
```

But I think this problem is related to our proxy...

Thanks for the support!

**Comment by colezlaw** [comment]
If you know which cert it's failing on (either your proxy or NVD/CVE) you can either add the certificate itself or the signing chain to your trust store. If you don't have access to modify the system trust store (in $JAVA_HOME/lib/security/cacerts) you can copy it elsewhere and import it using keytool, then specify that trust store on the command line (`mvn -Djavax.net.ssl.trustStore=/path/to/cacerts`) or if you need to always have that set, you can set the environment variable `JAVA_TOOL_OPTIONS` to have `-Djavax.net.ssl.trustStore=/path/to/cacerts`.

**Comment by jeremylong** [comment]
Thanks for confirming that this is fixed. 

@TorstenR - if you are still having issues with this could you open a new ticket?

--Jeremy

**Comment by mmukherjee** [comment]
Hello,
I had the same problem while using the plugin. I am behind a corporate proxy and had the following configurations -

Plugin version: 1.3.6
The pom file being -
`<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>1.3.6</version>
                <configuration>
                    <dataDirectory>/someplace/data</dataDirectory>
                </configuration>
                <executions>
                  <execution>
                    <goals>
                      <goal>check</goal>
                    </goals>
                  </execution>
                </executions>
              </plugin>`

The settings file -
`<proxies>
    <proxy>
      <id>myproxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>blah blah</host>
      <port>8080</port>
      <username>blah</username>
      <password>blah</password>
    </proxy>
  </proxies>
</settings>`

Having said that - the suggestion above to use - 'mvn -Ddownloader.quick.query.timestamp=false' worked. But then, going from the comments above, I was expecting not to use this.

Just FYI - I had the same certificate-chaining issues as well, but thanks to the debug logs, I was able to identify which cert was missing and managed to fix it.

**Comment by jeremylong** [comment]
Thank you for the report. I may have to make the quick query timestamp a more full fledged configuration parameter... I'll also add some documentation around the certificate chaining to the site documentation.

Glad you got it working.
