### ISSUE TITLE
Error reading parsing NVD CVE file, Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by john047** [dependency-check/DependencyCheck#4686]
Hello,

I faced with following errors:
```
[ERROR] Removing file from cache for https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.json.gz as a corrupted download is detected
[ERROR] org.owasp.dependencycheck.data.update.exception.CorruptedDatastreamException: Error reading parsing NVD CVE file
org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.update.exception.CorruptedDatastreamException: Error reading parsing NVD CVE file
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:160)
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:114)
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:41)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.owasp.dependencycheck.data.update.exception.CorruptedDatastreamException: Error reading parsing NVD CVE file
at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:108)
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:141)
at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:154)
... 6 common frames omitted
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297)
at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:276)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipAfterComma2(ReaderBasedJsonParser.java:2409)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2404)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:947)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:284)
at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:101)
... 8 common frames omitted
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] org.owasp.dependencycheck.data.update.exception.CorruptedDatastreamException: Error reading parsing NVD CVE file
[ERROR] No documents exist
ERROR: Job failed: exit code 243
```
What could be causing these errors?

**Comment by aikebah** [comment]
Some proxy that delivers you an incomplete datastream without signalling an error.
On the next run ODC should re-attempt the download (as it nowadays disposes apparently faulty downloads from the cache), in the past it would continue breaking on the cached corrupt datastream until the cached file expired.

**Comment by lestephane** [comment]
> On the next run ODC should re-attempt the download

Why does it not validate the file prior to adding it to the cache in the first place? The cache should contain the last good know (as in, valid, not truncated) copy, always. And the plugin configuration should allow the user to configure how old the dump for the current year is allowed to be. So that, if the corruption lasts for more than a few days, the CI pipelines start to fail, but not before.

Does that make sense?

**Comment by aikebah** [comment]
Best  way in my view to prevent CI jobs from failing if the download of the streams turns out to be very unreliable is to disable autoupdate for the regular CI and have a dedicated job for CVE database update (update only goal). That job might periodically fail for a while due to file-corruption in the download, which would make the CVE database be out of date until it successfully runs again.
The regular CI runs would then continue to succesfully scan your projects for the older known CVEs.

**Comment by aikebah** [comment]
Note: the cached NVD stream files are only used in the process of update of the CVE database. It plays no role in the actual scan.
