### ISSUE TITLE
Invalid column name 'cveId'

### ISSUE THREAD

**Issue by dmowfo** [dependency-check/DependencyCheck#4888]
We have setup a MSSQL database and connection to this database is working fine. The database is updated as expected though we are seeing the following error later on in the process when trying to check vulnerabilities found against entries found in the DB 

Have you see this before? there are no references to cveId within the database

Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Exception retrieving vulnerability for cpe:2.3:a:microsoft:.net_core:4.700.19.56404:*:*:*:*:*:*:*
	at org.owasp.dependencycheck.data.nvdcve.CveDB.getVulnerabilities(CveDB.java:635)
	at org.owasp.dependencycheck.analyzer.NvdCveAnalyzer.lambda$analyzeDependency$2(NvdCveAnalyzer.java:65)
	... 18 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: **Invalid column name 'cveId'.**
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.getVulnerabilities(CveDB.java:582)

**Comment by jeremylong** [comment]
The `software.cveId` column is defined here: https://github.com/jeremylong/DependencyCheck/blob/a82cac41e97e9cbfa8fac99c3c0a5e3f2699b72d/core/src/main/resources/data/initialize_mssql.sql#L48

I'm not sure how you setup the database - but it does not appear to be correct and I can't believe the update worked without an exception.

**Comment by dmowfo** [comment]
Thanks for your response. We used the following script from here 

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/data/initialize_mssql.sql

The problem is the column is named cveid and the console app looks to the trying to check for a column called cveId (with an upper case I.

**Comment by jeremylong** [comment]
I really need to convert the SQL to standard Screaming Query Language...

**Comment by jeremylong** [comment]
Next release should be within a week.

**Comment by dmowfo** [comment]
Hi there. When do you expect the next release to be please? Thanks
