### ISSUE TITLE
During the upgrade of SLF4j 2.0.0 and Logback 1.3.0, I do not receive any server logs.

### ISSUE THREAD

**Issue by shubhamGoswami88** [dependency-check/DependencyCheck#4903]
During the upgrade of SLF4j 2.0.0 and Logback 1.3.0, I do not receive any server logs.

Getting the below exception 

Exception in thread "main" java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider ch.qos.logback.classic.spi.LogbackServiceProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
   
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/core/Context
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.Context
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 15 more

**Comment by mprins** [comment]
> t com.ericsson.rm.bcd.server.cmd.Command.(Command.java:13)

this is not about code in this repository

**Comment by jeremylong** [comment]
Fixed with 7.2.1: https://github.com/jeremylong/DependencyCheck/blob/main/RELEASE_NOTES.md#version-721-2022-09-20

**Comment by ABIRAMI1997** [comment]
Hi @jeremylong , can you specify how it got resolved,  the corresponding GitHub link is not showing up.
