### ISSUE TITLE
Exceptions running Ant-Task dependency-check

### ISSUE THREAD

**Issue by Bigdatha** [dependency-check/DependencyCheck#4975]
Hi,

we are getting the following exceptions when running the Ant-Task **dependency-check** (full stacktrace below): 
```
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
  InitializationException: An exception occurred accessing the database
    caused by DatabaseException: org.owasp.dependencycheck.data.cpe.IndexException: Unable to close an in-memory index
    caused by IndexException: Unable to close an in-memory index
    caused by AccessDeniedException: C:\Users\xxxxxxxx\AppData\Local\Temp\dctempb2c52b41-0fc1-40e5-a8d7-bd78597a0dde\_0_Lucene84_0.doc
```
We are working on Windows 10 Enterprise with Netbeans 15, Adoptium OpenJDK 1.8.322 and DependencyCheck 7.3.0.

We have tried it with other JDKs and different Versions of Netbeans and DependencyCheck (on several machines), but with no success (however on Ubuntu 20.04 using the same IDE and JDK it works absolute fine).

Any idea why DependencyCheck cannot acces a file in my/our own user temp directory ?

Thanks in advance !

#### Task configuration
```
  <property name="dependency-check.home" value="${dep.home}"/>
  <path id="dependency-check.path">
    <pathelement location="${dependency-check.home}/dependency-check-ant.jar"/>
    <fileset dir="${dependency-check.home}/lib">
      <include name="*.jar"/>
    </fileset>
  </path>
  <taskdef resource="dependency-check-taskdefs.properties">
    <classpath refid="dependency-check.path" />
  </taskdef>
  <target name="» Check Dependencies" description="Dependency-Check Analysis">
    <dependency-check 
      failOnError="false" 
      assemblyAnalyzerEnabled="false"
      projectname="${ant.project.name}" 
      reportformat="HTML" 
      prettyprint="true" 
      reportOutputDirectory="${dep.home}/reports/${ant.project.name}">
      <fileset dir="lib">
        <include name="**/*.jar"/>
      </fileset>
    </dependency-check>
  </target>
```
#### Full stacktrace
```
One or more exceptions occurred during analysis:
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	InitializationException: An exception occurred accessing the database
		caused by DatabaseException: org.owasp.dependencycheck.data.cpe.IndexException: Unable to close an in-memory index
		caused by IndexException: Unable to close an in-memory index
		caused by AccessDeniedException: C:\Users\xxxxxxxx\AppData\Local\Temp\dctempb2c52b41-0fc1-40e5-a8d7-bd78597a0dde\_0_Lucene84_0.doc
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:671)
	at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1926)
	at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1883)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor476.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:573)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
Next Exception:
org.owasp.dependencycheck.exception.InitializationException: An exception occurred accessing the database
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer(CPEAnalyzer.java:200)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:808)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:644)
	at org.owasp.dependencycheck.taskdefs.Check.callExecuteAnalysis(Check.java:1926)
	at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:1883)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor476.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:573)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: org.owasp.dependencycheck.data.cpe.IndexException: Unable to close an in-memory index
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:234)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer(CPEAnalyzer.java:194)
	... 23 more
Caused by: org.owasp.dependencycheck.data.cpe.IndexException: Unable to close an in-memory index
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.buildIndex(AbstractMemoryIndex.java:236)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.open(AbstractMemoryIndex.java:128)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:229)
	... 24 more
Caused by: java.nio.file.AccessDeniedException: C:\Users\xxxxxxxx\AppData\Local\Temp\dctempb2c52b41-0fc1-40e5-a8d7-bd78597a0dde\_0_Lucene84_0.doc
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:410)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:406)
	at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:254)
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.createOutput(LockValidatingDirectoryWrapper.java:44)
	at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:43)
	at org.apache.lucene.codecs.lucene84.Lucene84PostingsWriter.<init>(Lucene84PostingsWriter.java:107)
	at org.apache.lucene.codecs.lucene84.Lucene84PostingsFormat.fieldsConsumer(Lucene84PostingsFormat.java:420)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.write(PerFieldPostingsFormat.java:168)
	at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:120)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:267)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:350)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:476)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:656)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3364)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3770)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3728)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.buildIndex(AbstractMemoryIndex.java:230)
	... 26 more
```

**Comment by aikebah** [comment]
My first suspicion for such cases would be antivirus/antimalware software blocking the access due to some false positive

**Comment by aikebah** [comment]
note that .doc is also the file extension of the legacy MS Word documents

**Comment by Bigdatha** [comment]
You're right, of course ... i could have come up with it myself.
Thank you very much, @aikebah !
Now i have to convince our admins to adapt the rules for the virus scanner ... ;-)
