### ISSUE TITLE
Error parsing output from `go list -json -m all`

### ISSUE THREAD

**Issue by itsecforu** [dependency-check/DependencyCheck#5005]
$  go list -json -m all
```
{
        "Path": "mysite.com/project",
        "Main": true,
        "Dir": "/root/project",
        "GoMod": "/root/projectr/go.mod",
        "GoVersion": "1.19"
}

```
$ go list -json -deps
`no Go files in /root/projectt`

$ cat go.mod
```
module mysite.com/project
go 1.19

```

Output

```
`[WARN]` While analyzing `project/go.mod` `go` generated the following warnings:
go: updates to go.sum needed, disabled by -mod=readonly
[WARN] An error occurred while analyzing 'project/go.mod' (Golang Mod Analyzer).
[INFO] Finished Golang Mod Analyzer (1 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (1 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)

[ERROR] Error analyzing '/project/go.mod'; Error parsing output from `go list -json -m all`

```
log:

```
ERROR - Error analyzing '/project/go.mod'; Error parsing output from `go list -json -m all`
2022-10-31 11:18:37,475 org.owasp.dependencycheck.App:214
DEBUG - unexpected error
org.owasp.dependencycheck.analyzer.exception.AnalysisException: Error analyzing '/project/go.mod'; Error parsing output from `go list -json -m all`
	at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:67)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
	at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:438)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:128)
	at org.owasp.dependencycheck.data.golang.GoModJsonParser.process(GoModJsonParser.java:71)
	at org.owasp.dependencycheck.processing.GoModProcessor.run(GoModProcessor.java:62)
	... 1 common frames omitted
```

**Comment by jeremylong** [comment]
ODC won't make changes to your local files. The error message says the mod file needs to be updated - which can be done by running: `go list -json -m all`. See the sequence below and the blank line added to the `go.mod` file:

```bash
$ echo "module mysite.com/project   
go 1.19" > go.mod

$ cat go.mod                     
module mysite.com/project
go 1.19

$ go list -json -m -mod=readonly all
go: updates to go.mod needed, disabled by -mod=readonly

$ go list -json -m all              
{
	"Path": "mysite.com/project",
	"Main": true,
	"Dir": "/Users/jeremy/Projects/samples/go",
	"GoMod": "/Users/jeremy/Projects/samples/go/go.mod",
	"GoVersion": "1.19"
}

$ cat go.mod                        
module mysite.com/project

go 1.19

$ go list -json -m -mod=readonly all
{
	"Path": "mysite.com/project",
	"Main": true,
	"Dir": "/Users/jeremy/Projects/samples/go",
	"GoMod": "/Users/jeremy/Projects/samples/go/go.mod",
	"GoVersion": "1.19"
}
```
