### ISSUE TITLE
Incompatibility with maven 3.3.9

### ISSUE THREAD

**Issue by pnavato** [dependency-check/DependencyCheck#5151]
I have just upgraded to dependency-check 7.4.1 to eliminate some false positive.  Running the plugin with maven 3.3.9 I get the same error described in https://github.com/jeremylong/DependencyCheck/issues/1054.  If I use maven 3.5.3 it works fine.
Documentation at https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html still says "The plug-in requires Maven 3.1 or higher".  Is this a regression that will be fixed?  If not, please, update the doc with the new minimum maven version.

**Comment by StefanKock** [comment]
For documentation: I had the same problem with maven 3.3.9, but works with maven 3.6.3

StackTrace I encountered:
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.4.1:check (default) on project symeda-default-pom: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] ArtifactResolverException: com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionRangeResolver
[ERROR] for parameter 1 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
[ERROR] while locating java.lang.Object annotated with *
[ERROR] Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
[ERROR] at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[ERROR] at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[ERROR] at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[ERROR] at java.lang.reflect.Field.set(Field.java:764)
...
```
