### ISSUE TITLE
Out of memory exception with 7.4.1

### ISSUE THREAD

**Issue by antaln** [dependency-check/DependencyCheck#5175]
**Describe the bug**
Scan of a (proprietary) repository triggered via `mvn org.owasp:dependency-check-maven:7.4.1:aggregate -Dformats=HTML,CSV,XML,JSON,JUNIT` fails with java.lang.OutOfMemoryError, after consuming `[INFO] Final Memory: 1581M/3909M`.

Same repository worked with 7.4.0 on the same host with same maven configuration and heap size: `[INFO] Final Memory: 62M/2573M`

Repository has 300+ node_modules directories (apparently nested within modules inside the top-level node_modules dir).
I cannot share the package.json, but I could provide other statistics if they are relevant.

**Version of dependency-check used**
The problem occurs using version 7.4.1 of the maven plugin. It does not occur with 7.4.0.

**Log file**
Stack trace of failure:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:472)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:486)
        at java.lang.StringBuilder.append(StringBuilder.java:166)
        at org.owasp.dependencycheck.exception.ExceptionCollection.lambda$getMessage$2(ExceptionCollection.java:215)
        at org.owasp.dependencycheck.exception.ExceptionCollection$$Lambda$380/257065944.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.owasp.dependencycheck.exception.ExceptionCollection.getMessage(ExceptionCollection.java:212)
        at org.apache.maven.exception.DefaultExceptionHandler.getMessage(DefaultExceptionHandler.java:271)
        at org.apache.maven.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:121)
        at org.apache.maven.exception.DefaultExceptionHandler.handleException(DefaultExceptionHandler.java:93)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:879)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**To Reproduce**

1. Run `mvn org.owasp:dependency-check-maven:7.4.1:aggregate -Dformats=HTML,CSV,XML,JSON,JUNIT` on a repository with ~400 node_modules directories within modules of top_level node_modules directory.

**Expected behavior**
mvn should work with modest memory requirements.

**Additional context**

**Comment by antaln** [comment]
From the stack trace, it seems that it fails when composing a large list of exceptions, but I have no idea why there would be many more of them between 7.4.1 and 7.4.0 given the same repository state.

**Comment by aikebah** [comment]
Would you be able to share one or a few open-source node components from your package json that have a significant tree of nested node modules inside? That would make it easier for me (not being that familiar with the node ecosystem, so I don't know which packages typically haul in an ocean of transitive dependencies) to create a reproducer and debug what's going on.

**Comment by aikebah** [comment]
Gut feel regarding the out-of-memory is that your build runs into a bunch of OSSindex rate limit HTTP 429 (as I've also seen reports of many 429s with recent ODC versions I suspect that to be at the root of the 'too many exceptions in the exception collection triggering the out-of-memory on creation of the log message)
