### ISSUE TITLE
Could not connect to Central search

### ISSUE THREAD

**Issue by MokhFn** [dependency-check/DependencyCheck#5291]
**Describe the bug**
When using the latest version of DependencyCheck, i face an error : 
`[ERROR] Could not connect to Central search. Analysis failed.
`And the analysis keeps on trying for 7 attempts, then halts the process.

**Version of dependency-check used**
The problem occurs using the latest version.

**Log file** 

```
Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

💖 Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished Archive Analyzer (7 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (3 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Could not connect to MavenCentral (502): Bad Gateway
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted
[WARN] An error occurred while analyzing 'path/to/private/repo' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Could not connect to MavenCentral (504): Gateway Time-out
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted
[WARN] An error occurred while analyzing 'path/to/private/repo' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Could not connect to MavenCentral (504): Gateway Time-out
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted
[WARN] An error occurred while analyzing '/home/vsts/work/1/.m2/repository/org/scala-sbt/compiler-bridge_2.11/1.7.1/compiler-bridge_2.11-1.7.1-sources.jar' (Central Analyzer).
[INFO] Finished Central Analyzer (1144 seconds)
[INFO] Finished Assembly Analyzer (2 seconds)
[INFO] Finished PE Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished NPM CPE Analyzer (1 seconds)
[INFO] Created CPE Index (1 seconds)
[INFO] Finished CPE Analyzer (9 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished RetireJS Analyzer (3 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (7 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Finished Unused Suppression Rule Analyzer (0 seconds)
[INFO] Analysis Complete (1181 seconds)
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-report.xml
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-report.html
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-report.json
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-report.csv
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-report.sarif
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-jenkins.html
[INFO] Writing report to: /home/vsts/work/1/s/dependency-check/dependency-check-junit.xml
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.
[ERROR] Could not connect to Central search. Analysis failed.

Dependency Check completed with exit code 242.
Dependency Check reports:
[ '/home/vsts/work/1/s/dependency-check/dependency-check-jenkins.html',
  '/home/vsts/work/1/s/dependency-check/dependency-check-junit.xml',
  '/home/vsts/work/1/s/dependency-check/dependency-check-report.csv',
  '/home/vsts/work/1/s/dependency-check/dependency-check-report.html',
  '/home/vsts/work/1/s/dependency-check/dependency-check-report.json',
  '/home/vsts/work/1/s/dependency-check/dependency-check-report.sarif',
  '/home/vsts/work/1/s/dependency-check/dependency-check-report.xml' ]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 242)."
##[error]Dependency Check exited with an error code (exit code: 242).
Ending Dependency Check...
```

**Comment by buddy-security** [comment]
Me facing the same issue. I am using command line. Sitting behind a proxy.. I used the following command line:
dependency-check.bat --project "QHP 2.7" --scan "D:\Users\sss\Documents\QHP 2.7" --proxyserver blah.blahblah.net --proxyport 4343
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (126 ms)
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the userÆs risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

? Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished Archive Analyzer (16 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (6 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Could not connect to MavenCentral (504): Gateway Time-out
        at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
        ... 8 common frames omitted
[WARN] An error occurred while analyzing 'D:\Users\sss\Documents\QHP 2.7\agent\lib\activation-1.1.jar' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Could not connect to MavenCentral (504): Gateway Time-out
        at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
        at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
        ... 8 common frames omitted
[WARN] An error occurred while analyzing 'D:\Users\sss\Documents\QHP 2.7\agent\lib\antlr-2.7.7.jar' (Central Analyzer).
[ERROR] Could not connect to Central search. Analysis failed.

**Comment by ethesx** [comment]
@MokhFn  search.maven.org is down.

![Screenshot 2023-01-12 103942](https://user-images.githubusercontent.com/2558082/212111862-53c5eb76-872b-47ae-98d4-d73fb8ce628d.png)

**Comment by MokhFn** [comment]
@ethesx Oh, indeed, i should have checked that first, thanks !
I'll close the issue then.

**Comment by ryandutton** [comment]
Is anyone else seeing degraded performance with the Central Analyser? It's take around 14 minutes to complete each time I run Dependency Check.

<img width="406" alt="central" src="https://user-images.githubusercontent.com/72393782/212297741-2bb83881-2dcd-437d-a5ce-9415a330ce9f.png">

**Comment by kuldeep0508** [comment]
We are also facing the degraded performance with the Central Analyser

**Comment by yansifw** [comment]
Same degraded performance with Central Analyser

**Comment by ryandutton** [comment]
It took a while but they have finally acknowledged that there is another incident https://status.maven.org/incidents/mblzqd69jjpz

**Comment by aldobongio** [comment]
I can confirm that at the time of this writing it is still not working:
`INFO] Analysis Started
[INFO] Finished Archive Analyzer (52 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (9 seconds)
[ERROR] Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 7 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:364)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Could not connect to MavenCentral (504): Gateway Time-out
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:231)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:341)
	... 8 common frames omitted`
