### ISSUE TITLE
CentralAnalyzer.fetchMavenArtifacts failing to fetch files from https://search.maven.org

### ISSUE THREAD

**Issue by functicons** [dependency-check/DependencyCheck#5297]
Our CVE scanning got lots of errors from `CentralAnalyzer` when fetching pom files from https://search.maven.org. It looks like a transient error. I have a few questions:

1) I know I can disable CentralAnalyzer [1] with property `analyzer.central.enabled=false` or CLI flag `--disableCentral`, but could someone help me understand what the analyzer does and the consequence of disabling it. A concrete example would be helpful.
2) It is possible to get the artifacts from a local cache? our scanning should avoid external dependencies/connections.
3) Is there a backup site for search.maven.org?

```
[ERROR] Error retrieving https://search.maven.org/remotecontent?filepath=org/eclipse/persistence/jakarta.persistence/2.2.2/jakarta.persistence-2.2.2.pom; received response code 502; Bad Gateway
[ERROR] Analysis task was cancelled.
[ERROR] One or more fatal errors occurred
[WARN] An unexpected error occurred during analysis of '/workspace/bigtop/presto_340-1_all/usr/lib/presto/plugin/presto-pinot/larray-0.2.1.jar' (Central Analyzer): java.lang.InterruptedException: sleep interrupted
[ERROR] 
org.owasp.dependencycheck.analyzer.exception.UnexpectedAnalysisException: java.lang.InterruptedException: sleep interrupted
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:355)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:229)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:352)
	... 8 common frames omitted
```

[1]: https://github.com/jeremylong/DependencyCheck/blob/v7.4.4/core/src/main/java/org/owasp/dependencycheck/analyzer/CentralAnalyzer.java#L151

**Comment by uvwildos** [comment]
We had a full unprecedented production outage on thursday 12.January because of this issue.

https://serverfault.com/questions/1120168/access-denied-to-search-maven-org
https://issues.sonatype.org/browse/MVNCENTRAL-7785

it looks like a DOS attack filter on the gateway to the search.maven.org...
or some configuration errors in the server cluster?

So far the only solution was to disable the dependencyCheck in our CICD system.
Not a pretty workaround at all!

I am trying to use the nexus analyzer but without success so far.

**Comment by aikebah** [comment]
@uvwildos Disabling just the centralAnalyzer `--disableCentral` as documented on the [CLI configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) page should work to get dependency-check finishing successfully. It may however may trigger more False Positives (hence disabling it is discouraged for CLI-users) that you would have to suppress locally if dependency-check is configured build-breaking on vulnerabilities in your pipeline.

For libraries published on Maven Central that don't package the maven coordinate information (pom) CentralAnalyzer helps establish their proper G/A/V coordinates which help the logic to better match and reduce FP rates as many suppressions use the maven coordinates to select the applicable suppression-rule.

The Nexus analyzer AFAIK is coded to work with Nexus v2 only, so if you're trying against a Nexus v3 instance I expect it will indeed fail to work.

**Comment by alexandrumd** [comment]
Isn't it possible to handle a timeout exception in case CentralAnalyzer is down?
In the incident we had the timeout was basically given by the CI job execution limit of 1 hour (and the "fix" was to use the bash `timeout` since we call dependencyCheck from a bash script).
I presume that if after let's say 1 minute, dependency-check cannot use CentralAnalyzer to fetch pom files and what else it needs from https://search.maven.org/, it would be good to skip and not block/ hang execution for a very long time.

**Comment by yansifw** [comment]
Looks like CentralAnalyzer is down again, it would be nice to have a timeout in order to control these issues.
Thanks!

**Comment by uvwildos** [comment]
> @uvwildos Disabling just the centralAnalyzer `--disableCentral` as documented on the [CLI configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) page should work to get dependency-check finishing successfully. It may however may trigger more False Positives (hence disabling it is discouraged for CLI-users) that you would have to suppress locally if dependency-check is configured build-breaking on vulnerabilities in your pipeline.
> 
> For libraries published on Maven Central that don't package the maven coordinate information (pom) CentralAnalyzer helps establish their proper G/A/V coordinates which help the logic to better match and reduce FP rates as many suppressions use the maven coordinates to select the applicable suppression-rule.
> 
> The Nexus analyzer AFAIK is coded to work with Nexus v2 only, so if you're trying against a Nexus v3 instance I expect it will indeed fail to work.


Thanks a lot for this important config detail for disable Central  I did not get from the documentation! 
So I save wasting my time on trying to get this to work!!!

FROM SEARCH

> Sets whether the Nexus Analyzer will be used (requires Nexus v2 or Pro v3). You can.....

so the documentation thinks it should work with v3

**Comment by ryandutton** [comment]
There is an argument of `readtimeout` which at facevalue, looks like it would timeout any requests after initial connection is made. I am yet to confirm this https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by aikebah** [comment]
> > @uvwildos Disabling just the centralAnalyzer `--disableCentral` as documented on the [CLI configuration](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) page should work to get dependency-check finishing successfully. It may however may trigger more False Positives (hence disabling it is discouraged for CLI-users) that you would have to suppress locally if dependency-check is configured build-breaking on vulnerabilities in your pipeline.
> > For libraries published on Maven Central that don't package the maven coordinate information (pom) CentralAnalyzer helps establish their proper G/A/V coordinates which help the logic to better match and reduce FP rates as many suppressions use the maven coordinates to select the applicable suppression-rule.
> > The Nexus analyzer AFAIK is coded to work with Nexus v2 only, so if you're trying against a Nexus v3 instance I expect it will indeed fail to work.
> 
> Thanks a lot for this important config detail for disable Central I did not get from the documentation! So I save wasting my time on trying to get this to work!!!
> 
> FROM SEARCH
> 
> > Sets whether the Nexus Analyzer will be used (requires Nexus v2 or Pro v3). You can.....
> 
> so the documentation thinks it should work with v3

It may have worked for the early v3 beta's, but I think already quite early in the process the legacy API was removed. In any case NexusAnalyzer is attempting to access `<nexusURL>identify/sha1/<sha1 of jar>`, which back in the days of Nexus v2 was `https://<nexushost>/service/local/identify/sha1/<sha1 of jar>` If the identify-by-sha1 XML-over-HTTP service from back in v2 is still offered on v3 it should work, but to my knowledge (and according to all Google results I get) the services were replaced by a new JSON REST-API.
