### ISSUE TITLE
Checker fails on NVD JSON data

### ISSUE THREAD

**Issue by perleino** [dependency-check/DependencyCheck#5397]
**Describe the bug**
The checker is failing on downloaded data.

**Version of dependency-check used**
i tried 8.0.2 and 7.4.4  same problem on both 

**Log file**
```
    Error reading NVD JSON data: /tmp/dctempe2080850-4a0a-4330-a220-cd2028fd13b8/cve2011_10289635041315304727.json.gz
    
    > Task :dependencyCheckAnalyze
    Unable to find the NVD CVE file to parse
    org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to find the NVD CVE file to parse
    at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:124)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:141)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:154)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:114)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:41)
    at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
    Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end of ZLIB input stream (through reference chain: org.owasp.dependencycheck.data.nvd.json.DefCveItem["configurations"]->org.owasp.dependencycheck.data.nvd.json.DefConfigurations["nodes"]->java.util.ArrayList[0]->org.owasp.dependencycheck.data.nvd.json.DefNode["children"]->java.util.ArrayList[0]->org.owasp.dependencycheck.data.nvd.json.DefNode["cpe_match"]->java.util.ArrayList[23])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
    at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
    at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
    at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
    at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229)
    at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:113)
    ... 8 more
    Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
    at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
    at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
    at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
    at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
    at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
    at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:276)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipAfterComma2(ReaderBasedJsonParser.java:2486)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2481)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:950)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:285)
    at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
    ... 29 more
    Unable to continue dependency-check analysis.
    Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
```
**To Reproduce**
I just run the checker through a gradle plugin 
**Expected behavior**
I expect it not to fail

**Comment by mprins** [comment]
>  Unexpected end of ZLIB input stream

The downloaded zip file is corrupt; there is nothing we can do; this service is not under control of the project.
Failing the build is the smartest thing to do; not doing so would create a false statement of security.

**Comment by perleino** [comment]
Can it be filtered out or simliar?

**Comment by perleino** [comment]
ah.. the file was cached on our maven proxy.. so when we cleaned up the proxy, the issue disappeared 

closing this issue.

**Comment by constantin-baciu** [comment]
How did you clean your cache? I'm using Jenkins and this keeps happening.

**Comment by zhuchangzhi** [comment]
> 
in maven localRepository
org/owasp/dependency-check-data/7.0/nvdcache/nvdcve-1.1-2021.json.gz
default in ${user.home}/.m2/repository/
