### ISSUE TITLE
Number format exception when running dependency checker

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#54]
One of the NIST updates seems to be causing a number format exception

I am using version 1.0.4

INFO: Processing http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml
Exception in thread "main" java.lang.NumberFormatException: For input string: "2013418100420"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:495)
    at java.lang.Integer.parseInt(Integer.java:527)
    at org.owasp.dependencycheck.dependency.VulnerableSoftware.compareTo(VulnerableSoftware.java:188)
    at org.owasp.dependencycheck.dependency.VulnerableSoftware.compareTo(VulnerableSoftware.java:34)
    at java.util.TreeMap.compare(TreeMap.java:1188)
    at java.util.TreeMap.put(TreeMap.java:531)
    at java.util.TreeSet.add(TreeSet.java:255)
    at org.owasp.dependencycheck.dependency.Vulnerability.updateVulnerableSoftware(Vulnerability.java:187)
    at org.owasp.dependencycheck.dependency.Vulnerability.addVulnerableSoftware(Vulnerability.java:174)
    at org.owasp.dependencycheck.dependency.Vulnerability.addVulnerableSoftware(Vulnerability.java:157)
    at org.owasp.dependencycheck.data.nvdcve.NvdCve20Handler.endElement(NvdCve20Handler.java:197)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1789)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2965)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
    at org.owasp.dependencycheck.data.update.AbstractUpdateTask.importXML(AbstractUpdateTask.java:286)
    at org.owasp.dependencycheck.data.update.StandardUpdateTask.update(StandardUpdateTask.java:110)
    at org.owasp.dependencycheck.data.update.DatabaseUpdater.update(DatabaseUpdater.java:77)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:353)
    at org.owasp.dependencycheck.Engine.<init>(Engine.java:77)
    at org.owasp.dependencycheck.App.runScan(App.java:119)
    at org.owasp.dependencycheck.App.run(App.java:102)
    at org.owasp.dependencycheck.App.main(App.java:71)

**Comment by seanboylan** [comment]
Forgot to mention that this is causing dependency checker to crash

**Comment by jeremylong** [comment]
This is a known bug that has been fixed in 1.1.1. Please upgrade to the
latest version.

Thanks!

Jeremy
