### ISSUE TITLE
Offline build logs error connecting to jeremylong.github.io

### ISSUE THREAD

**Issue by Joshua-Barclay** [dependency-check/DependencyCheck#544]
We are trying to implement the DependencyCheck Maven module in our enterprise-wide parent POM.
Our enterprise environment is heavily controlled and therefore all Maven builds must be completed in a fully offline mode.

We have created an internal mirror of the CVE files and configured the Maven module to use the mirror.
Every build reports the following error when running offline:

``` java
java.net.UnknownHostException: jeremylong.github.io
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:208)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:176)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
        at java.net.Socket.connect(Socket.java:590)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:187)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:417)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:512)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:227)
        at sun.net.www.http.HttpClient.New(HttpClient.java:320)
        at sun.net.www.http.HttpClient.New(HttpClient.java:336)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:1004)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:940)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:858)
        at org.owasp.dependencycheck.data.update.EngineVersionCheck.getCurrentRe
leaseVersion(EngineVersionCheck.java:214)
        at org.owasp.dependencycheck.data.update.EngineVersionCheck.shouldUpdate
(EngineVersionCheck.java:148)
        at org.owasp.dependencycheck.data.update.EngineVersionCheck.update(Engin
eVersionCheck.java:113)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:492)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:346)

        at org.owasp.dependencycheck.maven.MavenEngine.analyzeDependencies(Maven
Engine.java:95)
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:97)

        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseD
ependencyCheckMojo.java:423)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:88)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:613)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
352)
```

Currently the only way to disable the outbound check to `jeremylong.github.io` is to set the key `autoupdate=false` which also disables the CVE update.

It would be very useful for controlled enterprise environments like ours to disable only the `jeremylong.github.io` autoupdate check via configuration.

**Comment by stevespringett** [comment]
If you've created an internal mirror then it's a best practice to run an updateonly job on a regular basis. This job should block all other dc jobs, which have autoupdate set to false.

If autoupdate is true and multiple dc jobs are executing at the same time, it's likely you'll run into database corruption issues.

**Comment by jeremylong** [comment]
The stack trace in the logs for that particular error can be ignored. I've updated the snapshot version to exclude the stack trace. While ODC does make an attempt to determine the latest published version by checking the gh-pages site; failures should be ignored. This check is done to let users know if a newer version of the tool is available.

The code changes to remove the stacktrace will be included in the next release.

**Comment by Joshua-Barclay** [comment]
I was aware that the error did not block the process, but I know that when we distribute it throughout our organisation many of our devs would not understand that.

Removing the stacktrace from the output completely addresses the issue from our perspective, thank you.
