### ISSUE TITLE
ant build owasp from jenkins issue:  Multiple Exceptions Occured

### ISSUE THREAD

**Issue by robertchen** [dependency-check/DependencyCheck#559]
BUILD FAILED
/ci/jenkins/jobs/01.Build.Nightly/workspace/dev/build/build-owasp.xml:25: Multiple Exceptions Occured
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occured during dependency-check analysis
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:427)
    at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:831)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.Main.runBuild(Main.java:853)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Next Exception:
org.owasp.dependencycheck.data.update.exception.UpdateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:232)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:82)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:492)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:346)
    at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:831)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.Main.runBuild(Main.java:853)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:221)
    ... 21 more
Caused by: java.lang.NullPointerException
    at org.owasp.dependencycheck.dependency.Reference.compareTo(Reference.java:144)
    at org.owasp.dependencycheck.dependency.Reference.compareTo(Reference.java:28)
    at java.util.TreeMap.compare(TreeMap.java:1290)
    at java.util.TreeMap.put(TreeMap.java:538)
    at java.util.TreeSet.add(TreeSet.java:255)
    at org.owasp.dependencycheck.dependency.Vulnerability.addReference(Vulnerability.java:110)
    at org.owasp.dependencycheck.data.update.nvd.NvdCve20Handler.endElement(NvdCve20Handler.java:205)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importXML(ProcessTask.java:150)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:162)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:116)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:45)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Total time: 42 seconds
Build step 'Conditional step (single)' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
ERROR: Failed to evaluate groovy script.
java.lang.NullPointerException: Cannot get property 'result' on null object
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:56)
    at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:156)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
    at Script1.run(Script1.groovy:3)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:580)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:618)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:589)
    at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:168)
    at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:362)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)

$ cat build-owasp.xml
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="dependency-check" name="owasp">

```
    <property name="owasp.report.dir" value="../../owasp"/>
    <property name="dependency-check.home" value="/ci/dependency-check-ant"/>

<path id="dependency-check.path">
    <pathelement location="${dependency-check.home}/dependency-check-ant.jar"/>
        <fileset dir="${dependency-check.home}/lib">
                <include name="*.jar"/>
        </fileset>
</path>

<taskdef resource="dependency-check-taskdefs.properties">
            <classpath refid="dependency-check.path" />
    </taskdef>

    <target name="init-dir">
            <mkdir dir="${owasp.report.dir}" />
    </target>

    <target name="dependency-check" description="Dependency-Check Analysis" depends="init-dir">
        <dependency-check projectname="Paymentus"
                          reportoutputdirectory="${owasp.report.dir}"
                          reportformat="ALL">

            <fileset dir="../Lib">
                <include name="**/*.jar"/>
            </fileset>
        </dependency-check>
</target>
```

</project>

**Comment by robertchen** [comment]
ant version: 1.9.6
building from command line is successful  , but sometimes not from jenkins

**Comment by jeremylong** [comment]
What version of dependency-check is being used?  1.4.3 was released and
likely includes fixes for this. Also, I would recommend deleting/purging
the current database when upgrading to 1.4.3.

On Sep 7, 2016 11:18 AM, "robertchen" notifications@github.com wrote:

ant version: 1.9.6
building from command line is successful , but sometimes not from jenkins

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/jeremylong/DependencyCheck/issues/559#issuecomment-245314612,
or mute the thread

**Comment by bloihl** [comment]
I was experiencing a similar problem with 1.4.2 using both Jenkins and the CLI that started on Friday (same stack trace wrt Reference#compareTo throwing the NPE). I worked on this today and upgrading to 1.4.3 CLI does in fact fix this issue. I have yet to verify using the jenkins plugin because we won't perform the update to the plugin until we have scheduled maintenance time.

**Comment by jeremylong** [comment]
Friday was when the (unexpected by me) data showed up in the feed from
NIST. So it looks like that was the issue you were experiencing. 1.4.3
should resolve the issue in jenkins as well.

Jeremy

**Comment by bloihl** [comment]
Yes, I know it will. Thank you for your quick fix!

**Comment by robertchen** [comment]
after update dependency-check-ant.jar and the lib files to the new jar files, the issue is gone.
