### ISSUE TITLE
IllegalArgumentException when running with MySQL Database

### ISSUE THREAD

**Issue by ercpe** [dependency-check/DependencyCheck#562]
We are running version 1.3.6 and 1.4.2/1.4.3 using maven. Starting a few days ago, we see an exception on every time the dependency check is executed.

Running in with -X shows 

```
[DEBUG] Initializing CPE Analyzer
[DEBUG] Database dialect: MySQL
[INFO] Creating the CPE Index
[ERROR] Unexpected exception occurred initializing CPE Analyzer.
[DEBUG] 
java.lang.IllegalArgumentException: Field must have either TokenStream, String, Reader or Number value; got stored,indexed,tokenized<product:>
    at org.apache.lucene.document.Field.tokenStream(Field.java:555)
    at org.apache.lucene.index.DocInverterPerField.processFields(DocInverterPerField.java:103)
    at org.apache.lucene.index.DocFieldProcessor.processDocument(DocFieldProcessor.java:248)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:253)
    at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:455)
    at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1534)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1204)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1185)
    at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.buildIndex(CpeMemoryIndex.java:214)
    at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.open(CpeMemoryIndex.java:119)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:159)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.initialize(CPEAnalyzer.java:133)
    at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:442)
    at org.owasp.dependencycheck.maven.MavenEngine.initializeAnalyzer(MavenEngine.java:137)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:380)
    at org.owasp.dependencycheck.maven.MavenEngine.analyzeDependencies(MavenEngine.java:95)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:314)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:291)
    at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:75)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:423)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
    at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:185)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[DEBUG] Initializing False Positive Analyzer
[DEBUG] Begin Analyzer 'False Positive Analyzer'
```

After that, the various Analyzer are executed (Dependency Building, Filename Analyzer, Jar Analyzer, etc.)

At the end:

```
.....
[DEBUG] Closing Analyzer 'Archive Analyzer'
[DEBUG] Attempting to delete temporary files
[DEBUG] Closing Analyzer 'File Name Analyzer'
[DEBUG] Closing Analyzer 'Jar Analyzer'
[DEBUG] Attempting to delete temporary files
[DEBUG] Closing Analyzer 'Central Analyzer'
[DEBUG] Closing Analyzer 'Nexus Analyzer'
[DEBUG] Closing Analyzer 'Nuspec Analyzer'
[DEBUG] Closing Analyzer 'Assembly Analyzer'
[DEBUG] Closing Analyzer 'OpenSSL Source Analyzer'
[DEBUG] Closing Analyzer 'Hint Analyzer'
[DEBUG] Closing Analyzer 'CPE Analyzer'
[DEBUG] Closing Analyzer 'False Positive Analyzer'
[DEBUG] Closing Analyzer 'Cpe Suppression Analyzer'
[DEBUG] Closing Analyzer 'Dependency Bundling Analyzer'
[DEBUG] Closing Analyzer 'NVD CVE Analyzer'
[DEBUG] Closing Analyzer 'Vulnerability Suppression Analyzer'
[DEBUG] 
----------------------------------------------------
END ANALYSIS
----------------------------------------------------
[INFO] Analysis Complete (11131 ms)
[DEBUG] Exception(s) analyzing Jenkins Test
Multiple Exceptions Occured
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occured during dependency-check analysis
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:427)
    at org.owasp.dependencycheck.maven.MavenEngine.analyzeDependencies(MavenEngine.java:95)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:314)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:291)
    at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:75)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:423)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
    at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:185)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Next Exception:
org.owasp.dependencycheck.exception.InitializationException: Unexpected Exception
    at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:460)
    at org.owasp.dependencycheck.maven.MavenEngine.initializeAnalyzer(MavenEngine.java:137)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:380)
    at org.owasp.dependencycheck.maven.MavenEngine.analyzeDependencies(MavenEngine.java:95)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:314)
    at org.owasp.dependencycheck.maven.AggregateMojo.generateDataFile(AggregateMojo.java:291)
    at org.owasp.dependencycheck.maven.AggregateMojo.runCheck(AggregateMojo.java:75)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:423)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
    at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:185)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
    at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Field must have either TokenStream, String, Reader or Number value; got stored,indexed,tokenized<product:>
    at org.apache.lucene.document.Field.tokenStream(Field.java:555)
    at org.apache.lucene.index.DocInverterPerField.processFields(DocInverterPerField.java:103)
    at org.apache.lucene.index.DocFieldProcessor.processDocument(DocFieldProcessor.java:248)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:253)
    at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:455)
    at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1534)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1204)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1185)
    at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.buildIndex(CpeMemoryIndex.java:214)
    at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.open(CpeMemoryIndex.java:119)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:159)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.initialize(CPEAnalyzer.java:133)
    at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:442)
    ... 39 more
```

**Comment by Lucas-C** [comment]
Same error here

**Comment by jeremylong** [comment]
As mentioned in the [release notes](https://groups.google.com/forum/#!topic/dependency-check/88ctFUZBIns) I would highly recommend everyone upgrade to 1.4.3. As part of the upgrade, the database should be recreated.

Do you still see the issue after re-creating the database and having all clients using 1.4.3?

**Comment by ercpe** [comment]
Version 1.4.3 looks better. I'll try a few more projects and report back.

**Comment by jeremylong** [comment]
@ercpe can this issue be closed or are you still seeing a problem?

**Comment by ercpe** [comment]
Yes, we're running 1.4.3 with multiple projects now and everything seems to be OK now.
Thanks for your help.
