### ISSUE TITLE
Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta; received response code 503; Service Unavailable

### ISSUE THREAD

**Issue by larrydiamond** [dependency-check/DependencyCheck#5630]
Totally not a bug here, but does cause gradle to fail.    Thank you for making a great tool!

> Task :dependencyCheckAnalyze
Verifying dependencies for project sqgraph
Checking for updates and analyzing dependencies for vulnerabilities
Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta; received response code 503; Service Unavailable
Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta; received response code 503; Service Unavailable
Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta; received response code 503; Service Unavailable
Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta; received response code 503; Service Unavailable
Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.doMetaDownload(NvdCveUpdater.java:410)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:355)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:501)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:133)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:900)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:705)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:631)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:100)
        at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by aikebah** [comment]
There is also not a question in your ticket. When you search the closed tickets you will find numerous tickets for similar cases including mitigations

https://github.com/jeremylong/DependencyCheck/issues?q=is%3Aissue+nvd+503
