### ISSUE TITLE
Add flag for docker container to disable PEAnalyzer

### ISSUE THREAD

**Issue by trdyer** [dependency-check/DependencyCheck#5838]
**Is your feature request related to a problem? Please describe.**
We are currently seeing errors where analyzing Google.Protobuff.dll is failing. I am basing this off the following log file, but to be honest where the logs are showing results from many threads it could be a different file.

```
2023-07-25 14:50:35,103 org.owasp.dependencycheck.AnalysisTask:90
WARN  - An error occurred while analyzing '/src/src/<REDACTED>/bin/Debug/net7.0/Google.Protobuf.dll' (PE Analyzer).
2023-07-25 14:50:35,107 org.owasp.dependencycheck.AnalysisTask:91
DEBUG - 
org.owasp.dependencycheck.analyzer.exception.AnalysisException: java.io.EOFException: Expected to read bytes from the stream
	at org.owasp.dependencycheck.analyzer.PEAnalyzer.analyzeDependency(PEAnalyzer.java:273)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException: Expected to read bytes from the stream
	at org.boris.pecoff4j.io.DataReader.safeRead(DataReader.java:157)
	at org.boris.pecoff4j.io.DataReader.skipBytes(DataReader.java:85)
	at org.boris.pecoff4j.io.ResourceParser.alignDataReader(ResourceParser.java:299)
	at org.boris.pecoff4j.io.ResourceParser.readStringPair(ResourceParser.java:217)
	at org.boris.pecoff4j.io.ResourceParser.readStringTable(ResourceParser.java:204)
	at org.boris.pecoff4j.io.ResourceParser.readStringFileInfo(ResourceParser.java:246)
	at org.boris.pecoff4j.io.ResourceParser.readVersionInfo(ResourceParser.java:151)
	at org.boris.pecoff4j.io.ResourceParser.readVersionInfo(ResourceParser.java:122)
	at org.owasp.dependencycheck.analyzer.PEAnalyzer.analyzeDependency(PEAnalyzer.java:165)
	... 7 common frames omitted
```

**Describe the solution you'd like**
We wish to leave the other --experimental analyzers enabled. Other analyzers appear to have the ability to pass a CLI flag to dependency-check.sh that will disable various analyzers.

Something like `--disablePEAnalyzer` that would disable the analyzer.

**Describe alternatives you've considered**
We could disable all analyzers but there doesn't appear to be an `enable` option other than --experimental.

**Additional context**
We are running the docker container as part of a github action.

**Comment by trdyer** [comment]
As well I would also love to see something like the `ossIndexRemoteErrorWarnOnly` flag that would allow us to treat the errors as warnings rather than being fatal.

**Comment by aikebah** [comment]
@trdyer for the latter I presume you'd like a similar switch as `failOnError` for the [maven plugin](http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)? That is: a flag that is by default true, causing it to exit with RC 13 on fatal errors and RC 14 on non-fatal errors (e.g. errors of individual analyzers so that the results of the tool are to be considered incomplete), changing the behavior for non-fatal errors to return RC 0 as if all went well (still breaking on fatal errors)
