### ISSUE TITLE
 An error appeared after upgrading from version 8.4.0 to version 8.4.1. The element type "logger" must be terminated by the matching end-tag "</logger>".

### ISSUE THREAD

**Issue by readonlyuser1** [dependency-check/DependencyCheck#6001]
When scanning we always see this error.
This error also appears if you do --updateonly.
Logs: https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559
![image](https://github.com/jeremylong/DependencyCheck/assets/89613988/9c797103-605b-4f02-b143-7862c8fe519a)

**/usr/share/dependency-check/bin/dependency-check.sh --updateonly**
INFO[0017] Running: [/bin/sh -c /usr/share/dependency-check/bin/dependency-check.sh --updateonly] 
`
Failed to auto configure default logger context
Reported exception:
ch.qos.logback.core.joran.spi.JoranException: Problem parsing XML document. See previously reported errors.
	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:65)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:64)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:134)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:[41](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L41)7)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at org.owasp.dependencycheck.App.<clinit>(App.java:63)
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/usr/share/dependency-check/lib/dependency-check-cli-8.4.1.jar!/logback.xml; lineNumber: 17; columnNumber: 3; The element type "logger" must be terminated by the matching end-tag "</logger>".
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:12[51](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L51))
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:59)
	... 13 more
01:07:10,[56](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L56)5 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
01:07:10,566 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/share/dependency-check/lib/dependency-check-cli-8.4.1.jar!/logback.xml]
01:07:10,[57](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L57)7 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1ad282e0 - URL [jar:file:/usr/share/dependency-check/lib/dependency-check-cli-8.4.1.jar!/logback.xml] is not of type file
01:07:10,6[60](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L60) |-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@7f41[63](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L63)10 - XML_PARSING - Parsing fatal error on line 17 and column 3
01:07:10,[66](https://gitlab.com/gitlab-ci-utils/docker-dependency-check/-/jobs/5345141559#L66)0 |-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@7f416310 - org.xml.sax.SAXParseException; systemId: jar:file:/usr/share/dependency-check/lib/dependency-check-cli-8.4.1.jar!/logback.xml; lineNumber: 17; columnNumber: 3; The element type "logger" must be terminated by the matching end-tag "</logger>".`

**Comment by jeremylong** [comment]
Sorry about that - the updated version should be released shortly.
