### ISSUE TITLE
Bug: mono-devel required to succesfully parse .Net binaries

### ISSUE THREAD

**Issue by mhohimer** [dependency-check/DependencyCheck#607]
On Ubuntu16.04 (and maybe other linux variants), mono-runtime and mono-devel are required for the tool to successfully parse .dll files.

When mono-devel is not present, GrokAssembly.exe writes a warning message to stdout, causing the following exception (this is for tag 1.4.3):

> org.owasp.dependencycheck.analyzer.exception.AnalysisException: Couldn't parse GrokAssembly result
        at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.analyzeFileType(AssemblyAnalyzer.java:182)
        at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.analyze(AbstractFileTypeAnalyzer.java:193)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:401)
        at org.owasp.dependencycheck.App.runScan(App.java:271)
        at org.owasp.dependencycheck.App.run(App.java:163)
        at org.owasp.dependencycheck.App.main(App.java:68)
Caused by: org.xml.sax.SAXParseException: Content is not allowed in trailing section.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.analyzeFileType(AssemblyAnalyzer.java:131)
        ... 5 common frames omitted

**Comment by jeremylong** [comment]
The documentation and error messages have been updated.
