### ISSUE TITLE
Elixir mix_audit results are failing with parsing at dependency checks

### ISSUE THREAD

**Issue by AbhilashR2020** [dependency-check/DependencyCheck#6074]
**Describe the bug**
The mix_audit response is failing, and due to which the scan check is not including the results of elixir

**Version of dependency-check used**
The problem occurs using version 8.4.3 of the cli

**Log file**
[INFO] Launching: [/home/test/.mix/escripts/mix_audit, --version] from /tmp/dctemp6548414e-8f7c-4fde-8ff5-9ac9c4251ace
[INFO] Launching: [/home/test/.mix/escripts/mix_audit, --format, json] from /home/test/DDDD/CONTINUATION_HEADERS/test-api
Exception in thread "Thread-12" java.lang.NullPointerException
        at org.owasp.dependencycheck.data.elixir.MixAuditJsonParser.process(MixAuditJsonParser.java:117)
        at org.owasp.dependencycheck.processing.MixAuditProcessor.processMixAuditOutput(MixAuditProcessor.java:138)
        at org.owasp.dependencycheck.processing.MixAuditProcessor.run(MixAuditProcessor.java:95)
        at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] Finished Elixir Mix Audit Analyzer (1 seconds)

**To Reproduce**
run scan check on elixir application
 ./bin/dependency-check.sh --enableExperimental -s /home/test/DDDDDD/CONTINUATION_HEADERS/test-api/ -f JSON

**Expected behavior**
The response from mix_audit seems coming fine. but json parsing is failing. The output results in a final html report with elixir error

**Additional context**

**Comment by chadlwilson** [comment]
Closing this due to it being stale/old and not having easy reproduction instructions. If it is still an issue please give clearer instructions on how to reproduce.
