### ISSUE TITLE
I have a problem with OWASP owasp-dependency-check

### ISSUE THREAD

**Issue by diecolbe** [dependency-check/DependencyCheck#6158]
**Describe the bug**
[ERROR] Error updating the NVD Data
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:338)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:110)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:904)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:709)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:635)
	at org.owasp.dependencycheck.App.runScan(App.java:261)
	at org.owasp.dependencycheck.App.run(App.java:193)
	at org.owasp.dependencycheck.App.main(App.java:88)
Caused by: io.github.jeremylong.openvulnerability.client.nvd.NvdApiException: NVD Returned Status Code: 403
	at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:346)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:317)
	... 7 common frames omitted

**Comment by reespozzi** [comment]
Experiencing this as well, with the addition of a bunch of 
```
NVD API request failures are occurring; retrying request for the 5 time
NVD API request failures are occurring; retrying request for the 6 time
NVD API request failures are occurring; retrying request for the 7 time
NVD API request failures are occurring; retrying request for the 8 time
NVD API request failures are occurring; retrying request for the 9 time
NVD API request failures are occurring; retrying request for the 10 time
NVD API request failures are occurring; retrying request for the 11 time
NVD API request failures are occurring; retrying request for the 5 time
NVD API request failures are occurring; retrying request for the 6 time
```
before this error is spat out

**Comment by hylkevds** [comment]
Ran into the same issue, and noticed the API-Key warning. So, I tried that:

> Exception generating email

Seems like the NVD API is not quite ready for use :)

**Comment by jeremylong** [comment]
See #6149
