### ISSUE TITLE
maven plugin: 9.0.1  java.lang.NoClassDefFoundError: org/apache/commons/jcs3/engine/CacheStatus

### ISSUE THREAD

**Issue by sysmat** [dependency-check/DependencyCheck#6160]
**Describe the bug**
When using version 9.0.1 there is error

**Version of dependency-check used**
The problem occurs using version 9.0.1 of the ____ (maven plugin)

```xml
<plugin>
     <groupId>org.owasp</groupId>
     <artifactId>dependency-check-maven</artifactId>
    <version>9.0.1</version>

```
**Log file**
When reporting errors, 99% of the time log file output is required. Please post the log file as a [gist](https://gist.github.com/) and provide a link in the new issue.

```
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: org/apache/commons/jcs3/engine/CacheStatus
	at org.apache.commons.jcs3.auxiliary.disk.AbstractDiskCache.getStatus(AbstractDiskCache.java:493)
	at org.apache.commons.jcs3.engine.control.CompositeCache.dispose(CompositeCache.java:1232)
	at org.apache.commons.jcs3.engine.control.CompositeCacheManager.freeCache(CompositeCacheManager.java:580)
	at org.apache.commons.jcs3.engine.control.CompositeCacheManager.freeCache(CompositeCacheManager.java:567)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4647)
	at org.apache.commons.jcs3.engine.control.CompositeCacheManager.shutDown(CompositeCacheManager.java:620)
	at org.apache.commons.jcs3.engine.control.CompositeCacheManager.lambda$initialize$0(CompositeCacheManager.java:248)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.jcs3.engine.CacheStatus
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
```

**To Reproduce**
1. just run maven goal with dependency-check-maven

**Expected behavior**
to work

**Additional context**
- it is regresion from 8.4.3 version
- java 8
- maven 3.9.5

**Comment by dbwiddis** [comment]
Duplicate of #6141

**Comment by sysmat** [comment]
@dbwiddis thx, I didn't see it
