### ISSUE TITLE
Gradle Plugin: NullPointerException in ReportTool

### ISSUE THREAD

**Issue by JessHolle** [dependency-check/DependencyCheck#6187]
When running v9.0.2 of the Gradle plugin's `dependencyCheckAnalyze` task, I get:
```
> Invocation of method 'normalizeSeverity' in  class org.owasp.dependencycheck.reporting.ReportTool threw exception java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "sev" is null at templates/gitlabReport.vsl[line 97, column 23]
```

I don't have a full stack trace because this is happening in a CI/CD environment, though clearly we can modify that to request a full stack trace if need be.

Oddly when I ran this on my own machine prior to pushing to CI/CD the task ran just fine.

Plugin configuration used is:
```
dependencyCheck {
  scanConfigurations = ['releaseRuntimeClasspath']
  suppressionFile = "${projectDir}/../owasp-dep-check-suppressions.xml"
  format = 'ALL'

  // increase this level if need be but for now we strictly hold the line at no vulnerabilities
  failBuildOnCVSS = 0.1

  nvd {
    apiKey=NVDApiKey
  }
}
```

**Comment by jeremylong** [comment]
Apparently "ALL" is broken - because the gitlab report is broken...

**Comment by jeremylong** [comment]
oh... I think I just figured out why... I'll have to put this on a backlog and fix it next week though. Some CVEs don't have a CVSSv3... I think the contributed report my only support v3...

**Comment by JessHolle** [comment]
Ah...

So:
1. Is this indeed specific to the Gitlab report (and thus we can work around this by listing specific other reports)?
2. Is there a separate issue open on the report issue to link this to?  Or should we continue to track via this issue?

**Comment by jeremylong** [comment]
@weyhmueller or @niklasfi mind taking a look at this one?  In other reports we check if the CVSSv3 is present and if it is not we look for the CVSSv2. 

@JessHolle correct - this is specific to the GitLab report so you can just specify all of the reports you need and just skip the GitLab one. This issue will continue to be tracked here.

**Comment by jeremylong** [comment]
I would fix this right now - but due to work and travel I may not be able to get to this until next week.

**Comment by weyhmueller** [comment]
Should be fixed with #6193. I changed it to use the same logic like other reports do.

**Comment by jeremylong** [comment]
Thanks - I'll likely be able to release this in 2-3 days.

**Comment by platformbeheer-otv** [comment]
If anyone is interested, got this stacktrace in 9.0.2

```
[INFO] Analysis Complete (32 seconds)
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.xml
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.html
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.json
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.csv
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.sarif
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-jenkins.html
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-junit.xml
[INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-gitlab.json
Exception in thread "main" org.apache.velocity.exception.MethodInvocationException: Invocation of method 'normalizeSeverity' in  class org.owasp.dependencycheck.reporting.ReportTool threw exception java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "sev" is null at templates/gitlabReport.vsl[line 97, column 23]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:308)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:235)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:704)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:75)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:242)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
	at org.apache.velocity.runtime.directive.Foreach.renderBlock(Foreach.java:309)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:279)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
	at org.apache.velocity.runtime.directive.Foreach.renderBlock(Foreach.java:309)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:279)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
	at org.apache.velocity.runtime.RuntimeInstance.render(RuntimeInstance.java:1519)
	at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1450)
	at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:239)
	at org.owasp.dependencycheck.reporting.ReportGenerator.processTemplate(ReportGenerator.java:469)
	at org.owasp.dependencycheck.reporting.ReportGenerator.processTemplate(ReportGenerator.java:427)
	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:357)
	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:351)
	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:327)
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1264)
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1213)
	at org.owasp.dependencycheck.App.runScan(App.java:272)
	at org.owasp.dependencycheck.App.run(App.java:194)
	at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "sev" is null
	at org.owasp.dependencycheck.reporting.ReportTool.normalizeSeverity(ReportTool.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)
	... 28 more
##[error]The operation was canceled.
##[section]Finishing: Dependency Check
```

**Comment by squelix** [comment]
> If anyone is interested, got this stacktrace in 9.0.2
> 
> ```
> [INFO] Analysis Complete (32 seconds)
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.xml
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.html
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.json
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.csv
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-report.sarif
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-jenkins.html
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-junit.xml
> [INFO] Writing report to: D:\azagent-p\A1\_work\25\TestResults\dependency-check-gitlab.json
> Exception in thread "main" org.apache.velocity.exception.MethodInvocationException: Invocation of method 'normalizeSeverity' in  class org.owasp.dependencycheck.reporting.ReportTool threw exception java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "sev" is null at templates/gitlabReport.vsl[line 97, column 23]
> 	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:308)
> 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:235)
> 	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)
> 	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:704)
> 	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:75)
> 	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:242)
> 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
> 	at org.apache.velocity.runtime.directive.Foreach.renderBlock(Foreach.java:309)
> 	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:279)
> 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
> 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
> 	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)
> 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
> 	at org.apache.velocity.runtime.directive.Foreach.renderBlock(Foreach.java:309)
> 	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:279)
> 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
> 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
> 	at org.apache.velocity.runtime.RuntimeInstance.render(RuntimeInstance.java:1519)
> 	at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1450)
> 	at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:239)
> 	at org.owasp.dependencycheck.reporting.ReportGenerator.processTemplate(ReportGenerator.java:469)
> 	at org.owasp.dependencycheck.reporting.ReportGenerator.processTemplate(ReportGenerator.java:427)
> 	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:357)
> 	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:351)
> 	at org.owasp.dependencycheck.reporting.ReportGenerator.write(ReportGenerator.java:327)
> 	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1264)
> 	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1213)
> 	at org.owasp.dependencycheck.App.runScan(App.java:272)
> 	at org.owasp.dependencycheck.App.run(App.java:194)
> 	at org.owasp.dependencycheck.App.main(App.java:89)
> Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "sev" is null
> 	at org.owasp.dependencycheck.reporting.ReportTool.normalizeSeverity(ReportTool.java:126)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)
> 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)
> 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)
> 	... 28 more
> ##[error]The operation was canceled.
> ##[section]Finishing: Dependency Check
> ```

I have the same errors in 9.0.2.
