### ISSUE TITLE
Using cached NVD Data feed results in NullPointerException

### ISSUE THREAD

**Issue by UlrichLohrmann** [dependency-check/DependencyCheck#6202]
**Describe the bug**
I cached the NVD data feed using vulnz API and uploaded all downloaded *json.gz files into a RAW Nexus repository. When executing OWAP dependency check I reference the cached NVD data using --nvdDatafeed command line option. Result is a NPE

Exception in thread "main" java.lang.NullPointerException
        at java.base/java.time.ZoneId.from(Unknown Source)
        at java.base/java.time.ZonedDateTime.from(Unknown Source)
        at java.base/java.time.ZonedDateTime.until(Unknown Source)
        at java.base/java.time.Duration.between(Unknown Source)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.checkUpdate(NvdApiDataSource.java:443)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.processDatafeed(NvdApiDataSource.java:117)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:108)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:711)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:637)
        at org.owasp.dependencycheck.App.runScan(App.java:262)
        at org.owasp.dependencycheck.App.run(App.java:194)
        at org.owasp.dependencycheck.App.main(App.java:89)

**Version of dependency-check used**
The problem occurs using version X9.0.2 of the cli

**To Reproduce**

Call dependency check with --nvdDatafeed option

dependency-check.sh --nvdDatafeed 'https://host/nexus3/repository/NVDApiCache/nvdcve-{0}.json.gz' -o '...' -f HTML -f XML -s '...' --nvdApiKey '...' --disableRetireJS --disableAssembly

**Expected behavior**
No NPE

Regards
Ulrich

**Comment by jeremylong** [comment]
Try running purge. This looks like it might be an issue with using a database created with 8.4.3 and then trying to utilize 9.x.

**Comment by jeremylong** [comment]
While I did just create a PR to resolve the NPE - running purge should resolve the issue for you.

**Comment by UlrichLohrmann** [comment]
Running dependecy-check.sh --purge solved this. 

Thank you very much for this fast reply.
