### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError DependencyCheck jenkins plugin 9.0.8

### ISSUE THREAD

**Issue by zdani7** [dependency-check/DependencyCheck#6418]
Initially, the report was generated successfully, but this week it has started to fail in all pipelines. The error that it shows is as follows:

`Exception in thread "main" java.lang.NoSuchMethodError: org.owasp.dependencycheck.data.nvdcve.DatabaseProperties.getTimestamp(Ljava/lang/String;)Ljava/time/ZonedDateTime;
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:287)
	at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:116)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:900)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:705)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:631)
	at org.owasp.dependencycheck.App.runScan(App.java:259)
	at org.owasp.dependencycheck.App.run(App.java:191)
	at org.owasp.dependencycheck.App.main(App.java:86)
ERROR: Mark build as failed because of exit code 1`

Appreciate your help

**Comment by aikebah** [comment]
Jenkins plugin support is at https://plugins.jenkins.io/dependency-check-jenkins-plugin/

From the symptoms it looks as if your Jenkins setup has corrupted its DependencyCheck CLI installation somehow
