### ISSUE TITLE
MAC Unable connect to database 

### ISSUE THREAD

**Issue by rocenpe** [dependency-check/DependencyCheck#6423]
**Describe the bug**
I can not connect to dependency check database from mac station. 
From windows and linux functional well. On mac I connect via DBever functional well too.

I run command:
bash ~/Downloads/dependency-check/bin/dependency-check.sh  -f HTML -f JSON --out Artifacts --enableExperimental --scan /Users/mNDBMB/Library/Developer/Xcode/DerivedData/Imos-dxrtibiixlstpycbbmkwwmvbhlhz/SourcePackages --log Artifacts/dependency-check-log.log --disableBundleAudit --propertyfile ~/dependencycheck.properties  --dbDriverPath ~/Downloads/postgresql-42.7.1.jar

**Version of dependency-check used**
database version 8.2.1
I try use client dependency check version 8.2.1 and 9.0.9.
I try use postgresql java driver 42.5.4 and 42.7.1

**Log file**
2024-01-25 12:32:33,100 org.owasp.dependencycheck.analyzer.AnalyzerService:113
DEBUG - Loaded Analyzer Libman Analyzer
2024-01-25 12:32:33,101 org.owasp.dependencycheck.utils.Settings:1170
DEBUG - Settings.getDataFile() - file: '/Users/mNDBMB/Downloads/dependency-check/data'
2024-01-25 12:32:33,651 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:143
DEBUG - Loading driver 'org.postgresql.Driver'
2024-01-25 12:32:33,657 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:146
DEBUG - Loading driver from: /Users/mNDBMB/Downloads/postgresql-42.7.1.jar
2024-01-25 12:32:33,679 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:178
DEBUG - Loading database connection
2024-01-25 12:32:33,680 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:179
DEBUG - Connection String: jdbc:postgresql://P054P001.PROD.KB.CZ:5432/dc_prod
2024-01-25 12:32:33,680 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:180
DEBUG - Database User: dcuser
2024-01-25 12:32:43,816 org.owasp.dependencycheck.data.nvdcve.DatabaseManager:204
DEBUG - Unable to connect to the database
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:444)
	at org.postgresql.Driver.connect(Driver.java:297)
	at org.owasp.dependencycheck.data.nvdcve.DriverShim.connect(DriverShim.java:93)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:187)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.<init>(DatabaseManager.java:125)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:289)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1025)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:896)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:711)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:637)
	at org.owasp.dependencycheck.App.runScan(App.java:262)
	at org.owasp.dependencycheck.App.run(App.java:194)
	at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:139)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:455)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 17 common frames omitted

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by aikebah** [comment]
Most likely you have firewall software blocking the network access for the java process of dependency-check
