### ISSUE TITLE
One or more exceptions occurred during analysis: Could not find artifact

### ISSUE THREAD

**Issue by spyhunter99** [dependency-check/DependencyCheck#643]
On version 1.4.4.1 maven plugin

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:1.4.4.1:check (default) on project mymodule: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] Could not find artifact org.hyperic:sigar-dist:zip:1.6.4.129 in sonatype-public-repository (https://oss.sonatype.org/content/groups/public)

````
<dependency>
            <groupId>org.hyperic</groupId>
            <artifactId>sigar</artifactId>
           <version>1.6.5.132-6</version>
        </dependency>
        <dependency>
            <groupId>org.hyperic</groupId>
            <artifactId>sigar-dist</artifactId>
            <version>1.6.5.132-6</version>
            <type>zip</type>
        </dependency>
````

Running the build with -X for debug yields this

````
[ERROR] Could not find artifact org.hyperic:sigar-dist:zip:1.6.4.129 in sonatype-public-repository (https://oss.sonatype.org/content/groups/public)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:1.4.4.1:check (default) on project mymodule: One or more exceptions occurred during dependency-check analysis
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: One or more exceptions occurred during dependency-check analysis
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:120)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:466)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Could not find artifact org.hyperic:sigar-dist:zip:1.6.4.129 in sonatype-public-repository (https://oss.sonatype.org/content/groups/public)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies(BaseDependencyCheckMojo.java:708)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts(BaseDependencyCheckMojo.java:633)
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:92)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] Entering finalize
[DEBUG] Entering finalize
[DEBUG] Entering finalize
````

If i remove the owasp check, the build runs just fine. Maven has no trouble resolving the artifact, but it's not in the sonatype. It may be possible that the plugin is only selecting the first repository listed in the pom and not all of them.

**Comment by jeremylong** [comment]
I am having a problem replicating this error.  I can get Maven itself (i.e. `mvn package`) if the repository is not setup correctly. However, once this corrected Maven downloads the dependencies correctly and dependency-check runs without an exception.  Even if I define the repo and dependency in a child module and use the aggregate goal on the parent sigar is downloaded correctly.

Can you tell me more about your maven setup (version, jdk, os, etc.)? How are you invoking dependency-check (mvn site, using the aggregate goal, etc.)? Where is the repo defined for the sigar dependencies (in the settings.xml, in a parent pom, or in the child pom that depends on sigar)?  Any chance you can provide a sample pom.xml that fails?

**Comment by spyhunter99** [comment]
Sorry missed that this was updated. Just ran this again and got a similar error message. Again, it was with a secondary repository using 1.4.5

`mvn org.owasp:dependency-check-maven:1.4.5:check`

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:1.4.5:check (default-cli) on project fgsms-jboss-esb-agent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] Could not find artifact org.jboss.savara.dependencies.esb:jbossesb-rosetta:jar:4.7 in sonatype-public-repository (https://oss.sonatype.org/content/groups/public)
[ERROR] -> [Help 1]

again, the build works ok normally, it's just when running the check. I think it's related to there being more than one repository defined in the parent pom. The code base i'm running against is here
`git clone https://github.com/mil-oss/fgsms.git`

module that fails: `-rf :fgsms-jboss-esb-agent`

**Comment by spyhunter99** [comment]
full trace

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:1.4.5:check (default-cli) on project fgsms-jboss-esb-agent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[DEBUG] Entering finalize
[ERROR] Failure to find org.jboss.savara.dependencies.esb:jbossesb-rosetta:jar:4.7 in https://oss.sonatype.org/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-public-repository has elapsed or updates are forced
[DEBUG] Entering finalize
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:1.4.5:check (default-cli) on project fgsms-jboss-esb-agent: One or more exceptions occurred during dependency-check analysis
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: One or more exceptions occurred during dependency-check analysis
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:120)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:494)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Failure to find org.jboss.savara.dependencies.esb:jbossesb-rosetta:jar:4.7 in https://oss.sonatype.org/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-public-repository has elapsed or updates are forced
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.collectDependencies(BaseDependencyCheckMojo.java:710)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.scanArtifacts(BaseDependencyCheckMojo.java:633)
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:92)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by johannesboon** [comment]
In order to try to solve this issue https://github.com/jeremylong/DependencyCheck/issues/562 by upgrading our project from version 1.3.3 to 1.4.5 we started getting this issue as well.

    [ERROR] Failed to execute goal org.owasp:dependency-check-maven:1.4.5:check (default-cli) on project poliskluis-api: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
    [ERROR] Failure to find some.groupid:artifactid:jar:1.0 in https://internal.servername/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced

This dependency can be retrieved via one of the declared repositories in our pom.xml that we use for our own internal libraries but not from any public repository.

**Comment by johannesboon** [comment]
We have a couple of different repositories defined and a company internal nexus mirror. This results in the following different couple of attempts to download the artifact during build time (before the analysis). As it is an internal artifact should we exclude it through supression-file.xml ?

    Downloading: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-releases/idin/merchant/library/1.0/library-1.0.pom
    Downloading: https://repoj.rhea.company.net/nexus/content/groups/public/idin/merchant/library/1.0/library-1.0.pom
    Downloading: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-libraries/idin/merchant/library/1.0/library-1.0.pom
    Downloaded: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-libraries/idin/merchant/library/1.0/library-1.0.pom (454 B at 0.7 KB/sec)
    Downloading: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-releases/idin/merchant/library/1.0/library-1.0.jar
    Downloading: https://repoj.rhea.company.net/nexus/content/groups/public/idin/merchant/library/1.0/library-1.0.jar
    Downloading: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-libraries/idin/merchant/library/1.0/library-1.0.jar
    Downloaded: https://repoj.rhea.company.net/nexus/content/repositories/project-awesomewebapp-libraries/idin/merchant/library/1.0/library-1.0.jar (1020 KB at 2150.8 KB/sec)

**Comment by johannesboon** [comment]
According to a round of debugging the problem stems from BaseDependencyCheckMojo.remoteRepos
which is initialized with a defaultValue = "${project.remotePluginRepositories}"

According to https://wiki.eclipse.org/Aether/Using_Aether_in_Maven_Plugins there is difference between:

    project.remotePluginRepositories (The project's remote repositories to use for the resolution of plugins and their dependencies)

and

    project.remoteProjectRepositories (The project's remote repositories to use for the resolution of project dependencies)

At least for this purpose it seems we suffer from using the former instead of the latter - which might not be different for every user, but in this case it makes all the difference.

**Comment by johannesboon** [comment]
To test my assumption (and have a workaround) I just rewrote my pom.xml to also include 

    <pluginRepositories>
        <pluginRepository>
    ... etc.

in line with my existing

    <repositories>
        <repository>
    ... etc.

The fact that after that the problem is gone supports my previous assumption of project.remotePluginRepositories being incorrect for retrieving project dependencies.

**Comment by jeremylong** [comment]
Sorry about the delay in responding to this. The code around retrieving artifacts in the Maven plugin has been completely refactored and now uses `${project.remoteArtifactRepositories}`. I believe this resolves the issue.
