### ISSUE TITLE
Unable to download the NVD CVE data

### ISSUE THREAD

**Issue by nmi8080a** [dependency-check/DependencyCheck#645]
I'm unable to download the NVD CVE data using the maven plugin. I don't have any problems downloading the data files manually via Chrome web browser. I am on RHEL 7.2 and not behind a proxy.

In addition to solving this problem, I would also like to ask if a simple mechanism could be added to point the plugin at a directory containing the NVD database downloads. It would help where the internet download does not work for one reason or another and also would be good for working offline.

/usr/local/share/applications/apache-maven-3.3.9/bin/mvn org.owasp:dependency-check-maven:check -X

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/share/applications/apache-maven-3.3.9
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.el7.x86_64", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
<<<<<<<<<<<<<<<<<<<munch>>>>>>>>>>>>>>>>>>>
[INFO] Checking for updates
[DEBUG] Database dialect: H2
[DEBUG] Database dialect: H2
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz
[DEBUG] Entering finalize
[DEBUG] Available Protocols:
[DEBUG] SSLv2Hello
[DEBUG] SSLv3
[DEBUG] TLSv1
[DEBUG] TLSv1.1
[DEBUG] TLSv1.2
[ERROR] IO Exception: Connection reset
[DEBUG] Exception details
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:261)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:228)
        at org.owasp.dependencycheck.data.update.nvd.UpdateableNvdCve.add(UpdateableNvdCve.java:101)

**Comment by nmi8080a** [comment]
I solved my problem: at some point in the RHEL 7 java upgrade process the java.security file is not automatically updated but instead creates an .rpmnew file that must be manually replaced to update the jdk.tls.disabledAlgorithms settings (deleting everything after the 768).

**Comment by jeremylong** [comment]
Glad you figured this out.  Regarding your question - the feature to point the update process at a directory instead of NVD is already there. Simply set the `cveUrl12Modified`, `cveUrl20Modified`, `cveUrl12Base`, and `cveUrl20Base` to a file:///location/of/nvd/files. See the advanced configuration section of the [configuration page](http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html) for examples (note, the %d will need to be in the base URI so ODC can calculate the location for the XML file for each year).
