### ISSUE TITLE
How to use it in command line offline

### ISSUE THREAD

**Issue by Lzmupupup** [dependency-check/DependencyCheck#6490]
org.owasp.dependencycheck.exception.NoDataException: No documents exist
        at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:1163)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:641)
        at org.owasp.dependencycheck.App.runScan(App.java:262)
        at org.owasp.dependencycheck.App.run(App.java:194)
        at org.owasp.dependencycheck.App.main(App.java:89)
2024-02-21 10:44:40,674 org.owasp.dependencycheck.utils.Settings:881
DEBUG - Deleting ALL temporary files from `/tmp/dctemp68d23e28-c129-47fa-a06c-fe07239a19fd`
2024-02-21 10:44:40,690 org.owasp.dependencycheck.App:90
DEBUG - Exit code: 13

**Comment by Lzmupupup** [comment]
![Uploading IMG_0948.jpeg…]()

**Comment by Lzmupupup** [comment]
Which parameters need to be disabled offline

**Comment by jeremylong** [comment]
See the published documentation: https://jeremylong.github.io/DependencyCheck/data/index.html

**Comment by Lzmupupup** [comment]
> See the published documentation: https://jeremylong.github.io/DependencyCheck/data/index.html

I read the documentation, it says what permissions are needed, it doesn't say how to use the offline command line, can you tell me how to use it, the local virus library is deployed

**Comment by Lzmupupup** [comment]
In other words, it can only be used with an Internet connection and cannot be deployed offline

**Comment by jeremylong** [comment]
Did you actually read the article? It goes through what resources need to be pulled down in order to operate in an offline mode. You can't just use dependency-check offline without planning your implementation a little.
