### ISSUE TITLE
How to solve the following errors？

### ISSUE THREAD

**Issue by zhchangqing** [dependency-check/DependencyCheck#6516]
[INFO] Analysis Started
[INFO] Finished Archive Analyzer (1 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[ERROR] Cannot connect to Artifactory
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at [java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131](http://java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131))
        at [java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371](http://java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371))
        at [java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314](http://java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314))
        at [java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309](http://java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309))
        at [java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654](http://java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654))
        at [java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473](http://java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473))
        at [java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369](http://java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369))
        at [java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396](http://java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396))
        at [java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480](http://java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480))
        at [java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458](http://java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458))
        at [java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201](http://java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201))
        at [java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172](http://java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172))
        at [java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500](http://java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500))
        at [java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415](http://java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415))
        at [java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450](http://java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450))
        at [java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421](http://java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421))
        at [java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580](http://java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580))
        at [java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183](http://java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183))
        at [java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142](http://java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142))
        at org.owasp.dependencycheck.data.artifactory.ArtifactorySearch.connect(ArtifactorySearch.java:182)
        at org.owasp.dependencycheck.data.artifactory.ArtifactorySearch.preflightRequest(ArtifactorySearch.java:302)
        at org.owasp.dependencycheck.analyzer.ArtifactoryAnalyzer.prepareFileTypeAnalyzer(ArtifactoryAnalyzer.java:140)
        at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.prepareAnalyzer(AbstractFileTypeAnalyzer.java:83)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:102)
        at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:830)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:666)
        at org.owasp.dependencycheck.App.runScan(App.java:262)
        at org.owasp.dependencycheck.App.run(App.java:194)
        at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at [java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439](http://java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439))
        at [java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306](http://java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306))
        at [java.base/sun.security.validator.Validator.validate(Validator.java:264](http://java.base/sun.security.validator.Validator.validate(Validator.java:264))
        at [java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231](http://java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231))
        at [java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132](http://java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132))
        at [java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638](http://java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638))
        ... 24 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at [java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141](http://java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141))
        at [java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126](http://java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126))
        at [java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297](http://java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297))
        at [java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434](http://java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434))
        ... 29 common frames omitted
[ERROR] Exception occurred initializing Artifactory Analyzer.

**Comment by jeremylong** [comment]
looks like you do not have the correct root cert in your cacerts file. Google usually helps: https://docs.mend.io/bundle/wsk/page/how_to_resolve_error_message__pkix_path_building_failed__sun_security_provider_certpath_suncertpathbuilderexception__unable_to_find_valid_certification_path_to_requested_target_.html

**Comment by zhchangqing** [comment]
tks



发件人："Jeremy Long" ***@***.***>
发送日期：2024-03-14 18:45:44
收件人："jeremylong/DependencyCheck" ***@***.***>
抄送人：zhchangqing ***@***.***>,Author ***@***.***>
主 题：Re: [jeremylong/DependencyCheck] How to solve the following errors？ (Issue #6516)

looks like you do not have the correct root cert in your cacerts file. Google usually helps: https://docs.mend.io/bundle/wsk/page/how_to_resolve_error_message__pkix_path_building_failed__sun_security_provider_certpath_suncertpathbuilderexception__unable_to_find_valid_certification_path_to_requested_target_.html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

************************************************************************************************
提示信息：
本邮件（及任何附件）可能含有机密、专有、具有特权或者受法律保护的资料，仅供指定收件人（或负责将资料转交收件人的人士）使用。如您非本邮件指定收件人，则无权阅读、打印、保留、复制、传播本邮件或其任何部分。如您误收本邮件，请立即销毁或从您的系统中删除，并通知寄件人。中国光大银行不保证本电子邮件是安全的、无错误的/或者免除病毒的，因为电子邮件信息可能会在传输过程中被截取、修改、损坏、遗失、延迟/或者变得不完整/或者被病毒感染。因此，中国光大银行及寄件人不对因本邮件内容的任何错误和遗漏而造成的损失或损害承担任何责任。
This message (and any attachments) may contain information that is confidential, proprietary, privileged or otherwise protected by law. The message is intended solely for the named addressee (or a person responsible for delivering it to the addressee). If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please destroy the message or delete it from your system immediately and notify the sender. CEB cannot guarantee that this e-mail is secure, error free and/or virus-free as e-mail messages could be intercepted, altered, corrupted, lost, delayed or become incomplete and/or infected by viruses in the course of their transmission. CEB and the sender therefore do not accept liability for any loss or damage arising from any errors or omissions in the contents of this e-mail.
************************************************************************************************
