### ISSUE TITLE
NoSuchFieldError READ_DATE_TIMESTAMPS_AS_NANOSECONDS when plugin is used in subprojects

### ISSUE THREAD

**Issue by veita** [dependency-check/DependencyCheck#6542]
When the Depencency Check plugin is used in subprojects and certain third-party plugins that pull in older versions of the `jackson-databind` library are configured in the project, then the dependency task may fail with the error below.

**Version of dependency-check used**
The problem occurs using version 9.0.10 of the Gradle plugin in Gradle 8.7.

**Logged error**
```
Caused by: java.lang.NoSuchFieldError: READ_DATE_TIMESTAMPS_AS_NANOSECONDS
    at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._withFormatOverrides(InstantDeserializer.java:298)
    at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.createContextual(JSR310DateTimeDeserializerBase.java:121)
    at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:830)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:638)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:615)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:188)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:28)
    at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:830)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:648)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4861)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4731)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
    at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:338)
    at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:349)
    at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:116)
    at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
    at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:711)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:637)
    at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:103)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**To Reproduce**
Go to https://github.com/veita/gradle-plugin-dependency-bug and follow the steps describe there.

**Expected behavior**
The Dependency Check plugin should work regardless of the project structure and other plugins that may be present.

**Additional context**
The issue might be seen as a bug in Gradle.

**Comment by veita** [comment]
This issue is related to https://github.com/jeremylong/DependencyCheck#gradle-build-environment

**Comment by aikebah** [comment]
The issue is in how Gradle works with its plugin classpath... not much we can do about that, apart from documenting how to override Gradle's plugin classpath resolution making projects pin a compatible version of the library that Gradle should use on the plugin classpath.
