### ISSUE TITLE
While running dependency in angular project we get [ERROR] java.lang.NullPointerException: null, can that be ignored

### ISSUE THREAD

**Issue by Amrin-Taj** [dependency-check/DependencyCheck#6642]
Our's is mono repo project. i have few questions
1. For mono repo should we run the dependency check separately to all the projects and not the main package.json
2. when i am running the bat command i am getting some errors, can those be ignored or is there any way to fix it.

a. [ERROR] java.lang.NullPointerException: null
        at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
        at org.owasp.dependencycheck.analyzer.AbstractNpmAnalyzer.gatherEvidence(AbstractNpmAnalyzer.java:398)
        at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.processDependencies(NodePackageAnalyzer.java:433)
        at org.owasp.dependencycheck.analyzer.NodePackageAnalyzer.analyzeDependency(NodePackageAnalyzer.java:270)
        at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
        at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

b. NodeAuditAnalyzer failed on <path of package-lock.json>

c. [ERROR] Exception occurred initializing Pnpm Audit Analyzer.

d. [ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
[ERROR] Unable to read yarn audit output.
[ERROR] Unable to read pnpm audit output.

Thanks in advance, any help will be appreciated :).

**Comment by aikebah** [comment]
One of the entries in your package.json appears to have a license field that is not following the npm docs at
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license

As the NullPointerException location indicates that you're having a deprecated legacy license-field that does not have a `type` property, whereas all documented deprecated license metadata structure types contain a `type` field.
