### ISSUE TITLE
CPE analyzer throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by costas80** [dependency-check/DependencyCheck#6733]
**Describe the bug**

Our CI jobs running the ODC maven plugin started failing with a `java.lang.ArrayIndexOutOfBoundsException` error. This seems to be raised randomly as re-executing the build several times can result in the error not appearing and the build succeeding. In addition, these builds with the same configuration have been completing without problems for several weeks.

To rule out an issue with the local NVD database I have also tried running first `mvn org.owasp:dependency-check-maven:9.2.0:purge` but the error still remains.

As these builds just started failing (and randomly so), I imagine this is due to some sort of race condition. Any insights on what could be triggering this (or a fix) would be most welcome.

**Version of dependency-check used**

Version 9.2.0 of the ODC maven plugin (running with Java 21 and maven 3.9.0).

**Log file**

The log file varies but is always a `java.lang.ArrayIndexOutOfBoundsException`. Adding below a few stacktraces obtained by running maven with debug logging (from independent runs).

Error 1:

```
java.lang.ArrayIndexOutOfBoundsException: Index -24931 out of bounds for length 4960
	at org.apache.lucene.util.compress.LZ4.decompress(LZ4.java:130)
	at org.apache.lucene.codecs.lucene87.LZ4WithPresetDictCompressionMode$LZ4WithPresetDictDecompressor.decompress(LZ4WithPresetDictCompressionMode.java:101)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader$BlockState.document(CompressingStoredFieldsReader.java:643)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.document(CompressingStoredFieldsReader.java:659)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.visitDocument(CompressingStoredFieldsReader.java:678)
	at org.apache.lucene.index.CodecReader.document(CodecReader.java:84)
	at org.apache.lucene.index.BaseCompositeReader.document(BaseCompositeReader.java:141)
	at org.apache.lucene.index.IndexReader.document(IndexReader.java:352)
	at org.apache.lucene.search.IndexSearcher.doc(IndexSearcher.java:287)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.getDocument(AbstractMemoryIndex.java:321)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:454)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:287)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:785)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Error 2:

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -27681 out of bounds for byte[5008]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.apache.lucene.util.compress.LZ4.decompress(LZ4.java:134)
	at org.apache.lucene.codecs.lucene87.LZ4WithPresetDictCompressionMode$LZ4WithPresetDictDecompressor.decompress(LZ4WithPresetDictCompressionMode.java:101)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader$BlockState.document(CompressingStoredFieldsReader.java:643)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.document(CompressingStoredFieldsReader.java:659)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.visitDocument(CompressingStoredFieldsReader.java:678)
	at org.apache.lucene.index.CodecReader.document(CodecReader.java:84)
	at org.apache.lucene.index.BaseCompositeReader.document(BaseCompositeReader.java:141)
	at org.apache.lucene.index.IndexReader.document(IndexReader.java:352)
	at org.apache.lucene.search.IndexSearcher.doc(IndexSearcher.java:287)
	at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.getDocument(AbstractMemoryIndex.java:321)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:454)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:287)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:785)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Error 3:

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 8 out of bounds for byte[7]
    at java.lang.System.arraycopy (Native Method)
    at java.io.BufferedOutputStream.write (BufferedOutputStream.java:129)
    at org.apache.lucene.store.OutputStreamIndexOutput.writeBytes (OutputStreamIndexOutput.java:53)
    at org.apache.lucene.store.DataOutput.writeBytes (DataOutput.java:52)
    at org.apache.lucene.util.packed.PackedWriter.flush (PackedWriter.java:86)
    at org.apache.lucene.util.packed.PackedWriter.add (PackedWriter.java:66)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.saveInts (CompressingStoredFieldsWriter.java:200)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.writeHeader (CompressingStoredFieldsWriter.java:220)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.flush (CompressingStoredFieldsWriter.java:245)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.finishDocument (CompressingStoredFieldsWriter.java:172)
    at org.apache.lucene.index.StoredFieldsConsumer.finishDocument (StoredFieldsConsumer.java:68)
    at org.apache.lucene.index.DefaultIndexingChain.finishStoredFields (DefaultIndexingChain.java:463)
    at org.apache.lucene.index.DefaultIndexingChain.processDocument (DefaultIndexingChain.java:499)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments (DocumentsWriterPerThread.java:208)
    at org.apache.lucene.index.DocumentsWriter.updateDocuments (DocumentsWriter.java:415)
    at org.apache.lucene.index.IndexWriter.updateDocuments (IndexWriter.java:1471)
    at org.apache.lucene.index.IndexWriter.updateDocument (IndexWriter.java:1757)
    at org.apache.lucene.index.IndexWriter.addDocument (IndexWriter.java:1400)
    at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.buildIndex (AbstractMemoryIndex.java:226)
    at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.open (AbstractMemoryIndex.java:128)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open (CPEAnalyzer.java:230)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer (CPEAnalyzer.java:195)
    at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare (AbstractAnalyzer.java:102)
    at org.owasp.dependencycheck.Engine.initializeAnalyzer (Engine.java:830)
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:666)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1960)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:1143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

Error 4

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 8 out of bounds for byte[7]
    at java.lang.System.arraycopy (Native Method)
    at java.io.BufferedOutputStream.implWrite (BufferedOutputStream.java:224)
    at java.io.BufferedOutputStream.write (BufferedOutputStream.java:200)
    at org.apache.lucene.store.OutputStreamIndexOutput.writeBytes (OutputStreamIndexOutput.java:53)
    at org.apache.lucene.store.DataOutput.writeBytes (DataOutput.java:52)
    at org.apache.lucene.util.packed.PackedWriter.flush (PackedWriter.java:86)
    at org.apache.lucene.util.packed.PackedWriter.add (PackedWriter.java:66)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.saveInts (CompressingStoredFieldsWriter.java:200)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.writeHeader (CompressingStoredFieldsWriter.java:220)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.flush (CompressingStoredFieldsWriter.java:245)
    at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.finishDocument (CompressingStoredFieldsWriter.java:172)
    at org.apache.lucene.index.StoredFieldsConsumer.finishDocument (StoredFieldsConsumer.java:68)
    at org.apache.lucene.index.DefaultIndexingChain.finishStoredFields (DefaultIndexingChain.java:463)
    at org.apache.lucene.index.DefaultIndexingChain.processDocument (DefaultIndexingChain.java:499)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments (DocumentsWriterPerThread.java:208)
    at org.apache.lucene.index.DocumentsWriter.updateDocuments (DocumentsWriter.java:415)
    at org.apache.lucene.index.IndexWriter.updateDocuments (IndexWriter.java:1471)
    at org.apache.lucene.index.IndexWriter.updateDocument (IndexWriter.java:1757)
    at org.apache.lucene.index.IndexWriter.addDocument (IndexWriter.java:1400)
    at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.buildIndex (AbstractMemoryIndex.java:226)
    at org.owasp.dependencycheck.data.cpe.AbstractMemoryIndex.open (AbstractMemoryIndex.java:128)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open (CPEAnalyzer.java:230)
    at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer (CPEAnalyzer.java:195)
    at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare (AbstractAnalyzer.java:102)
    at org.owasp.dependencycheck.Engine.initializeAnalyzer (Engine.java:830)
    at org.owasp.dependencycheck.Engine.analyzeDependencies (Engine.java:666)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck (BaseDependencyCheckMojo.java:1960)
    at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute (BaseDependencyCheckMojo.java:1143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**To Reproduce**

Simply run the ODC with `mvn dependency-check:aggregate` 

**Expected behavior**

No `ArrayIndexOutOfBoundsException` errors should occur.

**Comment by costas80** [comment]
All issues have been resolved after a VM reboot. This is odd considering that jobs were running in a container which had been restarted, so this was not due to e.g. a JVM restart.

I'm closing this issue now but at least even closed it may serve as a reference for anyone coming across this in the future.
