### ISSUE TITLE
NVD Updates Failing for 12+ Hours

### ISSUE THREAD

**Issue by SHAZAM-Analytics** [dependency-check/DependencyCheck#6748]
The NVD update reaches 82% then stops. This has occurred with multiple different servers for the last 12+ hours.

This has blocked our pipeline for that time. Is there a workaround? e.g. a web address we can manually download the update data and extract it to our cache?

Error:

```
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:389)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:116)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:427)
        at org.owasp.dependencycheck.App.run(App.java:172)
        at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryExceededException: NVD Update Failed: attempted to retrieve starting index 224000 from the NVD unsuccessfully five times.

```
We use an nvdApiKey.

 Version is 9.2.0

The commands our script runs are as follows...

set JAVA_HOME=S:\sqa\node\tools\java\jdk17
set path=%PATH%;S:\sqa\node\tools\java\jdk17\bin
S:\sqa\node\tools\dependency-check\bin\dependency-check --nvdApiKey XXXX --updateonly --data S:\sqa\depcheckdata

**Comment by aikebah** [comment]
If you first checked open issues you would've found #6746
