### ISSUE TITLE
Cannot connect Dependency-check to Central DB

### ISSUE THREAD

**Issue by twist9743** [dependency-check/DependencyCheck#6832]
Hi, i was trying to make a Dependency-check with Central DB and im getting Error like on screenshot
![image](https://github.com/jeremylong/DependencyCheck/assets/55599236/4b216e6e-fc41-4ea4-b113-3e7e0b07836f)
I tryed DB like: postgresql, mysql, mariadb and in all types of DBs im getting this exception.
Am i doing something wrong or its initialize files issue?

**Comment by chadlwilson** [comment]
Most likely a configuration or DB driver availability problem. You probably need to share the full error, how you are trying to run ODC (CLI? plugin? container?) and the database configuration you are passing (`connectionString`, `dbDriverName`, `dbDriverPath` etc).

Also, take a look at https://github.com/jeremylong/DependencyCheck/issues/4087

**Comment by twist9743** [comment]
I ran ODC  and DB in container.     
Here is my command, that i gives to ODC container, when i used postgresql:
 --dbDriverPath /usr/share/dependency-check/plugins/postgresql-42.2.19.jar --dbPassword *MyPass* --dbUser *user* --connectionString jdbc:postgresql://IP:PORT/dependencycheck --proxyserver *Proxy* --proxyport *Port*--updateonly
Here is output:
Exception in thread "main" java.lang.IllegalStateException: Connection factory returned null from createConnection
        at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:416)
        at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:113)
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:538)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:714)
        at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.getConnection(DatabaseManager.java:575)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.getProperties(CveDB.java:549)
        at org.owasp.dependencycheck.data.nvdcve.DatabaseProperties.<init>(DatabaseProperties.java:104)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:302)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:1032)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:896)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:427)
        at org.owasp.dependencycheck.App.run(App.java:172)
        at org.owasp.dependencycheck.App.main(App.java:89)

**Comment by chadlwilson** [comment]
As I said, if you look at https://github.com/jeremylong/DependencyCheck/issues/4087#issuecomment-1048024989 you will see that you probably need to set the driver name properly.

Also, make sure the Postgres driver is mounted or installed/available in the correct place inside the container.

**Comment by twist9743** [comment]
About the path, i changen container endpoint to check, if driver is already installed in container, so it is path from container.
I'll check link, and if error doesnt fix, write a comment below.

**Comment by twist9743** [comment]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d4b00000, 1048576, 0) failed; error='Not enough space' (errno=12)
 There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 1048576 bytes. Error detail: committing reserved memory.
An error report file with more information is saved as:
/src/hs_err_pid1.log
[1197.944s][warning][os] Loading hsdis library failed

This error happens, is not enought space in DB, or for container?

**Comment by chadlwilson** [comment]
Not enough memory available to the container **or** potentially the host running the container.

I think you should be able to google/search these type of errors. This is not specific to ODC.

**Comment by twist9743** [comment]
Yeah, but thanks at all

**Comment by chadlwilson** [comment]
If your DB connectivity problem is resolved now, please close this ticket :-)
