### ISSUE TITLE
Exception caught: org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true

### ISSUE THREAD

**Issue by vinod272** [dependency-check/DependencyCheck#710]
Following is the entry from the log file.Please let me know if this issue is something to worry about, i think a particular jar file is not being analyzed.

2017-04-18 19:48:40,670 org.owasp.dependencycheck.data.central.CentralSearch:95
DEBUG - Searching Central url https://search.maven.org/solrsearch/select?q=1:"80b4ffe7c26ee97313bea2ddda5835fd38812ee4"&wt=xml
2017-04-18 19:48:40,673 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:259
DEBUG - Available Protocols:
2017-04-18 19:48:40,673 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:261
DEBUG - SSLv2Hello
2017-04-18 19:48:40,673 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:261
DEBUG - SSLv3
2017-04-18 19:48:40,673 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:261
DEBUG - TLSv1
2017-04-18 19:48:40,674 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:261
DEBUG - TLSv1.1
2017-04-18 19:48:40,674 org.owasp.dependencycheck.utils.SSLSocketFactoryEx:261
DEBUG - TLSv1.2
2017-04-18 19:48:40,745 org.owasp.dependencycheck.utils.Downloader:183
DEBUG - Download of http://search.maven.org/remotecontent?filepath=org/eclipse/jetty/orbit/org.objectweb.asm/3.1.0.v200803061910/org.objectweb.asm-3.1.0.v200803061910.pom complete
2017-04-18 19:48:40,746 org.owasp.dependencycheck.xml.pom.PomParser:99
DEBUG - 
**org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true**.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:93)
	at org.owasp.dependencycheck.xml.pom.PomParser.parse(PomParser.java:62)
	at org.owasp.dependencycheck.xml.pom.PomUtils.readPom(PomUtils.java:57)
	at org.owasp.dependencycheck.xml.pom.PomUtils.analyzePOM(PomUtils.java:123)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:226)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:113)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:99)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2017-04-18 19:48:40,746 org.owasp.dependencycheck.xml.pom.PomParser:64

**Comment by jeremylong** [comment]
I'm unable to replicate the reported error. It appears that you have run into a pom.xml that contains a doc type declaration. However, the log file provided does not isolate which pom.xml is causing this (yes, a problem with the logging that was introduced when we parallelized the scans). Without knowing exactly which dependencies you are scanning the best I can do is try to fix the logging for this case.

**Comment by jeremylong** [comment]
An example of this issue was given in the [discussion forum ](https://groups.google.com/forum/#!topic/dependency-check/Lx6N2onVpL0).  This issue can be replicated using:

```xml
        <dependency>
            <groupId>qdox</groupId>
            <artifactId>qdox</artifactId>
            <version>1.6.1</version>
        </dependency>
```
