### ISSUE TITLE
NIST Feeds Moved?

### ISSUE THREAD

**Issue by pioto** [dependency-check/DependencyCheck#747]
It seems that my `mvn dependency-check:check` goal started failing today:

The root cause seems to be that https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz now returns a 404 response:

<details>

```
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz
[DEBUG] Available Protocols:
[DEBUG] SSLv2Hello
[DEBUG] SSLv3
[DEBUG] TLSv1
[DEBUG] TLSv1.1
[DEBUG] TLSv1.2
[ERROR] IO Exception: HEAD request returned a non-200 status code
[DEBUG] Exception details
org.owasp.dependencycheck.utils.DownloadFailedException: HEAD request returned a non-200 status code
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:266)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:228)
        at org.owasp.dependencycheck.data.update.nvd.UpdateableNvdCve.add(UpdateableNvdCve.java:101)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveCurrentTimestampsFromWeb(NvdCveUpdater.java:348)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:267)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:87)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:683)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:490)
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:97)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:494)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARNING] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[DEBUG] Update Error
org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download the NVD CVE data.
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:102)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:683)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:490)
        at org.owasp.dependencycheck.maven.CheckMojo.runCheck(CheckMojo.java:97)
        at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:494)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error making HTTP GET request.
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:286)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:281)
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:228)
        at org.owasp.dependencycheck.data.update.nvd.UpdateableNvdCve.add(UpdateableNvdCve.java:101)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.retrieveCurrentTimestampsFromWeb(NvdCveUpdater.java:348)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:267)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:87)
        ... 26 more
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: GET request returned a non-200 status code
        at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:266)
        ... 32 more


```

</details>

I think NIST must have moved their feeds around or something.

https://nvd.nist.gov/vuln/data-feeds suggests that the URL in question should be something like:

https://static.nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-modified.xml.gz

**Comment by jeremylong** [comment]
While I agree that the data-feeds have updated the URL, the original URLs that were provided still seem to work for me. Are you still seeing a 404?

**Comment by pioto** [comment]
It seems that NIST must have realized they broke things for everyone; that old URL is now functioning again.

**Comment by efenderbosch** [comment]
The above URL is returning a 404 again. How can we work around this?

```
[INFO] Checking for updates
[ERROR] IO Exception: HEAD request returned a non-200 status code
[ERROR] IO Exception: GET request returned a non-200 status code
[WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARNING] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist

Unable to continue dependency-check analysis.
```

**Comment by stevespringett** [comment]
I confirmed the outage. It appears the feed is available again though. I recommend setting up an internal mirror of the NVD and update it daily, that way your scans are not affected by outages. My org does this globally and we run hundreds of scans a day and are never affected. Worst case scenario is that the mirror isn't updated for a day if/when NVD has issues.

https://github.com/stevespringett/nist-data-mirror

**Comment by efenderbosch** [comment]
Thanks @stevespringett. I think I'll drop your code in an AWS Lambda, save the contents to S3 buckets and update my pom to use them.

**Comment by StFS** [comment]
This seems to be happening again now. We have quite a few broken vulnerability scans that have failed in the past few days because we're getting a 404 from NVD.
The offending URL seems to be https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz

Sorry to post this here as I know this is not a problem with this plugin, but does anybody know what is the appropriate forum to ask about this in?

Also, is the correct way to fix this to simply set a property for the URL?

Something like:
`-Dcve.url-2.0.modified=https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-modified.xml.gz`

**Comment by albuch** [comment]
@StFS there was a dependency-check release made yesterday that fixed the URLs for NVD feeds.
You can update DC to v 3.1.2 to fix the issue.
See #1171

**Comment by focbenz** [comment]
Were also affected ... updating to 3.1.2 is the only option or can the links be fixed?

**Comment by StFS** [comment]
@albuch Thanks, updating the plugin worked wonders for us.
