### ISSUE TITLE
GKA3092140547360193761.exe": CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by wallyh010** [dependency-check/DependencyCheck#788]
Just updated to dependency-check 2.0 command-line tool and getting the following error while attempting to check .Net DLLs.  Previous version of dependency-check works.  Thanks.

### Reporting Bugs/Errors
DEBUG - Initializing Assembly Analyzer
2017-07-05 10:09:23,055 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:217
DEBUG - Extracted GrokAssembly.exe to C:\Users\myuserid\AppData\Local\Temp\dctemp5c9a8826-584b-4189-b409-1deafc70ae5a\GKA3092140547360193761.exe
2017-07-05 10:09:23,055 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:219
DEBUG - Extracted GrokAssembly.exe.config to C:\Users\myuserid\AppData\Local\Temp\dctemp5c9a8826-584b-4189-b409-1deafc70ae5a\GKA3092140547360193761.exe.config
2017-07-05 10:09:23,055 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:266
WARN  - An error occurred with the .NET AssemblyAnalyzer;
this can be ignored unless you are scanning .NET DLLs. Please see the log for more details.
2017-07-05 10:09:23,055 org.owasp.dependencycheck.analyzer.AssemblyAnalyzer:268
DEBUG - Could not execute GrokAssembly Cannot run program "C:\Users\myuserid\AppData\Local\Temp\dctemp5c9a8826-584b-4189-b409-1deafc70ae5a\GKA3092140547360193761.exe": CreateProcess error=193, %1 is not a valid Win32 application
2017-07-05 10:09:23,055 org.owasp.dependencycheck.Engine:667
ERROR - Exception occurred initializing Assembly Analyzer.
2017-07-05 10:09:23,055 org.owasp.dependencycheck.Engine:668
DEBUG - 
org.owasp.dependencycheck.exception.InitializationException: An error occurred with the .NET AssemblyAnalyzer
	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.initializeFileTypeAnalyzer(AssemblyAnalyzer.java:270)
	at org.owasp.dependencycheck.analyzer.AbstractFileTypeAnalyzer.initializeAnalyzer(AbstractFileTypeAnalyzer.java:79)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.initialize(AbstractAnalyzer.java:135)
	at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:665)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:512)
	at org.owasp.dependencycheck.App.runScan(App.java:229)
	at org.owasp.dependencycheck.App.run(App.java:162)
	at org.owasp.dependencycheck.App.main(App.java:67)
Caused by: java.io.IOException: Cannot run program "C:\Users\myuserid\AppData\Local\Temp\dctemp5c9a8826-584b-4189-b409-1deafc70ae5a\GKA3092140547360193761.exe": CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.owasp.dependencycheck.analyzer.AssemblyAnalyzer.initializeFileTypeAnalyzer(AssemblyAnalyzer.java:247)
	... 7 common frames omitted
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 9 common frames omitted

**Comment by jeremylong** [comment]
PR #787 should resolve this issue. 2.0.1 will be released shortly to resolve two significant issues.

**Comment by jeremylong** [comment]
2.0.1 was just released - can you confirm that this issue was resolved?

**Comment by NathanLindshield** [comment]
Issue was resolved for me, thx!

**Comment by jeremylong** [comment]
Thanks for the confirmation!
