### ISSUE TITLE
OWASP-DC 2.0.0 SAXParseException - Bean has no property named cvssConfidentialImpact 

### ISSUE THREAD

**Issue by fadiserhan** [dependency-check/DependencyCheck#790]
Hi Jeremy,

I just recently upgraded the jenkins owasp plugin to 2.0.0 and identified some errors afterwards. I am getting an: `SAXParseException - Bean has no property named cvssConfidentialImpact`...  

Here is the error log from the owasp jenkins plugin: 
https://gist.github.com/fserhan/14ea13c927f692dabaa4b9a78f126258

I already tried to execute my dedicated jenkins to job to fetch latest data from NVD first and then started a again client's scans but failing with same error. Do you have more insights?

Thanks in advance,
Fadi

**Comment by NathanLindshield** [comment]
I get this error too in 2.0.1 as well
----
org.xml.sax.SAXParseException; lineNumber: 22726; columnNumber: 77; Error at line 22726 char 77: Bean has no property named cvssConfidentialImpact
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:3363)
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:3389)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1348)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1916)
	at org.jenkinsci.plugins.DependencyCheck.parser.ReportParser.parse(ReportParser.java:126)
	at hudson.plugins.analysis.core.AbstractAnnotationParser.parse(AbstractAnnotationParser.java:54)
	at hudson.plugins.analysis.core.FilesParser.parseFile(FilesParser.java:323)
	at hudson.plugins.analysis.core.FilesParser.parseFiles(FilesParser.java:281)
	at hudson.plugins.analysis.core.FilesParser.parserCollectionOfFiles(FilesParser.java:232)
	at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:203)
	at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:31)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:976)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckPublisher.perform(DependencyCheckPublisher.java:86)
	at hudson.plugins.analysis.core.HealthAwarePublisher.perform(HealthAwarePublisher.java:68)
	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:295)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: java.lang.NoSuchMethodException: Bean has no property named cvssConfidentialImpact
	at org.apache.commons.digester.BeanPropertySetterRule.end(BeanPropertySetterRule.java:196)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1345)
	... 33 more

**Comment by stevespringett** [comment]
Please use the Jenkins issue tracker to report issues

https://issues.jenkins-ci.org
