### ISSUE TITLE
NullPointerException in NvdCveUpdater.update()

### ISSUE THREAD

**Issue by dbsanfte** [dependency-check/DependencyCheck#813]
`[INFO] Checking for updates`
`Exception in thread "main" java.lang.NullPointerException
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:175)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:714)
	at org.owasp.dependencycheck.App.runUpdateOnly(App.java:365)
	at org.owasp.dependencycheck.App.run(App.java:143)
	at org.owasp.dependencycheck.App.main(App.java:67)`

Looks like the culprit is an unchecked null, fixed in master but present in 2.0.1.

Will there be a release from master soon to resolve this? I can't update my database.

**Comment by jeremylong** [comment]
The goal will be to release the next version, at the latest, the 23rd of July.

**Comment by dbsanfte** [comment]
Alrighty, thanks. I was able to do a local snapshot build of master and use that for now.

Cheers.
