### ISSUE TITLE
Ant-Task: nested suppressionFile-Elements don't evaluate Ant-Properties

### ISSUE THREAD

**Issue by cstsw** [dependency-check/DependencyCheck#818]
As of dependency-check-ant-2.0.1 Ant-Properties are not evaluated in nested suppressionFile-Elements.

E.g. the task declared as follows...
```
<dependency-check ...>
   ...
   <suppressionfile>${basedir}/path/relative/to/basedir/dependency-check-suppressions.xml</suppressionfile>
</dependency-check>
```
... will produce the following exception:

```
org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
        Error initializing the suppression analyzer: Suppression file '${basedir}\path/relative/to/basedir\dependency-check-suppressions.xml' does not exists
        Error initializing the suppression analyzer: Suppression file '${basedir}\path/relative/to/basedir\dependency-check-suppressions.xml' does not exists
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:541)
        at org.owasp.dependencycheck.taskdefs.Check.execute(Check.java:976)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
```

However the intenal/undocumented Attribute with the corresponding name does that evaluation:
`<dependency-check ... suppressionfile="${basedir}/path/relative/to/basedir/dependency-check-suppressions.xml"> ... </dependency-check>`

**Comment by jeremylong** [comment]
Thanks for the bug report. Unfortunately, to solve the issue we had to change the task definition slightly:

```xml
<dependency-check ...>
   <suppressionfile path="${basedir}/path/relative/to/basedir/dependency-check-suppressions.xml" />
</dependency-check>
```

The patch will be released included in the next release (hopefully today).

**Comment by cstsw** [comment]
Thanks for the quick fix, Jeremy. I can confirm it as of version 2.1.0.
