### ISSUE TITLE
Add version checking ala Findbugs

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#82]
The findbugs maven plugin warns when a newer version of the plugin exists. Dependency-check maven plugin (and other interfaces) should do the same.

--Jeremhy

**Comment by novobank-auto** [comment]
Hi Jeremy,

I could see following errors displayed in "cve.2.9.trace" file and "dependency-check.log" file. Error is displayed.

Currently executing on Jenkins CI. Fatching code from Github and doing Dependency check

Could you help me to solve. 
====================================
File Name : cve.2.9.trace
===================================
03-26 18:06:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1142)
	at org.h2.jdbc.JdbcConnection.getGeneratedKeys(JdbcConnection.java:1475)
	at org.h2.jdbc.JdbcStatement.getGeneratedKeys(JdbcStatement.java:700)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:635)
	at org.owasp.dependencycheck.data.update.xml.NvdCve20Handler.saveEntry(NvdCve20Handler.java:267)
	at org.owasp.dependencycheck.data.update.xml.NvdCve20Handler.endElement(NvdCve20Handler.java:160)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
	at org.owasp.dependencycheck.data.update.task.ProcessTask.importXML(ProcessTask.java:152)
	at org.owasp.dependencycheck.data.update.task.ProcessTask.processFiles(ProcessTask.java:164)
	at org.owasp.dependencycheck.data.update.task.ProcessTask.call(ProcessTask.java:118)
	at org.owasp.dependencycheck.data.update.task.ProcessTask.call(ProcessTask.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
 ==================================================================



=============================================
File Name : dependency-check.log
=============================================
And also following error in "dependency-check.log" file

Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.Engine analyzeDependencies
INFO: Analysis Complete
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading driver: org.h2.Driver
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: 'C:\Users\user\.jenkins\workspace\novoloan_platform_DependencyCheck\dependency-check-data'
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.utils.Settings getConnectionString
FINE: Connection String: 'jdbc:h2:file:C:\Users\user\.jenkins\workspace\novoloan_platform_DependencyCheck\dependency-check-data\cve.2.9;AUTOCOMMIT=ON;FILE_LOCK=SERIALIZED;'
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: 'C:\Users\user\.jenkins\workspace\novoloan_platform_DependencyCheck\dependency-check-data'
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Need to create DB Structure: false
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Loading database connection
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Connection String: jdbc:h2:file:C:\Users\user\.jenkins\workspace\novoloan_platform_DependencyCheck\dependency-check-data\cve.2.9;AUTOCOMMIT=ON;FILE_LOCK=SERIALIZED;
Mar 27, 2015 3:08:04 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory initialize
FINE: Database User: dcuser
Mar 27, 2015 3:08:19 PM org.owasp.dependencycheck.data.nvdcve.CveDB finalize
FINE: Entering finalize
Mar 27, 2015 3:08:19 PM org.owasp.dependencycheck.data.nvdcve.CveDB finalize
FINE: Entering finalize
Mar 27, 2015 3:08:36 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
INFO: Download Complete for NVD CVE - 2011
Mar 27, 2015 3:08:36 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
WARNING: An exception occurred downloading NVD CVE - 2011
Some CVEs may not be reported.
Mar 27, 2015 3:08:36 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
FINE: Download Task Failed
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@111de0a rejected from java.util.concurrent.ThreadPoolExecutor@881d8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:641)
	at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:216)
	at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Mar 27, 2015 3:08:59 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
INFO: Download Complete for NVD CVE - 2014
Mar 27, 2015 3:08:59 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
WARNING: An exception occurred downloading NVD CVE - 2014
Some CVEs may not be reported.
Mar 27, 2015 3:08:59 PM org.owasp.dependencycheck.data.update.task.DownloadTask call
FINE: Download Task Failed
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1c3552d rejected from java.util.concurrent.ThreadPoolExecutor@881d8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:641)
	at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:216)
	at org.owasp.dependencycheck.data.update.task.DownloadTask.call(DownloadTask.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
