### ISSUE TITLE
Jenkins pipeline Plugin not working 

### ISSUE THREAD

**Issue by BjoernWeiler** [dependency-check/DependencyCheck#824]
Hi,

i was trying to get dependency Check plugin working on our Jenkins (docker container running on a Kubernetes cluster). I ran into different types of errors i couldn't find any good descriptions. So i thought i open a issue here.

SetUp:
Jenkins Version: 2.70 (based on jenkinsci/jenkins:alpine)
Dependency Check Plugin: 2.0.1.2

BuildImage (based on alpine:3.5) running oracle Java 1.8.131 for maven builds

 
Problem #1 

Executing the following snippet (generated with Pipeline Syntax) to generate a Dependency Check Report 

`        stage("Dependency Check") {							  		
            	step([$class: 'DependencyCheckBuilder', 
            	            	     datadir: '', 
            	            	    hintsFile: '', 
            	            	    includeCsvReports: false, 
            	            	    includeHtmlReports: true, 
            	            	    includeJsonReports: false, 
            	            	    isAutoupdateDisabled: false, 
            	            	    outdir: '', 
            	            	    scanpath: '', 
            	            	    skipOnScmChange: false, 
            	            	    skipOnUpstreamChange: false, 
            	            	    suppressionFile: '', zipExtensions: ''])
         }`

got me the following error i can't find a solution for (only problems from 2015 on much older plugin versions which are allready fixed )

`java.io.NotSerializableException: hudson.ClassicPluginStrategy$AntClassLoader2
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:218)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:227)
Caused: java.io.IOException: Unable to serialize org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder$1@79b7cad6
	at hudson.remoting.UserRequest.serialize(UserRequest.java:229)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:85)
	at hudson.remoting.Channel.call(Channel.java:837)
	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:86)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:194)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE`

The job is partly executed in a Kubernetes Pod where the Buildimage is started. 

![dc-pipeline](https://user-images.githubusercontent.com/30437321/28574523-862aa826-714e-11e7-98c2-34ef3220a7c9.png)

Anyone got an Idea for this? I read some stuff about Settings not getting passed from master to slave but i couldn't really make sense of it. 

Problem #2
Running Dependency Check locally with the maven plugin is working just fine. But since i couldn't get the Plug into work i tried to include it in the maven build on Jenkins witch left me with the following error:

`[INFO] No dependencies were identified that could be analyzed by dependency-check
[INFO] Checking for updates
[INFO] starting getUpdatesNeeded() ...
[ERROR] IO Exception: Connection reset
[ERROR] IO Exception: Connection reset
[WARNING] Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[WARNING] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] No documents exist`

Researching this got me to the page https://jeremylong.github.io/DependencyCheck/data/index.html
were this problem is described. 
But: 
- we are not behind a proxy
- a curl from the container with the buildimage to https://nvd.nist.gov/vuln/data-feeds works just fine
- the buildimage doesn't use openJDK but plain oracle java 1.8.131 (because of this i don't think the tls settings are involved)

any ideas to fix either one of the problems would be really appreciated since i really like the tool and plugin and want to include this in our CI.

Thanks in advance

**Comment by stevespringett** [comment]
For problem 1 (Jenkins), can you move the ticket over to https://issues.jenkins-ci.org/ please.

**Comment by BjoernWeiler** [comment]
Done: https://issues.jenkins-ci.org/browse/JENKINS-45782

**Comment by jeremylong** [comment]
@BjoernWeiler for problem 2 - when you are running dependency-check in the Maven build can you provide any details about the configuration and how you are running dependency-check?  Also, running with `-X` can provide additional debugging information to figure out where the error occurred.

**Comment by BjoernWeiler** [comment]
Dependency Check rusn with the first clean deploy from jenkins maven plugin with the following Configuration in the pom:

```xml
<plugins>
	<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>2.1.0</version>
                <configuration>
                    <cveValidForHours>12</cveValidForHours>
                    <failOnError>false</failOnError>
                    <failBuildOnCVSS>10</failBuildOnCVSS>
                    <jarAnalyzerEnabled>true</jarAnalyzerEnabled>
                </configuration>              
                <executions>
                    <execution>
                    	<id>owasp-execution</id>		
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>			
</plugins>
```




Running with debug information gives the following errors:

```
[DEBUG] Checking for updates from: https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.xml.gz
[DEBUG] Available Protocols:
[DEBUG] SSLv2Hello
[DEBUG] SSLv3
[DEBUG] TLSv1
[DEBUG] TLSv1.1
[DEBUG] TLSv1.2
[ERROR] IO Exception: Connection reset
[DEBUG] Exception details
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:254)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:221)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:574)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:547)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[DEBUG] Setting: downloader.quick.query.timestamp='false'
[DEBUG] Available Protocols:
[DEBUG] SSLv2Hello
[DEBUG] SSLv3
[DEBUG] TLSv1
[DEBUG] TLSv1.1
[DEBUG] TLSv1.2
[ERROR] IO Exception: Connection reset
[DEBUG] Exception details
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:254)
	at org.owasp.dependencycheck.utils.Downloader.getLastModified(Downloader.java:221)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:574)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater$TimestampRetriever.call(NvdCveUpdater.java:547)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Seems to be a handshake problem but i dont know why :/

**Comment by jeremylong** [comment]
@BjoernWeiler just confirming, using the maven plugin from your workstation is successful and the maven plugin fails when you attempt to run it from your CI?

**Comment by BjoernWeiler** [comment]
yes.

**Comment by jeremylong** [comment]
@stevespringett does this look like the throttling issue we've seen?

**Comment by stevespringett** [comment]
In the case of the Jenkins plugin running multiple simultaneous jobs, the exceptions are a bit higher up the stack, specifically an UpdateException is thrown when the NVD send back a 403. However, I think a 403 with the server closing the connection will actually result in a connection reset, so this is something we should anticipate and educate users on.
