### ISSUE TITLE
NullPointerException in Lucene indexer

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#849]
The following is repeatable and only occurs during multiple simultaneous Jenkins jobs. The issue is repeatable using either a shared data directory or a per-workspace directory.

When multiple simultaneous jobs are occurring, one or more of the jobs may fail due to one or more items in the ExceptionCollection containing the following trace:

`
java.lang.NullPointerException
	at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.search(CpeMemoryIndex.java:252)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.searchCPE(CPEAnalyzer.java:310)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:228)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:535)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:115)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:98)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Other times, the message will be NullPointerException, but the trace will be empty.

I've attempted to reproduce this issue using the command-line without success. Therefore it's my theory that the issue is a thread/race/timing issue that only occurs when multiple instances of the Engine are running in the same JVM - as is the case with Jenkins.

It's been a long time since I've tested this scenario, so I'm not exactly sure when the issue was introduced.

**Comment by jeremylong** [comment]
Thanks for finding this; a patch will be included in the next release.

**Comment by jeremylong** [comment]
@stevespringett the patch will at least alleviate some of the issues. However, dependency-check is not currently thread-safe.  Is there a way in Jenkins to mark a plugin as not being threadsafe?

**Comment by stevespringett** [comment]
Not to my knowledge. Plugins are expected to be thread safe. There are ways to configure each job not to run while another Dependency-Check job is running, but that is a manual process that requires every job to have this special configuration.

I know older versions of the core did behave correctly when running in this environment. Not sure if they were exactly thread safe or not, but I could not manually trigger the reported issue simply by running a few jobs at the same time. I can do this repeatably with the current version.

**Comment by stevespringett** [comment]
I'll test the patch later tonight as well.

**Comment by stevespringett** [comment]
I haven't been able to reproduce the NPE originally reported, but the new error is:
```
Analyzing Dependencies
One or more exceptions were thrown while executing Dependency-Check
Exception Caught: org.owasp.dependencycheck.exception.NoDataException
Message: No documents exist
org.owasp.dependencycheck.exception.NoDataException: No documents exist
	at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:897)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:604)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:167)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:98)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at org.jenkinsci.plugins.DependencyCheck.AbstractDependencyCheckBuilder.perform(AbstractDependencyCheckBuilder.java:85)
	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckBuilder.perform(DependencyCheckBuilder.java:195)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
```
This only occurs when executing simultaneous jobs.

**Comment by jeremylong** [comment]
Simultaneous jobs with their own data directory or shared data directory?

**Comment by stevespringett** [comment]
Meaning that the data directory could be defined as:
~/jenkins/dcdata
or it might be defined as:
${WORKSPACE}/dcdata

So either all dc jobs use the shared data diretory (~/jenkins/dcdata) or all dc jobs have their own independent data directory in their project workspace.

This was a test I performed to see if the shared data directory had any impact on the errors I was receiving. It did not.

**Comment by stevespringett** [comment]
[[JENKINS-46397]  Intermittent failures with NullPointerException when analyzing](https://issues.jenkins-ci.org/browse/JENKINS-46397)

Issue was discovered and reported by another user as well.
