### ISSUE TITLE
docker run example not working

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#857]
I'm using the docker example from https://github.com/jeremylong/DependencyCheck, but this does not work for me. Following error occured:

+ docker pull owasp/dependency-check
Using default tag: latest
latest: Pulling from owasp/dependency-check
5040bd298390: Already exists
fce5728aad85: Already exists
76610ec20bf5: Already exists
60170fec2151: Already exists
e98f73de8f0d: Already exists
11f7af24ed9c: Already exists
49e2d6393f32: Already exists
bb9cdec9c7f3: Already exists
ac8ad6cf6fce: Pulling fs layer
6dfc6f0fc931: Pulling fs layer
6dfc6f0fc931: Verifying Checksum
6dfc6f0fc931: Download complete
ac8ad6cf6fce: Verifying Checksum
ac8ad6cf6fce: Download complete
ac8ad6cf6fce: Pull complete
6dfc6f0fc931: Pull complete
Digest: sha256:a62afba9075a9823d765e3395a4f9d868a0094b600a649179860e711fd85e9c6
Status: Downloaded newer image for owasp/dependency-check:latest
[Pipeline] sh
[opensource-owasp-scan] Running shell script
+ chmod -R 775 /home/jenkins-master/workspace/opensource-owasp-scan
[Pipeline] sh
[opensource-owasp-scan] Running shell script
+ ls -la /home/jenkins-master/workspace/opensource-owasp-scan
total 148
drwxrwxr-x.    6 wpci wpci    100 Aug 25 06:19 .
drwxrwxrwx. 1081 wpci wpci 114688 Aug 25 01:36 ..
drwxrwxr-x.    2 wpci wpci     31 Aug 25 06:18 owasp
drwxrwxr-x.    4 wpci wpci     31 Aug 25 06:19 OWASP-Dependency-Check
drwxrwxr-x.    4 wpci wpci   4096 Aug 25 06:18 prod-infra-header-forwarding
drwxrwxr-x.    2 wpci wpci   4096 Aug 25 06:19 scanresults
[Pipeline] echo
Run the OWASP Scan for container prod-infra-header-forwarding:0.0.32
[Pipeline] sh
[opensource-owasp-scan] Running shell script
+ docker run --rm -v /home/jenkins-master/workspace/opensource-owasp-scan/prod-infra-header-forwarding:/src -v /home/jenkins-master/workspace/opensource-owasp-scan/OWASP-Dependency-Check/data:/usr/share/dependency-check/data -v /home/jenkins-master/workspace/opensource-owasp-scan/OWASP-Dependency-Check/reports:/report owasp/dependency-check --scan /src --format ALL --project prod-infra-header-forwarding --suppression /src/owasp/owasp-suppress.xml --mono /bin
org.h2.message.DbException: Log file error: "/usr/share/dependency-check/data/dc.trace.db", cause: "java.io.FileNotFoundException: /usr/share/dependency-check/data/dc.trace.db (Permission denied)" [90034-176]
org.h2.message.DbException: Log file error: "/usr/share/dependency-check/data/dc.trace.db", cause: "java.io.FileNotFoundException: /usr/share/dependency-check/data/dc.trace.db (Permission denied)" [90034-176]
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:291)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:312)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:260)
	at org.h2.message.TraceSystem.write(TraceSystem.java:244)
	at org.h2.message.Trace.error(Trace.java:166)
	at org.h2.engine.Database.reconnectModified(Database.java:426)
	at org.h2.engine.Database.beforeWriting(Database.java:2526)
	at org.h2.engine.Database.open(Database.java:633)
	at org.h2.engine.Database.openDatabase(Database.java:260)
	at org.h2.engine.Database.<init>(Database.java:254)
	at org.h2.engine.Engine.openSession(Engine.java:57)
	at org.h2.engine.Engine.openSession(Engine.java:164)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
	at org.h2.engine.Engine.createSession(Engine.java:125)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:150)
	at org.owasp.dependencycheck.Engine.initializeEngine(Engine.java:229)
	at org.owasp.dependencycheck.Engine.<init>(Engine.java:217)
	at org.owasp.dependencycheck.Engine.<init>(Engine.java:196)
	at org.owasp.dependencycheck.Engine.<init>(Engine.java:187)
	at org.owasp.dependencycheck.App.runScan(App.java:224)
	at org.owasp.dependencycheck.App.run(App.java:162)
	at org.owasp.dependencycheck.App.main(App.java:67)
Caused by: org.h2.jdbc.JdbcSQLException: Log file error: "/usr/share/dependency-check/data/dc.trace.db", cause: "java.io.FileNotFoundException: /usr/share/dependency-check/data/dc.trace.db (Permission denied)" [90034-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 30 more
Caused by: java.io.FileNotFoundException: /usr/share/dependency-check/data/dc.trace.db (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.h2.store.fs.FilePathDisk.newOutputStream(FilePathDisk.java:280)
	at org.h2.store.fs.FileUtils.newOutputStream(FileUtils.java:222)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:308)

**Comment by jeremylong** [comment]
I've been focused on some core engine issues, I will try and look into this soon.

**Comment by jeremylong** [comment]
@githubhs17 I just updated the docker image.  Can you try again?
