### ISSUE TITLE
SuppressionFiles doesn't supports interpolated strings

### ISSUE THREAD

**Issue by Nyshu** [dependency-check/DependencyCheck#869]
**Description:** _

> suppressionFiles when provided with interpolatedStrings gives java.lang.ArrayStoreException
_
**Example:**
suppressionFiles = [ "${rootProject.rootDir}/dependencyCheckSuppressionFile.xml",
                         "${rootProject.rootDir}/dependencyCheckSuppressionFile2.xml" ]

```
Caused by: java.lang.ArrayStoreException
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.determineSuppressions(AbstractAnalyze.groovy:210)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze$determineSuppressions.callCurrent(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.initializeSettings(AbstractAnalyze.groovy:141)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:60)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 92 more

```

**Comment by Nyshu** [comment]
https://github.com/jeremylong/dependency-check-gradle/issues/53

Linked to gradle specific issue
