### ISSUE TITLE
"Table not found" error after deleting dc.h2.db

### ISSUE THREAD

**Issue by apeppelsICTU** [dependency-check/DependencyCheck#898]
Hey there, 

We are using DependencyCheck in the form of the Jenkins plugin, running on a Windows build slave. 
After deleting the database because of an updating issue, the following error keeps popping up when clearing the workspace. As can be seen autoUpdate is set to true. I was wondering if you could point me in the right direction when troubleshooting this.

```
provisioning config files...
copy managed file [suppress-owasp.xml] to file:/e:/jenkins/workspace/OWASP-dependency-check-||||||||||||/suppress-owasp.xml
[DependencyCheck] OWASP Dependency-Check Plugin v2.1.1
[DependencyCheck] Executing Dependency-Check with the following options:
[DependencyCheck]  -name = OWASP-dependency-check-|||||||||||
[DependencyCheck]  -scanPath = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck]  -scanPath = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck]  -scanPath = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck]  -scanPath = ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck]  -outputDirectory = e:/jenkins/workspace/OWASP-dependency-check-|||||||||||
[DependencyCheck]  -dataDirectory = e:/jenkins/workspace/OWASP-dependency-check-|||||||||||/dependency-check-data
[DependencyCheck]  -suppressionFile = e:/jenkins/workspace/OWASP-dependency-check-||||||||||||/suppress-owasp.xml
[DependencyCheck]  -dataMirroringType = none
[DependencyCheck]  -isQuickQueryTimestampEnabled = true
[DependencyCheck]  -jarAnalyzerEnabled = true
[DependencyCheck]  -nodeJsAnalyzerEnabled = true
[DependencyCheck]  -nspAnalyzerEnabled = true
[DependencyCheck]  -composerLockAnalyzerEnabled = true
[DependencyCheck]  -pythonDistributionAnalyzerEnabled = true
[DependencyCheck]  -pythonPackageAnalyzerEnabled = true
[DependencyCheck]  -rubyBundlerAuditAnalyzerEnabled = true
[DependencyCheck]  -rubyGemAnalyzerEnabled = true
[DependencyCheck]  -cocoaPodsAnalyzerEnabled = true
[DependencyCheck]  -swiftPackageManagerAnalyzerEnabled = true
[DependencyCheck]  -archiveAnalyzerEnabled = true
[DependencyCheck]  -assemblyAnalyzerEnabled = true
[DependencyCheck]  -centralAnalyzerEnabled = true
[DependencyCheck]  -nuspecAnalyzerEnabled = true
[DependencyCheck]  -nexusAnalyzerEnabled = false
[DependencyCheck]  -autoconfAnalyzerEnabled = true
[DependencyCheck]  -cmakeAnalyzerEnabled = true
[DependencyCheck]  -opensslAnalyzerEnabled = true
[DependencyCheck]  -showEvidence = true
[DependencyCheck]  -formats = XML HTML 
[DependencyCheck]  -autoUpdate = true
[DependencyCheck]  -updateOnly = false
[DependencyCheck] Scanning: ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck] Scanning: ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck] Scanning: ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck] Scanning: ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.data.nvdcve.DatabaseException
[DependencyCheck] Cause: Table "CPEENTRY" not found; SQL statement:
[DependencyCheck] DELETE FROM cpeEntry WHERE id IN (SELECT id FROM cpeEntry LEFT JOIN software ON cpeEntry.id = software.CPEEntryId WHERE software.CPEEntryId IS NULL) [42102-196]
[DependencyCheck] Message: org.h2.jdbc.JdbcSQLException: Table "CPEENTRY" not found; SQL statement:
[DependencyCheck] DELETE FROM cpeEntry WHERE id IN (SELECT id FROM cpeEntry LEFT JOIN software ON cpeEntry.id = software.CPEEntryId WHERE software.CPEEntryId IS NULL) [42102-196]
[DependencyCheck] org.owasp.dependencycheck.data.nvdcve.DatabaseException: org.h2.jdbc.JdbcSQLException: Table "CPEENTRY" not found; SQL statement:
[DependencyCheck] DELETE FROM cpeEntry WHERE id IN (SELECT id FROM cpeEntry LEFT JOIN software ON cpeEntry.id = software.CPEEntryId WHERE software.CPEEntryId IS NULL) [42102-196]
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.prepareStatements(CveDB.java:339)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:268)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.getInstance(CveDB.java:210)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:672)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:600)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.executeDependencyCheck(DependencyCheckExecutor.java:167)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:98)
[DependencyCheck] 	at org.jenkinsci.plugins.DependencyCheck.DependencyCheckExecutor.call(DependencyCheckExecutor.java:46)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:205)
[DependencyCheck] 	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
[DependencyCheck] 	at hudson.remoting.Request$2.run(Request.java:356)
[DependencyCheck] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
[DependencyCheck] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[DependencyCheck] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[DependencyCheck] 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
[DependencyCheck] 	at java.lang.Thread.run(Unknown Source)
[DependencyCheck] Caused by: org.h2.jdbc.JdbcSQLException: Table "CPEENTRY" not found; SQL statement:
[DependencyCheck] DELETE FROM cpeEntry WHERE id IN (SELECT id FROM cpeEntry LEFT JOIN software ON cpeEntry.id = software.CPEEntryId WHERE software.CPEEntryId IS NULL) [42102-196]
[DependencyCheck] 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:179)
[DependencyCheck] 	at org.h2.message.DbException.get(DbException.java:155)
[DependencyCheck] 	at org.h2.command.Parser.readTableOrView(Parser.java:5552)
[DependencyCheck] 	at org.h2.command.Parser.readTableOrView(Parser.java:5529)
[DependencyCheck] 	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:796)
[DependencyCheck] 	at org.h2.command.Parser.parseDelete(Parser.java:819)
[DependencyCheck] 	at org.h2.command.Parser.parsePrepared(Parser.java:378)
[DependencyCheck] 	at org.h2.command.Parser.parse(Parser.java:321)
[DependencyCheck] 	at org.h2.command.Parser.parse(Parser.java:293)
[DependencyCheck] 	at org.h2.command.Parser.prepareCommand(Parser.java:258)
[DependencyCheck] 	at org.h2.engine.Session.prepareLocal(Session.java:578)
[DependencyCheck] 	at org.h2.engine.Session.prepareCommand(Session.java:519)
[DependencyCheck] 	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
[DependencyCheck] 	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
[DependencyCheck] 	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.prepareStatements(CveDB.java:336)
[DependencyCheck] 	... 16 more
[DependencyCheck] ```

**Comment by stevespringett** [comment]
were you successfully able to delete the dependency-check-data directory? Windows has known file locking issues with Java that may be causing this.

**Comment by apeppelsICTU** [comment]
No initially I did have issues with that, that must be it. If the problem persists after forcefully deleting the workspace again, I'll report back here. Thanks!

**Comment by apeppelsICTU** [comment]
The issue was resolved after disconnecting the build slave; the Java process used for jenkins remoting had the directory under lock. After deleting the workspace manually and updating dc.h2.db the dependency checker is working fine again. Thank you for your input!
