### ISSUE TITLE
ArrayIndexOutOfBoundsException when running demo

### ISSUE THREAD

**Issue by markus-mnm** [dependency-check/DependencyCheck#9]
I checked our the source yesterday (0.3.2.5-SNAPSHOT) and when running through the step :  java -jar dependency-check-0.3.2.5-SNAPSHOT.jar -a Testing -out . -scan ./test-classes -scan ./lib

Then I get :
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at org.owasp.dependencycheck.utils.UrlStringUtils.extractImportantUrlData(UrlStringUtils.java:98)
        at org.owasp.dependencycheck.dependency.EvidenceCollection.urlCorrection(EvidenceCollection.java:300)
        at org.owasp.dependencycheck.dependency.EvidenceCollection.containsUsedString(EvidenceCollection.java:193)
        at org.owasp.dependencycheck.data.cpe.CPEAnalyzer.collectionContainsString(CPEAnalyzer.java:443)
        at org.owasp.dependencycheck.data.cpe.CPEAnalyzer.verifyEntry(CPEAnalyzer.java:424)
        at org.owasp.dependencycheck.data.cpe.CPEAnalyzer.determineCPE(CPEAnalyzer.java:145)
        at org.owasp.dependencycheck.data.cpe.CPEAnalyzer.analyze(CPEAnalyzer.java:459)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:250)
        at org.owasp.dependencycheck.App.runScan(App.java:145)
        at org.owasp.dependencycheck.App.run(App.java:122)
        at org.owasp.dependencycheck.App.main(App.java:71)`

The problem seems to be  when it tries to parse "http://jsoup.org/"
when pathParts length is 0 and then this fails
   `if (!pathParts[pathParts.length - 1].isEmpty())`

this made it work for us:
    `if (pathParts.length>0 && !pathParts[pathParts.length - 1].isEmpty())`

**Comment by jeremylong** [comment]
Thanks Markus! I feel like an idiot for making a stupid mistake like that.... Guess I need to add another unit test.

Thanks for pointing this out; I've applied the patch and pushed it to github.

**Comment by markus-mnm** [comment]
We are currently trialing your dependency checker at my work place. Thank your for your work.

**Comment by jeremylong** [comment]
Awesome, you'll have to let me know what people think. There are a few bug fixes that will be released soon. Additionally, there are several plugins that will be released during BlackHat at the end of July. Plugins for build systems, CI, etc.
