### ISSUE TITLE
Getting nullpointer with v 3.0.0

### ISSUE THREAD

**Issue by davidkarlsen** [dependency-check/DependencyCheck#931]
I am getting this NPE with v 3.0.0:
```
15:13:04 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.6:site (default-site) on project jfr-srv: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.6:site failed. NullPointerException -> [Help 1]
15:13:04 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.6:site (default-site) on project jfr-srv: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.6:site failed.
15:13:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
15:13:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
15:13:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
15:13:04 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
15:13:04 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
15:13:04 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
15:13:04 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
15:13:04 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
15:13:04 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
15:13:04 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
15:13:04 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
15:13:04 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
15:13:04 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
15:13:04 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:13:04 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:13:04 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:13:04 	at java.lang.reflect.Method.invoke(Method.java:498)
15:13:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
15:13:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
15:13:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
15:13:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
15:13:04 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.6:site failed.
15:13:04 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
15:13:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
15:13:04 	... 20 more
15:13:04 Caused by: java.lang.NullPointerException
15:13:04 	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1089)
15:13:04 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:924)
15:13:04 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:660)
15:13:04 	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.generate(BaseDependencyCheckMojo.java:609)
15:13:04 	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:238)
15:13:04 	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:337)
15:13:04 	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:178)
15:13:04 	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:132)
15:13:04 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
15:13:04 	... 21 more
```

**Comment by jeremylong** [comment]
Any chance you could run that with `-X` and provide a complete log of the dependency-check execution?

**Comment by davidkarlsen** [comment]
https://filebin.ca/3e1cZpE8CTPd/last420lines.txt

**Comment by vrozov** [comment]
I got similar NPE and error
```
[DEBUG] Unable to connect to the database
java.sql.SQLException: No suitable driver found for jdbc:h2:file:...
```

**Comment by stevespringett** [comment]
@vrozov the driver issue may be related to #930 which would affect any potential integration with the core. Jeremy has fixed this in 60fd4f6311e1febf9b4e019f65fc0e8ef5e9897b

**Comment by vrozov** [comment]
@stevespringett Thank you for the update. Is there a workaround for maven and travis builds?

**Comment by stevespringett** [comment]
Not to my knowledge. Issue has been fixed and will be available in 3.0.1

**Comment by davidkarlsen** [comment]
Could you do a release for 3.0.1 for this - or do you have to wait for more issues? Since it's quite blocking.

**Comment by jeremylong** [comment]
I'll push a release shortly.

**Comment by ghost** [comment]
@jeremylong  When 3.0.1 for gradle will be released? The same problem exists. :confused:

**Comment by jeremylong** [comment]
It was published this morning - took a bit longer as I was having an issue setting up a new computer...

https://plugins.gradle.org/plugin/org.owasp.dependencycheck

**Comment by davidkarlsen** [comment]
works fine!
