### ISSUE TITLE
Engine.openDatabase() swallows fatal exceptions

### ISSUE THREAD

**Issue by bentmann** [dependency-check/DependencyCheck#954]
For a file-based H2 database, `Engine.openDatabase()` attempts to copy the db to a temporary location. If this copy fails (disk full, missing permission, etc.) there's only a debug log message with the details (cf. https://github.com/jeremylong/DependencyCheck/blob/v3.0.1/dependency-check-core/src/main/java/org/owasp/dependencycheck/Engine.java#L959)
````
DEBUG org.owasp.dependencycheck.Engine - Unable to open db in read only mode
java.nio.file.FileSystemException: .../dc.h2.db -> .../dctemp3b024a50-8399-4974-b63a-08d2169906ba/dc.h2.db: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:253)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:954)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:733)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:647)
````
As a follow-up error, a NPE occurs (because the `CveDB` instance has been closed before the copy operation) whose details are again only logged at debug level:
````
ERROR org.owasp.dependencycheck.data.nvdcve.CveDB - Unable to access the local database.

Ensure that '(path)' is a writable directory. If the problem persist try deleting the files in '(path)' and running Dependency-Check Core again. [...].
DEBUG org.owasp.dependencycheck.data.nvdcve.CveDB -
java.lang.NullPointerException: null
        at org.owasp.dependencycheck.data.nvdcve.CveDB.dataExists(CveDB.java:808)
        at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:1054)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:651)
ERROR org.owasp.dependencycheck.Engine - No documents exist

Unable to continue dependency-check analysis.
````

With the current logging and exception handling, it's hard to diagnose the root cause (debug logging needs to be enabled).

Looking at some of the surrounding code, it might make more sense to have `openDatabase()` wrap the exceptions into a `DatabaseException` which `initializeAndUpdateDatabase()` would then properly recognize as a fatal error and abort the analysis with a more fitting error message early on.

**Comment by jeremylong** [comment]
Thank you for the observation and suggestion. I'll try to get this added shortly.

**Comment by bentmann** [comment]
Thanks
