### ISSUE TITLE
NPE in 3.0.1 when database corrupt

### ISSUE THREAD

**Issue by THausherr** [dependency-check/DependencyCheck#959]
### Reporting Bugs/Errors
long version:
https://gist.github.com/THausherr/bae46eb92999f4bdd5be2103d88cfef8

short version:
```
Caused by: java.lang.NullPointerException
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1089)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.runCheck(BaseDependencyCheckMojo.java:924)
	at org.owasp.dependencycheck.maven.BaseDependencyCheckMojo.execute(BaseDependencyCheckMojo.java:577)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

```

Wish: fail more gracefully. I have deleted the database in the maven repository and now it works.

**Comment by jeremylong** [comment]
Thanks for the suggestion.  Initial take is in the `openDatabase` we need to better handle exceptions of type `org.h2.jdbc.JdbcSQLException` and possibly point people to the purge command (which will delete the database files.

**Comment by jeremylong** [comment]
Error reporting was improved in 5.0.0.
