### ISSUE TITLE
Could not connect to Central search

### ISSUE THREAD

**Issue by CameliaTripon** [dependency-check/DependencyCheck#982]
Hi!

I'm getting this error while running the `dependencyCheckAnalyze` task

Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 5 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:288)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:198)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:137)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Could not connect to MavenCentral (400): Bad Request
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:181)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:266)
	... 8 more

I have the following configuration
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.owasp:dependency-check-gradle:3.0.1'
    }
}
```

```
apply plugin: 'org.owasp.dependencycheck'
dependencyCheck {
    format='XML'
}
```

It worked for me previously but from today I get this exception when running the task

**Comment by CameliaTripon** [comment]
I see now that is also reported in Issue 978 (https://github.com/jeremylong/DependencyCheck/issues/978). I will follow that topic and close this one.
